- tools/config/logpoint-windows-all.yml
Depending on the event, LogPoint might normalise windows 'subject account name' as caller_user, target_user, user or member. How do I handle this in field mapping?
> LogPoint windows mapping

- rules/windows/builtin/win_pass_the_hash.yml
— deleted useless KeyLength: '0'
— added filter condition to exclude AccountName='ANONYMOUS LOGON', because of false positives
[proof] http://serverfault.com/questions/338644/what-are-anonymous-logons-in-windows-event-log
> improved win_pass_the_hash.yml rule

- rules/windows/sysmon/sysmon_susp_regsvr32_anomalies.yml
Rule to detect COM scriptlet invocation when wscript.exe is spawned from regsvr32.exe. 
example: https://www.hybrid-analysis.com/sample/f34da6d84a9663928606894fbc494cd9bf2f03c98cf0c775462802558d3a50ef?environmentId=100
SCT script code:
var objShell = new ActiveXObject("WScript.shell");
> Update sysmon_susp_regsvr32_anomalies to detect wscript child process

- rules/web/web_sqlinjection_errors
Rule file that detects error messages from different DB providers that would occur during SQL Injection probing.
The rule file is not trying to be complete, it only contains some examples from http://www.sqlinjection.net/errors/ plus some I experienced occuring in SQLite databases. Maybe tag as `experimental` and explicitly ask for more pattern input from DB and SQLi experts?
> SQL Injection error message patterns

- rules/windows/other/win_reg_persistence.yaml
Add new rule for special persistence mechanisms and add current registry keys from Oddvar Moe's (@api0cradle) blog post: "https://oddvar.moe/2018/04/10/persistence-using-globalflags-in-image-file-execution-options-hidden-from-autoruns-exe/".
> Add rule for Windows registry persistence mechanisms

- rules/windows/sysmon/sysmon_cmstp_com_object_access.yml
Detections for UAC Bypass via CMSTP-associated COM Objects. See http://www.endurant.io/cmstp/detecting-cmstp-enabled-code-execution-and-uac-bypass-with-sysmon/ as well as https://twitter.com/hFireF0X/status/897640081053364225
Tested for robustness / false positive rate and status set to 'stable.'
> Add CMSTP UAC Bypass via COM Object Access

- rules/windows/sysmon/sysmon_attrib_hiding_files.yml
In the Intel exclusion: CommandLine: '+R +H +S +A *.cui'
the asterisk is a literal asterisk in the commandline argument, not sure how to escape this?
> Hiding files with attrib.exe sysmon rule

- rules/windows/sysmon/sysmon_susp_certutil_command.yml
Below is an example of a test - the command line does not
include the path nor the .exe. I think this comes from the
initial detection on the Image path and the later switch to
command line.
We could also use both the Image path and the Command Line...
Message: 
Process Create:
Image: C:\Windows\SysWOW64\certutil.exe
CommandLine: certutil  xx -decode xxx
Hashes: SHA1=8186D64DD28CD63CA883B1D3CE5F07AEABAD67C0
ParentImage: C:\Windows\System32\cmd.exe
ParentCommandLine: "C:\Windows\system32\cmd.exe"
> Fix CommandLine in rule sysmon_susp_certutil_command

- rules/windows/powershell/powershell_malicious_keywords.yml
Parsed the MITRE ATT&CK informations from the rules. My script crashed because the identifier "T" was missing.
Thanks for your work Flo & Tom!
> Missing Character

- rules/windows/builtin/win_multiple_suspicious_cli.yml
I thinkg the group by is missing for this rule. For the detection it's important that these cli tools are started on the same machine for alerting.
> Add group by to windows multiple suspicious cli rule

- tools/sigmac
It's useful to have the sigma rule name which raised the execption.
When using sigmac with the recursive option for a directory and searching for the "not implemented" error, it's hard to find which rule raised the exception.
> Add rule filename to "not implemented" exception output

- tools/sigma/backends/powershell.py
Improve handling for default naming of event id's ("EventID") and source. This makes the config file for at least the event id optional. Due to the nature of event logs, without this change the powershell config file was mandatory for the event id, otherwiese the ID was matched against the wrong field. See https://github.com/Neo23x0/sigma/issues/94#issuecomment-424077049. For `Get-WinEvent` the parameter is always `-LogName` for the log source and `ID` for the event id.
> Improve default field handling in PowerShell backend

- Makefile
Fall back to `mktemp` if `tempfile` is not available. Fixes `make` on macOS for me.
> Use mktemp if tempfile is not available, fixes `make` for macOS

- tools/sigma/backends/base.py
Add code optimizing the boolean expressions in the abstract syntax tree before generating output using the backend.
The main idea behind optimizing the AST is that less repeated terms is generally better for backend performance.  This is especially relevant to backends that do not perform any query language optimization down the road, such as those that generate code.
The following optimizations are currently performed:
-   Removal of empty OR(), AND()
-   OR(X), AND(X)                 =>  X
-   OR(X, X, ...), AND(X, X, ...) =>  OR(X, ...), AND(X, ...)
-   OR(X, OR(Y))                  =>  OR(X, Y)
-   OR(AND(X, ...), AND(X, ...))  =>  AND(X, OR(AND(...), AND(...)))
-   NOT(NOT(X))                   =>  X
-   NOT(ConditionNULLValue)       => ConditionNotNULLValue
- …
> Optimize the boolean expressions in the AST before generating output

- tools/sigma/backends/elasticsearch.py
This change enables to let the xpack-watcher backend print each watcher object as one compress json per line without the curl command. This is useful for the integration of sigmac into other projects where only the watcher code is needed for further manipulation.
> Additional output mode "json" for the xpack-watcher backend

- tools/sigma/backends/elasticsearch.py
Hi @Neo23x0 @thomaspatzke 
Thanks for your great work, Sigma was really needed for blue teams.
I have added Elastalert backend (with aggregation support) to be able to use Sigma rules in our environment. This backend uses Elasticsearch QS backend for making the filters.
If you need more details or you see things to improve my code, feel free to ask 👍
> Add elastalert backend support

- tools/sigma/backends/splunk.py
Added dc() instead of count() when group-by field is present. Because count() doesn't do a distinct count in Splunk. Must be the dc() function instead.
> Distinct count in aggragation function

- rules/windows/builtin/win_eventlog_cleared.yml
- rules/windows/builtin/win_rare_schtasks_creations.yml
- rules/windows/builtin/win_rare_service_installs.yml
- rules/windows/builtin/win_susp_commands_recon_activity.yml
- rules/windows/malware/av_relevant_files.yml
- rules/windows/powershell/powershell_xor_commandline.yml
- rules/windows/sysmon/sysmon_plugx_susp_exe_locations.yml
I'm pushing Elastalert rules to HELK, and while transforming rules from SIGMA to Elastalert format with Sigmac, I had to updated several rules due to:
* Duplicate Rule names (SIGMA rules with the same title)
* "count() by FIELDNAME" statements added to replace "count(FIELD_NAME)"
> Elastalert Integration Updates to SIGMA Rules

- tools/config/sumologic.yml
- tools/setup.py
- tools/sigma/backends/sumologic.py
Adding Sumologic backend - https://www.sumologic.com/
Inside Sumologic, there is no default field mapping. It's either done at ingestion with Field Extraction Rules (FER) defined by customer, either at parsing, meaning it is arbitrary per customer.
If you want to use generated output, either support the same FER, either review field mappings.
Things missing
* adding _index=<INDEX> or _sourceCategory=<VAL> as prefix. required for efficient processing if no FER
* implement timeframe. It seems currently only elasticsearch backend has it and was not sure how to map it. Sumologic has a timeslice operator
https://help.sumologic.com/05Search/Search-Query-Language/Search-Operators/timeslice
* Sumologic has no regex match in its basic search. It is done after initial search with 'parse regex' …
> Adding Sumologic backend

- rules/windows/builtin/win_hack_rubeus.yml
- rules/windows/builtin/win_net_ntlm_downgrade.yml
- rules/windows/sysmon/sysmon_cmdkey_recon.yml
- rules/windows/sysmon/sysmon_susp_reg_persist_explorer_run.yml
- rules/windows/sysmon/sysmon_susp_tscon_localsystem.yml
- rules/windows/sysmon/sysmon_susp_tscon_rdp_redirect.yml
As per the Sigma standard here:
https://github.com/Neo23x0/sigma/wiki/Specification
Changed all tags named "reference" to "references".
> Corrected reference to references as per Sigma's standard

- .yamllint
- rules/windows/builtin/win_susp_commands_recon_activity.yml
- tools/config/arcsight.yml
Fix the yamllint config in `.yamllint` to "extend" the default rule.
Previously, it didn't extend anything and only disabled a rule, which
means no rule at all were checked.
Also disable some rules in this file, because they report many errors in
the Sigma code base.
In the future, I suggest fixing these errors and re-enabling standard
rules like `trailing-spaces` or `indentation`.
Fixes #220.
---
Especially the config for ArcSight, that was invalid:
tools/config/arcsight.yml
89:5      error    duplication of key "product" in mapping  (key-duplicates)
90:5      error    duplication of key "conditions" in mapping  (key-duplicates)
rules/windows/builtin/win_susp_commands_recon_activity.yml
10:9      error    too many spaces after colon  (colons)
> Fix yamllint config

- tools/config/qradar.yml
- tools/sigma/backends/qradar.py
This PR will bring the option for Qradar timeframe. It's not a hard requirement so timeframe query will only be generate if the users have specifically picked timeframe: 7d for example.
```
title: Rare Service Installs
description: Detects rare service installs that only appear a few times per time frame and could reveal password dumpers, backdoor installs or other types of malicious services 
status: experimental
author: Florian Roth
tags:
- attack.persistence
- attack.privilege_escalation
- attack.t1050
logsource:
service: system
detection:
selection:
EventID: 7045
timeframe: 7d
condition: selection | count() by ServiceFileName < 5 
falsepositives: 
- Software installation
- Software updates
level: low
```
```
SELECT count(None) as agg_val from events where …
```
> extending the qradar backend to allow for timeframe query

- rules/windows/sysmon/sysmon_susp_certutil_command.yml
* Certutil switches can be called like `/verifyctl`, not just like `-verifyctl` that we were currently monitoring.
* Since the above change would extend (double) the number of command lines we monitor, and to better protect against renamed `certutil`, made CommandLine detections more generic (not requiring `certutil` string in most cases). This produced very few false positives in a large production environment. 
* Added `encode` switch which can be used to base64 encode files for stealth during collection/exfiltration.
I'm open to switching the CommandLine matches to a regex match to simplify the detection, but wasn't sure about the performance hit. Thoughts?
> Added '/' prefix, -encode switch, better renamed certutil coverage

- tools/sigma/backends/splunk.py
When no field is present, use "count" , when field is present use "dc(field)". As described in the Sigma specifications.
Splunk throws errors when using "count()" with empy fields. use "count" instead.
> Adapt count function when aggfield not present

- rules/windows/builtin/win_psexesvc_start.yml
- rules/windows/sysmon/sysmon_win_reg_persistence.yml
- tests/test_rules.py
I added a test for when a rule uses "1/all of them" style conditions but only has one named condition. 
This one is not a big deal but at least it keeps things consistent.
> Unnecessary 1/all of them

- rules/windows/malware/av_exploiting.yml
McAfee classifies some Meterpreter events with the "Mpreter" keyword
> adding MPreter as McAfee classifies it

- rules/windows/sysmon/sysmon_malware_backconnect_ports.yml
If the destination is a private IP, it's most probably not a malware connect back.
> Added private IP filter to reduce FPs

- rules/windows/sysmon/sysmon_sysinternals_eula_accepted.yml
Mostly inspired by "Ps.exe Renamed SysInternals Tool". This provides another method to detect Sysinternals tools if the registry change was missed for whatever reason.
Tested. Only fires on what it should fire on.
> Added a detection path through process spawn

- rules/windows/sysmon/sysmon_susp_vssadmin_ntds_activity.yml
Added esentutl command to sysmon_susp_vssadmin_ntds_activity.yml to detect attempts to copy ntds.dit. Note that the vss flag is only supported on win10 and windows 2016. 
Saw in a tweet from @bohops and @grayfold3d this morning, seemed like a good thing to add to the rule.
> Added esentutl copy command to sysmon_susp_vssadmin_ntds_activity.yml

- rules/apt/apt_apt29_thinktanks.yml
- rules/apt/apt_cloudhopper.yml
- rules/apt/apt_dragonfly.yml
- rules/apt/apt_elise.yml
- tests/test_rules.py
Added a new test to check if a rule still uses Sysmon 1 or EID 4688. The test does not cause a failure since there are a number of rules that still need updating.
Also, updated four rules to use process_creation, though I quickly realized I need to automate the conversion somehow since the process is so error prone.
> Process create

- tools/sigma/backends/elasticsearch.py
This PR adds:
- The ability to have multiple alert types in the generated elastalert alert
- Support for the [HTTP POST](https://elastalert.readthedocs.io/en/latest/ruletypes.html#http-post) elastalert alert type
With a simple rule `logs_cleared.yml`:
```yaml
title: Windows security event logs cleared
description: Detects when security logs are cleared
tags:
- defense evasion
logsource: 
detection:
selection: 
EventID: 1102
level: high
```
```
$ python3 tools/sigmac logs_cleared.yml -c config.yml \
-t elastalert \
-O alert_methods=http_post \
-O http_post_url=http://127.0.0.1:4444 \
-O http_post_include_rule_metadata
```
Result:
```yaml
alert:
- post
description: Detects when security logs are cleared
filter:
- query:
query_string:
query: …
```
> Add HTTP POST alert type to the Elastalert backend (closes #256)

- rules/windows/process_creation/win_office_shell.yml
Cybereason link was broken. Couldn't find anything with a super similar file path. The below link might be a valid replacement but went better safe than sorry and just removed it completely. https://www.cybereason.com/hubfs/Cybereason%20Labs%20Analysis%20Operation%20Cobalt%20Kitty-Part1.pdf
> Remove invalid link

- rules/apt/apt_chafer_mar18.yml
- rules/apt/apt_pandemic.yml
- rules/apt/apt_ta17_293a_ps.yml
- rules/apt/apt_zxshell.yml
- rules/apt/crime_fireball.yml
- rules/windows/other/win_tool_psexec.yml
- rules/windows/sysmon/sysmon_cmstp_execution.yml
- rules/windows/sysmon/sysmon_dns_serverlevelplugindll.yml
- rules/windows/sysmon/sysmon_logon_scripts_userinitmprlogonscript.yml
- rules/windows/sysmon/sysmon_stickykey_like_backdoor.yml
- rules/windows/sysmon/sysmon_sysinternals_eula_accepted.yml
- rules/windows/sysmon/sysmon_uac_bypass_eventvwr.yml
- tests/test_rules.py
In this pull request:
- Migrated the last detection strategies to the new process_creation log source
- Enabled test for Sysmon 1 / EID 4688 instead of process_creation
Also, I still have a few tests I'd like to implement but I would love to hear what rule tests you guys would find useful. Tweet at me here:
https://twitter.com/alkhatib_tareq
> Migrated the last detections to process_creation

- rules/windows/builtin/win_mal_creddumper.yml
- rules/windows/process_creation/win_multiple_suspicious_cli.yml
forgot to delete event id from wrong logsource last time. 
for some reason if we use simple "selection and ..." condition second document with logsource security / eid 4697 is not involved into final generated query (in case both documents have just "selection"). So decided to create multiple sections (1/2) and explicitly define them in condition.
Please let me know if there is simpler option.
update: `nbstat.exe` changed to `nbtstat.exe` in [Quick Execution of a Series of Suspicious Commands](https://github.com/Neo23x0/sigma/blob/99b15edf8add183543ca5738ec93f87416c34bd9/rules/windows/process_creation/win_multiple_suspicious_cli.yml) rule
> updated detection logic

- rules/apt/apt_turla_service_png.yml
Fixed tagging in Turla PNG Dropper Service rule with correct group (Turla, `attack.g0010`) and technique usage (New Service, `attack.t1050`).
> fix tagging in turla png dropper service rule

- tools/sigma/backends/base.py
- tools/sigmac
As suggested in #213, this PR adds the possibility to take backend options from a configuration file, which should simplify the CLI usage.  
One can specify both individual backend options (`--backend-option`) and specify a configuration file as well - in this case, options are merged, and priority is given to the options passed via the CLI.
Sample usages:
```bash
$ cat backend_config.yml 
emails: alerts@mydomain.tld
smtp_host: smtp.google.com
from_addr: noreply@mydomain.tld
expo_realert_time: 10m
$ RULE=rules/windows/builtin/win_susp_sam_dump.yml
$ python3 tools/sigmac $RULE -t elastalert --backend-config backend_config.yml
alert:
- email
description: Detects suspicious SAM dump activity as cause by QuarksPwDump and other
password dumpers
email:
- alerts@mydomain.tld
filter:
- query: …
```
> Accept backend options from a configuration file (closes #213)

- rules/windows/sysmon/sysmon_stickykey_like_backdoor.yml
Remove backslashes in CommandLine for sticky key rule to match command line which is exactly "cmd.exe sethc.exe 211" after triggering the backdoor. The detection with *\cmd.exe... would not match.
> Remove backslashes in CommandLine for sticky key rule

- rules/linux/lnx_shell_clear_cmd_history.yml
I developed a new signature for linux in order to detect, when the command history was cleared for defense evasion. The signature was tested with Atomic Test T1146, https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1146/T1146.yaml .
> Add new signature for linux clear command history

- rules/windows/process_creation/win_susp_powershell_enc_cmd.yml
Remove easy to bypass CommandLine and environment-specific filter.
> Remove loose wildcard filter in powershell encoded cmd rule

- rules/windows/process_creation/win_susp_svchost.yml
Adding rpcnet.exe as ParentImage for legit spawn of svchost.
> Update win_susp_svchost rule

- rules/windows/process_creation/win_system_exe_anomaly.yml
Restrict whitelist filter to exact system directories in where the binaries are located. Otherwise, an attacker only has to place his binaries inside a sub-folder called System32 or SysWow64 and would therefore bypass this valuable generic rule.
Is there a reason to use less restricted filters here?
This one like the other PRs is an output of my in-depth analysis of wildcards used in filters: https://github.com/Karneades/SigmaFilterCheck.
> Restrict filter in system exe anomaly rule

- rules/windows/process_creation/win_mshta_spawn_shell.yml
I know there are HP printers which trigger this detection rule. But such loose filters allow simple bypasses.
```
mshta vbscript:CreateObject("wscript.Shell").Run("wscript.exe test.js /HP/HP")
```
| Field | Value |
| ------------- | ------------- |
| ParentImage |  C:\Windows\System32\mshta.exe  |
| CommandLine | "C:\Windows\System32\wscript.exe" test.js /HP/HP |
> Remove too loose filter in mshta rule

- rules/windows/process_creation/win_susp_gup.yml
We should remove such a loose filter as default filter (`'*\updater\*'`).
Instead of removing the filter completely, we could make a more restricted filters for default Notepad++ installation paths. According to [Notepad++ Install Folder](http://docs.notepad-plus-plus.org/index.php/Notepad%2B%2B_Install_Folder) folders are typically ` %APPDATA%\Notepad++\` or `C:\Program Files\Notepad++\`. But filtering for AppData may again be more dangerous than it might help.
> Remove too loose filter in notepad++ updater rule

- rules/windows/builtin/win_user_creation.yml
The creation of a new user creates a Windows Event Log of Type Security with the Event Code 4720. In an AD environment, only domain controller should create these Windows Event Logs. If these logs are seen from non domain controller, this is an indicator of compromise.
https://patrick-bareiss.com/detecting-local-user-creation-in-ad-with-sigma/
> New Sigma rule detecting local user creation

- rules/linux/lnx_shell_priv_esc_prep.yml
I created a new detection rule, which detects the preparation steps for privilege escalation under Linux. A comprehensive list of commands to enumerate a potential flaw can be found here:
https://blog.g0tmi1k.com/2011/08/basic-linux-privilege-escalation/
I wrote a blog article about it for more information:
https://patrick-bareiss.com/detect-privilege-escalation-preparation-in-linux-with-sigma/
The aggregation function count() is used, which is fine for this detection rule. A distinct count would be even better but I got parser errors running the | dc() by host > 6 .
> Added Sigma Use Case detecting Privilege Escalation Preparation in Linux

- rules/network/net_dns_c2_detection.yml
I created a new Sigma detection rule, which should detect malicious C2 communication over DNS. The idea is to distinct count the number of dns query per parent domain. If this value is huge, it is an indicator that the dns queries are used to transfer data.
> New C2 DNS Tunneling Sigma Detection Rule

- tools/sigma/backends/elasticsearch.py
It looks like the parenthesization generated by the ES-QS backend is insufficient when the query contains multiple expressions.
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html
> The familiar boolean operators AND, OR and NOT (also written &&, || and !) are also supported but beware that they do not honor the usual precedence rules, so parentheses should be used whenever multiple operators are used together
Use the rule:
```yaml
title: Sample rule
tags: []
logsource:
service: sysmon
detection:
process_creation:
EventID: 1
excluded_paths:
Image:
- 'C:\\\\Windows*'
ms_utils:
Image:
- 'C:\\\\Windows\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe'
condition: process_creation and (ms_utils or not excluded_paths) …
```
> Correct parenthesization for NOT expressions in the ES-QS backend

- rules/windows/process_creation/win_system_exe_anomaly.yml
While merging https://github.com/Neo23x0/sigma/pull/321 the filter explorer's default path got lost and that generates a lot of events :)
> Add default path for explorer to filter in exe anomaly rule

- tools/sigma/backends/elasticsearch.py
I noticed that in some cases, it is desirable to allow generating Elastalert rules with the `http_post` alert type without a `http_post_url` set. This is because you don't necessarily know at compile-time where Elastalert will send alerts, which is something you might want to specify later, in the elastalert configuration file. This is especially true if you compile a sigma rule once but use it in several elastaler environments
Example before the patch:
```yaml
$ ./tools/sigmac -O alert_methods=http_post -t elastalert sample.sigma
alert:
- debug
description: ''
filter:
- query:
query_string:
query: EventID:"1102"
index: logstash-*
name: Detect-event-logs-cleared_0
priority: 2
realert:
minutes: 0
type: any
```
After the patch:
```yaml
$ ./tools/sigmac -O alert_methods=http_post -t …
```
> Allow generating Elastalert rules with the http_post alert type without specifying a URL at generation time

- rules/windows/process_creation/win_office_spawn_exe_from_users_directory.yml
I'm unable to parse `rules/windows/process_creation/win_office_spawn_exe_from_users_directory.yml` because the reference list is not parsable as string list.
With Golang's YAML Unmarshaler I get the following error: 
```
yaml: unmarshal errors:  line 5: cannot unmarshal !!map into string
```
> fix: fixed reference list, otherwise it's not valid string list

- tools/sigma/backends/elasticsearch.py
From ElasticSearch 7.0, the URI to access to Watcher API changes
Deprecation: [PUT /_xpack/watcher/watch/{id}] is deprecated! Use [PUT /_watcher/watch/{id}] instead.
> New URI for watcher (ES v7+)

- rules/windows/builtin/win_rdp_potential_cve-2019-0708.yml
Hi,
It's rule for detect potential exploit of CVE-2019-0708 in event windows. Rule is based on event created (http://www.eventid.net/display-eventid-56-source-TermDD-eventno-9421-phase-1.htm)  when use scan CVE-2019-0708 (https://github.com/zerosum0x0/CVE-2019-0708).
Sincerly.
Lionel & Christophe
> Add rule for CVE-2019-0708

- tools/sigma/backends/elasticsearch.py
While utilizing Kibana to track watches directly from the watch index it became quickly apparent that useful metadata was not available. In my project's case it was the title, description and tags from the sigma rule. By adding them to the metadata field it makes it easier to utilize them in visualizations of the watches themselves. In the future perhaps the contents of the metadata field could be given as an option for each user.
> added metadata field to the watcher alert

- tools/sigma/backends/elasticsearch.py
When only one `condition` exists `filter` doesn't use a `must` array.
When `timeframe` exists, it tries to push the condition in a `must` array and create it first if it doesn't exists replacing the single condition.
```
$ tools/sigmac --target es-dsl --config tools/config/elk-winlogbeat.yml rules/windows/builtin/win_rare_service_installs.yml
{
"query": {
"constant_score": {
"filter": {
"bool": {
"must": [
{
"range": {
"date": {
"gte": "now-7d"
}
}
}
]
}
}
}
},
"aggs": {
"event_data.ServiceFileName_count": {
"terms": {
"field": "event_data.ServiceFileName"
},
"aggs": {
"limit": {
"bucket_selector": {
"buckets_path": {
"count": "_count"
},
"script": "params.count < 5"
}
}
}
}
}
}
```
`EventID: 7045` disappeared
```
$ tools/sigmac --target es-dsl --config tools/config/elk-winlogbeat.yml …
```
> fix missing condition when unique plus timeframe

- rules/windows/sysmon/sysmon_mimikatz_detection_lsass.yml
GrantedAccess is 0x1010 not 0x1410 in recent versions of mimikatz.
This modification should address both
> Add detection for recent Mimikatz versions

- rules/windows/sysmon/sysmon_renamed_binary.yml
Detects the execution of a renamed binary often used by attackers or malware leveraging new Sysmon OriginalFileName datapoint.
> Sigma/Add Sysmon Renamed Binary

- contrib/sigma2elastalert.py
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.
[flake8](http://flake8.pycqa.org) testing of https://github.com/Neo23x0/sigma on Python 3.7.1
$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./contrib/sigma2sumologic.py:123:5: F821 undefined name 'parser_print_help'
parser_print_help()
^
./contrib/sigma2sumologic.py:211:32: F821 undefined name 'r'
f.write(json.dumps(r, indent=4, sort_keys=True) + " ERROR: %s\n\nQUERY: %s" % (e, sumo_query))
^
./contrib/sigma2elastalert.py:165:32: E999 SyntaxError: invalid syntax
print "Converting file " + file
^
./tools/sigma/parser/collection.py:52:27: F821 undefined name 'SigmaCollectionParseError'
raise SigmaCollectionParseError("action …
```
> Use print() function in both Python 2 and Python 3

- tools/config/elk-winlogbeat-old.yml
- tools/config/elk-winlogbeat.yml
Fix #384 .
In this version I kept two version of the file, one old (pre-version 7 of winlogbeat) and one new (post version 7 of winlogbeat) version of the config file. Does it make sense? If it is the case, how should we name the files?
> Modified winlogbeat config to adhere to winlogbeat 7 field names

- rules/windows/sysmon/sysmon_win_binary_susp_com.yml
Relevant when directly retrieving pentest tools from github, e.g. Powershell mafia & co
> Include Github raw URLs in suspicious downloads detection rule

- tools/sigma/backends/elasticsearch.py
From https://docs.graylog.org/en/3.0/pages/upgrade/graylog-2.5.html
> Before Elasticsearch 6, queries for keyword fields were split by whitespaces and combined with OR operators resulting, for example, in type:(ssh login) and type:(ssh OR login) being equivalent. This is no longer the case in Elasticsearch 6 and now those queries are different: the former looking for the ssh login value, the second for either ssh or login values.
This is an issue with the queries generated by sigma. For instance, the following rule:
```yml
detection:
selection:
EventID:
- 4624
- 4625
```
.. translates into
```bash
$ ./tools/sigmac -t es-qs test.rule -c config.yaml
EventID:("4624" "4625")
```
Which for ES 5.x is functionally equivalent to `if (EventID == '4624' || EventID == '4625')`, …
> Support OR queries for Elasticsearch 6 and above

- rules/windows/builtin/win_susp_dhcp_config_failed.yml
This prevents EventID collision for this rule with other sources/logs that share the same EventIDs.
specifically a lot with Microsoft-Windows-Security-SPP
> prevent EventID collision for dhcp

- rules/windows/builtin/win_susp_dhcp_config_failed.yml
Hello guys!
We've been testing that rule and noticed a typo.
We believe that this is a typo, because in a similar [rule](https://github.com/Neo23x0/sigma/blob/a82ea0a02238952d3e7f50d18d0a291f222e4411/rules/windows/builtin/win_susp_dhcp_config.yml) from the same author service is `system` (which represents channel) and for all events listed in original rule (1031, 1032, 1034) channel is `system`, not `dhcp`:
You can find event samples in [original article](https://blog.3or.de/mimilib-dhcp-server-callout-dll-injection.html) from Dimitrios Slamaris @dim0x69 : 
(`System` provider mentioned in a corresponding field)
Here is a screenshot from [WELM project](https://github.com/nsacyber/Windows-Event-Log-Messages) dataset analysis:
(`System` provider mentioned in the first column)
> Win susp dhcp config failed fix

- rules/windows/process_creation/win_mmc_spawn_shell.yml
- rules/windows/process_creation/win_susp_mmc_source.yml
Fix generic process dedection rule: remove cmd.exe filter to match what title says: detect all processes created by MMC.
Add (analog to [win_mshta_spawn_shell.yml](https://github.com/Neo23x0/sigma/blob/master/rules/windows/process_creation/win_mshta_spawn_shell.yml) a dedicated rule for dedecting MMC spawning a shell. And it covers the (removed) cmd part from the existing rule [win_susp_mmc_source.yml](https://github.com/Neo23x0/sigma/blob/master/rules/windows/process_creation/win_susp_mmc_source.yml).
> Improve MMC rules: fix generic rule and add new rule for shell spawning

- rules/windows/sysmon/sysmon_powersploit_schtasks.yml
Add default task name and powershell task command to match what the rule name says: detects default config.
We could also remove the "updater" name, to be more flexibel to catch a custom task name. It shouldn't give a lot FPs.
> improve(rule): add Empire links and userland match

- tools/sigma/backends/elasticsearch.py
Slashes within wildcard queries were not being escaped resulting in incorrect DSL queries.
See https://github.com/Neo23x0/sigma/issues/387 for more info
> Correctly escape slashes within es-dsl wildcard queries (issue #387)

- rules/windows/builtin/win_susp_add_sid_history.yml
Hello guys!
We've improved this rule simulating malicious behaviour and analysing available artifacts. 
For some reason we couldn't trigger Event IDs 4765 and 4766, now we are under investigation about that case. 
But during modification of SIDHistory we've notices another event — 4738, and it has quite specific field which could be used for that kind of changes detection — `SidHistory`. 
When SID History is added, it just provide list of SID's in SidHistory attribute:
In case of cleaning SIDHistory OS generates 4738 event with "%%1793" value ("value not set") in SIDHistory field:
In case of other events (like password update) OS generates 4738 events with "-" value in SIDHistory field:
xml events attached:
[xml_logs.log](https://github.com/Neo23x0/sigma/files/3399684/xml_logs.log)
> Win susp add sid history improvement

- rules/windows/process_creation/win_sdbinst_shim_persistence.yml
A shim database can be loaded from any path, not just AppPatch. I updated the rule to trigger on any sdb installation. `sdbinst.exe` should be rare enough in most environments to trigger on its execution alone, but I'm keeping the file to stay on the safe side.
> Fixed commandline to detect any shim install from any location

- rules/windows/powershell/powershell_malicious_commandlets.yml
- rules/windows/sysmon/sysmon_renamed_powershell.yml
rules about `renamed powershell `exist twice :
` rules/windows/sysmon/sysmon_renamed_powershell.yml`
`rules/windows/process_creation/win_powershell_renamed_ps.yml`
alert level also differs in rules:
in sysmon: **critical**
in process_creation : **high**
1 of the 2 rules could  be deleted?
fix on `powershell_malicious_commandlets.yml  `is about `Get-SystemDriveInfo`which matches `Get-System`
> powershell false positives

- tools/sigma/backends/elasticsearch.py
The es-dsl backend supports the configuration option "dateField" that determines the name of the field used for a specific time-range (a more detailled description: ref #402).
In this commit I add the same logic to the xpack-watcher backend.
> Use configuration option "dateField" in xpack watcher 

- rules/linux/lnx_shell_priv_esc_prep.yml
Attackers may look to exploit binaries with the sticky bits enabled.  By being able to run a binary as a different user or group, they may be able to run separate commands as an elevated user.
> Added Sticky Bits

- rules/windows/process_creation/win_susp_taskmgr_parent.yml
… privileges (show processes from all users --> UAC) and its parent is still the old taskmgr
happens on "old" systems (win7, win2008)
> Sysmon rules cleanup and move to process_creation

- rules/proxy/proxy_chafer_malware.yml
- rules/proxy/proxy_ios_implant.yml
Hi all
These two rules used the URI Query Field for detection and checked against those two strings in this field:
- '*/asp.asp?ui=*'
- '*/list/suc?name=*'
But by definition the URI Query part starts at "?ui=*" respectively "?name=*". Therefore there would never be a match of this rule if the SIEM parses the URL correctly into a query and path part. I changed the detection field to "URL" to get a match.
Andi
> rule: changed two proxy rules from uri-query to url

- Makefile
- tools/config/limacharlie.yml
- tools/setup.py
- tools/sigma/backends/limacharlie.py
This adds a new backend to convert rules to LimaCharlie.io [D&R rules](https://doc.limacharlie.io/en/master/dr/).
The D&R rules are like AWS lambda applied to data from endpoint (either native LC events, or External Logs like Windows Event Logs).
This changes a bit the meta of a Sigma backend. Instead of generating a search query for a more-or-less generic log viewer, it generates "D&R rules" for specific event types in LC.
It means we support multiple Sigma rule "products", and for each ones we attempt to convert the various selector values into the specific LC event type and the specific relevant LC fields (all LC events are JSON).
The drawback of all this is that it means we can't use the current Sigma config file model (as far as I can tell, but I may be wrong) because of the wide …
> Adding Backend for LimaCharlie D&R rules

- rules/windows/other/win_wmi_persistence.yml
> fix: bound keywords to field in WMI persistence rule

- rules/windows/powershell/powershell_prompt_credentials.yml
> fix: bound keywords to field in PS cred prompt rule

- rules/windows/builtin/win_alert_active_directory_user_control.yml
- rules/windows/builtin/win_alert_enable_weak_encryption.yml
- rules/windows/builtin/win_alert_mimikatz_keywords.yml
- rules/windows/builtin/win_av_relevant_match.yml
- rules/windows/builtin/win_mal_creddumper.yml
- rules/windows/builtin/win_susp_msmpeng_crash.yml
- rules/windows/builtin/win_susp_sam_dump.yml
See #501.
Fixed rules
- rules/windows/builtin/win_susp_msmpeng_crash.yml
- rules/windows/builtin/win_alert_active_directory_user_control.yml
- rules/windows/builtin/win_av_relevant_match.yml
- rules/windows/builtin/win_mal_creddumper.yml
- rules/windows/builtin/win_susp_sam_dump.yml
- rules/windows/builtin/win_alert_mimikatz_keywords.yml
- rules/windows/builtin/win_alert_enable_weak_encryption.yml
> fix: bound windows event log rules to message field

- rules/windows/sysmon/sysmon_logon_scripts_userinitmprlogonscript.yml
See #501.
I had to slightly change the condition logic because until now we used different event ids with different fields - therefore I split the condition and field mapping.
Fixed rule:
- rules/windows/sysmon/sysmon_logon_scripts_userinitmprlogonscript.yml
> fix: bound sysmon logon script rule to field

- tools/sigma/backends/limacharlie.py
Many refactors to ready the backend to generate rules ready for production use in LimaCharlie.
This targets the Process Creation category of rules primarily since they translate to LC easily.
High level changes:
- Implemented a new conversion of wildcard-string to proper Operator use and regular expression. This implementation is a bit more messy than the previous one, but as far as we can tell it is now correct in all cases. The previous one generated many invalid sequences in existing rules. We will see how it goes but might do a PR later on to port it to the WDATP backend (where we took the old implementation) to fix it.
- Support "keyword" searches on more event types.
- Many fixes.
> LimaCharlie Productionization

- tools/sigma/backends/limacharlie.py
Adding support for basic proxy rules using the HTTP_REQUEST events from the Chrome LC Agent.
> LimaCharlie basic support for Proxy rule category.

- Makefile
Add sdist when building. This makes it easier to build packages from PyPi for example Debian PPA pkgs etc.
This will not affect anything else, just make the source distribution available in PyPi as a tar.gz archive.
If this gets merged, please bump the version and push to PyPi as well.
> Add source distribution for PyPi when building

- rules/windows/builtin/win_pass_the_hash_2.yml
- rules/windows/powershell/powershell_data_compressed.yml
- rules/windows/process_creation/win_data_compressed_with_rar.yml
Some duplicate rule titles are causing Elastalert to error on duplicate rule names.
> Elastalert error, duplicate rule titles

- CHANGELOG.md
The release date for the version should be added to each section (_The release date of each version is displayed_ is one of the guiding principles in _Keep a Changelog_.). It helps when reading the changelog.
FTR I used `git log --tags --simplify-by-decoration --pretty="format:%ci %d"` for getting the dates.
> Add release date for each version in changelog

- tests/test-backend-es-qs.py
- tools/requirements-devel.txt
- tools/sigma/backends/elasticsearch.py
- tools/sigma/parser/condition.py
- tools/tests/test_backend_elasticsearch.py
- tools/tests/test_parsing.py
Currently, the converter does not support the following condition for elasticsearch backend.
```
count(MyDistinctFieldName) by MyGroupedField > X
```
The current PR fixes the above aggregation case for ES-DSL backend according to the specifications, see https://github.com/Neo23x0/sigma/wiki/Specification#condition
Adjust code in `generateAggregation` method to check if the aggregation count field is set.
```
cd tools/
python -m pytest tests/
```
Tested locally by installing the package and run the conversion.
1. Install Sigma converter `pip install sigmatools==0.12.1`
2. Checkout Sigma repo (b6f94b1352597e8386a0509e5f87b298ed139096)
3. Run the following from the root directory of the repository.
```bash
sigmac --target es-dsl -c tools/config/winlogbeat.yml …
```
> [feature] extend es-dsl to support nested aggregations

- rules/windows/powershell/powershell_malicious_commandlets.yml
PowerUp allow attackers to check if is possible to have a local privilege escalation attacks against Windows systems. The main function is called "Invoke-AllChecks" and check possible path of escalation.
> Add the ability to detect PowerUp - Invoke-AllChecks

- rules/windows/process_creation/win_system_exe_anomaly.yml
Following an event with @maximelb , we have noticed \SystemRoot\System32\ is missing from the valid paths. This fork is a fix adding it to the paths.
Also, fun fact.
The original rule is referencing to one of my tweets: https://twitter.com/GelosSnake/status/934900723426439170
Closing circles and good cyber karma to us all.
> FP in win_system_exe_anomaly.yml

- tools/sigma/backends/limacharlie.py
LimaCharlie is adding a new `event/ORIGINAL_FILE_NAME` field which maps to the OriginalFileName in various Sigma rules.
> Adding LimaCharlie support for OriginalFileName field.

- tools/config/helk.yml
typo in network_initiated that included an ending `"`
> HELK SIGMAC fix name of network_initiated

- rules/windows/sysmon/sysmon_mal_namedpipes.yml
Covenant (https://github.com/cobbr/Covenant) can use named pipes for peer to peer communication.
The default named pipe name is "\gruntsvc".
References: https://posts.specterops.io/designing-peer-to-peer-command-and-control-ad2c61740456
> Add Covenant default named pipe

- .gitignore
- rules/windows/process_creation/win_apt_gallium.yml
sha1 process creation only makes sense for sysmon.
Add gallium ttp related to softether vpn binary located under an unusual file path.
> additional gallium ttp

- rules/cloud/aws_ec2_download_userdata.yml
- rules/cloud/aws_ec2_startup_script_change.yml
- rules/cloud/aws_guardduty_disruption.yml
- rules/cloud/aws_iam_backdoor_users_keys.yml
- rules/cloud/aws_rds_change_master_password.yml
- rules/cloud/aws_rds_public_db_restore.yml
More rules for the AWS environment. 
These rules can be used to detect potential exploits by scripts and tools like [Pacu](https://github.com/RhinoSecurityLabs/pacu).
Each rule has a reference to a specific exploit available as part of Pacu.
New rules:
1. Downloading of User Data associated with AWS EC2 instances
1. Change of startup shell script for AWS EC2 instances
1. AWS GuardDuty disruption to avoid detection
1. Change the master password of an AWS RDS database instance
1. Backdoor of users AWS API keys
1. Restore AWS RDS db instance from a snapshot with public access
> More rules for AWS events

- rules/network/zeek_susp_kerberos_rc4.yml
- tools/config/splunk-zeek.yml
Added a rule to detect Kerberos TGS requests with rc4-hmac encryption in Zeek logs.  As well as a log source config for Zeek logs in Splunk.
rules/network/zeek_susp_kerberos_rc4.yml
tools/config/splunk-zeek.yml
> rule: Zeek Suspicious kerberos network traffic RC4

- rules/windows/process_creation/win_service_stop.yml
rule `win_service_stop `is about services being stopped
taskkill, on the other hand, can be called in a lot of contexts and generate a lot of false positives
> fix false positive on taskkill.exe not related to service stop at all

- rules/windows/process_creation/win_local_system_owner_account_discovery.yml
got a FP matching on 'rmdir' whereas 'dir' is intended in the rule
> rule local account discovery: fix FP on rmdir matching dir

- rules/web/web_exchange_cve_2020_0688_exploit.yml
New rule to detect exploitation of [CVE 2020-0688](https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2020-0688), based on the PoC at https://github.com/Ridter/cve-2020-0688
> CVE 2020-0688 Exploit attempt rule

- rules/windows/process_creation/win_susp_eventlog_clear.yml
- rules/windows/process_creation/win_susp_fsutil_usage.yml
rule was initially `'* cl *'`
with the current  status, it matches on `'*cl*'` (without space around cl)
restore it to its original behaviour
here's a false positive that matched the wrong rule as there is 'cl' in ClickToRun :
`wevtutil.exe im "C:\ProgramData\Microsoft\ClickToRun\....`
More generally, there seem to be quite some rules that got rewritten with `"|contains" ` and just the pattern` 'XX'` in quotes whereas it initially was `'* XX *'` with spaces
The "new" rules will, IMHO, generate a lot more false positives and would need to be patched accordingly
> Rule: restore initial behaviour matching single word with spaces on each side

- rules/windows/process_creation/win_mal_adwind.yml
- rules/windows/sysmon/sysmon_apt_pandemic.yml
- rules/windows/sysmon/sysmon_uac_bypass_eventvwr.yml
- rules/windows/sysmon/sysmon_uac_bypass_sdclt.yml
(see sysmon changelog  here : https://github.com/Neo23x0/sysmon-version-history#v60
```
Release date: 17.02.2017
...
interprets and displays registry paths in their common format
...
```
https://github.com/SwiftOnSecurity/sysmon-config/blob/master/sysmonconfig-export.xml#L547
`Schema version 3.30 and higher change HKLM\="\REGISTRY\MACHINE\" and HKU\="\REGISTRY\USER\" and HKCR\="\REGISTRY\MACHINE\SOFTWARE\Classes\" and CurrentControlSet="ControlSet001"-->`
> fix sysmon registry rules with HKLM/HKU format as used since 02/2017 in sysmon

- rules/windows/builtin/win_ad_replication_non_machine_account.yml
As described in [Microsoft's documentation](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/reference-connect-accounts-permissions#ad-ds-connector-account) the MSOL_xxx account is used for synchronization, resulting in false positives for the "Active Directory Replication from Non Machine Account" rule.
> Exclude Azure AD sync accounts from AD Replication rule

- rules/windows/sysmon/sysmon_apt_oceanlotus_registry.yml
- rules/windows/sysmon/sysmon_disable_security_events_logging_adding_reg_key_minint.yml
- rules/windows/sysmon/sysmon_new_dll_added_to_appcertdlls_registry_key.yml
- rules/windows/sysmon/sysmon_new_dll_added_to_appinit_dlls_registry_key.yml
- rules/windows/sysmon/sysmon_registry_persistence_key_linking.yml
- rules/windows/sysmon/sysmon_susp_reg_persist_explorer_run.yml
- rules/windows/sysmon/sysmon_suspicious_keyboard_layout_load.yml
- rules/windows/sysmon/sysmon_uac_bypass_sdclt.yml
- fix some rules with data as received by Sysmon and not it appears in hives or reports
- performance fix (patch rules with `startswith` `contains` and `endswith` with only 1 check, might have better performance in backend SIEMs)
> sysmon registry events fix

- rules/web/web_citrix_cve_2019_19781_exploit.yml
- rules/web/web_cve_2018_2894_weblogic_exploit.yml
- rules/web/web_multiple_suspicious_resp_codes_single_source.yml
- rules/web/web_pulsesecure_cve-2019-11510.yml
- rules/windows/builtin/win_rare_schtasks_creations.yml
- rules/windows/builtin/win_rare_service_installs.yml
- rules/windows/process_creation/win_susp_cli_escape.yml
- tools/config/ecs-proxy.yml
- `ecs-proxy.yml` SIGMAC additions to match taxonomy
- fix spelling and typo in description
- better coverage and fixed character that would cause rule to not fire for `rules/windows/process_creation/win_susp_cli_escape.yml` 
- update 4 web rules to use `c-uri` instead of `c-uri-path` which a) taxonomy states to use and b) majority of rules are using `c-uri`
- http server response code to use taxonomy of `sc-status`
> Updates sigmac and rules

- rules/windows/process_creation/win_apt_bear_activity_gtr19.yml
Fixing the problem described in HELK here: https://github.com/Cyb3rWard0g/HELK/issues/442 where when running sigmac to generate elastalert rules, this rule has a title collision with another rule in the same directory and causes elastalert to fail to start.
> Eliminate title collision

- tools/config/winlogbeat-modules-enabled.yml
- tools/config/winlogbeat.yml
When Sysmon logs a "RegistryEvent" event of ID 13, the event might contain a field named `RuleName` as shown in the following excerpt.
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Events>
<Event
xmlns='http://schemas.microsoft.com/win/2004/08/events/event'>
<System>
<Provider Name='Microsoft-Windows-Sysmon' Guid='{5770385f-c22a-43e0-bf4c-06f5698ffbd9}'/>
<EventID>13</EventID>
<Version>2</Version>
<Task>13</Task>
<TimeCreated SystemTime='2020-03-18T03:52:07.173448000Z'/>
<EventRecordID>160631</EventRecordID>
<Correlation/>
<Execution ProcessID='2156' ThreadID='3628'/>
<Channel>Microsoft-Windows-Sysmon/Operational</Channel>
<Computer>win10.sec699-40.lab</Computer>
<Security UserID='S-1-5-18'/> …
```
> Add Winlogbeat's RuleName field to mapping

- rules/windows/builtin/win_susp_dhcp_config.yml
- rules/windows/process_creation/win_etw_trace_evasion.yml
- rules/windows/process_creation/win_powershell_amsi_bypass.yml
- rules/windows/process_creation/win_sysmon_driver_unload.yml
- rules/windows/process_creation/win_system_exe_anomaly.yml
- rules/windows/sysmon/sysmon_wmi_module_load.yml
- rules/windows/sysmon/sysmon_wmi_module_load.yml
Added WmiPrvSE.exe to detection as the different casing was causing false positives
- rules/windows/process_creation/win_system_exe_anomaly.yml
Added "C:\Windows\system32" (lowercase system32) to detection as it was causing false positives
removed trailing whitesapce 
- rules/windows/builtin/win_susp_dhcp_config.yml
Added missing source Microsoft-Windows-DHCP-Server to detection (similar to rules/windows/builtin/win_susp_dhcp_config_failed.yml)
The change was done based on studying the reference in the rule and triggering false positive with Event ID 1033 from Microsoft-Windows-Security-SPP
- rules/windows/process_creation/win_etw_trace_evasion.yml
Added missing status (set to experimental), added falsepositives
- …
> Minor fixes to several rules

- rules/windows/sysmon/sysmon_susp_desktop_ini.yml
Detects unusual processes accessing `desktop.ini`, which can be leveraged to alter how Explorer displays a folder's content (i.e. renaming files) without changing them on disk.
Reference: https://isc.sans.edu/forums/diary/Desktopini+as+a+postexploitation+tool/25912/
> Add "Suspicious desktop.ini Action" rule

- rules/windows/builtin/win_ad_user_enumeration.yml
When the "Read all properties" permission of a user object is set to be audited in the AD, an event of ID 4662 (An operation was performed on an object) is triggered whenever a property is accessed.
This rule detects these events by flagging any non-machine `SubjectUserName` (i.e. another user) which accesses an object of the [`User` AD schema class](https://docs.microsoft.com/en-us/windows/win32/adschema/c-user).
Advantages of this rule include the detection of insider-enumeration through automated tools such as BloodHound or manually through the usage of the PowerShell ActiveDirectory module. Although this rule qualifies as a medium severity one, this event could be qualified as high/critical one if flagged on non-used canary user-accounts.
False positives may include administrators …
> Add AD User Enumeration

- tools/sigma/backends/limacharlie.py
Stop generating rules in the LC backend when a "timeframe" parameter is present. It will eventually be supported but we don't want to generate bad rules in the meantime.
> Remove generation of LC rules with timeframe.

- tools/sigma/backends/elasticsearch.py
**#TODO:once update this, update the PR / else where using this release note https://github.com/Neo23x0/sigma/pull/659**
Updates for elasticsearch backend. In short gives users the option to fix beats/ECS Elastic 7 because removal of analyzed fields by using case insensitivity regex.
Additionally, gives users more control over how their fields are named in terms of what is analyzed VS not and ability to whitelist/blacklist all of it
- Backend Options/Parameters:
- convert rules into case insensitivity
- list of analyzed fields
- list of analyzed subfields
- nested analyzed field
- ability to use keyword as base
- blacklist/whitelist for all above
- Case insensitivity code:
- turn `*` into `.*` unless escaped
- do not perform if value is UUID
- escape lucence regex invalid characters since …
> Elastic backend updates

- rules/windows/builtin/win_net_ntlm_downgrade.yml
Recent Windows versions rely on the ["MSV1_0" authentication package](https://docs.microsoft.com/en-us/windows/win32/secauthn/msv1-0-authentication-package). Tests have shown that NTLM downgrade attacks can be performed as detected by this rule although some of the registry keys are located in an `Lsa` subkey (`MSV1_0`). This commit introduces additional wildcards to handle these cases and ensure the previous ones are still included.
I have opted for wildcards as I was unsure whether the original use-case has been broken in a recent update or if it was erroneous from the start.
> Update the NTLM downgrade registry paths

- tools/sigma/backends/elasticsearch.py
Hi, 
I added two custom backend-options for es-rule backend. 
`index_patterns` allows you to specify on which patterns should the rule be executed. 
The reason behind this is that executing the rule on unnecessary indices may cause significant search overhead. Also some people have multi-tenant clusters and this will allow them to generate sigma rules for different Kibana spaces with different SIEM patterns (although that may require to add also output index option). Original values are moved to default settings for the options.
`execution_interval` allows you to simply change the execution interval of the rule.
Example input (backend-config.yml):
```
index_patterns: "winlogbeat-*,auditbeat-*"
execution_interval: "10m
```
Example output:
```
./sigmac --target es-rule --config …
```
> es-rule backend options for index-patterns and time interval

- rules/windows/sysmon/sysmon_registry_persistence_search_order.yml
This rule detects new user hive COM servers whose targets are in a user-writable folder. Matches highlight possible traces of COM object hijacking leveraging the COM Search Order where user-defined settings supersede system-wide settings.
> User-specific COM objects can be registered by any process at medium integrity level and are only visible to the user that installs them. However, they take precedence over machine-wide objects in the COM subsystem. COM object hijacking is a technique in which malicious software can replace a benign system-wide COM object with a malicious user-specific object that gets loaded in its place.
>
> Source: [cyberbit.com](https://www.cyberbit.com/blog/endpoint-security/com-hijacking-windows-overlooked-security-vulnerability/)
> Add Windows Registry Persistence COM Search Order Hijacking

- rules/windows/process_creation/win_susp_netsh_dll_persistence.yml
- tests/mapping-conditional-multi.yml
The [Sigma specification's status component](https://github.com/Neo23x0/sigma/wiki/Specification#status-optional) states the following:
> Declares the status of the rule:
>  - stable: the rule is considered as stable and may be used in production systems or dashboards.
>  - test: an almost stable rule that possibly could require some fine tuning.
>  - experimental: an experimental rule that could lead to false results or be noisy, but could also identify interesting events.
However the Sigma Rx YAML specification states the following:
> ```yaml
> status:
>     type: //any
>     of:
>         - type: //str
>           value: stable
>         - type: //str
>           value: testing
>         - type: //str
>           value: experimental
> ```
The specification confuses the `test` and …
> Update rules to follow the Sigma state specification

- rules/windows/process_creation/win_renamed_binary.yml
Besides this addition a rule for catching the binary description which is `Network Command Shell` and at the same time the image name is not `netsh.exe` could be added. But I'm not sure yet because of duplicate purpose with this one.
> Add netsh to renamed binary rule

- rules/windows/process_creation/win_bootconf_mod.yml
The rule was not effective as it looked for non-compatible conditions.
> Fix a bad CommandLine search

- rules/windows/process_creation/win_susp_script_execution.yml
This rule was giving too many false negatives, and could be easily bypassed, making it inefficient.
```psh
cscript.exe .\test.jse
```
```psh
cscript.exe '.\test.jse'
cscript.exe .\test.jse \E:Jscript
cscript.exe .\test.jse [any option]
```
This PR aims at detecting all of the above.
> Widen the search as it gives too many false negatives

- Makefile
- README.md
- tools/config/ecs-proxy.yml
- tools/config/ecs-zeek-corelight.yml
- tools/config/ecs-zeek-elastic-beats-implementation.yml
- tools/config/filebeat-defaultindex.yml
- tools/config/logstash-defaultindex.yml
- tools/config/logstash-linux.yml
- tools/config/logstash-windows.yml
- tools/config/winlogbeat-modules-enabled.yml
- tools/config/winlogbeat-old.yml
- tools/config/winlogbeat.yml
- tools/sigma/backends/ee-outliers.py
At NVISO we use [ee-outliers](https://github.com/nviso-be/ee-outliers) to tag Sigma hits in Elasticsearch, something no other backend in Sigma support currently.
We've released the framework to the open-source community [back in December 2018](https://blog.nviso.eu/2018/12/11/announcement-open-sourcing-ee-outliers/) and would like to do the same with our Sigma backend we use to convert Sigma rules to ee-outliers use cases.
Any feedback is more than welcome!
> ee-outliers backend

- rules/windows/sysmon/sysmon_cve-2020-1048.yml
after testing, correct event type is either SetValue or DeleteValue (didn't see CreateValue being used with the PoC but doesn't hurt to set it here)
CreateKey is used when opening the key to list values underneath it
> fix CVE 2020-1048 rule

- README.md
The description in the readme is outdated
````
sigmac --target-list
usage: sigmac [-h] [--recurse] [--filter FILTER]
[--target {kibana,ala-rule,splunk,ala,splunkxml,fieldlist,graylog,es-rule,qualys,arcsight-esm,mdatp,netwitness,arcsight,elastalert-dsl,sql,carbonblack,xpack-watcher,limacharlie,qradar,logiq,powershell,grep,ee-outliers,elastalert,es-qs,es-dsl,logpoint,sumologic}]
[--lists] [--config CONFIG] [--output OUTPUT]
[--backend-option BACKEND_OPTION]
[--backend-config BACKEND_CONFIG] [--defer-abort]
[--ignore-backend-errors] [--verbose] [--debug]
[inputs [inputs ...]]
sigmac: error: unrecognized arguments: --target-list
````
> replace --target-list with --lists

- rules/windows/sysmon/sysmon_cve-2020-1048.yml
The condition field in this rule was in the global section which overwrote the condition in sub-rules and generated FPs. For example, once Sigma read the rule, the bottom sub-rule's "condition" was overwritten with "1 of them".
Fixes #767
> Remove "condition" from global rule in CVE-2020-1048.

- rules/linux/auditd/lnx_auditd_create_account.yml
This new rules detects the Mitre Att&ck technique "Create account" on Linux systems.
> Create a new rule to detect "Create Account"

- rules/windows/process_creation/win_netsh_allow_port_rdp.yml
This rule detects RDP port opening with netsh. Both the 'add portopening' and 'add rule' way to open the port
> added rule for Netsh RDP port opening

- rules/linux/auditd/lnx_auditd_susp_C2_commands.yml
This rule detects all the suspicious activities declared in 'https://github.com/Neo23x0/auditd'.
It uses the keyword chosen in these rules. 
I am open to changing it in order to do the selection on the binaries names instead of the keyword.
> Create a rule for "suspicious activities"

- rules/windows/sysmon/sysmon_susp_run_key_img_folder.yml
A lot of software is using the AppData folder for startup keys. Some examples:
- Microsoft Teams (\AppData\Local\Microsoft\Teams)
- Resilio (\AppData\Roaming\Resilio Sync\)
- Discord ( (\AppData\Local\Discord\)
- Spotify ( (\AppData\Roaming\Spotify\)
Too many to whitelist them all
> Remove AppData folder as suspicious folder

- rules/windows/process_creation/win_susp_file_characteristics.yml
A lot of Windows apps does not have any file characteristics. Some examples:
- Gamebar: C:\\Program Files\\WindowsApps\\Microsoft.XboxGamingOverlay_3.38.25003.0_x64__8wekyb3d8bbwe\\GameBarFT.exe
- YourPhone: C:\\Program Files\\WindowsApps\\Microsoft.YourPhone_1.20022.82.0_x64__8wekyb3d8bbwe\\YourPhoneServer/YourPhoneServer.exe
And also other images:
- All C:\Windows\System32\OpenSSH (scp, sftp, ssh etc) does not have a description and company.
- Python 2.7, 3.3 and 3.7 does not have any file characteristics.
So I don't think it is possible to whitelist all options, maybe it is worthwhile to check the \Downloads\ folder otherwise it would be better to just delete the rule. All other suspicious folders are covered by /rules/windows/process_creation/win_susp_exec_folder.yml
> Susp file characteristics: Reduce FP of legitime processes

- rules/windows/sysmon/sysmon_cve-2020-1048.yml
Added detection of `.com` executables, the second use of TargetObject should have been Details to properly match.
> Changes to sysmon_cve-2020-1048

- rules/linux/lnx_shell_clear_cmd_history.yml
I suggest a new point of view to detect that bash_history has been cleared : Instead of trying to detect all the commands that can do that, we could monitor the size of the file and log whenever it has less than 1 line.
> Edit Clear Command History

- other/godmode_sigma_rule.yml
- rules-unsupported/sysmon_process_reimaging.yml
- rules/windows/process_creation/win_hktl_createminidump.yml
- rules/windows/sysmon/sysmon_lsass_memory_dump_file_creation.yml
- rules/windows/sysmon/sysmon_tsclient_filewrite_startup.yml
This commit fixes the incorrect spelling. When dumping the fieldlist it gives `TargetFileName` and `TargetFilename`. However, there are more rules that are using `TargetFilename` than `TargetFileName` so this commit changes the "wrong" ones. Some backends support both, and it should be case-insensitive when using the fields, but having this correct looks way cleaner.
If that's ok; I would continue doing this for `OriginalFileName` and `OriginalFilename`.
> All Rules use 'TargetFilename' instead of 'TargetFileName'.

- rules/windows/malware/win_mal_octopus_scanner.yml
Rule to detect the Octopus Scanner malware that affected several GitHub repositories:
https://securitylab.github.com/research/octopus-scanner-malware-open-source-supply-chain
> Octopus Scanner malware rule

- rules/windows/malware/win_mal_flowcloud.yml
Rule to detect FlowCloud malware used by TA410, as reported by [Proofpoint](https://www.proofpoint.com/us/blog/threat-insight/ta410-group-behind-lookback-attacks-against-us-utilities-sector-returns-new).
> TA410 FlowCloud malware detection

- tools/README.md
typo, was missing the `=` and `*`.
also, show option when using case insensitive for everything, how to "exclude" a field from that regex.
> typo and another example

- rules/windows/malware/win_mal_flowcloud.yml
- rules/windows/process_creation/win_apt_mustangpanda.yml
- rules/windows/process_creation/win_apt_wocao.yml
- rules/windows/sysmon/sysmon_susp_adsi_cache_usage.yml
- rules/windows/sysmon/sysmon_susp_office_dotnet_assembly_dll_load.yml
- rules/windows/sysmon/sysmon_susp_procexplorer_driver_created_in_tmp_folder.yml
- rules/windows/sysmon/sysmon_suspicious_keyboard_layout_load.yml
- rules/windows/sysmon/sysmon_svchost_dll_search_order_hijack.yml
A backslash before a wildcard needs to be escaped with another backslash.
> Fix rules with incorrect escaping of wildcars

- rules/windows/process_creation/win_invoke_obfuscation_obfuscated_iex_commandline.yml
The rule win_invoke_obfuscation_obfuscated_iex_commandline has the
wrong field name for the "process_creation" tag. Rename from "service"
to "category"
> Fix logsource field name from service->category

- rules/windows/process_creation/win_net_enum.yml
To match a double-backslash you actually need three backslashes, since two
backslashes gets reduced to one.
> Fix match for double-backslash

- rules/windows/builtin/win_invoke_obfuscation_obfuscated_iex_services.yml
- rules/windows/builtin/win_meterpreter_or_cobaltstrike_getsystem_service_installation.yml
- rules/windows/builtin/win_tap_driver_installation.yml
The global document defines a "selection" identifier which is also defined the
individual rules. The rule identifier is getting overwritten by the global identifier.
Fix by giving unique names to the global identifier.
> Identifiers shared between global document and rule gets overwritten

- rules/windows/builtin/win_ad_object_writedac_access.yml
The AccessMask field needs to be quoted so that it is compared correctly.
> Fix quoting for AD Object WriteDAC Access

- tools/sigma/backends/carbonblack.py
This should address the grouping issue from #660.
The grouping issue was solved by just slamming some parentheses around the fields in the listExpression field.
-----
```yaml
detection:
selection:
SomeField:
- 'foo'
- 'bar'
AnotherField: 'baz'
```
```
$ sigmac -t carbonblack -c carbon-black.yml test-rule.yaml
((SomeField:foo OR SomeField:bar) AND AnotherField:baz)
```
> Add parentheses around field list groups in CB

- contrib/sigma2sumologic.py
Discovered in #378 
https://docs.python.org/3.8/library/argparse.html#argparse.ArgumentParser.print_help
> Undefined name: parser_print_help() --> parser.print_help()

- tools/sigma/parser/collection.py
Discovered in #378.  `SigmaCollectionParseError()` is called on line 55 but it is never defined or imported which means that NameError will be raised instead of SigmaCollectionParseError.
> Undefined name: from .exceptions import SigmaCollectionParseError

- tools/sigma/config/mapping.py
If there is a default mapping specified for a fieldmapping and that field is
referenced multiple times in the rule, the default mapping will be "pop"ped
and return the unmapped key on subsequent uses.
Don't pop the value. Just return the first entry.
> Fix multiple references to default field mapping in same rule

- rules/windows/other/win_defender_disabled.yml
- rules/windows/other/win_defender_threat.yml
- tools/config/logstash-windows.yml
- tools/config/powershell.yml
- tools/config/winlogbeat-modules-enabled.yml
- tools/config/winlogbeat-old.yml
- tools/config/winlogbeat.yml
Hello,
I created two rules for Windows Defender logs based on Microsoft [documentation](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/troubleshoot-microsoft-defender-antivirus).
`win_defender_disabled.yml ` rule detects Event IDs that disable Defender or parts of it:
- 5001 - Real-time protection is disabled.
- 5010 - Scanning for malware and other potentially unwanted software is disabled.
- 5012 - Scanning for viruses is disabled.
- 5101 - The antimalware platform is expired.
`win_defender_threat.yml` rule detects actions taken by Defender components to detect/stop threat:
- 1006 - The antimalware engine found malware or other potentially unwanted software.
- 1116 - The antimalware platform detected malware or other potentially unwanted …
> Windows Defender logsource and rules

- tools/sigma/backends/mdatp.py
Updating the mdatp backend file as it is currently impossible to set an ActionType as there is no mapping to EventType.
This effect rules that are using Event ID 12.
I used information from:
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-schema-reference.
> Update to mdatp backend

- rules/windows/registry_event/sysmon_disable_security_events_logging_adding_reg_key_minint.yml
- rules/windows/registry_event/sysmon_new_dll_added_to_appcertdlls_registry_key.yml
To be consistent with the behaviour of the other rules, the eventID should not
be specified as part of the rule. The category defines the eventID.
> Fixes for rules in new sysmon registry_event category

- rules/windows/file_event/sysmon_hack_dumpert.yml
- rules/windows/file_event/sysmon_tsclient_filewrite_startup.yml
- rules/windows/file_event/sysmon_wmi_persistence_script_event_consumer_write.yml
Fix a couple of typos
For sysmon_hack_dumpert:
Make sure the logsource is category file_event and not sysmon. Don't set
the category at the global level. Instead set in the individual document.
> Fixes for rules in the sysmon file_event category

- tools/sigma/sigma2misp.py
create_new_event() -> create_new_event(args, misp) to fix:
flake8 testing of https://github.com/Neo23x0/sigma on Python 3.8.3
% _flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics_
```
./tools/sigma/sigma2misp.py:11:16: F821 undefined name 'misp'
if hasattr(misp, "new_event"):
^
./tools/sigma/sigma2misp.py:12:16: F821 undefined name 'misp'
return misp.new_event(info=args.info)["Event"]["id"]
^
./tools/sigma/sigma2misp.py:12:36: F821 undefined name 'args'
return misp.new_event(info=args.info)["Event"]["id"]
^
./tools/sigma/sigma2misp.py:14:13: F821 undefined name 'misp'
event = misp.MISPEvent()
^
./tools/sigma/sigma2misp.py:15:18: F821 undefined name 'args'
event.info = args.info
^
./tools/sigma/sigma2misp.py:16:12: F821 undefined name 'misp'
return …
```
> Fix undefined names in sigma2misp.py

- rules/windows/network_connection/sysmon_regsvr32_network_activity.yml
- tools/config/generic/sysmon.yml
This change removes dns events from the network connection category. The
one change is that sysmon_regsvr32_network_activity.yml needs to test
the network connection category separately from the DNS event id.
> Proposed fix for https://github.com/Neo23x0/sigma/issues/889

- Makefile
- tools/config/stix-qradar.yml
- tools/config/stix-windows.yml
- tools/config/stix.yml
- tools/sigma/backends/stix.py
Backend for Sigma rules to STIX - Structured Threat Information Expression 2.1 (https://docs.oasis-open.org/cti/stix/v2.1/csprd01/stix-v2.1-csprd01.html)
Including mapping for windows logs fields and QRadar fields
Example sigmac translation:
```
/sigmac -t stix \
> -c stix \
> -c stix-qradar \
> -c stix-windows \
> /rules/windows/sysmon/sysmon_stickykey_like_backdoor.yml
```
```
[((x-event:code = '13' OR x-event:id = '13') AND (windows-registry-key:key LIKE '%\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sethc.exe\Debugger' OR windows-registry-key:key LIKE '%\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\utilman.exe\Debugger' OR windows-registry-key:key LIKE '%\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution …
```
> STIX backend added including mapping configurations for windows logs and QRadar

- rules/windows/file_event/sysmon_creation_system_file.yml
- rules/windows/file_event/sysmon_susp_adsi_cache_usage.yml
- rules/windows/file_event/sysmon_susp_procexplorer_driver_created_in_tmp_folder.yml
- rules/windows/image_load/sysmon_susp_office_dotnet_assembly_dll_load.yml
- rules/windows/image_load/sysmon_svchost_dll_search_order_hijack.yml
- rules/windows/image_load/sysmon_wmi_persistence_commandline_event_consumer.yml
- rules/windows/registry_event/sysmon_suspicious_keyboard_layout_load.yml
Several fixes for sysmon rules got lost when the rules were refactored to use
categories.
Re-add the fixes.
https://github.com/Neo23x0/sigma/commit/38afd8b5def24191616ff0f0c0324cfbb7f0d6d0
https://github.com/Neo23x0/sigma/commit/422b2bffd77b217e6cec9a67c496b0aa44711ece
https://github.com/Neo23x0/sigma/commit/dfae2a6df6f5bbc90a7b476c22fc9c8fedab47e9
> Re-fix sysmon rules that lost changes with category refactoring.

- rules/windows/registry_event/sysmon_uac_bypass_eventvwr.yml
Issue: https://github.com/Neo23x0/sigma/issues/888
The rules were not merged correctly with the transition to sysmon categories.
Split the rule into separate documents: one for the registry_event and one for
the process_creation
> Proposed fix for sysmon_uac_bypass_eventvwr

- rules/windows/process_creation/win_susp_ditsnap.yml
ditsnap, a credential access tool used in ransomware attacks as in https://thedfirreport.com/2020/06/21/snatch-ransomware/
> ditsnap, a credential access tool used in ransomware attacks

- tools/sigma/backends/stix.py
Custom STIX object "x-sigma" for fields that missing mapping, so the pattern is STIX valid if mapping is missing.
for example `RelativeTargetName` mapping is missing and translated to `x-sigma:relativetargetname`: 
```
[((x-event:id = '5145' OR x-event:code = '5145') AND x-windows:sharename LIKE '\\\\%\\SYSVOL' AND x-sigma:relativetargetname LIKE '%ScheduledTasks.xml' AND x-windows:accesses LIKE '%WriteData%')]
```
> Custom STIX object "x-sigma" for fields that missing mapping [stix backend]

- tools/sigma/sigmac.py
Wrong indentation of line 182 meant that even where config options
were given, the default per backend was being used, rendering
custom config useless.
> Fix for indentation issue

- rules/windows/process_creation/win_webshell_recon_detection.yml
Looking for processes spawned by web server components that indicate reconnaissance by popular public domain webshells for whether perl, python or wget are installed.
> Webshell Recon Detection Via CommandLine & ProcessesAdd files via upload

- tools/sigma/backends/elasticsearch.py
Fixed the `fieldNameMapping` function call to match function signature of the `DeepFieldMappingMixin` class.
> fixed wrong function call for elastalert aggregation. fixes #940

- rules/windows/process_creation/win_wmiprvse_spawning_process.yml
Rule Title: Wmiprvse Spawning Process
Rule ID: d21374ff-f574-44a7-9998-4a8c8bf33d7d
This rule has a typo under the detection filter. It is filtering by a 'Username' field when it should be 'User'. Resolving that typo here.
> Change fitler typo from 'Username' to 'User' for Wmiprvse Spawning Process rule

- rules/windows/registry_event/sysmon_asep_reg_keys_modification.yml
remove false positives in Windows being too broad and add specific keys looked at + add keys from wow64
Encountered some false positives with keys being "\software\Microsoft\Windows NT\CurrentVersion\Windows XX\YY\ZZ" but can't recall the exact details, so only look for persistence methods in Windows being appinit DLL + WindowsShellLoadAndRun
> SIGMA ASEP: remove some false positives

- rules/windows/process_creation/win_susp_rasdial_activity.yml
`rasdial` is an `exe`, and probably appear as `rasdial.exe`
`LIKE` is more fit in this case
> Update win_susp_rasdial_activity.yml to use `contains` instead of `equal`

- README.md
I suspect this [pull request](https://github.com/Neo23x0/sigma/pull/659) mentioned in [this issue](https://github.com/Neo23x0/sigma/issues/194) actually fixes elasticsearch the field problems. I got my problems solved by following the configuration suggestions in the conversation https://github.com/Neo23x0/sigma/pull/659#issue-386776046. 
Furthermore I just found out, that there is an option for showing the available backend options (`--backend-help`). I did not know this was there.
Additionally there exists a [README.md](https://github.com/Neo23x0/sigma/blob/master/tools/README.md) in the `tools/` folder that also describes specific settings for ECS and Elastic beats. Sadly I did not find any of this until now, because I just used `sigmac` via `pip`.
So I created this pull requests to …
> added troubleshooting links to root README.md

- rules/network/zeek/zeek_rdp_public_listener.yml
Zeek rule that detects publicly accessible RDP services
> Zeek RDP rule

- tools/README.md
- tools/sigma/backends/elasticsearch.py
- elastic backend adds ability to use an analyzed field / different field for if a value contains wildcard (also will prepare for new wildcard data type usage)
-elastic backend tweaks for if a sub field was set as an analyzed field or different type (other than keyword) to still be applied if both keyword and that field were sub fields. Scenarios of 3 or more field types.....
- elastic backend escape / don't escape logic for '.' in regex and case insensitivity
- update elastic sigmac readme to support new wildcard backend option as well as some cleanup of the readme
> ES and Readme from SOC Prime

- rules/windows/other/win_defender_psexec_wmi_asr.yml
Block process creations originating from PSExec and WMI commands
- This rule blocks processes created through PsExec and WMI from running.
> Added support for Defender's PSExec and WMI ASR rules.

- rules/windows/builtin/win_dcsync.yml
AD Connect on premise AD accounts to Azure AD.  The replication process is completed under the context of the 'MSOL_xxxxxxxx' user account.  The AD Connect application is installed on a member server (i.e. not on a DC).  
https://techcommunity.microsoft.com/t5/azure-advanced-threat-protection/ad-connect-msol-user-suspected-dcsync-attack/m-p/788028
https://blog.xpnsec.com/azuread-connect-for-redteam/
> + Adding exclusion for Azure AD Sync (MSOL_xxxxxxxx)

- rules/windows/builtin/win_vul_cve_2020_1472.yml
From Microsoft's own [documentation](https://support.microsoft.com/en-gb/help/4557222/how-to-manage-the-changes-in-netlogon-secure-channel-connections-assoc):
> After the August 11, 2020 updates have been applied to DCs, events can be collected in DC event logs to determine which devices in your environment are using vulnerable Netlogon secure channel connections (referred to as non-compliant devices in this article). Monitor patched DCs for event ID 5829 events.
This rule triggers on the events that are now generated to detect vulnerable devices.
> Added win_vul_cve_2020_1472 rule

- tools/sigma/sigma2misp.py
Error was: `AttributeError: 'PyMISP' object has no attribute 'MISPEvent'`
Thanks to @rfoster55 for the code suggestions.
Closes #970 
Closes #808
> Fix error with pymisp in sigma2misp

- tools/sigma/parser/condition.py
The original method to find the closing parentheses will raise a ValueError when the condition is something like this
`filter1 and (filter2 or (filter3 and filter4))`
The parser should find the closing token in pairs with the opening token.
So the parser will support nested parentheses in the conditions.
> Add support nested parentheses for Sigma condition

- rules/windows/builtin/win_root_certificate_installed.yml
Ref: https://github.com/Neo23x0/sigma/issues/1013
Sigmac Output
`python .\sigmac -t splunk -c .\config\splunk-windows.yml ..\rules\windows\builtin\win_.yml
(source="WinEventLog:Microsoft-Windows-PowerShell/Operational" EventCode="4104" (ScriptBlockText="*Import-Certificate * Cert:\\LocalMachine\\Root*" OR ScriptBlockText="*Move-Item * Cert:\\LocalMachine\\Root*"))
((Image="*\\certutil.exe" CommandLine="*-addstore * root*") OR (Image="*\\CertMgr.exe" CommandLine="*/add * root*"))`
> [OSCD] Create win_root_certificate_installed.yml

- rules/windows/process_creation/win_powershell_disable_windef_av.yml
This identifies attempts to disable Windows Defender from powershell that is commonly leveraged by malicious threat actors, such as EvilCorp/TA505, Lazarus, and others.
> [OSCD] Powershell Disable Windows Defender AV

- rules/windows/process_creation/win_using_settingsynchost_as_lolbin.yml
This utility is not included in the [LOLBAS repository](https://github.com/LOLBAS-Project/LOLBAS) but can be used by attackers as LOLBin.
> [OSCD] Using SettingSyncHost.exe as LOLBin

- rules/windows/process_creation/win_invoke_obfuscation_via_use_rundll32.yml
Made it a single regular expression.
In the first version (?i).?cmd./c\s*"set\s+.*downloadstring&&.rundll32.powershell.(value|invoke|comspec|iex)." , but I changed it because the script can be of this type:
'Invoke-Expression (New-Object Net.WebClient).DownloadString&&RuNdll32 SHELL32.DLL ShellExec_RunDLL "PoWERsheLl" " -noPRoFIL " " ( ^& ( '{1}{2}{3}{0}' -f 'eM','GE','t-child','IT' ) ( '{0}{1}' -f'E','nV:igFm' ) ).'VAlUE' ^| . ( '{1}{0}'-f 'x','ie')"'
And i add in regular 'iex' because 'invoke' could be different.
> [OSCD] Detects Obfuscated Powershell via use Rundll32 in Scripts #30 (process_creation) 

- rules/windows/powershell/powershell_invoke_obfuscation_via_use_rundll32.yml
Made it a single regular expression. 
In the first version (?i).*?cmd.*\/c\s*"set\s+.*downloadstring&&.*rundll32.*powershell.*(value|invoke|comspec|iex).*" , but I changed it because the script can be of this type: 
'Invoke-Expression (New-Object Net.WebClient).DownloadString&&RuNdll32 SHELL32.DLL ShellExec_RunDLL "PoWERsheLl" " -noPRoFIL " " ( ^& ( '{1}{2}{3}{0}' -f 'eM','GE','t-child','IT' ) ( '{0}{1}' -f'E','nV:igFm' ) ).'VAlUE' ^| . ( '{1}{0}'-f 'x','ie')"'
And i add in regular 'iex' because 'invoke' could be different.
> [OSCD] Detects Obfuscated Powershell via use Rundll32 in Scripts #30 (4104, 4103)

- rules/windows/process_creation/sysmon_long_powershell_commandline.yml
[OSCD Initiative] Develop Sigma rules for PowerShell Abuse #575: Task #67 (Too long PowerShell command lines).
> [OSCD] Too Long Powershell CommandLine Rule added

- rules/windows/process_creation/win_susp_mounted_share_deletion.yml
OSCD Sprint 2 Atomic Red Team Windows - #1013 item 6 - T1070.005: Network Share Connection Removal (one process_creation rule and one PowerShell rule)
Sigmac Test:
`❯ python .\sigmac -t splunk -c .\config\splunk-windows.yml ..\rules\windows\process_creation\win_susp_mounted_share_deletion.yml
((Image="*\\net.exe" OR Image="*\\net1.exe") (CommandLine="*/delete*"))`
> [OSCD] Create win_susp_mounted_share_deletion.yml

- rules/windows/builtin/win_susp_logon_explicit_credentials.yml
Part of oscd sprint 2 - https://github.com/Neo23x0/sigma/issues/576
Sigmac Testing:
`❯ python .\sigmac -t splunk -c .\config\splunk-windows.yml ..\rules\windows\builtin\win_susp_logon_explicit_credentials.yml
(source="WinEventLog:Security" (EventCode="4648" (Image="*\\cmd.exe" OR Image="*\\powershell.exe" OR Image="*\\pwsh.exe" OR Image="*\\winrs.exe" OR Image="*\\wmic.exe" OR Image="*\\net.exe" OR Image="*\\net1.exe" OR Image="*\\reg.exe" OR Image="*\\winrs.exe")) NOT (Target_Server_Name="localhost"))`
> [OSCD] Create win_susp_logon_explicit_credentials.yml

- rules-unsupported/sysmon_always_install_elevated_parent_child_correlated.yml
Page [48 ](https://image.slidesharecdn.com/kheirkhabarovoffzonefinal-181117201458/95/hunting-for-privilege-escalation-in-windows-environment-48-638.jpg) from #574 
Since the slide showing the usage of correlation of events, it was suggested to add the rules to rules-unsupported. Following suggestion from @yugoslavskiy - https://github.com/Neo23x0/sigma/issues/574#issuecomment-707441823
Logic of the rule provided in the description
> [OSCD] Always Install Elevated

- tools/config/ecs-proxy.yml
- tools/sigma/backends/elasticsearch.py
Hi,
i thought it would be a good idea to support the ndjson Format for elasticsearch kibana.
A test on my installation 7.9.2 + 7.9.3 runs fine and I didn't saw problems regarding the new feature around index references while import.
A note about ndjson format for every reviewer:
* Some fields just got renamed compared to the old kibana json format
* ndjson must not be indented
* one json entitiy per line, multiple objects without <,> seperator 
* Wanted index-pattern name has to be in the `searchSourceJSON` field as also in the `references`
Feedback is very welcome
Regards,
Hendrik
> Elasticsearch Kibana ndjson backend

- tools/sigma/sigma2attack.py
using sigma2attack on the repository database fails on a recent python3 installation (python 3.9 tested on windows) because of bad usage of `open` and unicode caracters in [win_defender_disabled.yml](/rules/windows/other/win_defender_disabled.yml).
> Fix unicode error in sigma2attack

- rules/windows/process_creation/win_apt_lazarus_session_highjack.yml
As described in the references, the binary name is MSDTC.exe, not MSTDC.exe.
https://media.kasperskycontenthub.com/wp-content/uploads/sites/43/2018/03/07180244/Lazarus_Under_The_Hood_PDF_final.pdf
> Fix typo in win_apt_lazarus_session_hijack.yml

- tools/config/ecs-cloudtrail.yml
There was previously no mapping for the role name field in the ecs-cloudtrail.yml.
This field can actually help trace the effective role that is making the API calls.
> added role name field to ecs-cloudtrail.

- Makefile
- tools/config/fireeye-helix.yml
- tools/sigma/backends/fireeye-helix.py
Adds a backend for conversion to Helix MQL queries.
A couple of relevant questions I encountered while writing this:
* Would it make sense to provide an easier way to override the mixin that's adding wildcards around contains statements? Right now it seems like everyone that doesn't need balanced wildcards for contains statements is rewriting strings after the fact, which isn't very efficient
* Along the same lines, there isn't a great way of handling mid string wildcards right now. Talking about examples like: `*SYSTEM\\*ControlSet*\Control\Lsa*\NtlmMinClientSec`, `\AppData\Roaming\Oracle*\java*.exe`, or `*/E:vbscript * C:\Users\\*.txt" /F`. None of these are going to be well supported or performant in very many systems and the ways backends seem to be handling them right now are kinda …
> Backend: FireEye Helix

- tools/config/carbon-black.yml
DestinationHostname is mapped to wrong fieldname in Carbon Black, should be mapped to <domain>
> Fix field mapping for DestinationHostname

- tools/config/winlogbeat.yml
Noticed process_creation/win_renamed_binary.yml wasn't generating hits where I thought it should because OriginalFileName was missing from the winlogbeat.yml config.
Let me know if there's a different branching/PR process you would prefer I follow.
> Updated winlogbeat.yml config to include OriginalFileName

- tools/sigma/backends/mdatp.py
This adds process detail mappings for the tables `DeviceFileEvents` and `DeviceRegistryEvents`, as well as some missing ones used in other backend configs to `DeviceProcessEvents`.
`IMPHASH` was added to the skipped fields list as it's available in MD ATP.
Default operator was changed from `==` to `=~` as Sigma is case insensitive by default.
Lastly it maps the following generic events to relevant hunt tables:
- `registry_event`: `DeviceRegistryEvents`
- `file_event`: `DeviceFileEvents`
- `network_connection`: `DeviceNetworkEvents`
> mdatp: Mapping and generic event changes, case insensitive search

- tools/sigma/sigmac.py
Hi,
I have added a flag called `--print0` to sigmac which changes the delimiter of the results from newline to the NUL-character.  
The use case for that is being able to deal with multiline results. The NUL-byte as record separator is widely supported by Unix tools such as `xargs -0` or `parallel -0`. The name for the flag was inspired by `-print0` from the `find` utility.
> Add sigmac flag to delimit results by NUL instead of \n

- rules/windows/builtin/win_impacket_psexec.yml
Made changes to support detection of Impacket's PsExec.
Inspired from:
https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_susp_psexec.yml
> Added rule for Impacket's PsExec execution

- rules/web/win_webshell_regeorg.yml
- rules/windows/other/win_defender_history_delete.yml
- rules/windows/process_creation/win_control_panel_item.yml
- rules/windows/process_creation/win_dnscat2_powershell_implementation.yml
- rules/windows/process_creation/win_mouse_lock.yml
- rules/windows/process_creation/win_webshell_detection.yml
- rules/windows/process_creation/win_webshell_recon_detection.yml
- rules/windows/registry_event/sysmon_susp_mic_cam_access.yml
- rules/windows/sysmon/sysmon_abusing_azure_browser_sso.yml
- tests/test_rules.py
- Fix discrepancies between "reference" and "references" in rules
- Add a test to test_rules.py for this
Wiki about specs should be patched to reflect that the correct field name is "references" and not "reference" : https://github.com/Neo23x0/sigma/wiki/Specification#references-optional
> fix "references" field + add test for references in plural form

- README.md
Added [SIEGMA](https://github.com/3CORESec/SIEGMA) to the list of projects that utilizes Sigma and also added a section for [S2AN](https://github.com/3CORESec/S2AN) in the scripts, below Sigma2attack.
> add SIEGMA and S2AN

- rules/web/web_solarwinds_cve_2020_10148.yml
There is a typo in file extension in the CERT's Vulnerability Note, as pointed out here: 
https://twitter.com/em1rerdogan/status/1343100528415432705
> Fixed typo in file format

- rules/windows/process_creation/win_susp_adfind.yml
Original field on event log is Process Command Line so translated field name will be ProcessCommandLine
> Typo on field name

- rules/windows/process_creation/win_mouse_lock.yml
- rules/windows/process_creation/win_susp_adfind.yml
For the "mouse lock" rule, the logsource product field was missing.
> Fix missing product mouse lock

- rules/windows/process_creation/win_susp_adfind.yml
In the rule, the logsource field should be changed from service to category
> Fix bug changing the logsource

- rules/windows/image_load/sysmon_uac_bypass_via_dism.yml
- rules/windows/process_access/sysmon_load_undocumented_autoelevated_com_interface.yml
- rules/windows/registry_event/sysmon_bypass_via_wsreset.yml
Using UAC bypass is a good way to detect malicious actions. Despite the simplicity of this mechanism, it can be used like an IOC.
3 rules.
> [OSCD] UAC bypass added

- rules/windows/process_creation/win_susp_rpcping.yml
Detects using Rpcping.exe to send a RPC test connection to the target server (-s) and force the NTLM hash to be sent in the process.
#1014
> [OSCD] rpcping lolbin

- rules/windows/process_creation/win_rasautou_dll_execution.yml
- rules/windows/sysmon/sysmon_rasautou_dll_execution.yml
task 69, #1014 
Attack doesn't work in Windows 10 as options '-d' and '-p' were removed in Windows 10.
Standart 4688 in WIn7 doesn't log command line, that is why only Sysymon1 is required
Do i have some way to include only Sysmon1 and not 4688?
> [OSCD] Rasautou.exe LOLbin

- rules/linux/macos_create_account.yml
Covering:
MacOs task 34 T1136.001: Local Account #1012
Regarding the outcome of #1048 we can consider renaming the file name prefix and also move it into the right folder.
> [OSCD]  MacOS local account creation

- rules/linux/lnx_local_groups.yml
- rules/linux/macos_local_groups.yml
Covering:
Linux task 12 T1069.001: Local Groups #1011
MacOs task 21 T1069.001: Local Groups #1012
Regarding the outcome of #1048 we can consider renaming the file name prefix and also move it into the right folder.
> [OSCD] Local System Groups Discovery

- rules/windows/image_load/sysmon_susp_script_dotnet_clr_dll_load.yml
frameworks like .net2js produces scripts with .net embedded inside it. rule will help execution of those scripts through these frameworks. This covers hta, js, vbs files for now. this will also help in bring your own assembly attacks.
> [OSCD] script applications loading .net dll

- rules/windows/file_event/sysmon_susp_clr_logs.yml
forensic file traces observed when offensive tools like .Net2js, sharpshooter which internally use .NET for execution. CLR logs are captured in the mentioned folder and can be a trace for such attempts. I did not add svchost might create fp.
> [OSCD] suspicious clr logs creation

- rules/windows/powershell/powershell_bad_opsec_artifacts.yml
This detects powershell code artifacts left by attackers in community attack tool powershell payloads as part of bad opsec practices leveraging customized variants of Cobaltstrike Powershell Beacon, PoshC2, Powersploit, Empire, etc.
[Resubmitted per feedback from @yugoslavskiy]
> [OSCD] Bad Opsec Powershell Artifacts

- rules/linux/macos_startup_items.yml
Covering:
Macos Task 10 T1037.005: Startup Items #1012
Regarding the outcome of #1048 we can consider renaming the file name prefix and also move it into the right folder.
> [OSCD] MacOS Startup Items

- rules/linux/macos_network_sniffing.yml
Covering:
Macos task 11 T1040: Network Sniffing #1012
Regarding the outcome of #1048 we can consider renaming the file name prefix and also move it into the right folder.
> [OSCD] MacOS Network Sniffing

- rules/windows/builtin/win_privesc_cve_2020_1472.yml
For this issue [#574](https://github.com/Neo23x0/sigma/issues/574)
> [OSCD] Added a rule to detect possible Zerologon exploitation

- rules/windows/process_creation/sysmon_always_install_elevated_windows_installer.yml
Page [48](https://image.slidesharecdn.com/kheirkhabarovoffzonefinal-181117201458/95/hunting-for-privilege-escalation-in-windows-environment-48-638.jpg) from #574 
Alternative to #1195  because the rule is on the unsupported folder. Following suggestion from @yugoslavskiy - https://github.com/Neo23x0/sigma/issues/574#issuecomment-710690252
>  [OSCD] Always Install Elevated Alternative

- .github/workflows/sigma-test.yml
- rules/windows/file_event/sysmon_non_priv_program_files_move.yml
Page 37 from #574 
I took some liberties in changing the detection a bit to make more sense to me, but let me know if it's now incorrect. I put wildcards around  `\Program Files\` and `\Program Files (x86)\` and made `*temp*` be linked with an OR instead of an AND
```
>tools/sigmac -c sysmon -c helk --target es-qs rules/windows/file_event/sysmon_non_priv_program_files_move.yml
(event_id:"11" AND IntegrityLevel:"Medium" AND (file_name.keyword:(*\\Program\ Files\\* OR *\\Program\ Files\ \(x86\)\\*) OR file_name.keyword:\\Windows\\* OR file_name.keyword:*temp*))
```
> [OSCD] Add Files Dropped to Program Files by Non-Priviledged Process Rule

- rules/windows/process_creation/win_susp_tracker_execution.yml
Added a rule to detect the potential DLL injection and execution using lolbas tracker.exe. If tracker.exe is executed with /d and /c argument, it could be a sign of DLL injection into the target process.
> [OSCD] Added a rule to detect the execution of tracker.exe with suspicious arguments

- rules/windows/process_creation/win_susp_runonce_execution.yml
Added a rule to detect the execution of runonce with suspicious parameters. If runonce has been executed with /AlternateShellStartup param, it'll run payload configured in the key HKLM\SOFTWARE\Microsoft\Active Setup\Installed Components and StubPath value
> [OSCD] Added a rule to detect execution of runonce with suspicious parameters

- rules/windows/other/win_pcap_drivers.yml
There is no event id 4697 in channel "system" (at least in my logs), but in "security". The blog post from the references is working with channel "security" too.
> fix service from system to security for rule win_pcap_drivers.yml

- tools/sigma/backends/elasticsearch.py
elasticsearch supports selection of returned fields with the keyword "_source" not "_source_"
> bugfix field support

- tools/sigma/backends/qradar.py
Hi there,
I've extended the Qradar implementation.
Fixes:
- Search queries have to use double quotes instead of single quotes (fixes issue #787). Queries look like the sample below:
```
SELECT UTF8(payload) AS search_payload,
sourceip,
EventID,
"Parent Process Path",
"Process Name",
"Process CommandLine",
"SHA256 Hash",
username
FROM EVENTS
```
- Null compares are now possible.
```
username:
- null
```
will generate to:
```
username IS NULL
```
- The optimized INCIDR() use is now possible for /24 and /16 networks with a selection syntax as follows ('10.141.*' doesn't work):
```
src_ip:
- '10.141.0.0/16'
```
will output to:
```
INCIDR('10.141.0.0/16', sourceip))
```
I know that it is far away from being perfect, but the previous version was even more incomplete.
> Fixing Qradar implementation for creating valid AQL queries

- rules/windows/builtin/win_scheduled_task_deletion.yml
According to [this tweet](https://twitter.com/matthewdunwoody/status/1352356685982146562), this event should be of
- low volume
- high value
I was not sure on including a regex check for the  _TaskName_ (e.g. `\TASKNAME`) should be implemented. [Microsoft stated](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4699#security-monitoring-recommendations), that the creation of tasks in the scheduled task root node has been observed in malicious software/actors.
The scheduled task path could be changed during the task creation, so it might not be a good idea to limit the rule that way.
> rule: scheduled task deletion

- README.md
[I packaged](https://github.com/BlackArch/blackarch/pull/2863/files) sigma into [BlackArck](https://blackarch.org/), I thought so it was a good idea to display with repology which distros packaged sigma.
> readme: package in linux distros

- rules/cloud/aws_update_login_profile.yml
Otherwise es-rule ends up with a null risk_score and invalid severity.
> fix: case in level

- rules/windows/process_creation/win_apt_hafnium.yml
- rules/windows/process_creation/win_susp_service_dir.yml
Mostly based on TrueSec's report 
https://blog.truesec.com/2021/03/07/exchange-zero-day-proxylogon-and-hafnium/
> HAFNIUM activity

- tools/sigma/backends/elasticsearch.py
Don't create unnecessary deltas between runs.
> es-rule: make risk scores stable

- tools/sigma/backends/netwitness-epl.py
- tools/sigma/backends/netwitness.py
Incoherent null expressions:
```
nullExpression = "%s exists"
notNullExpression = "%s exists"
```
changed to coherent and fixed EPL to use `not null` instead of `exists`
Ref: http://esper.espertech.com/release-7.1.0/esper-reference/html/epl-operator.html#epl-operator-ref-logical-null
> [bugfix] netwitness and netwitness-epl backends have incoherent null expressions

- tools/config/winlogbeat-modules-enabled.yml
Args is an array of the exploded command line and causes many rules to misfire. See rules/windows/process_creation/win_susp_svchost_no_cli.yml as an example. If CommandLine is mapped to process.args, there will always be an element of the args array that matches when svchost.exe is executed, whether or not there are process arguments.
> Map CommandLine appropriately

- tools/sigma/backends/mdatp.py
This pull request fixes three issues:
| Problem | Solution | Lines | 
| --- | --- | --- |
|`CommandLine` mapping for Registry, File and Network events was missing| Mapping to `InitiatingProcessCommandLine` added |  [L118](https://github.com/SigmaHQ/sigma/pull/1411/files#diff-a0ba69d20c11067bfe3b4ed8ab54c83e17e2f2eb6ee580e5120c3f045b85ee2dR118) [L133](https://github.com/SigmaHQ/sigma/pull/1411/files#diff-a0ba69d20c11067bfe3b4ed8ab54c83e17e2f2eb6ee580e5120c3f045b85ee2dR133) [L149](https://github.com/SigmaHQ/sigma/pull/1411/files#diff-a0ba69d20c11067bfe3b4ed8ab54c83e17e2f2eb6ee580e5120c3f045b85ee2dR149) |
|`*Port` conditions were using `=~` which is not accepted by DfE for integer fields | New `porttype_mapping` function defined which uses `==`| …
> Various Defender for Endpoint (mdatp) bug fixes

- tools/sigma/backends/base.py
The loop in the base Elastic backend returns the first condition only which is all it can do. Ultimately, this needs to be handled by the deriving classes. Until that is done, at least alert rule writers that something is wrong.
> Elastic: raise an error from the base backend if a rule has multiple conditions

- tools/config/winlogbeat-modules-enabled.yml
- tools/config/winlogbeat-old.yml
- tools/config/winlogbeat.yml
Sysmon process create events capture the "product" field from a file version info structure. However, this isn't reflected in the winlogbeat config.
Evidence confirming the field in winlogbeat (couldn't link directly to the field)
https://www.elastic.co/guide/en/beats/winlogbeat/master/exported-fields-winlog.html
Similar config entries for HELK: https://github.com/SigmaHQ/sigma/blob/master/tools/config/helk.yml#L128
> Update winlogbeat configuration file to support File Product details

- tools/sigma/backends/elasticsearch.py
As reported in the issues #542 and #543, currently `count() > condition` result in a produced code, that does not work in the **es-dsl** backend.
In this PR I fixed the problem, by adding the missing keys in the produced aggregation.
Let us consider the rule reported #542 . Now, the aggregation looks like this:
```sh
"aggs": {
"clientip_count": {
"terms": {
"field": "clientip"
},
"aggs": {
"single_clientip_count": {
"value_count": {
"field": "clientip"
}
},
"limit": {
"bucket_selector": {
"buckets_path": {
"count": "single_clientip_count"
},
"script": "params.count > 10"
}
}
}
}
}
```
I report for the sake of discussion, alternative solutions, that I considered but discarded
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_m …
> Fix es-dsl aggregation generation when aggfield is not given

- rules/windows/process_creation/win_apt_chafer_mar18.yml
- rules/windows/registry_event/sysmon_comhijack_sdclt.yml
- rules/windows/registry_event/sysmon_cve-2020-1048.yml
- rules/windows/registry_event/sysmon_reg_office_security.yml
- rules/windows/registry_event/sysmon_reg_silentprocessexit.yml
- rules/windows/registry_event/sysmon_reg_silentprocessexit_lsass.yml
- rules/windows/registry_event/sysmon_runonce_persistence.yml
- rules/windows/registry_event/sysmon_stickykey_like_backdoor.yml
- rules/windows/registry_event/sysmon_win_reg_persistence.yml
- rules/windows/registry_event/sysmon_win_reg_telemetry_persistence.yml
- tools/config/generic/windows-audit.yml
this pull request
- removes the "SetValue", "CreateValue" etc. EventTypes from the rules in category "registry_event" 
- it adds condition für EventID 4657 and the Operation Type to queries in the Windows native auditing config
> feat: generic registry events compatible with native audit logging

- tools/config/thor.yml
A previous commit added a log source detailing *.log files with
product: linux. This caused linux specific Sigma rules to apply to
all *.log file, including those on Windows. To distinguish these
cases, expand the file path pattern to include the typical start
for unix / windows paths ( / vs [A-Z]:\ )
> fix: Distinguish Windows and Linux logfiles by path separator

- tools/sigma/backends/ala.py
Regexes can only be used with regex operation in ala, therefore when contains, startswith, or endswith are used the string should not contain .* or even *.
> Fix contains and starts/ends with queries in ala backend

- tools/config/winlogbeat-modules-enabled.yml
- tools/config/winlogbeat-old.yml
- tools/config/winlogbeat.yml
Added ScriptBlockText as a field for winlogbeat configs as per https://www.elastic.co/guide/en/beats/winlogbeat/master/exported-fields-winlog.html. 
This enables using Sigma queries for ScriptBlock Logging in ElasticSearch SIEM instances.
> Add ScriptBlockText to Winlogbeat Configs

- rules/windows/network_connection/sysmon_rdp_reverse_tunnel.yml
- rules/windows/process_creation/win_hack_secutyxploded.yml
- rules/windows/process_creation/win_susp_csi.yml
- rules/windows/process_creation/win_susp_renamed_debugview.yml
Correct the sysmon case-sensitive Key .
Form the sysmon shema
`<manifest schemaversion="4.60" binaryversion="14.0">`
`<event name="SYSMONEVENT_CREATE_PROCESS" value="1" level="Informational" template="Process Create" rulename="ProcessCreate" ruledefault="include" version="5">`
`<data name="OriginalFileName" inType="win:UnicodeString" outType="xs:string" />`
`<event name="SYSMONEVENT_NETWORK_CONNECT" value="3" level="Informational" template="Network connection detected" rulename="NetworkConnect" version="5">`
`<data name="DestinationIp" inType="win:UnicodeString" outType="xs:string" />`
Test ok with :
`python sigmac --recurse -t elastalert -c config\generic\sysmon.yml -c config\TEST_ECS-sysmon.yml ..\rules\windows`
> Correct the sysmon case-sensitive Key

- rules/network/zeek/zeek_dns_suspicious_zbit_flag.yml
The DNS Z flag is bit within the DNS protocol header that is, per the IETF design, meant to be used reserved (unused). Although recently it has been used in DNSSec, the value being set to anything other than 0 should be rare. Otherwise if it is set to non 0 and DNSSec is being used, then excluding the legitimate domains is low effort and high reward.
references:
- 'https://twitter.com/neu5ron/status/1346245602502443009'
- 'https://tools.ietf.org/html/rfc2929#section-2.1'
- 'https://www.netresec.com/?page=Blog&month=2021-01&post=Finding-Targeted-SUNBURST-Victims-with-pDNS'
> [Add Rule] Zeek Suspicious DNS Z Flag Set

- rules/windows/image_load/sysmon_alternate_powershell_hosts_moduleload.yml
- rules/windows/image_load/sysmon_powershell_execution_moduleload.yml
By default some backends perform case sensitive match on field values (SQLite), since the real values in event logs use uppercase letters, it is better to use them in the rules.
> Modified some field values for case sensitive backends (SQL)

- tools/sigma/backends/sql.py
- tools/tests/test_backend_sql.py
- tools/tests/test_backend_sqlite.py
When using SQL backends, rules with aggregates are converted into a SQL query looking like that : 
```sql
SELECT * FROM (SELECT count(*) AS agg FROM logs WHERE (Channel = "Microsoft-Windows-TaskScheduler/Operational" AND EventID = "106") GROUP BY TaskName) WHERE agg < 5
```
After execution, if there is a successful match the result is like :
| agg |
|-----|
|  1     | 
So, we loose all the information of the log that have successfully matched against the rule. To correct this, it is better to add all the missing fields in the query : 
```sql
SELECT * FROM (SELECT *, count(*) AS agg FROM logs WHERE (Channel = "Microsoft-Windows-TaskScheduler/Operational" AND EventID = "106") GROUP BY TaskName) WHERE agg < 5
```
This commit implement this behaviour (only for avg, sum, count, min, max SQL …
> Change to have raw log in rule results with SQL/SQlite Backends

- tools/sigma/backends/elasticsearch.py
Ref : https://github.com/SigmaHQ/sigma/issues/1450#issuecomment-840777032
This [commit](https://github.com/SigmaHQ/sigma/commit/0448e468705715cc3ba7e06c1afaffbf7c06862d#diff-a9fc01b8aa076e9d930106f26dc87e3ec565c519bb242eb4ca591620459f3f8b) introduce a bug when your are converting your rules for "es-rule" backend in recursive mode ("-r" option). In fact, the problem come from `self.rule_type = "threshold"` in `elasticsearch.py`, the backend class is directly updated in the function and not cleaned after rule generation so if you are iterating on multiple rules, the value is good as long as you don't have an aggregation in the rule. After the first rule with aggregation, all subsequent rules will have `"type": " "threshold"`.
The fastest way to correct the bug was by resetting the values of …
> Resolves #1450 - Bug in es-rule backend when using "-r" argument

- tools/sigma/backends/elasticsearch.py
`es-rule` use title for the id rule even if it is a uuid.
I have changed the behavior to have the uuid.
But if it is null I've keep the title.
> FIx ElasticSearchRuleBackend to use uuid instead of title for the rule id

- rules/windows/process_access/win_susp_shell_spawn_from_winrm.yml
Add a rule for detecting shell/binary spawn from WinRM host process.
Note regarding PowerShell:
* WinRM is used for PowerShell remoting, therefore, PowerShell commands are mostly executed inside the WinRM host process, so a child process for powershell will be missing unless someone executes powershell.exe over WinRM.
OSCD issues having mentioned WinRM
* https://github.com/SigmaHQ/sigma/issues/1014
* https://github.com/SigmaHQ/sigma/issues/576
> rule: add rule to detect shell spawn from WinRM host process

- rules/windows/builtin/win_remote_powershell_session.yml
- rules/windows/process_creation/win_remote_powershell_session_process.yml
Until now when searching for WinRM through the rules these rules were missing and only be found using other keywords like "powershell" or remoting. With adding the WinRM keyword it's easier to find WinRM related rules.
See https://github.com/SigmaHQ/sigma/pull/1493 for a new rule regarding WinRM too.
> Add keyword WinRM to remote powershell rules

- tools/sigma/backends/elasticsearch.py
Fix the issue  :
- #1486
-  #674
Fix all errors _400_ when import in Kibana 12.1 `Detection rules`.
Test with 819 rules :
`python sigmac --recurse -I -t es-rule -c .\config\winlogbeat-modules-enabled.yml ..\rules\windows  -o rules-windows.ndjson`
> Fix errors when import es-rule ndjson to KIBANA

- rules/windows/builtin/win_invoke_obfuscation_clip+_services.yml
- rules/windows/builtin/win_invoke_obfuscation_stdin+_services.yml
- rules/windows/builtin/win_invoke_obfuscation_var+_services.yml
- rules/windows/builtin/win_invoke_obfuscation_via_compress_services.yml
- rules/windows/builtin/win_invoke_obfuscation_via_rundll_services.yml
- rules/windows/builtin/win_invoke_obfuscation_via_stdin_services.yml
- rules/windows/builtin/win_invoke_obfuscation_via_use_clip_services.yml
- rules/windows/builtin/win_invoke_obfuscation_via_use_mshta_services.yml
- rules/windows/builtin/win_invoke_obfuscation_via_use_rundll32_services.yml
- rules/windows/builtin/win_invoke_obfuscation_via_var++_services.yml
Hi,
finally found the solution to correct the bad conversion to SIEM.
Thanks to [Invoke-Obfuscation Obfuscated IEX Invocation](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/win_invoke_obfuscation_obfuscated_iex_services.yml)
> Fix missing eventid when converting windows obfuscation rules

- rules/cloud/aws_snapshot_backup_exfiltration.yml
I've written a rule for a cloud exfiltration technique that I've been researching, use of AWS' "Modify Snapshot Permissions" functionality to provide another AWS account access to EC2 snapshot files. This allows exfiltration without triggering any large network transfer detections that may be in place, since everything stays within AWS. 
Hopefully the rule follows the correct format.
> Contribute AWS snapshot exfiltration rule

- rules/windows/process_creation/process_creation_c3_load_by_rundll32.yml
This rule targets DLLs created with the default version of F-Secure's C3. These DLLs include the export function `StartNodeRelay`
> Added rule for rundll32 launch of default F-Secure C3 Relay

- rules/windows/process_creation/process_creation_SDelete.yml
detect [SDelete use](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1485/T1485.md)
use `OriginalFileName` in case user rename the file 
filter 
- '-h' help
- '-c' and '-z' is the clear the free space not file
> Add windows T1485 SDelete

- rules/windows/powershell/powershell_alternate_powershell_hosts.yml
- tools/config/winlogbeat-modules-enabled.yml
- tools/config/winlogbeat-old.yml
- tools/config/winlogbeat.yml
Hi,
Add some fix to make more accurate the detection
- Add powershell channel mapping to tools/config/winlogbeat-modules-enabled.yml
- Add powershell channel mapping to tools/config/winlogbeat-old.yml
- Add powershell channel mapping to tools/config/winlogbeat.yml
- Split powershell_alternate_powershell_hosts.yml to get the correct channel <-> EventId
```
D:\FrackSigma\Sigma\tools>python sigmac -t es-qs -c .\config\winlogbeat-modules-enabled.yml D:\FrackSigma\Sigma\rules\windows\powershell\powershell_alternate_powershell_hosts.yml
((winlog.event_id:("4103" OR "400") AND ContextInfo.keyword:*) AND (NOT (ContextInfo:"powershell.exe" OR Message:"powershell.exe")))
```
```
D:\FrackSigma\Sigma\tools>python sigmac -t es-qs -c .\config\winlogbeat-modules-enabled.yml …
```
> make powershell_alternate_powershell_hosts more accurate 

- tools/sigma/backends/elasticsearch.py
- tools/sigma/parser/collection.py
- tools/sigma/sigmac.py
Add some fun backend option to es-rule for @V1D1AN [S1EM](https://github.com/V1D1AN/S1EM)
**everything is deactivated by default**
To help when manage rule in Kibana
`python sigmac --recurse -t es-rule -I -c .\config\winlogbeat-modules-enabled.yml ..\rules -o rule.ndjson -O custom_tag=SigmaHQ`
To keen the link to the original file
`python sigmac --recurse -t es-rule -I -c .\config\winlogbeat-modules-enabled.yml ..\rules -o rule.ndjson -C .\frack113.yml`
My frack113.yml
```YAML
put_filename_in_ref: True
convert_to_url: False
path_to_replace: '..\'
dest_base_url: 'https://github.com/SigmaHQ/sigma/tree/master/'
```
It is **not** a valide URL just some info
To keen the link to the original file
`python sigmac --recurse -t es-rule -I -c .\config\winlogbeat-modules-enabled.yml ..\rules -o …
> Add some fun backend option for es-rule

- rules/windows/registry_event/sysmon_disable_microsoft_office_security_features.yml
If registry is set to 1 an external document will not show any warning before editing the document
Not the same as sysmon_reg_office_security.yml detect registry with changes to Office macro settings
To make to work with all version of office.
`TargetObject: HKU\S-1-5-21-56616125-1371661524-2852374103-1001\SOFTWARE\Microsoft\Office\16.0\Excel\Security\VBAWarnings`
so Split to :
- \SOFTWARE\Microsoft\Office\
- \VBAWarnings
the re can be `HKU\\\S+\\SOFTWARE\\Microsoft\\Office\\\d+\.0\\\w+\\Security\\VBAWarnings` but not all backend support it
> T1562.001 Atomic Test #18 - Disable Microsoft Office Security Features

- tools/config/generic/sysmon.yml
Add missing sysmon event ID to the Sigma Category.
from my https://github.com/SigmaHQ/sigma/issues/1525# I've create sysmon_error as it is not a status change
EventID | Sysmon name | Sigma category
-------- | --------- | ---------
2 | SYSMON_FILE_TIME | [file_change](https://github.com/trustedsec/SysmonCommunityGuide/blob/master/file-create-time-change.md)
4 | SYSMON_SERVICE_STATE_CHANGE | [sysmon_status](https://github.com/trustedsec/SysmonCommunityGuide/blob/master/operational-events.md)
16 | SYSMONEVENT_SERVICE_CONFIGURATION_CHANGE | [sysmon_status](https://github.com/trustedsec/SysmonCommunityGuide/blob/master/operational-events.md)
24 | SYSMON_CLIPBOARD | [clipboard_capture](https://github.com/trustedsec/SysmonCommunityGuide/blob/master/clipboard-capture.md)
25 | …
> Add missing sysmon EventID

- rules/windows/builtin/win_iso_mount.yml
- Rule is based on Windows logging
- Object access logging for 'Removable Storage' is required
Does that need to be added in?
> Detection rule for 'ISO mounts'

- tools/config/carbon-black-eedr.yml
Add support for VMware Carbon Black Cloud EEDR. Field mappings derived from https://developer.carbonblack.com/reference/carbon-black-cloud/cb-threathunter/latest/process-search-fields/
> Support for VMware Carbon Black Cloud EEDR

- rules/windows/process_creation/win_susp_bcdedit.yml
- rules/windows/process_creation/win_susp_wmi_execution.yml
- rules/windows/registry_event/sysmon_taskcache_entry.yml
Hi, I've modified two rules and added two new ones. Here's a short description to maybe justify this:
**Addition of Safemode Flags:**
BCDEDIT can be used with a few other parameters such as 'safemode' and 'network' to boot into safemode with networking enabled. Such was done in an older REvil campaign as I've added to the references. 
**Suspicious WMI Execution**
When we add the NODE parameter to the filter with 'ALL', commands run locally lose coverage. Either the filter should be a bit loose or it shouldn't be using NODE in the first place. Example, 'wmic process call create' is just as valid as me mentioning a node in there for remote coverage. Former covers more than the latter.
**TaskCache Entry**
If a new scheduled task is registered, these keys are populated by a new GUID or task …
> Rule Edits and 'TaskCache Entry' Rule

- rules/windows/process_creation/win_netsh_port_fwd.yml
- rules/windows/registry_event/win_portproxy_registry_key.yml
Add new port proxy registry rule and add two further references to the rules:
- https://adepts.of0x.cc/netsh-portproxy-code/
- https://www.dfirnotes.net/portproxy_detection/
> rule: add port proxy registry rule and further references

- rules/windows/powershell/powershell_powerview_malicious_commandlets.yml
Hello,
I am not very familiar with SIGMA but it seems that there is a typo on a cmdlet.
I'm not sure what I'm saying so don't hesitate to tell me if I'm wrong.
Thanks
> Typo on Find-DomainObjectPropertyOutlier

- rules/network/zeek/zeek_default_cobalt_strike_certificate.yml
Remark: I have replaced the dot in the fields to underscore.
```#fields	ts	id	certificate.version	certificate.serial	certificate.subject	certificate.issuer	certificate.not_valid_before	certificate.not_valid_after	certificate.key_alg	certificate.sig_alg	certificate.key_type	certificate.key_length	certificate.exponent	certificate.curve	san.dns	san.uri	san.email	san.ip	basic_constraints.ca	basic_constraints.path_len```
```1620943055.563566	FebYNp2042PTwLAlOf	3	08BB00EE	CN=,OU=,O=,L=,ST=,C=	CN=,OU=,O=,L=,ST=,C=	1432125684.000000	1747485684.000000	rsaEncryption	sha256WithRSAEncryption	rsa	2048	65537	-	-	-	-	-	-	-```
> Added rule for default cobalt strike certificate

- tools/sigma/backends/powershell.py
After seeing #1564, I reviewed the PowerShell backend and noticed there was already remapping for the `EventID` field. I changed it to use a mapping dictionary instead of a simple check due to the likelyhood of another one of these inconsistencies showing up in the future, which can then simply be added to the dictionary with no additional logic required.
> Generic remapping for PowerShell backend

- tools/sigma/backends/elasticsearch.py
Hi ,
Add multi custom tag in es-rule.
```
python sigmac -t es-rule --backend-help es-rule
custom_tag: Add custom tag. for multi split with a comma tag1,tag2  (default: None)
```
exemple : 
```
python sigmac -t es-rule -c .\config\winlogbeat.yml --backend-option custom_tag=sigma,network ..\rules\network\net_apt_equationgroup_c2.yml
```
get the correct `... "high", "tags": ["sigma", "network"], "to" ...`
close #1560
> add multi custom tag for issue #1560

- rules/windows/builtin/win_impacket_secretdump.yml
- rules/windows/builtin/win_net_ntlm_downgrade.yml
- rules/windows/builtin/win_net_use_admin_share.yml
- rules/windows/builtin/win_vul_cve_2020_0688.yml
- rules/windows/create_remote_thread/sysmon_suspicious_remote_thread.yml
- rules/windows/file_event/win_rclone_exec_file.yml
- rules/windows/process_access/sysmon_cmstp_execution.yml
- rules/windows/process_creation/win_apt_lazarus_activity_apr21.yml
- rules/windows/process_creation/win_apt_lazarus_activity_dec20.yml
- rules/windows/process_creation/win_apt_lazarus_loader.yml
- rules/windows/process_creation/win_apt_unc2452_cmds.yml
- rules/windows/process_creation/win_crime_maze_ransomware.yml
- rules/windows/process_creation/win_mal_adwind.yml
- rules/windows/process_creation/win_powershell_reverse_shell_connection.yml
- rules/windows/process_creation/win_susp_conhost.yml
- rules/windows/process_creation/win_susp_file_characteristics.yml
- rules/windows/process_creation/win_susp_outlook_temp.yml
- rules/windows/process_creation/win_susp_shell_spawn_from_mssql.yml
- rules/windows/process_creation/win_susp_userinit_child.yml
- rules/windows/sysmon/sysmon_dcom_iertutil_dll_hijack.yml
Changes in this PR : 
- Some backends (SQL, SQLite) don't like the '*' wildcard, so when it was possible the rules have been rewritten with modifiers (contains etc.)
- During the rewrite, I came across a lot of double backlashes in the rules. But according the [specs](https://github.com/SigmaHQ/sigma/wiki/Specification#general) : *"You don't have to escape characters except the string quotation marks `'`"* and *"Wildcards can be escaped with `\`, e.g. `\*`. If some wildcard after a backslash should be searched, the backslash has to be escaped: `\\*`"*. So, I removed a lot of trailing double backslashes, this changes are not very important for some backends (like Splunk) but it corrects some bad rules conversion for SQL/SQLite backends
- When I came across `CommandLine` field values with …
> Updated rules with modifiers instead of '*', removed trailing '\\', removed drive letter before "Users"

- rules/windows/image_load/sysmon_cve_2021_1675_print_nightmare.yml
This PR change : 
-  Paths used in the PrintNightmare Sysmon Image load based rule with modifiers instead of wildcard `*`
> Updated PrintNightmare Sysmon Imageload based rule with modifiers

- rules/windows/malware/av_printernightmare_cve_2021_34527.yml
Assign CVE-2021-34527 Windows Print Spooler Remote Code Execution Vulnerability
> Update and rename to av_printernightmare_cve_2021_34527.yml

- rules/windows/builtin/win_exploit_cve_2021_1675_printspooler.yml
XML of the event showing different ErrorCode on Windows 10 Host. 
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
<Provider Name="Microsoft-Windows-PrintService" Guid="{747ef6fd-e535-4d16-b510-42c90f6873a1}" /> 
<EventID>808</EventID> 
<Version>0</Version> 
<Level>2</Level> 
<Task>36</Task> 
<Opcode>12</Opcode> 
<Keywords>0x8000000000020000</Keywords> 
<TimeCreated SystemTime="2021-07-01T17:33:51.505479000Z" /> 
<EventRecordID>1</EventRecordID> 
<Correlation /> 
<Execution ProcessID="2616" ThreadID="5176" /> 
<Channel>Microsoft-Windows-PrintService/Admin</Channel> 
<Computer>DESKTOP-GB8KT3V.hawkio.local</Computer> 
<Security UserID="S-1-5-18" /> 
</System>
- <UserData>
- <LoadPluginFailed xmlns="http://manifests.microsoft.com/win/2005/08/windows/print …
```
> Added new possible ErrorCode

- rules/windows/builtin/win_exploit_cve_2021_1675_printspooler_Security.yml
This is the first rule I've added; I think I followed the guidelines correctly.
> Added new Print Spooler exploitation detection method

- tools/sigma/backends/elasticsearch.py
- tools/sigma/backends/mixins.py
Hi,
getRuleName() return `uuid` or if missing `title`.
The uuid does not allow a easy following in elastalert or SIEM.
So I changed it to `id-title`.
the function already handles duplicates natively
close #1618 
close #666
> Change getRuleName() to get 'id-title' instead of ('id' or 'title')

- tools/sigma/backends/graylog.py
Search queries generated by Graylog backend don't escape spaces in field values.
> Escape spaces in graylog backend

- rules/windows/builtin/win_mal_service_installs.yml
Fix mistake (incorrect logsource for event ID 4697) in PR #1629.
* Event ID 4697 belongs under `winlog.channel: Security`.
* Event ID 7045 belongs under `winlog.channel: System`.
Have tested that the latest changes result in rule detections - sorry for the mistake earlier.
> Update win_mal_service_installs.yml - Corrected logsource

- rules/windows/powershell/powershell_data_compressed.yml
Changed to `ScriptBlockText` (due to PowerShell logging-specific context).
> powershell_data_compressed.yml - Update selection

- tools/sigma/backends/mdatp.py
This reverts commit cdc434cfc485bfd7b0cfafbc7df7347c67d5eec1.
> Revert "feat: OriginalFileName mapping in MDATP ImageLoad events"

- tools/config/winlogbeat.yml
Change Imphash's value as current value only exists with the Sysmon processor module under Winlogbeat (which is seen in `winlogbeat-modules-enabled.yml`).
For more clarity regarding the same field (where Winlogbeat's Sysmon module is enabled), see #1667.
> Update winlogbeat.yml - Imphash Field

- tools/config/winlogbeat-modules-enabled.yml
Replaced mapping for Imphash (based on Winlogbeat's Sysmon processor module).
* In https://www.elastic.co/guide/en/beats/winlogbeat/current/exported-fields-ecs.html, we see `process.pe.imphash`.
* In Winlogbeat's Sysmon processor module found at https://raw.githubusercontent.com/elastic/beats/master/x-pack/winlogbeat/module/sysmon/config/winlogbeat-sysmon.js, we see at line 400 that it is processed into `process.pe.imphash` via `return namespace + ".pe.imphash";`.
> Update winlogbeat-modules-enabled.yml - Imphash Field

- tools/sigma/backends/ala.py
When using the contains modifier on sigma, the ala backend converts it to `where field contains ".*keyword.*"`, which causes it not to match the desired events.
The contains, startswith and endswith keyword on ala seems to exclude the need of using these kind of wildcards.
> Remove Field Value Wildcard in ALA Backend

- rules/windows/process_creation/process_creation_infdefaultinstall.yml
- rules/windows/process_creation/process_creation_syncappvpublishingserver_execute_arbitrary_powershell.yml
- rules/windows/process_creation/sysmon_creation_mavinject_dll.yml
Hi,
I check rule for:
|Tactic|Technique|Technique Name|Test|Test Name|Rule|
|---|---|---|---|---|---|
|defense-evasion|T1218|Signed Binary Proxy Execution|1|mavinject - Inject DLL into running process|add|
|defense-evasion|T1218|Signed Binary Proxy Execution|2|SyncAppvPublishingServer - Execute arbitrary PowerShell code|new one|
|defense-evasion|T1218|Signed Binary Proxy Execution|3|Register-CimProvider - Execute evil dll|-|
|defense-evasion|T1218|Signed Binary Proxy Execution|4|InfDefaultInstall.exe .inf Execution|add
for SyncAppvPublishingServer  think to remove the `win_syncappvpublishingserver_exe.yml`
> Some Redcanary T1228

- tests/test_rules.py
Hi,
Add a test to check if the rule use a duplicate ID.
Test on Ubuntu , get the same result as before the fix (so should be good).
Get a warning if a rule use a duplicate ID.
> test_rules.py check duplicate id

- rules/windows/builtin/win_susp_sdelete.yml
- tests/test_rules.py
Hi,
In tests/test_rules.py add: 
- check if  `modified` is good
- check if `date` and  `modified` are string  (for 2021-07-21 get a data type error for len() )
And of course fix `modified` in rules/windows/builtin/win_susp_sdelete.yml  :smile:
Test on Unbuntu 20.04
> Update date and modified test

- rules/windows/process_creation/sysmon_netcat_execution.yml
Hi,
Check use of [ncat.exe](https://nmap.org/ncat/).
I can not use OriginalFileName as is empty so it is easy to bypass the detection.😔
```
Ncat is a feature-packed networking utility which reads and writes data across networks from the command line.
Ncat was written for the Nmap Project as a much-improved reimplementation of the venerable Netcat.
It uses both TCP and UDP for communication and is designed to be a reliable back-end tool to instantly provide network connectivity to other applications and users.
Ncat will not only work with IPv4 and IPv6 but provides the user with a virtually limitless number of potential uses
```
Test 8  of #1013
> [OSCD] sysmon_netcat_execution.yml T1095

- tools/sigma/sigmac.py
Hi,
Update the `--output` argument.
If the filename end with `_` or `/` or `\` use it as prefix.
`python sigmac -t es-qs -r -c .\config\winlogbeat.yml ..\rules\windows\sysmon -o .\out\`
get 
Add `--output-extention`
example to have some '.txt' file : `python sigmac -t es-qs -r -c .\config\winlogbeat.yml ..\rules\windows\sysmon -o .\out\  -e txt`
close #552
> Update output arg options

- rules/windows/builtin/win_susp_eventlog_cleared.yml
- rules/windows/process_creation/process_creation_syncappvpublishingserver_execute_arbitrary_powershell.yml
- tests/test_rules.py
Hello,
I've add : 
- test_optional_related must be a list and `type` a good value
- test_optional_fields  must be a list
- test_optional_falsepositives must be a list
Make some shaping for previous push 
Fix 2 rules for `related` :relaxed:
> Update test_rules.py 

- rules/windows/process_creation/win_grabbing_sensitive_hives_via_reg.yml
Add variations to cover unicode substitutions to avoid evasion.
> Unicode contains a range for Spacing Modifier Letters (0x02B0 - 0x02FF) [4], which includes characters such as ˪, ˣ and ˢ. Some command-line parsers recognise these as letters and convert them back to l, x and s respectively. 
See (https://www.wietzebeukema.nl/blog/windows-command-line-obfuscation) by @Wietze
> cover evasions from unicode substitutions

- tools/sigma/config/collection.py
`self.paths` is supposed to be an iterable of `Path` objects, if you pass it using the `path=` parameter it can only be an iterable of strings (see line 53).
This patch converts the list of strings to Path objects to fix the issue and maximise backwards compatibility.
> Fixing exception caused by incorrect type of passed 'path' parameter

- tools/sigma/backends/carbonblack.py
In CarbonBlack EEDR, leading hyphens (e.g. `process_cmdline:-create`) cause syntax errors - presumably because hyphens are also used to negate conditions.
Whilst leading hyphens seem to be accepted in Carbon Black Response, escaping them doesn't impact the query results. If anything, it probably makes the rules more readable. 
E.g.:
| Case | Product | Syntax | Accepted? |
| -- | -- | -- | -- |
|Case 1| **Carbon Black Response**|  `cmdline:hello-world` | ✔ |
|| **Carbon Black Cloud (EEDR)**|  `process_cmdline:hello-world` | ✔ |
|Case 2| **Carbon Black Response**|  `cmdline:-create` | ✔|
|| **Carbon Black Cloud (EEDR)**|  `process_cmdline:-create` | ❌ |
|Case 3| **Carbon Black Response**|  `cmdline:\-create` | ✔|
|| **Carbon Black Cloud (EEDR)**|  `process_cmdline:\-create` | ✔ |
Sigma …
> [CarbonBlack] Adding extra escape character

- tools/config/carbon-black-eedr.yml
Couple of updates:
| Update | Comment | 
| --- | --- |
| Removed `netconn_remote_*` | Does not exist according to [the docs](https://developer.carbonblack.com/reference/carbon-black-cloud/cb-threathunter/latest/process-search-fields/). |
| Removed `process_internal_name` | Whilst a relevant and interesting field, this is inconsistent with other Sigma backends. <sub>(in my case, it caused FPs on Windows Update processes/files which use random filenames on disk but obviously keep the internal file name)</sub> |
| Renamed `regmod_new_name` | This field doesn't exist according to [the docs](https://developer.carbonblack.com/reference/carbon-black-cloud/cb-threathunter/latest/process-search-fields/), `regmod_name` does. |
| Removed `crossproc_name` | Removed from entries that also look for …
> [CarbonBlack EEDR] Several updates to config file

- rules/windows/powershell/powershell_CL_Invocation_LOLScript.yml
- rules/windows/powershell/powershell_CL_Invocation_LOLScript_v2.yml
- rules/windows/powershell/powershell_CL_Mutexverifiers_LOLScript.yml
- rules/windows/powershell/powershell_CL_Mutexverifiers_LOLScript_v2.yml
- rules/windows/powershell/powershell_accessing_win_api.yml
- rules/windows/powershell/powershell_automated_collection.yml
- rules/windows/powershell/powershell_clear_powershell_history.yml
- rules/windows/powershell/powershell_create_local_user.yml
- rules/windows/powershell/powershell_decompress_commands.yml
- rules/windows/powershell/powershell_dnscat_execution.yml
- rules/windows/powershell/powershell_get_clipboard.yml
- rules/windows/powershell/powershell_icmp_exfiltration.yml
- rules/windows/powershell/powershell_invoke_obfuscation_clip+.yml
- rules/windows/powershell/powershell_invoke_obfuscation_obfuscated_iex.yml
- rules/windows/powershell/powershell_invoke_obfuscation_stdin+.yml
- rules/windows/powershell/powershell_invoke_obfuscation_var+.yml
- rules/windows/powershell/powershell_invoke_obfuscation_via_compress.yml
- rules/windows/powershell/powershell_invoke_obfuscation_via_rundll.yml
- rules/windows/powershell/powershell_invoke_obfuscation_via_stdin.yml
- rules/windows/powershell/powershell_invoke_obfuscation_via_use_clip.yml
- rules/windows/powershell/powershell_invoke_obfuscation_via_use_mhsta.yml
- rules/windows/powershell/powershell_invoke_obfuscation_via_use_rundll32.yml
- rules/windows/powershell/powershell_invoke_obfuscation_via_var++.yml
- rules/windows/powershell/powershell_prompt_credentials.yml
- rules/windows/powershell/powershell_suspicious_export_pfxcertificate.yml
- rules/windows/powershell/powershell_suspicious_getprocess_lsass.yml
- rules/windows/powershell/powershell_suspicious_mounted_share_deletion.yml
- rules/windows/powershell/win_powershell_web_request.yml
Hi,
For PowerShell EventID 4104 :
1. Add `definition: 'Script block logging must be enabled'` if missing
2. `ScriptBlockText` is the correct field name
3. Remove list with only 1 value ( exclude filter)
> Clean-up Powershell EventID 4104

- tools/sigma/backends/elasticsearch.py
- tools/sigma/sigmac.py
HI,
Find the bug and fix it.
close #1759
```yaml
C:\FrackSigma\sigma\tools>python sigmac -t elastalert -c .\config\winlogbeat.yml ..\rules\windows\builtin\win_account_backdoor_dcsync_rights.yml
alert:
- debug
description: backdooring domain object to grant the rights associated with DCSync to a regular user or machine account using Powerview\Add-DomainObjectAcl DCSync Extended Right cmdlet, will allow to re-obtain the pwd hashes of any user/computer
filter:
- query:
query_string:
query: (winlog.channel:"Security" AND winlog.event_id:"5136" AND winlog.event_data.AttributeLDAPDisplayName:"ntSecurityDescriptor" AND winlog.event_data.AttributeValue.keyword:(*1131f6ad\-9c07\-11d1\-f79f\-00c04fc2dcd2* OR *1131f6aa\-9c07\-11d1\-f79f\-00c04fc2dcd2* OR *89e95b76\-444d\-4c62\-991a\-0facbeda640c*)) …
```
> Fix duplicate output in elastalert Backend

- rules/windows/file_event/sysmon_cve_2021_26858_msexchange.yml
- rules/windows/file_event/sysmon_lsass_memory_dump_file_creation.yml
- rules/windows/file_event/win_cve_2021_1675_printspooler.yml
- rules/windows/other/win_tool_psexec.yml
- rules/windows/sysmon/sysmon_cve_2021_31979_cve_2021_33771_exploits.yml
Hi
Fix case error of TargetFilename  as in the sysmon shema
```xml
<event name="SYSMON_FILE_TIME" value="2" level="Informational" template="File creation time changed" rulename="FileCreateTime" version="5">
<data name="RuleName" inType="win:UnicodeString" outType="xs:string" />
<data name="UtcTime" inType="win:UnicodeString" outType="xs:string" />
<data name="ProcessGuid" inType="win:GUID" />
<data name="ProcessId" inType="win:UInt32" outType="win:PID" />
<data name="Image" inType="win:UnicodeString" outType="xs:string" />
<data name="TargetFilename" inType="win:UnicodeString" outType="xs:string" />
<data name="CreationUtcTime" inType="win:UnicodeString" outType="xs:string" />
<data name="PreviousCreationUtcTime" inType="win:UnicodeString" outType="xs:string" />
</event>
```
> Correct TargetFilename case error

- rules/windows/process_creation/win_modif_of_services_for_via_commandline.yml
The ^ symbol designates the beginning of the string, but in this rule it is clearly intended to be the end of the string.
> Correcting regex in win_modif_of_services_for_via_commandline.yml

- tools/sigma/backends/elasticsearch.py
Hello
'hash' field are convert to [hash.lower OR hash.upper] which is not a normal behavior.
It must be an option.
So add `hash_normalise`  option
```
Backend options for es-qs
...
hash_normalise: Normalise hash field to lower , upper or both. If not use field is a normal field. Valid options are: lower/upper/both (default: None)
```
the rule
```yaml
logsource:
category: image_load
detection:
selection:
sha256:
- 123456789Frack113IsTheHash987654321
- The_Flag_Is_Not_Here
```
the results
```dos
C:\FrackSigma\sigma\tools>python sigmac -t es-qs -c .\config\generic\sysmon.yml -c .\config\winlogbeat-modules-enabled.yml C:\FrackSigma\test_rule.yml
(event.code:"7" AND winlog.channel:"Microsoft\-Windows\-Sysmon\/Operational" AND …
```
> add hash_normalise option for ElasticsearchWildcardHandlingMixin

- tests/test_rules.py
- tools/sigma/filter.py
Hi,
As my first PR #1802 has too many rules , I've close it.
Add new Attribute:
- tlp from https://www.cisa.gov/tlp  for internal organisation use
- target  a free optional list ('server','workstation','iot',..) 
Add new test:
- test_optional_tlp
- test_optional_target
- test_selection_list_one_value (deactivate because more than 170 rules to fix before but it is ready)
Add new filter :
- tlp=  (if rule have no tlp it is convert to "WHITE")
- target=
Check #1804 for more information
> Sigma Schema add new Attribute and test

- rules/windows/other/win_defender_amsi_trigger.yml
- tools/config/winlogbeat-modules-enabled.yml
Hi 
add mising System and Microsoft-Windows-Windows Defender/Operational field.
Fix win_defender_amsi_trigger.yml with the correct field name (check with the xml event on windows 10).
Windows Defense use space in field name and winlogbeat keep it.
find the trick so now: 
```cmd
python sigmac -t es-qs -c .\config\generic\sysmon.yml -c .\config\winlogbeat-modules-enabled.yml C:\FrackSigma\sigma\rules\windows\other\win_defender_amsi_trigger.yml
(winlog.channel:"Microsoft\-Windows\-Windows\ Defender\/Operational" AND event.code:"1116" AND winlog.event_data.Source\ Name:"AMSI")
```
> Update Mapping Winlogbeat modules enabled

- tools/sigma/backends/elasticsearch.py
- tools/sigma/sigmac.py
Hi,
to satisfy my co-workers fix the multi output file for elastalert.
Test with recursive option
```yaml
python sigmac -t elastalert -c .\config\generic\sysmon.yml -rI ..\rules\windows\sysmon
```
get all the alert in the screen 👍 
```winbatch
python sigmac -t elastalert -c .\config\generic\sysmon.yml -rI ..\rules\windows\sysmon -o bigfile.txt
```
get bigfile.txt with 14 alerts 👍 
```winbatch
python sigmac -t elastalert -c .\config\generic\sysmon.yml -rI ..\rules\windows\sysmon -o elast_
```
get 14 files with 1 alert / file 👍 
```winbatch
python sigmac -t kibana -c .\config\generic\sysmon.yml -rI ..\rules\windows\sysmon -o kiban_
```
As kibana backend produce only 1 file get `kiban_kibana_mono_output.rule`
If the backend do not support multi output get only 1 file : 
prefix  + backend …
> Fix elastalert multi output file

- tools/sigma/backends/base.py
Should reduce brackets on some output targets
> Optimising lists/subexpressions with only one item

- Pipfile
- Pipfile.lock
- tools/sigma/sigmac.py
For most backends, sigmac only output the converted rule(s) which led a lot of sigma users to build a specific tool to convert the rules and add missing fields (title, level etc...) to the output. For example, you can add the `author` field to be compliant with the DRL.
**This PR add two options (working together) to sigmac :** 
- `--output-fields OUTPUT_FIELDS` or `-of OUTPUT_FIELDS` : this option allows to provide fields of the Sigma rule you want to add to the output of the converted rule (title, id, status, description, author, references, fields, falsepositives, level, tags are available). 
- `--output-format {json,yaml}` or `-oF {json,yaml}` : this option allows to specified the output format (JSON or YAML). 
These options work with 1 rule or with `--recurse`.
Example in JSON : …
> Add an option to enhance the default output by choosing more fields + JSON/YAML

- rules/cloud/aws_cloudtrail_disable_logging.yml
- rules/cloud/aws_config_disable_recording.yml
- rules/cloud/aws_ec2_disable_encryption.yml
- rules/cloud/aws_ec2_download_userdata.yml
- rules/cloud/aws_ec2_startup_script_change.yml
- rules/cloud/aws_enum_listing.yml
- rules/cloud/aws_guardduty_disruption.yml
- rules/cloud/aws_iam_backdoor_users_keys.yml
- rules/cloud/aws_rds_change_master_password.yml
- rules/cloud/aws_rds_public_db_restore.yml
- rules/cloud/aws_root_account_usage.yml
- rules/cloud/aws_snapshot_backup_exfiltration.yml
- rules/cloud/aws_update_login_profile.yml
Hello
As my #1802 is to big to be check , I've make a split PR for rules/cloud/ more humain. 
So FIX : 
- selection  with a list of only 1 field
- field with list of only 1 value
- cleanup "sel1 and sel2 and selx..." when need
> Correct lists with only 1 value in cloud rules

- rules/network/net_susp_dns_b64_queries.yml
- rules/network/net_susp_telegram_api.yml
- rules/proxy/proxy_ua_bitsadmin_susp_tld.yml
- rules/proxy/proxy_ua_suspicious.yml
- rules/proxy/proxy_ursnif_malware_c2_url.yml
- rules/proxy/proxy_ursnif_malware_download_url.yml
- rules/web/web_citrix_cve_2020_8193_8195_exploit.yml
- rules/web/web_cve_2018_2894_weblogic_exploit.yml
- rules/web/web_solarwinds_supernova_webshell.yml
- rules/web/web_vsphere_cve_2021_21972_unauth_rce_exploit.yml
- rules/web/win_powershell_snapins_hafnium.yml
Hello
As my #1802 is to big to be check , I've make a split PR for "network" rules more humain.
So FIX :
-  selection with a list of only 1 field
-  field with list of only 1 value
- split `proxy_ursnif_malware` into 2 files proxy_ursnif_malware_c2_url.yml  and proxy_ursnif_malware_download_url.yml
> Correct lists with only 1 value in network rules

- tools/sigma/backends/elasticsearch.py
The Kibana Watcher interface uses the "name" field in the alert's metadata to fill the column.  This request changes references in the Watcher backend from the existing title field to the name field.
Advice would be appreciated if this change affects any current use cases.  The name and title fields can both be populated if this change breaks existing workflows for people.
This change was tested on ELK 7.12.
> Update Elasticsearch Watcher backend to populate name column in Kibana

- rules/windows/builtin/win_susp_athremotefxvgpudisablementcommand.yml
- rules/windows/builtin/win_susp_zip_compress.yml
- rules/windows/powershell/powershell_alternate_powershell_hosts.yml
- rules/windows/powershell/powershell_delete_volume_shadow_copies.yml
- rules/windows/powershell/powershell_downgrade_attack.yml
- rules/windows/powershell/powershell_exe_calling_ps.yml
- rules/windows/powershell/powershell_powercat.yml
- rules/windows/powershell/powershell_remote_powershell_session.yml
- rules/windows/powershell/powershell_renamed_powershell.yml
- rules/windows/powershell/powershell_suspicious_download.yml
- rules/windows/powershell/powershell_tamper_with_windows_defender.yml
- rules/windows/powershell/powershell_xor_commandline.yml
Hello,
add `definition: fields have to be extract from event` 
fix bad category instead of service for powershell_tamper_with_windows_defender.yml
check #1843
> Update powershell-classic rule

- tests/test_rules.py
Hello,
to help when there is a duplicate id ,I change the error message.
"Rule {rulename} has the same 'id' than {first_rulename} must be unique."
Example: 
```bash
frack113@frack113-virtual-machine:~/sigma$ pipenv run make test
rm -f .coverage
yamllint rules
tests/test_rules.py
[taxii2client.v20] [WARNING ] [2021-08-16 18:08:46,490] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2021-08-16 18:08:46,531] TAXII Server Response with different amount of objects! Setting per_request=692
[taxii2client.v20] [WARNING ] [2021-08-16 18:08:47,235] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2021-08-16 18:08:47,236] TAXII Server Response with …
```
> Update test_missing_id message

- rules/web/web_cve_2021_26858_iis_rce.yml
HI,
I don't the log to check if the rule is correct.
I use this part of the article in reference:
```
When exploiting this vulnerability with CVE-2021–26858, an SSRF attack is used to manipulate virtual directories.
For this reason, the Username field will contain the computer account, in our case lab.local\EXCHANGE$,
as the request is initiated by the Exchange server itself. Given this fact, another rule can be implemented:
event_log_source:’IIS’ AND http_method:’POST’ AND http_code:'200' 
AND url_path:'/ecp/DDI/DDIService.svc/SetObject' 
AND (Message contains 'schema=Reset' AND Message contains 'VirtualDirectory')
AND Username contains '$'
```
> rule: ProxyLogon web_cve_2021_26858_iis_rce.yml

- rules/windows/powershell/powershell_alternate_powershell_hosts.yml
- rules/windows/powershell/powershell_renamed_powershell.yml
Hi,
find some FP:
1. ContextInfo can never be 'powershell.exe'
2. HostApplication have:
- powershell.exe
- C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
with `HostName: ConsoleHost` HostApplication is the full command so use `|startswith`
> Fix some false positives in  renamed powershell

- rules/web/web_fortinet_cve_2021_22123_exploit.yml
May need taxonomy fixing for _content-type_ and _content-disposition_.
> Added rule for zero day CVE-2021-22123 in Fortinet WAFs

- tools/sigma/backends/sql.py
- tools/sigma/backends/sqlite.py
This PR is following #1785 .
It's adding asked things like help for select option and if select empty use '*' you now get `SELECT * FROM xxx WHERE ...`
But most important, this PR is adding field selection from Sigma rules to SQL and SQLite backend.
If the rule is using `fields : ['xxx', 'yyy']` (or any other yaml format), it will replace the `SELECT * ...` by `SELECT xxx, yyy ...`.
If you use both fields from rule and backend options, it will concatenate them.
When rule is using `fields : ['xxx', 'yyy']`, and using `sigmac -t sql ... --backend-option select=zzz`, it will replace the `SELECT * ...` by `SELECT xxx, yyy, zzz ...`.
Of course, if the rule and the backend option are not using fields at all, it keeps using the default `SELECT * ...`.
> [Ready] SQL & SQLite rule fields selection

- rules/cloud/aws/aws_ec2_disable_encryption.yml
- rules/cloud/aws/aws_ec2_download_userdata.yml
- rules/cloud/aws/aws_ec2_vm_export_failure.yml
- rules/cloud/aws/aws_iam_backdoor_users_keys.yml
- rules/cloud/aws/aws_rds_change_master_password.yml
- rules/cloud/aws/aws_rds_public_db_restore.yml
- rules/cloud/aws/aws_sts_assumerole_misuse.yml
aws_ec2_disable_encryption.yml
Remove `status: success` from selection criteria, not required
aws_ec2_vm_export_failure.yml
Remove filter3:
```
eventName: 'ConsoleLogin'
responseElements|contains: 'Failure'
```
Incompatible with selection criteria `eventName: 'CreateInstanceExportTask'`
aws_ec2_download_userdata.yml, aws_iam_backdoor_users_keys.yml, aws_rds_change_master_password.yml, aws_rds_public_db_restore.yml
Update reference
aws_sts_assumedrole_misuse.yml
Rename to aws_sts_assumerole_misuse.yml
Update references to "AssumedRole" to "AssumeRole"
Update selection criteria of `userIdentity.sessionContext: Role` to `userIdentity.sessionContext.sessionIssuer.type: Role`
> Update AWS CloudTrail rules

- rules/network/zeek/zeek_default_cobalt_strike_certificate.yml
zeek logging for `certificate.serial` is all letters are capitalized
> improve rule logic zeek_default_cobalt_strike_certificate.yml

- rules/network/zeek/zeek_dce_rpc_printnightmare_print_driver_install.yml
Zeek dce_rpc.log Detection of print driver installs over RPC (ie: possible PrintNightmare) using the three existing known RPC functions, as well as few others "discussed" but not directly related to PrintNightmare PoC or public post-compromise write-ups.
> Zeek DCE_RPC PrintNightmare

- rules/proxy/proxy_ua_apt.yml
https://www.welivesecurity.com/2021/08/24/sidewalk-may-be-as-dangerous-as-crosswalk/
> SideWalk User-Agent used by Sparkling Goblin

- tools/sigma/backends/elasticsearch.py
First commit is for adding the support of the authors field to elastic rules. This way (either comma-seperated string or list) authors will be converted and added to the elastic rule.
Second commit will be the support for subtechniques. Detection rules in elastic support the definition of subtechniques. It's handled the same way as techniques for tactics (inside a technique there's the field `subtechnique`).
---
Not really necessary, but in order to work 100% in elastic, the file `techniques.json` respectively the script `update-mitre.py` inside `tools\sigma\config\mitre` _should_ be changed a little. Reason for that is elastic doesn't store the technique name inside the subtechnique's names (e.g. `T1055.001` is only called "Dynamic-link Library Injection").
It'll work fine if not …
> [Elastic] Add support for authors and subtechniques

- rules/cloud/aws/aws_sts_assumerole_misuse.yml
Update selection criteria for AWS STS AssumeRole Misuse rule for any event by an AssumedRole userIdentity.
Closes SigmaHQ/sigma#1963.
> Update AWS STS AssumeRole Misuse rule

- rules/cloud/aws/aws_update_login_profile.yml
Update selection criteria for AWS Update Login Profile rule to check for mismatch between userIdentity.arn and requestParameters.userName.
Closes SigmaHQ/sigma#1966.
> Update AWS Update Login Profile rule

- rules/windows/builtin/win_petitpotam_network_share.yml
- rules/windows/builtin/win_petitpotam_susp_tgt_request.yml
This PR adds two host detections for PetitPotam
Although the PetitPotam coerced authentication attempt does not generate 4624/4625 events, our testing shows it does generate a 5145 event with specific values. We tested in environments with 90K 5145 events with zero false positives. Feedback welcomed!
Tested with Sigmac on a lab Splunk environment:
$ sigmac -t splunk rules/windows/builtin/win_petitpotam_network_share.yml -c tools/config/splunk-windows-index.yml
(index="windows" EventCode="5145" Share_Name="\\*\\IPC$" Relative_Target_Name="lsarpc" Account_Name="ANONYMOUS LOGON")
(base)
$ sigmac -t splunk rules/windows/builtin/win_petitpotam_network_share.yml -c tools/config/splunk-windows.yml
(source="WinEventLog:Security" EventCode="5145" Share_Name="\\*\\IPC$" …
> Adding Petitpotam/ADCS attack vector detections

- rules/linux/auditd/lnx_auditd_audio_capture.yml
Linux auditd rule for Audio Capture detection with arecord. Arecord utility is actually using /usr/bin/aplay, thus this is the binary that needs to be monitored with auditd rule
> New Rule - Linux-Audio-Capture

- rules/cloud/aws/aws_update_login_profile.yml
Missed updating field from `responseElements.accessKey.userName` to `requestParameters.userName` on last update.
> Update AWS Update Login Profile Rule fields

- rules/linux/auditd/lnx_auditd_hidden_files_steganography.yml
- rules/linux/auditd/lnx_auditd_hidden_zip_files_steganography.yml
- rules/linux/auditd/lnx_auditd_unzip_hidden_zip_files_steganography.yml
Rule for hidding zip files in images, was considering also logging for steghide - will try to do that later as it is not installed by default in linux
> New Rule - Linux Auditd Hidden Files - Steganography

- tools/sigma/backends/mdatp.py
Mapped OriginalFileName to ProcessVersionInfoOriginalFileName in DeviceProcessEvents. Tested and works for rules such as https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/win_renamed_binary.yml
> Mapped OriginalFileName in DeviceProcessEvents

- tests/test_rules.py
Hello,
old message
```bash
======================================================================
ERROR: test_invalid_logsource_attributes (__main__.TestRules)
----------------------------------------------------------------------
Traceback (most recent call last):
File "tests/test_rules.py", line 589, in test_invalid_logsource_attributes
for key in logsource:
TypeError: 'NoneType' object is not iterable
======================================================================
ERROR: test_sysmon_rule_without_eventid (__main__.TestRules)
----------------------------------------------------------------------
Traceback (most recent call last):
File "tests/test_rules.py", line 311, in test_sysmon_rule_without_eventid
service = logsource.get('service', '')
AttributeError: 'NoneType' object has no …
```
> fix test_rules.py errors when no logsource

- rules/windows/registry_event/sysmon_apt_leviathan.yml
- rules/windows/registry_event/sysmon_apt_oceanlotus_registry.yml
- rules/windows/registry_event/sysmon_office_test_regadd.yml
- rules/windows/registry_event/win_outlook_c2_registry_key.yml
- rules/windows/registry_event/win_portproxy_registry_key.yml
Hello,
find some rule with a bad `TargetObject`.
sysmon_apt_oceanlotus_registry.yml should need a deeper check.
> Fix registry TargetObject

- rules/linux/auditd/lnx_auditd_screencaputre_xwd.yml
Included "no -root window" option to make the rule more resilient.
> New Rule - Linux - Auditd - Screen Capture with xwd

- tools/sigma/backends/limacharlie.py
Some rules have started generating bad LimaCharlie rules because of the lack of some context.
This introduces a check on those rules to validate that the nodes under logical AND/OR operators are themselves operators and not simple strings.
> Add validation for LimaCharlie logical sub operators.

- rules/windows/process_creation/process_creation_possible_privilege_escalation_via_service_registry_permissions.yml
Hello
IntegrityLevel is in process creation and  in the references it is sysmon 1.
So this rule was broke.
> Fix bad category in possible_privilege_escalation_via_service_registry_permissions

- rules/linux/auditd/lnx_auditd_omigod_scx_runasprovider_executeshellcommand.yml
Rule to detect the use of the SCX RunAsProvider Invoke_ExecuteShellCommand to execute any UNIX/Linux command using the /bin/sh shell. SCXcore, started as the Microsoft Operations Manager UNIX/Linux Agent, is now used in a host of products including Microsoft Operations Manager. Microsoft Azure, and Microsoft Operations Management Suite.
> OMIGOD SCX RunAsProvider ExecuteShellCommand

- rules/windows/registry_event/sysmon_susp_mic_cam_access.yml
hello,
in the doc
```
Within the NonPackaged directory, you can see that the name of the keys are the full path of an executable with # replacing \.
```
So can not be `#C:#` , I have change to `:#` to match c:\ or d:\ ...
> fix detection in sysmon_susp_mic_cam_access

- rules/linux/auditd/lnx_auditd_omigod_scx_runasprovider_executescript.yml
This detection uses Auditd security events collected via the Syslog data connector to explore the use of the SCX RunAsProvider ExecuteScript to execute any UNIX/Linux script using the /bin/sh shell.
Script being executed gets created as a temp file in /tmp folder with a scx* prefix. Then it is invoked from the following directory /etc/opt/microsoft/scx/conf/tmpdir/. The file in that directory has the same prefix scx*.
The file is deleted after execution from the /etc/opt/microsoft/scx/conf/tmpdir.
SCXcore, started as the Microsoft Operations Manager UNIX/Linux Agent, is now used in a host of products including Microsoft Operations Manager. Microsoft Azure, and Microsoft Operations Management Suite.
> OMIGOD - Explore the use of SCX ExecuteScript to execute scripts using /bin/sh shell

- tools/config/carbon-black-eedr.yml
- tools/config/carbon-black.yml
- tools/config/ecs-auditd.yml
- tools/config/ecs-dns.yml
- tools/config/ecs-filebeat.yml
- tools/config/ecs-zeek-corelight.yml
- tools/config/ecs-zeek-elastic-beats-implementation.yml
- tools/config/logstash-zeek-default-json.yml
- tools/config/winlogbeat-modules-enabled.yml
- tools/sigma/sigma_configurations_check.py
- tools/sigma_configurations_check
Some update for #2033
Invalid backend name :  
- corelight_elasticsearch-rule 
- corelight_es-qs 
- corelight_elasticsearch-rule
- corelight_xpack-watcher
- corelight_splunk
- thor  
File with no Backends section: 
- elk-defaultindex-filebeat.yml 
- elk-defaultindex-logstash.yml 
- elk-defaultindex.yml 
- elk-linux.yml   
- elk-windows.yml
- elk-winlogbeat-sp.yml   
- elk-winlogbeat.yml 
Script is not the best but do the job for this time
> Fix config banckends name

- rules/windows/process_creation/win_apt_greenbug_may20.yml
- The intended value for the this B64 criteria was /server= but the current string does not EXACTLY match this causing unnecessary false positives.
- This PR amends this to 'L3NlcnZlcj0=' which should be the correct encoding
> win-apt-greenbug-fix small change to B64encoded value of '/server='

- rules/windows/builtin/win_susp_logon_explicit_credentials.yml
- rules/windows/other/win_lateral_movement_condrv.yml
- tests/test_rules.py
- tools/sigma/backends/sysmon.py
With contrib/sigmacover.py find a error with sysmon backend.
If logsource is not a string then signac exit with 'NoneType' object has no attribute 'lower'
- add a conversion to string in sysmon backend 
- add a check in test_rules.py
- fix the rules with invalid definition
> Fix logsource  not a string

- rules/windows/process_creation/win_susp_mshta_pattern.yml
it said 'mhsta.exe' and it should say 'mshta.exe'
> mispelled 'mshta.exe' in selection_base

- tools/sigma/backends/lacework.py
The Lacework Policy API requires that we have something populated for `remediation`.  Adding some placeholder text to satisfy this requirement.
> fix(backend): add remediation for lacework policy

- rules/windows/process_creation/win_trust_discovery.yml
Same as recent change to "Recon Activity with NLTEST" (see commit a2418e4d2cadeefa3b6a7bb639a92ff0872b89ca)
Added the command parameter '/trusted_domains' for nltest which can be used as an alternative to '/domain_trusts' to bypass detection. 
Tested on Windows 10.0.19042
Reference: https://www.harmj0y.net/blog/redteaming/a-guide-to-attacking-domain-trusts/
> Added alternative nltest command parameter

- rules/windows/process_creation/process_mailboxexport_share.yml
Probably a nitpick but it bugged me enough to create a pull request.
In the WebProxy exploit chain, the mailbox is used to upload the webshell, either using CVE-2021-31207 or a simple SMTP. Either way, the mailbox contains the webshell, which is then extracted using a command like the one below:
`New-MailBoxExportRequest – Mailbox john.doe@enterprise.corp -FilePath \\127.0.0.1\C$\path\to\webshell.aspx`
As such, this is establishing Persistence through Webshell. It is not Collection through email.
Refenece:
https://www.fireeye.com/blog/threat-research/2021/09/proxyshell-exploiting-microsoft-exchange-servers.html
> Corrected Technique

- rules/cloud/aws/aws_attached_malicious_lambda_layer.yml
- rules/cloud/aws/aws_suspicious_saml_activity.yml
Use correct case for `AssumeRoleWithSAML` event name.
`UpdateFunctionConfiguration`, `UpdateFunctionConfiguration20150331` and `UpdateFunctionConfiguration20150331v2` are all valid event names for updating Lambda function configuration, added selection condition for any of these.
> Update AWS SAML and Lambda rules

- tools/sigma/backends/carbonblack.py
Commit #2029 introduced the problem described in issue #2176. Line 160 from tools/sigma/backends/carbonblack.py makes every value a string. Because of this, some lists are interpreted as strings resulting in the problem described in #2176 as shown below.
```
$ ./sigmac -t carbonblack -c carbon-black-eedr win_apt_dragonfly.yml 
process_name:\[\' AND \\\\crackmapexec.exe\'\]
$ ./sigmac -t carbonblack -c carbon-black-eedr win_susp_control_cve_2021_40444.yml 
((process_name:control.exe AND parent_name:\[\' AND "\\winword.exe', '" AND "\\powerpnt.exe', '" AND \\\\excel.exe\'\]) AND ( -(process_cmdline:"\control.exe input.dll")))
```
Without `value = str(value)` at line 160 these rules are translated to the correct Carbon Black EEDR format.
```
$ ./sigmac -t carbonblack -c carbon-black-eedr …
```
> Fix errors introduced at commit 58d9e41

- rules/windows/process_creation/win_pc_susp_schtasks_user_temp.yml
I view many time this kind of line `C:\Windows\System32\schtasks.exe" /Create /TN "Updates\QUQovKcaZRcNZ" /XML "C:\Users\user\AppData\Local\Temp\tmpD7D5.tmp`  in malware sandbox repport.
I put `level: high` as it come from malware but medium could be fine.
There is no reason to program a task from the temp directory
> add win_pc_susp_schtasks_user_temp

- tools/sigma/backends/elasticsearch.py
Hi,
Elastic can not deal with "^" or "$" and make a full match
- if regex ^+$ -> remove no need
- if regex ^ -> remove and add ".*" at the end
- if regex $ -> remove ans ans ".*" at the star
- otherwise do nothing 
test with es-qs backend
> manage start end regex for Elastic

- rules/cloud/m365/microsoft365_activity_by_terminated_user.yml
- rules/cloud/m365/microsoft365_activity_from_anonymous_ip_addresses.yml
- rules/cloud/m365/microsoft365_activity_from_infrequent_country.yml
- rules/cloud/m365/microsoft365_data_exfiltration_to_unsanctioned_app.yml
- rules/cloud/m365/microsoft365_from_suspicious_ip_addresses.yml
- rules/cloud/m365/microsoft365_impossible_travel_activity.yml
- rules/cloud/m365/microsoft365_logon_from_risky_ip_address.yml
- rules/cloud/m365/microsoft365_potential_ransomware_activity.yml
- rules/cloud/m365/microsoft365_suspicious_inbox_forwarding.yml
- rules/cloud/m365/microsoft365_suspicious_oauth_app_file_download_activities.yml
- rules/cloud/m365/microsoft365_unusual_volume_of_file_deletion.yml
- rules/cloud/m365/microsoft365_user_restricted_from_sending_email.yml
- tools/config/generic/m365.yml
m365.yml and the rules. 
did not remove `eventSource` from rule even if it is not usefull when use `-c /config/generic/m365.yml`
> standardization m365

- rules/windows/process_creation/process_creation_office_from_proxy_executing_regsvr32_payload.yml
- rules/windows/process_creation/process_creation_office_from_proxy_executing_regsvr32_payload2.yml
- rules/windows/process_creation/process_creation_office_spawning_wmi_commandline.yml
- rules/windows/process_creation/win_susp_wuauclt.yml
- tools/config/generic/windows-audit.yml
ProcessCommandLine is from eventid 4688.
In all the other process_creation rule we use the sysmon name `ParentCommandLine`.
- fix ParentCommandLine to ParentCommandLine
- add ParentCommandLine to tools/config/generic/windows-audit.yml
- fix the detection of the rule `win_susp_wuauclt.yml` after try the payload in a VM
> Fix process command line

- tools/sigma/backends/sql.py
- tools/sigma/backends/sqlite.py
Some rules contain double quotes in their field values like this [one](https://github.com/SigmaHQ/sigma/blob/10b70edff055cfb12b16d934c77f9ccf4b97a529/rules/windows/process_creation/win_susp_winrm_awl_bypass.yml) : 
```yaml
detection:
contains_format_pretty_arg:       
CommandLine|contains:
- 'format:pretty'
- 'format:"pretty"'
```
In the current SQLite backend, the double quotes are not escaped so the resulting SQL query is not valid : 
```sql
AND (CommandLine LIKE "%format:pretty%" ESCAPE '\'
OR CommandLine LIKE "%format:"pretty"%" ESCAPE '\'
OR CommandLine LIKE "%format:"text"%" ESCAPE '\'
OR CommandLine LIKE "%format:text%" ESCAPE '\')
```
This PR solves the problem by escaping correctly the double quotes : 
```sql
AND (CommandLine LIKE "%format:pretty%" ESCAPE '\'
OR CommandLine LIKE …
```
> Fix double quotes escaping and values with commas in SQLite/SQL backends

- tools/sigma/parser/condition.py
Without this fix, `isinstance(ConditionOR(), ConditionAND)` yields `True` which is obviously not what one would expect
> fix condition token inheritance

- rules/windows/registry_event/win_registry_shell_open_keys_manipulation.yml
Make rule more generic regarding the included exefile detection instead of only naming it "uac bypass". Add further references and attack tags. There is also an other rule regarding asep reg key manipulation which also includes exefile: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry_event/sysmon_asep_reg_keys_modification.yml.
> Update shell open key rule

- rules/windows/process_creation/win_susp_emotet_rundll32_execution.yml
Prevent possible FPs from non-windows native calls using paths surrounded by quotes which might happen by 3rd party calls to rundll32.exe
> Rule Fix: Paths with Quotes

- rules/windows/registry_event/sysmon_win_reg_persistence_recycle_bin.yml
Very funny
Test in a VM by hand
sysmon 13.30
```xml
<TargetObject name="T1547" condition="end with">CLSID\{645FF040-5081-101B-9F08-00AA002F954E}\shell\open\command</TargetObject>
```
> Add sysmon_win_reg_persistence_recycle_bin.yml

- rules/linux/macos/process_creation/macos_space_after_filename.yml
Picking up the work here https://github.com/SigmaHQ/sigma/issues/1012 to contribute a single rule for detecting files or commands run with a space at the end to masquerade as legit files. 
See https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1036.006/T1036.006.md
This rule does not work on the carbonblack backend, but this appears to be an issue with the converter and not the rule itself as elasticsearch es-qs conversion works fine. I'll open a separate issue for that. 
```
(sigma) ┌─(~/sigma)────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(me@me)─┐
└─(15:28:58 on T1036.006_space_after_filename_macos ✹ ✭)──> tools/sigmac --target carbonblack …
```
> Add Rule: MacOS - macos_space_after_filename.yml

- tools/config/hawk.yml
- tools/sigma/backends/hawk.py
Small update to HAWK sigmac backend.  All rules receive a "sigma" tag, and additionally a "qa" tag if marked as experimental
> Hawk tags enrichment

- rules/windows/powershell/powershell_script/powershell_malicious_commandlets.yml
Added EC2 to list of fp's.
Per:
2021-11-29 17:48:45 device-01.company.pvt PowerShell: 4103: CommandInvocation(Add-Type): "Add-Type" | ContextInfo= Severity = Informational Host Name = ConsoleHost Host Version = 5.1.14393.4583 Host ID = f4c1be35-faa8-44de-8743-5d38546eb1c3 Host Application = C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -NoLogo -WindowStyle hidden -ExecutionPolicy Unrestricted Import-Module C:\ProgramData\Amazon\EC2-Windows\Launch\Module\Ec2Launch.psd1; so Runspace ID = e4359a73-0de6-486f-ba02-3d52af58a9d0 Pipeline ID = 6 Command Name = Add-Type Command Type = Cmdlet Script Name = C:\ProgramData\Amazon\EC2-Windows\Launch\Module\Scripts\Set-Wallpaper.ps1 Command Path = Sequence Number = 70 User = DOMAIN\Username Connected User = Shell …
> adding amazon ec2 to list of false positives for powershell cmdlet detection

- rules/windows/process_creation/sysmon_logon_scripts_userinitmprlogonscript_proc.yml
Adding wildcard to netlogon to be a little more inclusive.
2021-11-29 19:45:32 device-01.company.pvt Sysmon: 1: Process Create | RuleName=technique_id=T1059.003,technique_name=Windows Command Shell | UtcTime=2021-11-29 19:45:32.212 | ProcessGuid={86DC4549-2DDC-61A5-15BE-030000003D00} | ProcessId=10540 | Image=C:\Windows\System32\cmd.exe | FileVersion=10.0.14393.0 (rs1_release.160715-1616) | Description=Windows Command Processor | Company=Microsoft Corporation | OriginalFileName=Cmd.Exe | OriginalCommandLine=C:\Windows\system32\cmd.exe /c ""\\remotehost\netlogon\cgllogin.bat" " | CommandLine=C:\Windows\system32\cmd.exe /c "\\remotehost\netlogon\cgllogin.bat " | CurrentDirectory=C:\Windows\system32\ | User=DOMAIN\Username | LogonGuid={86DC4549-2DC9-61A5-FF7B-B14A0A000000} | …
> Sysmon logon scripts userinitmprlogonscript proc

- rules/windows/process_creation/win_powershell_xor_commandline.yml
Adding filter for C:\Program Files\Amazon\SSM\ssm-document-worker.exe
per
2021-11-29 21:11:58 device-01.company.pvt Sysmon: 1: Process Create | RuleName=technique_id=T1059.001,technique_name=PowerShell | UtcTime=2021-11-29 21:11:58.966 | ProcessGuid={d7d4e535-421e-61a5-5417-01000000f500} | ProcessId=152 | Image=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe | FileVersion=10.0.17763.1 (WinBuild.160101.0800) | Description=Windows PowerShell | Company=Microsoft Corporation | OriginalFileName=PowerShell.EXE | OriginalCommandLine=powershell " [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 $keyExists = Test-Path \"Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Setup\OC Manager\Subcomponents\" $jsonObj = @() if ($keyExists) { $key = Get-Item …
> adding false positive filter for amazon ssm-document-worker

- rules/windows/process_creation/win_susp_copy_system32.yml
example:
Command=C:\Windows\System32\cmd.exe /c copy "C:\Program Files (x86)\BigFix Enterprise\BES Client\LMT\CIT\tmpDir\tmpArchiveWithTagFiles.zip" "C:\Program Files (x86)\BigFix Enterprise\BES Client\LMT\CIT\13126042_iso.zip
>  fixing false positive due to direct calls to xcopy and cmd.exe

- rules/windows/process_creation/process_creation_susp_del.yml
When command begins with C:\Windows\System32\cmd.exe it will always match susp_del_exe # ex - C:\Windows\System32\cmd.exe" /c del /f /q "C:\Program Files (x86)\Software Package\Client\tmpDir\"
Update ensures that the matching of malicious behavior is on the right side of the del cmd
> Fixing false positive when cmd.exe is called with full path

- rules/windows/sysmon/sysmon_config_modification_error.yml
Benign error:
```
2021-12-02 06:00:52 device01.company.pvt Sysmon: 255: Error report | UtcTime=2021-12-02 06:00:52.306 | ID=GetConfigurationOptions | Description=Failed to open service configuration with error 19 - Last error: The media is write protected. | pid=2100 | level=0 | sys_version=3 | category=255 | op=Info | Microsoft-Windows-Sysmon/Operational=true | key=0x8000000000000000 | id=27633868 | app="?" | tid=9868 | channel="Microsoft-Windows-Sysmon/Operational" | pid_user="NT AUTHORITY\SYSTEM" | sid=S-1-5-18 | account type=User | type=error(2) 
```
> adding filter for benign error from sysmon configuration

- rules-unsupported/sysmon_process_reimaging.yml
- rules/cloud/gworkspace/gworkspace_mfa_disabled.yml
- rules/linux/macos/process_creation/macos_gui_input_capture.yml
- rules/windows/builtin/win_alert_active_directory_user_control.yml
- rules/windows/builtin/win_invoke_obfuscation_var_services_security.yml
- rules/windows/deprecated/powershell_suspicious_invocation_generic.yml
- rules/windows/powershell/powershell_module/powershell_suspicious_invocation_generic_in_contextinfo.yml
- rules/windows/powershell/powershell_script/powershell_automated_collection.yml
- rules/windows/powershell/powershell_script/powershell_detect_vm_env.yml
- rules/windows/powershell/powershell_script/powershell_ntfs_ads_access.yml
- rules/windows/powershell/powershell_script/powershell_suspicious_invocation_generic_in_scriptblocktext.yml
- rules/windows/powershell/powershell_script/powershell_suspicious_recon.yml
- rules/windows/process_creation/process_creation_coti_sqlcmd.yml
- rules/windows/process_creation/process_creation_susp_7z.yml
- rules/windows/process_creation/process_creation_susp_winzip.yml
- rules/windows/process_creation/sysmon_long_powershell_commandline.yml
- rules/windows/process_creation/sysmon_susp_service_modification.yml
- rules/windows/process_creation/win_malware_conti_shadowcopy.yml
- rules/windows/process_creation/win_susp_disable_eventlog.yml
- rules/windows/process_creation/win_susp_powershell_parent_process.yml
- rules/windows/process_creation/win_susp_powershell_sam_access.yml
- tests/test_rules.py
... and migrate existing rules to use the preferred method 'all of selection*'
I also updated the [specification](https://github.com/SigmaHQ/sigma/wiki/Specification#condition) (Ctrl+F `all of them`) with a hint that discourages the "all of them" usage and wrote a test in tests/test_rules.py that declines new rules using "all of them".
> feat: discourage the usage of 'all of them'

- rules/windows/pipe_created/sysmon_alternate_powershell_hosts_pipe.yml
Used rule 867613fb-fa60-4497-a017-a82df74a172c as filter reference.  May be necessary to add more filters in the future.
> Adding filter for calls using \WINDOWS\System32\sdiagnhost.exe

- rules/windows/builtin/system/win_susp_system_update_error.yml
Get a simple trigger (low) when when a error occur in windows update.
The SOC must know if 0-days KB blocks .
the tags are put on my best way
> add win_susp_system_update_error rule

- rules/windows/registry_event/sysmon_asep_reg_keys_modification.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_classes.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_commun.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_currentcontrolset.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_currentversion.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_currentversion_nt.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_internet_explorer.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_office.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_session_manager.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_system_scripts.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_winsock2.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_wow6432node.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_wow6432node_classes.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_wow6432node_currentversion.yml
When alert trigger SOC operator cannot easily understand it.
So I have split it.
`condition` and `title` are more treatable by humans.
Filter part need to be optimize
> Split sysmon_asep_reg_keys_modification

- tools/sigma/parser/condition.py
Good day! There might be a possible bug - or potential improvement in the way the parser creates the resulting expression. 
If a rule has a `detection.condition` with an expression that contains a sub-expression, the parser will insert the logsource condition that results from the configuration to each expression - possibly creating duplicate checks in the resulting query. 
A condition of `cond1 and (cond2 or cond3)` will generate a query that includes the logsource condition for both the `cond1` and the subexpression `(cond2 or cond3)`.
This PR mitigates this by introducing a `depth` parameter to `SigmaConditionParser.parseSearch` to track the depth of the nested expressions, adding the logsource condition only to the outermost expression (`depth==0`)
> Logsource condition applied once in nested expression

- rules/windows/network_connection/sysmon_dllhost_net_connections.yml
Ex:
```
2021-12-07 19:39:05 devie-01.company.pvt Sysmon: 3: Network connection detected | RuleName=- | UtcTime=2021-12-07 19:38:22.376 | ProcessGuid={B7C4C965-9752-61A7-1443-000003006800} | ProcessId=14332 | Image=C:\Windows\System32\dllhost.exe | User=DOMAIN\Username | Protocol=tcp | Initiated=true | SourceIsIpv6=true | SourceIp=0:0:0:0:0:0:0:1 | SourceHostname=- | SourcePort=65521 | SourcePortName=- | DestinationIsIpv6=true | DestinationIp=0:0:0:0:0:0:0:1 | DestinationHostname=- | DestinationPort=50985 | DestinationPortName=- | pid=2664 | level=0 | sys_version=5 | category=Network connection detected (rule: NetworkConnect) | op=Info | Microsoft-Windows-Sysmon/Operational=true | key=0x8000000000000000 | id=337207190 | app="C:\Windows\sysmon64.exe" | tid=12228 | …
```
> Adding filter for ipv6 local for rundll32 net connections

- rules/windows/registry_event/sysmon_esentutl_volume_shadow_copy_service_keys.yml
Replace sysmon_volume_shadow_copy_service_keys.yml rule by sysmon_esentutl_volume_shadow_copy_service_keys.yml because of too many false positives
> False positives on sysmon_volume_shadow_copy_service_keys.yml

- rules/windows/process_creation/process_creation_susp_image_missing.yml
- rules/windows/process_creation/process_creation_susp_non_exe_image.yml
- rules/windows/process_creation/win_lolbin_execution_via_winget.yml
Add two new rules that detect uncommon process creation events (executable deleted, executable is no .exe file).
Also fixes a bug in an unrelated rule.
> Add rules for uncommon process creation events

- rules/windows/builtin/security/win_susp_lsass_dump_generic.yml
G'day! I've found instances of Defender triggering the generic lsass dump rule.
This PR adds `MsMpEng.exe` to the filter list of known tools of that specific rule. It also adds `C:\ProgramData\` to the list, as the newer defender installations run the executable from `%ProgramData%\Microsoft\Windows Defender\Platform\<Version>\`.
See: https://support.microsoft.com/en-us/topic/update-for-microsoft-defender-antimalware-platform-92e21611-8cf1-8e0e-56d6-561a07d144cc (under "File location changes")
> Added Defender to win_susp_lsass_dump_generic.yml

- rules/windows/pipe_created/sysmon_alternate_powershell_hosts_pipe.yml
```
2021-12-09 19:10:19 device-01.company.pvt Sysmon: 17: Pipe Created | RuleName=- | EventType=CreatePipe | UtcTime=2021-12-09 19:10:19.609 | ProcessGuid={8eb39540-5499-61b2-aca2-000000004000} | ProcessId=10216 | PipeName=\PSHost.132835506178328728.10216.DefaultAppDomain.wsmprovhost | Image=C:\Windows\system32\wsmprovhost.exe | pid=10272 | level=0 | sys_version=1 | category=Pipe Created (rule: PipeEvent) | op=Info | Microsoft-Windows-Sysmon/Operational=true | key=0x8000000000000000 | id=8630 | app="C:\Windows\sysmon64.exe" | tid=11388 | channel="Microsoft-Windows-Sysmon/Operational" | pid_user="NT AUTHORITY\SYSTEM" | sid=S-1-5-18 | account type=User | type=notice(4) | [E] | Archived=true | Company=Microsoft Corporation | CreationUtcTime=2021-12-09 19:10:19.453 | Description=OLE32 …
```
> adding allow for wsmprovhost.exe to call powershell pipes

- rules/windows/process_access/sysmon_cred_dump_lsass_access.yml
Get a FP with perfmon.exe on windows 20H2
```
Process accessed:
RuleName: -
UtcTime: 2021-12-10 18:43:29.865
SourceProcessGUID: {d4b94734-9fd0-61b3-3704-000000000d00}
SourceProcessId: 6220
SourceThreadId: 7120
SourceImage: C:\Windows\System32\perfmon.exe
TargetProcessGUID: {d4b94734-92f0-61b3-0c00-000000000d00}
TargetProcessId: 760
TargetImage: C:\Windows\system32\lsass.exe
GrantedAccess: 0x1410
CallTrace: C:\Windows\SYSTEM32\ntdll.dll+9d234|C:\Windows\System32\KERNELBASE.dll+2c0ce|C:\Windows\System32\wdc.dll+7e50|C:\Windows\System32\wdc.dll+aa0d|C:\Windows\System32\wdc.dll+c910|C:\Windows\System32\wdc.dll+15280|C:\Windows\System32\KERNEL32.DLL+17034|C:\Windows\SYSTEM32\ntdll.dll+52651
SourceUser: DESKTOP-TR9HG5K\frack113
TargetUser: AUTORITE NT\Système
```
> FP  perfmon.exe to sysmon_cred_dump_lsass_access.yml

- rules/web/web_cve_2021_44228_log4j_fields.yml
- rules/web/web_fortinet_cve_2021_22123_exploit.yml
- rules/web/win_webshell_regeorg.yml
- tools/config/arcsight-zeek.yml
- tools/config/ecs-proxy.yml
- tools/config/ecs-zeek-corelight.yml
- tools/config/ecs-zeek-elastic-beats-implementation.yml
- tools/config/humio.yml
- tools/config/logstash-zeek-default-json.yml
- tools/config/splunk-zeek.yml
The problem is that we use cs-referrer in our rules, which is the correct spelling of that word. But the field name in the header of requests is `referer`, which is a misspelled form, but used in HTTP requests. I would, for the sake of consistency, use that misspelled word in our rules, hoping that services also use that misspelled field name in their log data.
> fix: referrer > referer adjustments

- rules/web/web_cve_2021_44228_log4j_fields.yml
When the original is compiled it requires one TRUE from each Field (implicit AND) ... believe the intent is to search all fields of any trace which hence explicit OR in "condition"
> Log4j OR each section vs implicit AND

- rules/windows/process_creation/win_pc_susp_regsvr32_image.yml
would it be an option to use another logic: regsrv32 without .dll as a file extension? will check that, why limiting the rule to just jpg.
> rule: add further reference in regsrv32 rule

- rules/windows/process_creation/win_using_sc_to_hide_sevices.yml
This rule detects a cool trick to hide services from UI tools, seen in current Talos blog post which referred to a SANS blog post. Technique was used in an exchange compromise to hide the service.
Hide services when special permissions were set at service creation. Seen in section _Installation stealth and persistence_ in Talos' blog post [Threat hunting in large datasets by clustering security events](https://blog.talosintelligence.com/2021/10/threat-hunting-in-large-datasets-by.html). This blog post references another one from SANS, [Red Team Tactics: Hiding Windows Services](https://www.sans.org/blog/red-team-tactics-hiding-windows-services/).
* _In the following steps, the script deletes PowerShell logs and registers the final payload as a Windows service using a long command line …
> rule: abuse of permissions to hide services

- rules/windows/process_creation/process_creation_susp_shell_spawn_by_java_keytool.yml
Rule (around ADSelfService Plus RCE) described in https://redcanary.com/blog/intelligence-insights-december-2021 and references to https://www.synacktiv.com/en/publications/how-to-exploit-cve-2021-40539-on-manageengine-adselfservice-plus.html are found in RedCanary's article.
> rule: add new rule to detect shell spawn by Java keytool

- rules/windows/process_creation/win_susp_rundll32_activity.yml
es-dsl does not work properly because the rule syntax is not valid
https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/win_susp_rundll32_activity.yml
59 to 61 lines
- CommandLine|contains|all:
- 'syssetup.dll'
- SetupInfObjectInstallAction'
should be like below
- CommandLine|contains|all:
- 'syssetup.dll'
- 'SetupInfObjectInstallAction'
> (win_susp_rundll32_activity.yml) Rule syntax error

- rules/windows/file_event/win_fe_creation_scr_binary_file.yml
Example
```
2022-01-10 22:13:56 device-01.domain.pvt Sysmon: 11: File created | RuleName=technique_id=T1047,technique_name=File System Permissions Weakness | UtcTime=2022-01-10 02:13:56.122 | ProcessGuid={520D48D4-358B-61DC-1C00-000000006506} | ProcessId=1816 | Image=C:\Program Files (x86)\Symantec\Symantec Endpoint Protection\14.3.1169.0100.105\Bin\ccSvcHst.exe | TargetFilename=C:\Windows\Temp\SymDelta_1816\content.zip.tmp\cur.scr | CreationUtcTime=2022-01-10 22:13:56.122 | pid=372 | level=0 | sys_version=2 | category=File created (rule: FileCreate) | op=Info | Microsoft-Windows-Sysmon/Operational=true | key=0x8000000000000000 | id=6627251 | app="sysmon64.exe" | tid=2600 | channel="Microsoft-Windows-Sysmon/Operational" | pid_user="NT AUTHORITY\SYSTEM" | sid=S-1-5-18 | account type=User | …
```
> fp where symantec apparently performs this behavior with .scr files

- rules/windows/process_creation/win_powershell_xor_commandline.yml
Fixes a false positive when joinppath is used, along with other items... example of fp:
```
Export-DhcpServer -Leases -File (Join-Path $env:TEMP dhcp_output.txt) 
```
This attempts to narrow down the use of join with a -, and either a space, single quote or double quote.  Other string markers can also be added, not sure of ` works
> Fp attempting to detect suspicious xor encoded powershell

- rules/windows/process_access/sysmon_cred_dump_lsass_access.yml
@Neo23x0, Directly not related to this PR but I have a query regarding a certain change done to this rule.
This rule will not detect _mimikatz_ accessing LSASS (sekurlsa::logonPasswords) since **0x1010** access was removed in _fix: FPs with Aurora_ commit a month ago.
So, this means we are intentionally removing coverage for _mimikatz_ and delegating it to _Suspicious GrantedAccess Flags on LSASS Access_ rule instead? Also, if Aurora generates **0x1010** then it defeats the purpose of the commit.
> Added two filters in Credentials Dumping Tools Accessing LSASS Memory

- rules/windows/process_creation/win_lolbin_execution_via_winget.yml
Hello, 
A sanity check of our rule deployment pipeline noticed that the creation date of this rule is formatted incorrectly.
I think the date should be as proposed in this PR. (Of course we can manually overwrite this internally, but it's better to have this changed in the Sigma master.)
> Fix incorrectly formatted Winget LOLbin creation date

- rules/windows/file_event/file_event_susp_task_write.yml
- rules/windows/powershell/powershell_script/powershell_azurehound_commands.yml
- rules/windows/process_creation/win_purplesharp_indicators.yml
- tests/test_rules.py
It is not mandatory in the sigma standard but mandatory for this repository.
I added or changed descriptions for existing rules to not fail on the new constraint.
> feat: check for the existence of a description field

- rules/windows/process_creation/win_run_executable_invalid_extension.yml
If extension does not match known extensions for executables, can be used for av bypass. dumb trick but works against defender
> Detects executable running with non executable extension

- rules/windows/builtin/security/win_user_added_to_local_administrators.yml
- rules/windows/builtin/security/win_user_creation.yml
Just seems like a typo because all other found rules use `Provider_Name` instead of `provider_Name`.
> Adjust case sensitivity of Provider_Name field

- rules/windows/process_creation/process_creation_susp_image_missing.yml
Can apparently occur with 4688 events.
> fix: Add filter for empty image to rule

- rules/windows/process_creation/win_run_executable_invalid_extension.yml
```
2022-01-27 14:00:27 hostname.example.com Sysmon: 1: Process Create | RuleName=technique_id=T1218.002,technique_name=rundll32.exe | UtcTime=2022-01-27 14:00:27.882 | ProcessGuid={2CB38191-A57B-61F2-0977-000000005700} | ProcessId=9136 | Image=C:\Windows\System32\rundll32.exe | FileVersion=10.0.14393.4169 (rs1_release.210107-1130) | Description=Windows host process (Rundll32) | Company=Microsoft Corporation | OriginalFileName=RUNDLL32.EXE | OriginalCommandLine=C:\Windows\system32\rundll32.exe C:\Windows\system32\inetcpl.cpl,ClearMyTracksByProcess Flags:276824072 WinX:0 WinY:0 IEFrame:0000000000000000 | CommandLine=C:\Windows\system32\rundll32.exe C:\Windows\system32\inetcpl.cpl,ClearMyTracksByProcess Flags:276824072 WinX:0 WinY:0 IEFrame:0000000000000000 | …
```
> adding filter for fp of iexplorer calling cpl

- rules/windows/process_creation/process_creation_tool_nircmd.yml
- rules/windows/process_creation/process_creation_tool_nircmd_as_system.yml
- I've modified the "process_creation_tool_nircmd_as_system.yml" rule and removed the "elevatecmd" as it's not really necessary. When the tool is run with the following commandline: "elevatecmd runassystem" it will actually spawn another "nircmd" process with just the "runassystem" commandline
- I've also modified the "process_creation_tool_nircmd.yml" and removed edge cases with a more generic form (that is maybe more prone to FP tbh). I've added other ways to execute commands from the docs.
> Update nircmd rules

- tools/sigma/backends/limacharlie.py
Fix the generation of statements with a wildcard-only value (`*`) in the LimaCharlie backend.
Used to generate a `ends with: ''` (empty value), now generates a more proper `exists` operator.
> Fix wildcard-only generation in LimaCharlie.

- rules/windows/registry_event/sysmon_wdigest_enable_uselogoncredential.yml
Get mamy FP when a GPO is use to secure 😃 
The bad behavior is to set to `1` the key cf ref
> Fix FP sysmon_wdigest_enable_uselogoncredential

- rules/application/antivirus/av_exploiting.yml
This typo keeps sneaking back in - critical for detection. 
Spelling correct according to https://www.nextron-systems.com/wp-content/uploads/2018/09/Antivirus_Event_Analysis_CheatSheet_1.5-2.pdf
https://github.com/SigmaHQ/sigma/pull/1363
> CobaltStrike typo

- rules/windows/file_event/sysmon_creation_system_file.yml
Example fp:
```
2022-02-06 06:23:37 internal.host.entry Sysmon: 11: File created | RuleName=- | UtcTime=2022-02-06 06:23:37.208 | ProcessGuid={852e9484-55d1-61ff-a723-000000003600} | ProcessId=8664 | Image=C:\Windows\system32\wbengine.exe | TargetFilename=\\?\Volume{2cf5436b-adba-4d10-adf5-9bd82a8e1468}\Windows\WinSxS\amd64_microsoft-windows-com-runtimebroker_31bf3856ad364e35_10.0.17763.1697_none_e3c85f9d79f5ccf7\RuntimeBroker.exe | CreationUtcTime=2022-02-06 06:23:37.208 | pid=3136 | level=0 | sys_version=2 | category=File created (rule: FileCreate) | op=Info | Microsoft-Windows-Sysmon/Operational=true | key=0x8000000000000000 | id=31885047 | app="C:\Windows\sysmon64.exe" | tid=4100 | channel="Microsoft-Windows-Sysmon/Operational" | pid_user="NT AUTHORITY\SYSTEM" | sid=S-1-5-18 | account …
```
> FP from wbengine when writing a system filename 

- tools/sigma/backends/limacharlie.py
Fixing an issue where the `exists` operators in LimaCharlie D&R rules do not support the `case sensitive` parameter. This fixes the validation of those rules by removing the parameter in that specific case.
> The LimaCharlie "exists" operator has no case param.

- tools/sigma/backends/sqlite.py
Since the SQLite backend is inherited from the SQL backend, string literals use `"` by default. This may lead to unexpected behaviours.
But as explained in the SQLite docs ([here](https://www.sqlite.org/quirks.html#double_quoted_string_literals_are_accepted)) using `'` is preferred with string literals.
> Replace double quoted string literals to single quoted (SQLite)

- rules/linux/auditd/lnx_auditd_alter_bash_profile.yml
By default, root user folders reside on `/root` instead of `/home`. This adds monitoring for that too.
> Adds root folder monitoring for bash configs

- sigma-schema.rx.yml
Adding the values that can be the status based on the wiki file to the actual specification yaml.
https://github.com/SigmaHQ/sigma/wiki/Specification#status-optional
> Add values that are referenced in the spec

- rules/windows/builtin/security/win_dpapi_domain_backupkey_extraction.yml
For  4ac1f50b-3bd0-4968-902d-868b4647937e the resources denote that the objectName should be LIKE (contains) bckupkey
https://threathunterplaybook.com/notebooks/windows/06_credential_access/WIN-190620024610.html
`WHERE LOWER(Channel) = "security"
AND o.EventID = 4662
AND o.AccessMask = "0x2"
AND lower(o.ObjectName) LIKE "%bckupkey%"`
> Fix detection criteria modifier to contains 'bckupkey'

- rules/windows/process_creation/proc_creation_win_run_executable_invalid_extension.yml
example fp:
```
2022-02-23 18:39:35 redacted.host.name Sysmon: 1: Process Create | RuleName=technique_id=T1218.002,technique_name=rundll32.exe | UtcTime=2022-02-23 18:39:35.534 | ProcessGuid={f4b6f253-7f67-6216-6b09-000000006e01} | ProcessId=8036 | Image=C:\Windows\SysWOW64\rundll32.exe | FileVersion=10.0.17763.1697 (WinBuild.160101.0800) | Description=Windows host process (Rundll32) | Company=Microsoft Corporation | OriginalFileName=RUNDLL32.EXE | OriginalCommandLine=rundll32.exe "C:\Windows\Installer\MSIEF64.tmp",zzzzInvokeManagedCustomActionOutOfProc SfxCA_89714750 3 CustomAction1!DeleteRegistry.CustomActions.RemoveEmptyRegistry | CommandLine=rundll32.exe C:\Windows\Installer\MSIEF64.tmp,zzzzInvokeManagedCustomActionOutOfProc SfxCA_89714750 3 …
```
> Filters false positive from msiexec.exe

- rules/windows/process_creation/proc_creation_win_fsutil_symlinkevaluation.yml
From https://www.cybereason.com/blog/cybereason-vs.-blackcat-ransomware
```
BlackCat enables local and remote [symbolic links](https://en.wikipedia.org/wiki/Symbolic_link) on the infected machine. A symbolic link is a type of file that contains a reference to another file. This is probably done to make sure that the ransomware is able to follow shortcuts on the machine in order to find the original file to encrypt:
fsutil behavior set SymlinkEvaluation R2L:1
fsutil behavior set SymlinkEvaluation R2R:1
```
> Add proc_creation_win_fsutil_symlinkevaluation

- rules/windows/powershell/powershell_classic/posh_pc_delete_volume_shadow_copies.yml
- rules/windows/powershell/powershell_script/posh_ps_susp_win32_shadowcopy.yml
- rules/windows/process_creation/proc_creation_win_bypass_squiblytwo.yml
- rules/windows/process_creation/proc_creation_win_cobaltstrike_load_by_rundll32.yml
- rules/windows/process_creation/proc_creation_win_hack_wce.yml
- rules/windows/process_creation/proc_creation_win_hacktool_imphashes.yml
- rules/windows/process_creation/proc_creation_win_hktl_createminidump.yml
- rules/windows/process_creation/proc_creation_win_powershell_defender_base64.yml
- rules/windows/process_creation/proc_creation_win_powershell_defender_disable_feature.yml
- rules/windows/process_creation/proc_creation_win_powershell_defender_exclusion.yml
- rules/windows/process_creation/proc_creation_win_renamed_paexec.yml
- rules/windows/process_creation/proc_creation_win_susp_mpiexec_lolbin.yml
- Imphash fields adjusted to support fields that contain all hashes in a single value (like used in Sysmon events)
- disabled some strings that use "utf16le", which isn't supported by all backends yet
- tightened up CobaltStrike DLL loader rule
- some "status" values changed to reflect the level of stability of certain rules
> Multiple adjustments in different rules

- tools/config/mitre/groups.json
- tools/config/mitre/software.json
- tools/config/mitre/tactics.json
- tools/config/mitre/techniques.json
- tools/config/mitre/update_mitre.py
- Updated MITRE ATT&CK tactics and techniques to v10.1;
- Added fields to the tactics and techniques such as the domains and the platforms;
- Creation of the group and software files;
- Added the ICS bundle;
- Removed the deprecated Pre-Attack bundle.
> Update MITRE ATT&CK tools to v10.1 with Groups and Software

- rules/windows/process_access/process_access_win_shellcode_inject_msf_empire.yml
@Neo23x0, I am not seeing any FPs from my side so far when using this sysmon & sigma rule combination. If you see some, let me know.
```xml
<ProcessAccess onmatch="include">
<Rule groupRelation="and">
<CallTrace condition="contains">UNKNOWN</CallTrace>
<GrantedAccess name="T1055" condition="contains any">0x147a;0x1f3fff</GrantedAccess>
</Rule>
</ProcessAccess>
```
> Added rule for shellcode injection by Metasploit and Empire

- rules/windows/file_event/file_event_win_susp_adsi_cache_usage.yml
Filter out ccm setup:
```
2022-03-26 15:03:15 redacted.host.name Sysmon: 11: File created | RuleName=technique_id=T1044,technique_name=File System Permissions Weakness | UtcTime=2022-03-26 15:03:15.958 | ProcessGuid={C493B211-2B32-623F-5310-000000008100} | ProcessId=5640 | Image=C:\Windows\ccmsetup\autoupgrade\ccmsetup.TMC00002.40.exe | TargetFilename=C:\Windows\SysWOW64\config\systemprofile\AppData\Local\Microsoft\Windows\SchCache\root.pvt.sch
```
> Filtering of ccm setup executables

- tools/sigma/backends/cim.py
- tools/sigma/backends/mdatp.py
- tools/sigma/backends/uberagent.py
A new category in hardcoded backend.
As I don't use these backends I added the new categories as best I could.
- cim.py  (splunkdm) tests with sigmac seem to be ok
- mdatp.py  tests with sigmac seem to be ok
- uberagent.py tests with sigmac  seem to be ok
> Backend with hardcoded  new registry category

- rules/windows/process_creation/proc_creation_win_bootconf_mod.yml
- rules/windows/process_creation/proc_creation_win_cobaltstrike_load_by_rundll32.yml
- rules/windows/process_creation/proc_creation_win_conti_cmd_ransomware.yml
- rules/windows/process_creation/proc_creation_win_crime_maze_ransomware.yml
- rules/windows/process_creation/proc_creation_win_crime_snatch_ransomware.yml
- rules/windows/process_creation/proc_creation_win_delete_systemstatebackup.yml
- rules/windows/process_creation/proc_creation_win_mal_darkside_ransomware.yml
- rules/windows/process_creation/proc_creation_win_mal_lockergoga_ransomware.yml
- rules/windows/process_creation/proc_creation_win_mal_ryuk.yml
- rules/windows/process_creation/proc_creation_win_malware_conti.yml
- rules/windows/process_creation/proc_creation_win_malware_emotet.yml
- rules/windows/process_creation/proc_creation_win_malware_ryuk.yml
- rules/windows/process_creation/proc_creation_win_office_from_proxy_executing_regsvr32_payload.yml
- rules/windows/process_creation/proc_creation_win_office_from_proxy_executing_regsvr32_payload2.yml
- rules/windows/process_creation/proc_creation_win_office_spawning_wmi_commandline.yml
- rules/windows/process_creation/proc_creation_win_susp_emotet_rundll32_execution.yml
- rules/windows/process_creation/proc_creation_win_susp_eventlog_clear.yml
- rules/windows/process_creation/proc_creation_win_susp_fsutil_usage.yml
- rules/windows/process_creation/proc_creation_win_susp_powershell_enc_cmd.yml
- rules/windows/process_creation/proc_creation_win_susp_system_user_anomaly.yml
- rules/windows/process_creation/proc_creation_win_susp_wuauclt.yml
- tools/config/generic/windows-audit.yml
- reverts some changes introduced by commit c5fa73c328acd5fac5c89c84f2a71c94efc65827
- removes the unnecessary/wrong field mapping
- fixes the rules to apply to CommandLine instead of ParentCommandLine as the author probably intended
- promotion of the status of some rules.
> Fix wrong field mapping of Windows Audit Log EventID 4688

- .github/workflows/sigma-test.yml
- rules/windows/builtin/firewall_as/win_firewall_as_add_rule.yml
- rules/windows/create_remote_thread/sysmon_suspicious_remote_thread.yml
- rules/windows/registry/registry_set/registry_set_disabled_tamper_protection_on_microsoft_defender.yml
- tests/check-baseline-local.sh
Also changed the workflow action to use a fixed version of evtx-baseline again. Can be tweaked using the variable `EVTX_BASELINE_VERSION`. This makes it possible to make upstream changes to existing baselines without breaking the GitHub actions of SigmaHQ.
> workflow: add checks against Windows 2022 baseline

- tools/config/generic/windows-services.yml
Fixed #2897 
windows-bits-client tag converted `WinEventlog:Microsoft-Windows-Bits-Client/Operational` but other channel is not add `WinEventLog:`.
Removed "WinEventlog:" to unify with other channel conversions.
ex: https://answers.microsoft.com/en-us/windows/forum/all/unknown-events-in-windowsbits-clientoperational/c0856f82-44a2-4998-9a3b-9d6eda328136
> changed windows-bits-client Channel

- rules/windows/process_creation/proc_creation_win_lolbas_execution_of_wuauclt.yml
The subtechnique `.011` is  specific to RunDLL32 proxy execution. There is no existing sub-technique specific to wuauclt.exe so only the top level technique should be referenced.
> Change MITRE ATT&CK tactic ID

- rules/windows/process_creation/proc_creation_win_sticky_keys_unauthenticated_privileged_cmd_access.yml
Most likely it comes from a bad parsing by Sigma2Splunkalert but since it is unmaintained and this is the only rule with a comma in title, this is the easy fix. 
Error in 'inputlookup' command: Invalid argument:
'_Privileged_Console_Access_whitelist.csv'
[| inputlookup "Using_Sticky-keys_To_Obtain_Unauthenticated,_Privileged_Console_Access_whitelist.csv]
> fix: Comma in title seems to break splunk search

- rules/windows/builtin/system/win_possible_zerologon_exploitation_using_wellknown_tools.yml
Help PySigma with integer types instead of string.
> String 2 Int for EventIDs

- rules/windows/powershell/powershell_script/posh_ps_tamper_defender.yml
- rules/windows/process_creation/proc_creation_win_susp_reg_disable_sec_services.yml
In proc_creation_win_susp_reg_disable_sec_services.yml
- Added two services
- Removed trailing spaces at the end of service names (is that correct that there should not be any? Or is there an obscure reason?)
In powershell_script/posh_ps_tamper_defender.yml
- Added other Defender options that can be disabled
- Added setting of default actions to allow
> Adding security services and defender options

- rules/windows/builtin/security/win_account_backdoor_dcsync_rights.yml
example, normal behavior when updating dns records from the field
```
2022-05-10 17:47:30 redacted.hostname Security-Auditing: 5136: A directory service object was modified. | OpCorrelationID={533af100-af63-4f8c-8369-80b9e23990ee} | AppCorrelationID=- | SubjectUserSid=S-1-5-18 | SubjectUserName=SYSTEM | SubjectDomainName=NT AUTHORITY | SubjectLogonId=0xa091d | DSName=REDACTED.com | DSType=Active Directory Domain Services | ObjectDN=cn=REDACTED,cn=ZoneScopeContainer,DC=REDACTED.com,cn=MicrosoftDNS,cn=System,DC=REDACTED,DC=com | ObjectGUID={a37d3707-8a78-47d9-854c-f0aae5ca3a75} | ObjectClass=dnsZoneScope | AttributeLDAPDisplayName=nTSecurityDescriptor | AttributeSyntaxOID=2.5.5.15 | AttributeValue= ....
```
> filtering out dnsZoneScope

- rules/proxy/proxy_ua_bitsadmin_susp_tld.yml
example
```
May 09 20:24:58 zscaler-nss CEF:0|Zscaler|NSSWeblog|5.0|Allowed|Allowed|3|act=Allowed app=HTTPS cat=Music and Audio Streaming dhost=i.scdn.co dst=151.101.70.248 src=redacted in=28636 outcome=206 out=204 request=i.scdn.co/image/ab67706f0000000281ef3ccc8db1d1868f24d0e9 rt=May 09 2022 20:24:58 sourceTranslatedAddress=redacted requestClientApplication=Microsoft BITS/7.8 requestMethod=GET suser=redacted_username spriv=Road Warrior externalId=7095835291257602051 fileType=Jpeg Files reason=Allowed destinationServiceName=Spotify cn1=0 cn1Label=riskscore cs1=HDG - Real Estate Ops cs1Label=dept cs2=Entertainment/Recreation cs2Label=urlsupercat cs3=Streaming Media cs3Label=appclass cs4=None cs4Label=malwarecat cs5=None cs5Label=threatname cs6=None cs6Label=dlpeng …
```
> Adds allow for spotify streaming, which uses this service

- rules/windows/file_event/file_event_win_powershell_exploit_scripts.yml
- rules/windows/process_creation/proc_creation_win_certoc_download.yml
- rules/windows/process_creation/proc_creation_win_certoc_execution.yml
- rules/windows/process_creation/proc_creation_win_cmdkey_recon.yml
- rules/windows/process_creation/proc_creation_win_lolbas_configsecuritypolicy.yml
- rules/windows/process_creation/proc_creation_win_lolbas_data_exfiltration_by_using_datasvcutil.yml
- rules/windows/process_creation/proc_creation_win_lolbas_extexport.yml
- rules/windows/process_creation/proc_creation_win_lolbas_extrac32.yml
- rules/windows/process_creation/proc_creation_win_lolbas_ieexec_download.yml
- rules/windows/process_creation/proc_creation_win_lolbin_gpscript.yml
- rules/windows/process_creation/proc_creation_win_lolbin_ie4uinit.yml
- rules/windows/process_creation/proc_creation_win_lolbin_ilasm.yml
- rules/windows/process_creation/proc_creation_win_shadow_copies_deletion.yml
- rules/windows/process_creation/proc_creation_win_susp_findstr.yml
- rules/windows/process_creation/proc_creation_win_uac_cmstp.yml
- Added 5 more PowerShell scripts for the rule "file_event_win_powershell_exploit_scripts.yml"
- Created a new rule for "certoc" lolbin to cover the "Download" option as described in the LOLBAS project
- Created a specific rule for the "IEExec" lolbin to cover the "Download" option as described in the LOLBAS Project
- Updated some rules to use "OriginalFileName" in addition to the "Image" selection
- Updated some rules to increase coverage.
> Rule Update (Batch 2)

- rules/windows/file_event/file_event_win_powershell_exploit_scripts.yml
- rules/windows/process_creation/proc_creation_win_susp_taskkill.yml
- rules/windows/process_creation/proc_creation_win_winword_lolbin.yml
This has the following addition/updates:
- Added "Invoke-EventViewer.ps1" script to the rule "file_event_win_powershell_exploit_scripts"
- Added "OriginalFileName" to "proc_creation_win_susp_taskkill"
- Created rule for "winword" being used as a LOLBIN to download and load arbitrary DLLs
> Quick Updates and Fixes

- tools/sigma/backends/hedera.py
The **csharp** sigmac backend generates C# code that must be added at compilation time or needed to be evaluated or compiled at runtime with CodeDom; sometimes the last method is detected as malicious behavior. 
Needs a solution to use the sigmac output at runtime in C# code.
Code example generated with the csharp backend:
`from x in evnt where ((x.Key == "8" | x.Key == "10") && new Regex(@"SourceImage.*.*\\powershell.exe", RegexOptions.IgnoreCase).IsMatch(x.Value) && new Regex(@"TargetImage.*.*\\lsass.exe", RegexOptions.IgnoreCase).IsMatch(x.Value)) select x;`
This problem could be solved by using the hedera backend that generates a dynamic linq compatible where clause.
Example:
`./sigmac -t hedera ../rules/windows/sysmon/sysmon_accessing_winapi_in_powershell_credentials_dumping.yml` …
> Hedera Backend - C# dynamic LINQ

- tools/sigma/backends/limacharlie.py
In LimaCharlie backend, support the alternate case for `OriginalFileName` since it's used with a lower case `Name` in various rules.
> Support alternate case for OriginalFileName.

- rules/windows/process_creation/proc_creation_win_susp_conhost_option.yml
When converting the rule using Sigmac to an Elastic Security compatible rule, the empty line under the References section results in the Sigmac output for the rule having a `null` value as the last reference.
The command used to convert the rule is:
`tools/sigmac -t es-rule -c tools/config/generic/sysmon.yml -c tools/config/winlogbeat-modules-enabled.yml -r rules/windows/ --backend-option keyword_field=""`
The `references` portion of the output from the above command for that rule is:
`"references": ["https://cybercryptosec.medium.com/covid-19-cyber-infection-c615ead7c29", "https://thedfirreport.com/2022/04/04/stolen-images-campaign-ends-in-conti-ransomware/", null]}`
If the converted rule is uploaded to Elastic Security, the `Failed to import 1 rule` error is seen; The error message is …
> Update proc_creation_win_susp_conhost_option.yml - Remove Empty Reference Line

- rules/linux/process_creation/proc_creation_lnx_atlassian_confluence_cve_2022_26134.yml
- rules/linux/process_creation/proc_creation_lnx_susp_java_children.yml
- Rule to detect "Confluence" java process spawning "/bin/bash" CLI (Maybe related to CVE 2022 26134).
- I actually don't know if this is normal or not. This is directly based on the screenshot provided by Veloxity and their analysis of  CVE 2022 26134 (https://www.volexity.com/wp-content/uploads/2022/06/Figure1.png)
- Full Blog: https://www.volexity.com/blog/2022/06/02/zero-day-exploitation-of-atlassian-confluence/
- Will definitely add to it as things get revealed.
> Atlassian Confluence CVE 2022 26134

- rules/linux/process_creation/proc_creation_lnx_dd_file_overwrite.yml
This rule is subject to false negatives for *nix distros which symlink /bin to /usr/bin.
By including both /bin and /usr/bin we can handle both flavors
> fix(rule): lnx_dd_file_overwrite /bin symlinks

- tools/sigma/backends/lacework.py
For special handling of list items which start or end with wildcards we should be treating the `ConditionOR` as a subexpression such that it gets wrapped in parens.  For instance we want `(x or y) and z` instead of `x or y and z`.
> fix(backend): use subexp when OR list items

- rules/cloud/aws/aws_ec2_startup_script_change.yml
The JSON payload for `ModifyInstanceAttribute` event currently looks like:
```
"requestParameters": {
"attribute": "userData",
...
},
```
Updating the selection_source from `requestParameters.userData: "*"` to `requestParameters.attribute: "userData"` accordingly.
Signed-off-by: Rachel Rice <rachel.rice@lacework.net>
> Update selection_source for AWS ec2 startup script rule

- rules/cloud/aws/aws_ecs_task_definition_backdoor.yml
This is a rule to detect the behavior performed by Rhino Security Labs Pacu's module ecs__backdoor_task_def.
> Submit a rule for ECS Backdoor Task Definition

- rules/cloud/azure/azure_federation_modified.yml
* Set logsource service to auditlogs instead of signinlogs
* Add reference to Microsoft documentation
* Set field name in selection to ActivityDisplayName instead of properties.message
The below query was confirmed on my company's environment.
https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-monitor-federation-changes
```
AuditLogs 
|  extend TargetResource = parse_json(TargetResources) 
| where ActivityDisplayName contains "Set federation settings on domain" or ActivityDisplayName contains "Set domain authentication" 
| project TimeGenerated, SourceSystem, TargetResource[0].displayName, AADTenantId, OperationName, InitiatedBy, Result, ActivityDisplayName, ActivityDateTime, Type
```
> Updating azure federation modified rule

- tools/sigma/backends/lacework.py
Lacework Query Language has been enhanced to support self join filters.
This will allow the Lacework Sigma backend to satisfy `process_creation` rules which specify `ParentImage` and `ParentCommandLine` filters
```
❯ python tools/sigmac -t lacework rules/linux/process_creation/proc_creation_lnx_susp_java_children.yml -O query
---
evaluatorId:
queryId: Sigma_Suspicious_Java_Children_Processes
queryText: |-
Sigma_Suspicious_Java_Children_Processes {
source {
LW_HE_PROCESSES
}
filter {
((MID, PPID_HASH) IN { source { LW_HE_PROCESSES } filter { EXE_PATH LIKE '%/java' } return { MID, PID_HASH } } and (contains(CMDLINE, '/bin/sh') or contains(CMDLINE, 'bash') or contains(CMDLINE, 'dash') or contains(CMDLINE, 'ksh') or contains(CMDLINE, 'zsh') or contains(CMDLINE, 'csh') or contains(CMDLINE, …
```
> feat(backend): support for parent process filters

- tools/config/winlogbeat.yml
`ProviderName: winlog.event_data.ProviderName` seems to be wrong (at least in our case). Actually, the mapping from the `winlogbeat-modules-enabled.yml` would be correct (which I have applied in this pull request), but we definitely don't use the modules (the other mappings don't apply). Maybe the two got mixed up? Can't verify it for the winlogbeat-modules case, but at least the `winlogbeat.yml` does seem to have this mapping wrong.
Also: The mapping identifier `ProviderName` doesn't occur in any windows rule (except one: `powershell/powershell_classic/posh_pc_wsman_com_provider_no_powershell.yml`).
Instead, the identifier `Provider_Name` is used.
> ProviderName seems to be wrong

- rules/windows/image_load/image_load_msdt_sdiageng.yml
Hello, 
I close the old pull request: process creation of  "sdiagnhost.exe". Detecting "sdiageng.dll" is more precise. Besides, this rule is able to detect both Follina and DogWalk attack.
> Rule: Follina and DogWalk exploit msdt.exe loading sdiageng.dll

- tools/sigma/parser/collection.py
SigmaCollectionParser should use deep copy to clone previous rule, otherwise the previously generated Sigma file would be affected.
```
$ ./tools/merge_sigma ./tests/collection_repeat.yml 
description: Test all features of Sigma collections
detection:
selection:
CommandLine: cmd.exe
EventID: 4688         <=== affected by 2nd Sigma
logsource:
service: security       <=== affected by 2nd Sigma
title: Sigma Collection Test
---
description: Test all features of Sigma collections
detection:
selection:
CommandLine: cmd.exe
EventID: 4688
logsource:
service: security
title: Sigma Collection Test
```
With deepcopy():
```
$ ./tools/merge_sigma ./tests/collection_repeat.yml 
description: Test all features of Sigma …
```
> using deepcopy to clone previous rule

- rules/windows/builtin/printservice/win_exploit_cve_2021_1675_printspooler.yml
example:
```
2022-06-18 08:51:28 REDACTED PrintService: 808: The print spooler failed to load a plug-in module PrintConfig registration timed out: C:\Windows\system32\regsvr32.exe /s "C:\Windows\system32\spool\drivers\x64\3\PrintConfig.dll", error code 0x1. See the event user data for context information. | pid=1700 | level=0 | sys_version=0 | category=Initializing | op=Spooler Operation Failed | SPOOLER_KEYWORD=true | Microsoft-Windows-PrintService/Admin=true | key=0x8000000000020000 | id=81 | app="?" | tid=4344 | channel="Microsoft-Windows-PrintService/Admin" | pid_user="NT AUTHORITY\SYSTEM" | sid=S-1-5-18 | account type=User | type=error(2) 
```
> False positive when print dll times out when attempting to register

- rules/windows/process_creation/proc_creation_win_lolbin_syncappvpublishingserver_vbs_execute_psh.yml
All format work:
```
- SyncAppvPublishingServer.vbs "\n;<code>"
- SyncAppvPublishingServer.vbs "n;<code>"
- SyncAppvPublishingServer.vbs ";<code>"
- SyncAppvPublishingServer.vbs "abc;<code>"
```
> To account for SyncAppvPublishingServer bypass

- rules/windows/builtin/security/win_susp_failed_logon_reasons.yml
This behavior happens too often in a normal enviornment, with day to day activity and no definitive threat.  I believe a different rule, detecting a larger volume of this behavior would warrant a high level rating.
Examples:
```
2022-06-29 12:37:08 REDACTED Security-Auditing: 4776: The computer attempted to validate the credentials for an account. | PackageName=MICROSOFT_AUTHENTICATION_PACKAGE_V1_0 | TargetUserName=JS0XXXXXXXXQP2$ | Workstation=JS0XXXXXXXXQP2 | Status=0xc0000072 | pid=684 | level=0 | sys_version=0 | category=Credential Validation | op=Info | Security=true | key=0x8010000000000000 | id=1359729128 | app="C:\Windows\System32\lsass.exe" | tid=1588 | channel="Security" | type=audit failure(0)
```
> Reducing the level of Account Tampering - Suspicious Failed Logon Reasons

- rules/windows/file_access/file_access_win_browser_credential_stealing.yml
hi @frack113 ,
found the rule "**Browser Credential Store Access - 91cb43db-302a-47e3-b3c8-7ede481e27bf**" matching on:
maybe "C:\WINDOWS\system32\" should be excluded as well?
> fix: FP fix

- rules/windows/process_access/proc_access_win_handlekatz_lsass_access.yml
@Neo23x0 Can you check false positives on this? May need to add additional filters.
The exact call trace is:
```
C:\Windows\SYSTEM32\ntdll.dll+9d234\|UNKNOWN(00000000001C119B)
```
I am using the below regex pattern but I suspect many backends may not support "_re_" so I didn't include it.
```
(?i)^C:\\Windows\\System32\\ntdll\.dll\+[a-z0-9]+\|UNKNOWN\([A-Z0-9]+\)$
```
This rule has a "false negative" scenario when adversaries use HandleKatz to duplicate LSASS handle by opening a benign process that has a handle to LSASS. In this way, LSASS is not touched. However, it is rare to find these benign processes and the writers of HandleKatz have said that this occurs in servers. 
Adversaries can skip this and directly target LSASS since it has a handle to itself.
> Rule for HandleKatz

- rules/windows/builtin/application/win_mssql_xp_cmdshell_audit_log.yml
- rules/windows/builtin/application/win_mssql_xp_cmdshell_change.yml
- rules/windows/process_creation/proc_creation_win_cmd_redirection_susp_folder.yml
- rules/windows/process_creation/proc_creation_win_inline_base64_mz_header.yml
- rules/windows/process_creation/proc_creation_win_net_user_add_never_expire.yml
- rules/windows/process_creation/proc_creation_win_susp_mofcomp_execution.yml
- rules/windows/registry/registry_set/registry_set_special_accounts.yml
This PR adds the following new rules based on the latest DFIR report (https://thedfirreport.com/2022/07/11/select-xmrig-from-sqlserver/) :
- Hide User Account Via Special Accounts Reg Key (f8aebc67-a56d-4ec9-9fbe-7b0e8b7b4efd)
- Net.exe User Account Creation - Never Expire (b9f0e6f5-09b4-4358-bae4-08408705bd5c) derived from (cd219ff3-fa99-45d4-8380-a7d15116c6dc)
- Base64 MZ Header In CommandLine (22e58743-4ac8-4a9f-bf19-00a0428d8c5f)
- Suspicious CMD Shell Redirect (8e0bb260-d4b2-4fff-bb8d-3f82118e6892)
- Suspicious Mofcomp Execution (1dd05363-104e-4b4a-b963-196a534b03a1)
- MSSQL XPCmdshell Suspicious Execution (7f103213-a04e-4d59-8261-213dddf22314)
- MSSQL XPCmdshell Option Change (d08dd86f-681e-4a00-a92c-1db218754417)
> DFIR Report - SELECT XMRig FROM SQLServer (New Rules)

- rules/windows/builtin/application/win_susp_msmpeng_crash.yml
- rules/windows/builtin/application/win_vul_cve_2021_41379.yml
- rules/windows/builtin/msexchange/win_exchange_cve_2021_42321.yml
- rules/windows/builtin/msexchange/win_exchange_transportagent_failed.yml
For windows when it is `Data` in the ETW, I have update the rule.
Some use keywords while events have a field name, so more digging is needed.
> Remove some keywords

- tools/config/splunk-zeek.yml
Line 407 was `source: id.orig_h` so that people could use the word `source` as an alias to `id.orig_h`, however there is a literal field with the name `source` in the `files.log` for Zeek, so having a Sigma query with something like `source: 'SMTP'` would yield `id.orig_h='SMTP'` in the resulting Splunk translation, which is incorrect. It should be `source='SMTP'`
Commenting out line 407 fixes this.
> Fix issue with using `source:` on Zeek `files` log

- rules/windows/process_creation/proc_creation_win_susp_regsvr32_anomalies.yml
Example:
```
2022-07-20 18:18:51 REDACTED Sysmon: 1: Process Create | RuleName=technique_id=T1117,technique_name=Regsvr32 | UtcTime=2022-07-20 18:18:51.084 | ProcessGuid={77295911-470B-62D8-5152-000000000402} | ProcessId=14752 | Image=C:\Windows\SysWOW64\regsvr32.exe | FileVersion=10.0.14393.1378 (rs1_release.170620-2008) | Description=Microsoft(C) Register Server | Company=Microsoft Corporation | OriginalFileName=REGSVR32.EXE | OriginalCommandLine="C:\Windows\SysWOW64\regsvr32.exe" /n /s /i:"cbfsconnect2017-Box" "C:\Program Files\Box\Box\Temp\cbfsconnect2017-Box\i386\cbfsconnectMntNtf2017.dll" | CommandLine=C:\Windows\SysWOW64\regsvr32.exe /n /s /i:cbfsconnect2017-Box "C:\Program Files\Box\Box\Temp\cbfsconnect2017-Box\i386\cbfsconnectMntNtf2017.dll" | …
```
> False positive when box app uses regsvr32

- rules/windows/process_creation/proc_creation_win_susp_psexex_paexec_escalate_system.yml
- rules/windows/registry/registry_add/registry_add_amsi_providers_persistence.yml
- rules/windows/registry/registry_add/registry_set_disk_cleanup_handler_new_entry_persistence.yml
- rules/windows/registry/registry_set/registry_set_aedebug_persistence.yml
- rules/windows/registry/registry_set/registry_set_chm_persistence.yml
- rules/windows/registry/registry_set/registry_set_disk_cleanup_handler_autorun_persistence.yml
- rules/windows/registry/registry_set/registry_set_disk_cleanup_handler_new_entry_persistence.yml
- rules/windows/registry/registry_set/registry_set_hangs_debugger_persistence.yml
- rules/windows/registry/registry_set/registry_set_hhctrl_persistence.yml
- rules/windows/registry/registry_set/registry_set_ifilter_persistence.yml
- rules/windows/registry/registry_set/registry_set_lsa_extension_persistence.yml
- rules/windows/registry/registry_set/registry_set_mpnotify_persistence.yml
- rules/windows/registry/registry_set/registry_set_sip_persistence.yml
- rules/windows/registry/registry_set/registry_set_winlogon_notify_key.yml
- rules/windows/registry/registry_set/regsitry_set_natural_language_persistence.yml
This PR covers missing persistence techniques based on this repo https://persistence-info.github.io/
I added the following rules:
- Persistence Via AMSI Providers (33efc23c-6ea2-4503-8cfe-bdf82ce8f705)
- Persistence Via AeDebug value (092af964-4233-4373-b4ba-d86ea2890288)
- Persistence Via CHM Helper DLL (976dd1f2-a484-45ec-aa1d-0e87e882262b)
- Persistence Via DiskCleanup Handler (d4e2745c-f0c6-4bde-a3ab-b553b3f693cc) + (d4f4e0be-cf12-439f-9e25-4e2cdcf7df5a)
- Persistence Via Hangs Key (833ef470-fa01-4631-a79b-6f291c9ac498)
- Persistence Via "Hhctrl.ocx" (f10ed525-97fe-4fed-be7c-2feecca941b1)
- Persistence Via IFilters (b23818c7-e575-4d13-8012-332075ec0a2b)
- Persistence Via LSA Extensions (41f6531d-af6e-4c6e-918f-b946f2b85a36)
- Persistence Via Mpnotify …
> New Persistence Rules

- rules/windows/process_creation/proc_creation_win_run_executable_invalid_extension.yml
I believe those CommandLine fields are errors and should be ParentCommandLine
The FP was added based on real client environments, they generate a lot of alerts
> Replace commandline by parentcommandline and add fp

- rules/windows/driver_load/driver_load_susp_temp_use.yml
- rules/windows/driver_load/driver_load_vuln_avast_anti_rootkit_driver.yml
- rules/windows/process_creation/proc_creation_win_susp_new_kernel_driver_via_sc.yml
Added new rules based on this https://www.aon.com/cyber-solutions/aon_cyber_labs/yours-truly-signed-av-driver-weaponizing-an-antivirus-driver/
- Detect vuln avast driver mentioned in the article via its HASH
- Rule to detect the installation of new drivers via "sc type=kernel"
> Avast vuln driver

- tools/sigma/backends/lacework.py
evalFrequency has been deprecated; it is no longer required for policies.
Signed-off-by: Rachel Rice <rachel.rice@lacework.net>
> chore: Remove evalFrequency from Lacework backend

- rules/linux/process_creation/proc_creation_lnx_webshell_detection.yml
- rules/windows/process_creation/proc_creation_win_webshell_spawn.yml
Updated these two rules following the NSA link provided in this tweet https://twitter.com/securepeacock/status/1554220498917228544
- Shells Spawned by Web Servers (8202070f-edeb-4d31-a010-a26c72ac5600)
- Linux Webshell Indicators (818f7b24-0fba-4c49-a073-8b755573b9c7)
NSA Link: https://media.defense.gov/2020/Jun/09/2002313081/-1/-1/0/CSI-DETECT-AND-PREVENT-WEB-SHELL-MALWARE-20200422.PDF
> Update Children Of Web Shell Rules

- rules/web/web_cve_2020_10148_solarwinds_exploit.yml
FP: /webresource.axd?d=<REDACTED>1&t=637823185705833095
Adds /api or /SolarWinds/ path check
> Narrowing the detection due to false positive matches of webresource.axd

- rules/proxy/proxy_empire_ua_uri_combos.yml
Rule should be applied on uri and not the uri-query
> proxy_empire_ua_uri_combos.yml: Change cs-uri-query to cs-uri to enable matching

- rules/windows/file_event/file_event_bloodhound_collection.yml
Similar idea to the [lsass dump detection rule](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file_event/file_event_win_lsass_dump.yml), this rule detects default file names outputted by SharpHound.
> BloodHound Collection Files

- rules/windows/process_creation/proc_creation_win_vul_java_remote_debugging.yml
For the `Java Running with Remote Debugging` rule, the detection has been improved to only trigger if the command includes a vulnerable JVM version. 
JRE/JDK 9 and later limit remote debugging access to localhost by default. See also [Remote Debugging Java Applications With JDWP](https://dzone.com/articles/remote-debugging-java-applications-with-jdwp)
So for everything later than Java 8, this rule produces loads of false positives
Most of the time, the additional selection  strings `jre1.*` or `jdk1.` are present. However, there may be occasions where a Java application is started without the JDK/JRE path present in the command line.
> Reduced False Positives for Java Running with Remote Debugging Rule

- rules/proxy/proxy_susp_flash_download_loc.yml
- rules/proxy/proxy_ua_susp.yml
proxy_susp_flash_download_loc:
* Change to c-uri inst of c-uri-query so we actually match on the path and not the query.
* r-dns instead of c-uri-stem as it appears cleaner in this case.
proxy_ua_susp.yml:
* Filter to avoid false positive traffic towards Adobe sites from Adobe products
> proxy_susp_flash_download_loc.yml: c-uri inst. of c-uri-query and r-dns inst of c-uri-stem, proxy_ua_susp.yml: Avoid adobe false positives

- .github/workflows/sigma-test.yml
- .gitmodules
- tests/test_rules.py
The TAXII-Servers often are unreliable. This way we could have consistent and more deterministic tests:
Pros: 
- Github servers are more reliable than TAXII.
- ! Faster offline tests. Once a user has downloaded the submodule, he doesn't have to download the data from TAXII every time. 
- Using pinned version of the data, we can retrace results and don't rely on potential dynamic TAXII results.
- TAXII is still a fallback when the subrepo is not initialized.
Cons: 
- The Github CLI Repo can be a little bit out of date. 
- Submodule needs to be updated every now and then.
> Using Attk CLI as Submodule to not rely on TAXII Service

- .gitmodules
Many Firewalls allow HTTPS but block SSH. 
This also allows cloning without auth which makes processes easier.
> chore: Change subrepo from ssh to https

- rules/windows/builtin/security/win_global_catalog_enumeration.yml
- rules/windows/builtin/security/win_susp_outbound_kerberos_connection.yml
Update to keep field names consistent for all rules which use EID 5156:
1. DestPort instead of DestinationPort
2. Application instead of Image
Current List:
[/rules/windows/builtin/security/win_global_catalog_enumeration.yml - Changed](https://github.com/SigmaHQ/sigma/blob/eded7e479db631f72ceef8d2960efae018048735/rules/windows/builtin/security/win_global_catalog_enumeration.yml)
[/rules/windows/builtin/security/win_rdp_reverse_tunnel.yml](https://github.com/SigmaHQ/sigma/blob/eded7e479db631f72ceef8d2960efae018048735/rules/windows/builtin/security/win_rdp_reverse_tunnel.yml)
[/rules/windows/builtin/security/win_remote_powershell_session.yml](https://github.com/SigmaHQ/sigma/blob/eded7e479db631f72ceef8d2960efae018048735/rules/windows/builtin/security/win_remote_powershell_session.yml) …
> Update fields for EID 5156 rules

- rules/proxy/proxy_ua_bitsadmin_susp_tld.yml
Observed false-positive traffic towards `.sfx.ms` for proxy_ua_bitsadmin_susp_tld.yml so updated the rule filter.
> proxy_ua_bitsadmin_susp_tld.yml fp filter

- rules/windows/builtin/security/win_account_backdoor_dcsync_rights.yml
In an hybrid environment (Azure AD + on-premises), we can see false positives on objects with the "**dnsZone**" ObjectClass. Specifically, we've seen:
```
DN :	DC=privatelink.blob.core.windows.net,cn=MicrosoftDNS,DC=ForestDnsZones,DC=redacted,DC=com
DN :	DC=privatelink.azurewebsites.net,cn=MicrosoftDNS,DC=ForestDnsZones,DC=redacted,DC=com
DN :	DC=privatelink.vaultcore.azure.net,cn=MicrosoftDNS,DC=ForestDnsZones,DC=redacted,DC=com
DN :	DC=privatelink.prod.migration.windowsazure.com,cn=MicrosoftDNS,DC=ForestDnsZones,DC=redacted,DC=com
DN :	DC=privatelink.siterecovery.windowsazure.com,cn=MicrosoftDNS,DC=ForestDnsZones,DC=redacted,DC=com
```
We can see references to these domain names at: https://docs.microsoft.com/en-us/azure/migrate/troubleshoot-network-connectivity#confirm-that-the-required …
> Filter out FP of dnsZone

- tools/sigma/backends/sqlite.py
**I know that `sigmac` has been deprecated in favour of pySigma** but for now the Sqlite backend hasn't been converted.
Details : 
- When generating "default" rulesets for Zircolite, I took notice that null values (e.g `CurrentDirectory: null`) are not handled correctly by the base class.
- **This is basically handled in the sqlite (not sql) backend just by replacing `None` by an empty string to avoid a Python Exception.**
> Update Sqlite backend to handle null values

- rules/cloud/azure/azure_application_gateway_modified_or_deleted.yml
- rules/cloud/azure/azure_application_security_group_modified_or_deleted.yml
- rules/cloud/azure/azure_container_registry_created_or_deleted.yml
- rules/cloud/azure/azure_dns_zone_modified_or_deleted.yml
- rules/cloud/azure/azure_firewall_modified_or_deleted.yml
- rules/cloud/azure/azure_firewall_rule_collection_modified_or_deleted.yml
- rules/cloud/azure/azure_keyvault_key_modified_or_deleted.yml
- rules/cloud/azure/azure_keyvault_modified_or_deleted.yml
- rules/cloud/azure/azure_keyvault_secrets_modified_or_deleted.yml
- rules/cloud/azure/azure_kubernetes_admission_controller.yml
- rules/cloud/azure/azure_kubernetes_cluster_created_or_deleted.yml
- rules/cloud/azure/azure_kubernetes_cronjob.yml
- rules/cloud/azure/azure_kubernetes_events_deleted.yml
- rules/cloud/azure/azure_kubernetes_network_policy_change.yml
- rules/cloud/azure/azure_kubernetes_pods_deleted.yml
- rules/cloud/azure/azure_kubernetes_role_access.yml
- rules/cloud/azure/azure_kubernetes_rolebinding_modified_or_deleted.yml
- rules/cloud/azure/azure_kubernetes_secret_or_config_object_access.yml
- rules/cloud/azure/azure_kubernetes_service_account_modified_or_deleted.yml
- rules/cloud/azure/azure_network_firewall_policy_modified_or_deleted.yml
- rules/cloud/azure/azure_network_firewall_rule_modified_or_deleted.yml
- rules/cloud/azure/azure_network_p2s_vpn_modified_or_deleted.yml
- rules/cloud/azure/azure_network_security_modified_or_deleted.yml
- rules/cloud/azure/azure_network_virtual_device_modified_or_deleted.yml
- rules/cloud/azure/azure_new_cloudshell_created.yml
- rules/cloud/azure/azure_subscription_permissions_elevation_via_activitylogs.yml
- rules/cloud/azure/azure_suppression_rule_created.yml
- rules/cloud/azure/azure_virtual_network_modified_or_deleted.yml
- rules/cloud/azure/azure_vpn_connection_modified_or_deleted.yml
All of these Azure rules are using what seems to be a custom field name of `properties.message` instead of the default log field name of `operationName`. Per Microsoft's documentation as well as my own testing with raw Azure Activity Logs sent to an external SIEM through EventHub, the default log field name is indeed `operationName`. 
Having this as `properties.message` means that any transform rules written for the default log field names will not properly transform these rules into queries.
My IDE also automatically reformatted these to match sigma standard field order and YAML spacing.
No other changes to the detection logic other than the renaming of the field `properties.message` to `operationName`.
I have not updated any of the `id` fields for these rules as I was not sure what a …
> Azure Activity Logs - operationName Field

- rules/proxy/proxy_ua_bitsadmin_susp_ip.yml
Change to endswith instead of startswith to avoid matching subdomains which starts with digits, example one: `3.au.download.windowsupdate.com`
> proxy_ua_bitsadmin_susp_ip.yml falsepositive fix

- rules/windows/powershell/powershell_script/posh_ps_disable_psreadline_command_history.yml
Powershell command history can be disabled by removing psreadline module
> posh_ps_disable_psreadline_command_history

- rules/windows/process_creation/proc_creation_win_schtasks_system.yml
This should be 'SYSTEM' not ' SYSTEM ' - these leading/trailing spaces are making this detection invalid since the /RU parameter value will be "NT AUTHORITY\SYSTEM".
> Fixing selection_user to match NT AUTHORITY\SYSTEM

- rules/windows/process_creation/proc_creation_win_file_permission_modifications.yml
Previous Filter of Image was wrong. Image can't endsWith (Code.exe and attrib.exe) at the same time. Same condition with other scenario. CommandLine filter is good.
> VS Code Filter Fix - Undo the last commit

- rules/windows/builtin/security/win_teams_suspicious_objectaccess.yml
- rules/windows/file_event/file_event_win_access_susp_teams.yml
- rules/windows/process_creation/proc_creation_win_teams_suspicious_command_line_cred_access.yml
Microsoft Teams is an Electron app, meaning that it runs in a browser window, complete with all the elements required by a regular web page (cookies, session strings, logs, etc.).
Electron does not support encryption or protected file locations by default, so while the software framework is versatile and easy to use, it is not considered secure enough for developing mission-critical products unless extensive customization and additional work is applied.
- https://www.vectra.ai/blogpost/undermining-microsoft-teams-security-by-mining-tokens
- https://www.bleepingcomputer.com/news/security/microsoft-teams-stores-auth-tokens-as-cleartext-in-windows-linux-macs/
> Microsoft Teams Suspicious ObjectAccess events

- rules/windows/file_event/file_event_win_notepad_plus_plus_persistence.yml
- rules/windows/image_load/image_load_side_load_from_non_system_location.yml
- rules/windows/image_load/image_load_uipromptforcreds_dlls.yml
- rules/windows/process_access/proc_access_win_direct_syscall_ntopenprocess.yml
- rules/windows/process_creation/proc_creation_win_cobaltstrike_process_patterns.yml
- rules/windows/process_creation/proc_creation_win_mstsc.yml
- rules/windows/process_creation/proc_creation_win_ntfs_short_name_path_use_cli.yml
- rules/windows/process_creation/proc_creation_win_reg_add_run_key.yml
- rules/windows/process_creation/proc_creation_win_susp_curl_download.yml
- rules/windows/process_creation/proc_creation_win_susp_direct_asep_reg_keys_modification.yml
- rules/windows/process_creation/proc_creation_win_susp_explorer_break_proctree.yml
- rules/windows/process_creation/proc_creation_win_susp_image_missing.yml
- rules/windows/process_creation/proc_creation_win_susp_non_exe_image.yml
- rules/windows/process_creation/proc_creation_win_susp_squirrel_lolbin.yml
- rules/windows/process_creation/proc_creation_win_system_exe_anomaly.yml
- rules/windows/process_creation/proc_creation_win_windows_terminal_susp_children.yml
- rules/windows/registry/registry_event/registry_event_runonce_persistence.yml
- This PR fixes some FP found in testing
- It also adds/reverts a change proposed in #3129 - After some testing, I think it's best to add the most known case of "/root," since most people don't have process history logs to be able to determine the source. For that, I left both options to be able to catch the initiating process and the results of an "explorer.exe" breaking the tree.
> Fix False-Positives In Testing

- rules/windows/process_creation/proc_creation_detect_execution_of_winPEAS.yml
- rules/windows/process_creation/proc_creation_win_winpeas_tool.yml
Hey,
I created a rule for our "magic" tool winPEAS :)
SPL test via Splunk
```
index=main AND EventCode=1 
Image IN ("*\\winPEASany.exe", "*\\winPEASany_ofs.exe", "*\\winPEASx64.exe", "*\\winPEASx64_ofs.exe", "*\\winPEASx86.exe", "*\\winPEASx86_ofs.exe")
OR OriginalFileName="winPEAS.exe"
OR CommandLine IN ("*domain*", "*systeminfo*", "*userinfo*", "*processinfo*", "*serviceinfo*", "*applicationsinfo*", "*networkinfo*", "*windowscreds*", "*browserinfo *", 
"*filesinfo *", "*fileanalysis*", "*eventsinfo*") 
NOT (Image="*\\systeminfo.exe" OR OriginalFileName="sysinfo.exe")
| fields Image CurrentDirectory dest User ParentImage OriginalFileName CommandLine ParentCommandLine 
| table _time Image  CurrentDirectory dest User ParentImage OriginalFileName CommandLine ParentCommandLine
| sort - _time …
```
> new rule for the winpeas tool

- tools/config/generic/windows-services.yml
The following rule
```
title: Loading Diagcab Package From Remote Path
id: 50cb47b8-2c33-4b23-a2e9-4600657d9746
```
uses `service: diagnosis-scripted` in its log source but `diagnosis-scripted` is not defined in `windows-services.yml` so the proper Channel will not be used possibly causing false positives.
> add diagnosis-scripted to windows services file

- rules/windows/builtin/security_mitigations/win_security_mitigations_defender_load_unsigned_dll.yml
- rules/windows/builtin/security_mitigations/win_security_mitigations_unsigned_dll_from_susp_location.yml
- tools/config/generic/windows-services.yml
The category `security-mitigations` was not defined which could potentially cause false positives so I defined it.
I am not sure why it was a category instead of a service. It does not filter on any specific event ID like all of the other categories do so I changed the rule category to service and defined it there. The logs seem to be saved in both the `UserMode` and `KernelMode` channels so I defined the Provider Name instead of Channel in order to check both of these logs.
> define security-mitigations service

- tools/README.md
- tools/config/datadog.yml
- tools/sigma/backends/datadog.py
- tools/tests/test_backend_datadog.py
This PR update to datagdog converter, I've added the possibiility to have differents 'attributes' than the default one from the rules. Example: `EventID` is translated to `@evt.id` to match our datadog indexation.
I also rewrite the datadog test so match the new update.
> Update datadog sigmac

- rules/compliance/firewall_cleartext_protocols.yml
- rules/network/zeek/zeek_smb_converted_win_lm_namedpipe.yml
- rules/network/zeek/zeek_smb_converted_win_susp_psexec.yml
Not all firewalls have a condition of action with values of accept, or forward, or 2.  some simply mark as blocked (true/false).
Also fixes some logic bugs that keep the sigma from ever matching properly
> FP: fixes some logic errors where conditions could not be met

- rules/windows/image_load/image_load_scrcons_imageload_wmi_scripteventconsumer.yml
- rules/windows/image_load/image_load_side_load_antivirus.yml
- rules/windows/image_load/image_load_wmic_remote_xsl_scripting_dlls.yml
- rules/windows/powershell/powershell_module/posh_pm_alternate_powershell_hosts.yml
- rules/windows/process_creation/proc_creation_win_lolbin_findstr.yml
- rules/windows/process_creation/proc_creation_win_wmi_persistence_script_event_consumer.yml
- rules/windows/registry/registry_set/registry_set_disable_winevt_logging.yml
This PR fixes some false positives found in testing
- Reduced the level of the following three rules due to untunable FP. By that, I mean that when the rules trigger the event doesn't contain enough information on its own to let the analysts know whether the action was malicious or not. It needs to be correlated with other events such as process creation for example in order to obtain useful information. Since I was able to trigger these rules in a benign way. I think it's better to reduce the level to medium. At least until correlation is introduced to SIGMA. (Example of FP was discussed in keybase)
- [b439f47d-ef52-4b29-9a2f-57d8a96cb6b8](https://github.com/SigmaHQ/sigma/blob/7fb8272f948cc0b528fe7bd36df36449f74b2266/rules/windows/image_load/image_load_scrcons_imageload_wmi_scripteventcon …
> Fix False Positives

- rules/windows/process_creation/proc_creation_win_susp_lolbin_non_c_drive.yml
[Any.run example](https://app.any.run/tasks/dba6aa0f-f981-4730-b274-e157ff61e685/) - if it used Win 10 and user doesn't have WinRAR, it'll mount and execute the same except not using Desktop folder in C drive.
> Add rule for suspicious lolbin executing in non-c drive

- rules/windows/process_creation/proc_creation_win_susp_non_exe_image.yml
Added false positive filter for Dell Docking Station Update Utility.
The Image has a value similar to: C:\Windows\Temp\Helper\C9632CF058AE4321B6B0B5EA39B710FE
ParentImage will always be: C:\Windows\Temp\*\TBT_Dock_Firmware\GetDockVer32W.exe
SHA256: cd2688a74a151b03282388dadb8b6aaca309f2535c8b2b21d1243846d2b259dc
> Filter Dell Update Utility: proc_creation_win_susp_non_exe_image.yml

- tools/config/fireeye-helix.yml
- tools/config/generic/windows-services.yml
- tools/config/powershell.yml
- tools/config/splunk-windows.yml
- tools/config/sumologic.yml
- tools/config/thor.yml
- tools/config/winlogbeat-modules-enabled.yml
- tools/config/winlogbeat-old.yml
- tools/config/winlogbeat.yml
- tools/config/zircolite.yml
This PR aims to add mapping to the `PowerShellCore/Operational` which is the event log used in PowerShell 7 instead of the usual PowerShell 5 `Microsoft-Windows-PowerShell/Operational`.
Note that I added it to the same category/service to avoid rule duplication in the future. As the EIDs are the same in both versions of PowerShell
---
Just for reference, if you want to set up PowerShell 7 logging use the following steps
- Execute `C:\Program Files\PowerShell\7\InstallPSCorePolicyDefinitions.ps1`
- Open `gpedit.msc` and navigate to `Administrative Templates`
- There you'll find a new folder called `PowerShell Core`. Which has a similar structure to the PowerShell 5 logging.
> Add PowerShellCore Eventlog

- rules/windows/process_access/process_access_win_shellcode_inject_msf_empire.yml
- rules/windows/process_creation/proc_creation_win_lolbin_susp_wsl.yml
- rules/windows/registry/registry_delete/registry_delete_removal_com_hijacking_registry_key.yml
- rules/windows/registry/registry_set/registry_set_asep_reg_keys_modification_currentversion.yml
- Adds a filter to the rule [dec44ca7-61ad-493c-bfd7-8819c5faa09b](https://github.com/SigmaHQ/sigma/blob/f976ad48c1dcd63b1e1e888ff662adf625b7021b/rules/windows/process_creation/proc_creation_win_lolbin_susp_wsl.yml) to fix a false positives that occurs via VsCode Server extension 
- Filter Visual Studio in the [250ae82f-736e-4844-a68b-0b5e8cc887da](https://github.com/SigmaHQ/sigma/blob/ee850aaf2cdc23d503e43593d9a1c20a5123c89c/rules/windows/process_access/process_access_win_shellcode_inject_msf_empire.yml) as it's causing FP just by starting it.
- Tighten the filters for the `everything.exe` process for the rules [20f0ee37-5942-4e45-b7d5-c5b5db9df5cd](https://github.com/SigmaHQ/sigma/blob/e93b7bf5711cd0f45decb6fe06ded830c77ecd57/rules/windows/registry/registry_ …
> Fix FP In Testing

- rules/windows/builtin/openssh/win_sshd_openssh_server_listening_on_socket.yml
- rules/windows/builtin/sshd/win_sshd_openssh_server_listening_on_socket.yml
- tools/config/elk-windows.yml
- tools/config/elk-winlogbeat-sp.yml
- tools/config/elk-winlogbeat.yml
- tools/config/fireeye-helix.yml
- tools/config/generic/windows-services.yml
- tools/config/logpoint-windows.yml
- tools/config/logstash-windows.yml
- tools/config/powershell.yml
- tools/config/splunk-windows.yml
- tools/config/sumologic.yml
- tools/config/thor.yml
- tools/config/winlogbeat-modules-enabled.yml
- tools/config/winlogbeat-old.yml
- tools/config/winlogbeat.yml
- Add "OpenSSH/Operational" log source to solve this [Issue #13](https://github.com/SigmaHQ/sigma-specification/issues/13)
- Add the first `sshd` rule, based on this [OpenSSH Server Listening On Socket](https://github.com/mdecrevoisier/SIGMA-detection-rules/blob/main/windows-openssh/win-os-OpenSSH%20server%20listening.yaml)
> Add OpenSSH Operational

- rules/windows/image_load/image_load_side_load_dbgcore_dll.yml
- rules/windows/image_load/image_load_side_load_dbghelp_dll.yml
This removes specific filters to the `dbghelp.dll` and `dbgcore.dll` Image Load rules. Since these 2 DLLs are used by a lot of processes living in the `C:\Program Files` and `C:\Program Files (x86)\` (Such as AV products and Dev Software which both often load their version of this DLL) it's better to add them to a generic filters
> fix: FP with dbgcore and dbghelp

- rules/windows/builtin/code_integrity/win_codeintegrity_attempted_dll_load.yml
- rules/windows/process_creation/proc_creation_win_cobaltstrike_process_patterns.yml
This PR fixes
- FP found with the Code Integrity rule
- A logic error that was introduced in #3514 (by me 😅) with the use of an `and` instead of an `or` and mislabeled selections
> Aurora - Fix FP Found In Testing

- rules/windows/builtin/system/win_system_susp_service_installation.yml
I think we should not add ProgramData (was just added on Friday) as we already got 2 FPs in a testing environment which tells me we can suspect many more FPs in-the-wild.
> fix: FPs in testing environment

- tools/config/elk-windows.yml
- tools/config/elk-winlogbeat-sp.yml
- tools/config/elk-winlogbeat.yml
- tools/config/fireeye-helix.yml
- tools/config/generic/windows-services.yml
- tools/config/hawk.yml
- tools/config/logpoint-windows.yml
- tools/config/logstash-windows.yml
- tools/config/powershell.yml
- tools/config/splunk-windows.yml
- tools/config/sumologic.yml
- tools/config/thor.yml
- tools/config/winlogbeat-modules-enabled.yml
- tools/config/winlogbeat-old.yml
- tools/config/winlogbeat.yml
- Fixes a broken provider name in the `hawk.yml` config (I don't think the ETW word is part of the provider name?)
- Add the missing provider to other configs
> feat: add missing `Microsoft-Windows-LDAP-Client/Debug` ETW provider

- rules/windows/process_creation/proc_creation_win_invoke_obfuscation_clip.yml
- rules/windows/process_creation/proc_creation_win_invoke_obfuscation_stdin.yml
- rules/windows/process_creation/proc_creation_win_invoke_obfuscation_var.yml
- rules/windows/process_creation/proc_creation_win_invoke_obfuscation_via_stdin.yml
- rules/windows/process_creation/proc_creation_win_invoke_obfuscation_via_use_clip.yml
- rules/windows/process_creation/proc_creation_win_invoke_obfuscation_via_var.yml
This PR aims to update the `Invoke-Obfuscation` rule that used regular expressions into rules that use simple concatenation. Basically, the regex allows for more specificity. The one used in the rule used a lot of greedy modifiers such as the `.*` and only a couple of markers. I would argue that the following update will give the same results in 90% of the case.
Note: Since the same regular expressions were used in the `System`, `Security`, and `PowerShell` variation of the rules. If this PR gets accepted, I would update the rest.
> fix: update invoke-obfuscation rules

- rules-deprecated/windows/proc_access_win_in_memory_assembly_execution.yml
- rules/application/rpc_firewall/rpc_firewall_sasec_recon.yml
- rules/linux/auditd/lnx_auditd_web_rce.yml
- rules/linux/builtin/lnx_shell_susp_log_entries.yml
- rules/windows/builtin/printservice/win_exploit_cve_2021_1675_printspooler.yml
- Renamed [0a3ff354-93fc-4273-8a03-1078782de5b7](https://github.com/SigmaHQ/sigma/blob/890c2496d1403df5e21782144e1582bcbab42fdb/rules/application/rpc_firewall/rpc_firewall_sasec_recon.yml) to Fix #3699 
- After I had a talk with [@M_haggis](https://twitter.com/M_haggis) we concluded that the EID `4909` doesn't exist in the referenced event log so it's been removed from the rule [4e64668a-4da1-49f5-a8df-9e2d5b866718](https://github.com/SigmaHQ/sigma/blob/890c2496d1403df5e21782144e1582bcbab42fdb/rules/windows/builtin/printservice/win_exploit_cve_2021_1675_printspooler.yml). This fixes #2744
- Deprecate [5f113a8f-8b61-41ca-b90f-d374fa7e4a39](https://github.com/SigmaHQ/sigma/blob/890c2496d1403df5e21782144e1582bcbab42fdb/rules/windows/process_access/proc_access_win …
> fix: fix issues and deprecate rule

- rules/windows/builtin/security/win_security_invoke_obfuscation_var_services_security.yml
- rules/windows/builtin/security/win_security_invoke_obfuscation_via_var_services_security.yml
- rules/windows/builtin/system/win_system_invoke_obfuscation_stdin_services.yml
- rules/windows/builtin/system/win_system_invoke_obfuscation_var_services.yml
- rules/windows/builtin/system/win_system_invoke_obfuscation_via_stdin_services.yml
- rules/windows/builtin/system/win_system_invoke_obfuscation_via_var_services.yml
- rules/windows/powershell/powershell_script/posh_ps_invoke_dnsexfiltration.yml
- rules/windows/powershell/powershell_script/posh_ps_invoke_nightmare.yml
This PR is a continuation of #3703
Note that I didn't update the PowerShell version of these rules due to the nonlinearity of the `ScriptBlockText` it could generate more FP than we wanted. So I kept it as regex for now.
> fix: update invoke-obfsucation ules to not use regex

- rules/windows/file/file_event/file_event_win_net_cli_artefact.yml
- rules/windows/registry/registry_set/registry_set_net_cli_ngenassemblyusagelog.yml
https://bohops.com/2021/03/16/investigating-net-clr-usage-log-tampering-techniques-for-edr-evasion/
e0b06658-7d1d-4cd3-bf15-03467507ff7c : 
check creation of the log file
28036918-04d3-423d-91c0-55ecf99fb892:
The key do not exist on Windows 10 and 11.
But can not generate a CreateKey event with sysmon or aurora so use the SetValue to trigger an alert
> .NET CLR Usage Log

- rules/windows/powershell/powershell_module/posh_pm_invoke_obfuscation_via_stdin.yml
- rules/windows/powershell/powershell_script/posh_ps_invoke_obfuscation_stdin.yml
- rules/windows/powershell/powershell_script/posh_ps_invoke_obfuscation_via_stdin.yml
- rules/windows/process_creation/proc_creation_win_lolbin_class_exec_xwizard.yml
- rules/windows/process_creation/proc_creation_win_powershell_cmdline_special_characters.yml
I noticed that  `{` was not escaped in some yml `|re` block.
This will cause regex compilation errors in programming languages ​​such as Rust, Java and .NET, So I escaped `{` explicitly.
ref: [Character Escapes in .NET](https://learn.microsoft.com/en-us/dotnet/standard/base-types/character-escapes-in-regular-expressions#character-escapes-in-net)
I would appreciate it if you could review🙏
> fix: explicitly escape `{` to make it clear that it is a literal

- rules/proxy/proxy_ua_bitsadmin_susp_tld.yml
- tests/test_rules.py
This PR adds a new test for a rare case that occurred in internal testing. Where someone adds a link to a rule but misses adding the reference field (See internal discussion for details).
Basically, it makes sure that if a rule doesn't have a `references` field then the description field doesn't contain special keywords used in the references. (Currently the supported keywords are `http://`, `https://` and `Internal Research`)
> feat: new test for special references case

- rules/windows/powershell/powershell_module/posh_pm_invoke_obfuscation_clip.yml
- rules/windows/powershell/powershell_module/posh_pm_invoke_obfuscation_stdin.yml
- rules/windows/powershell/powershell_module/posh_pm_invoke_obfuscation_var.yml
- rules/windows/powershell/powershell_module/posh_pm_invoke_obfuscation_via_var.yml
- rules/windows/powershell/powershell_script/posh_ps_invoke_obfuscation_clip.yml
- rules/windows/powershell/powershell_script/posh_ps_invoke_obfuscation_var.yml
- rules/windows/powershell/powershell_script/posh_ps_invoke_obfuscation_via_var.yml
I noticed some yml `|re` blocks have unneeded escapes like bellow. So I removed unneeded escapes in this PR.
- `\/c`
- `\/r`
- `\"`
- `\-`
Besides in rare cases,  `/`, `-` and `"` should not be escaped and will actually cause parsing errors on some regex libraries when there are unneeded escapes(ref: https://github.com/rust-lang/regex/issues/501#issuecomment-1333797955).
I have also confirmed that the regex which removed unneeded escapes didn't cause compilation errors in the following programming languages.
- Java (v17.0.4.1)
- Node.js (v18.12.1)
- Golang (v1.19)
- PHP (v8.1.111)
- .NET (v7.0.100) 
- Rust (v1.65.0)
- Perl (v5.30.3)
- Python (v3.11)
I would appreciate it if you could review🙏
> refactor: remove unneeded escapes(in `|re` block)

- rules-deprecated/windows/proc_creation_win_office_from_proxy_executing_regsvr32_payload.yml
- rules-deprecated/windows/proc_creation_win_office_from_proxy_executing_regsvr32_payload2.yml
- rules/windows/builtin/bits_client/win_bits_client_susp_domain.yml
- rules/windows/create_stream_hash/create_stream_hash_susp_domain_ext_combo.yml
- rules/windows/create_stream_hash/create_stream_hash_susp_domain_ext_combo_med.yml
- rules/windows/file/file_event/file_event_win_create_non_existent_dlls.yml
- rules/windows/image_load/image_load_side_load_scm.yml
- rules/windows/image_load/image_load_side_load_vmguestlib.yml
- rules/windows/image_load/image_load_susp_dll_load_system_process.yml
- rules/windows/network_connection/net_connection_win_binary_susp_com.yml
- rules/windows/process_creation/proc_creation_win_bitsadmin_download_susp_domain.yml
- rules/windows/process_creation/proc_creation_win_gpg4win_susp_usage.yml
- rules/windows/process_creation/proc_creation_win_office_proxy_exec_wmic.yml
- rules/windows/process_creation/proc_creation_win_tool_nircmd.yml
- rules/windows/process_creation/proc_creation_win_wsudo_susp_execution.yml
- Fixes FP found in testing in the rule `9e9a9002-56c4-40fd-9eff-e4b09bfa5f6c`
- Deprecate both `c0e1c3d5-4381-4f18-8145-2583f06a1fe5` and `9d1c72f5-43f0-4da5-9320-648cf2099dd0` and create new rule `e1693bc8-7168-4eab-8718-cdcaa68a1738`
- Added new rules related to the use of `Wsudo.exe` and `Gpg4win`
- Added new rules related to DLL sideloading (see `Files Changed` section)
- Added more suspicious file-sharing domains the multiple rules (see `Files Changed` section)
> feat: general updates and fixes

- rules/windows/pipe_created/pipe_created_mal_cobaltstrike_re.yml
- rules/windows/powershell/powershell_script/posh_ps_invoke_obfuscation_stdin.yml
I'm sorry I didn't notice it when I made the PR #3744. I have also removed unnecessary escaping, same as #3744.
> refactor: remove unnesessary escape(in |re block)

- rules/windows/builtin/security/win_security_service_installation_by_unusal_client.yml
- rules/windows/builtin/system/win_system_lpe_indicators_tabtip.yml
- rules/windows/builtin/system/win_system_system_service_installation_by_unusal_client.yml
- rules/windows/process_creation/proc_creation_win_susp_wermgr.yml
Fix error find in the workflow.
- proc_creation_win_susp_wermgr.yml had the used `id` than another rule but in uppercase 😄 
- fix integer / string.
> Fix workflow warning

- rules/windows/builtin/security/win_security_susp_scheduled_task_creation.yml
- tests/test_rules.py
This PR aims to fix a bug in the `test_unused_selection` test where if `selections` name is included in the condition. Where not included in the test. 
For example, if you use `sel` as a selection name and a condition of `all of selection_*`. The test will consider `sel` as part of `selection_` and skip it.
The fix removes special keywords from the condition and converts it to a list to do an exact match.
> feat: enhance unused selection test

- rules/application/antivirus/av_hacktool.yml
- rules/windows/builtin/system/win_system_service_install_hacktools.yml
- rules/windows/file/file_event/file_event_win_hivenightmare_file_exports.yml
- rules/windows/image_load/image_load_abusing_azure_browser_sso.yml
- rules/windows/image_load/image_load_susp_python_image_load.yml
- rules/windows/network_connection/net_connection_win_rdp_reverse_tunnel.yml
- rules/windows/network_connection/net_connection_win_rundll32_net_connections.yml
- rules/windows/network_connection/net_connection_win_susp_prog_location_network_connection.yml
- rules/windows/powershell/powershell_script/posh_ps_set_policies_to_unsecure_level.yml
- rules/windows/process_creation/proc_creation_win_apt_hurricane_panda.yml
- rules/windows/process_creation/proc_creation_win_mmc_spawn_shell.yml
- rules/windows/process_creation/proc_creation_win_mshta_spawn_shell.yml
- rules/windows/registry/registry_event/registry_event_mal_flowcloud.yml
- rules/windows/registry/registry_set/registry_set_susp_reg_persist_explorer_run.yml
- tests/test_rules.py
This PR fixes a bug in the test where the usage of a field with `or`/`-` operator inside the selection would skip the test. And one could write single-item lists.
The fix is done by looking if items parsed from the selection are lists or dict. Here is an example
```yml
selection:
- Image|contains:
- '\Users\All Users\'
- '\Users\Default\'
- '\Users\Public\'
- '\Users\Contacts\'
- '\Users\Searches\'
- '\config\systemprofile\'
- '\Windows\Fonts\'
- '\Windows\IME\'
- '\Windows\addins\'
- Image|endswith: '\$Recycle.bin'
- Image|startswith: 'C:\Perflogs\'
```
When this is parsed we get the following
```python
[{'Image|contains': ['\\Users\\All Users\\', '\\Users\\Default\\', '\\Users\\Public\\', '\\Users\\Contacts\\', '\\Users\\Searches\\', '\\config\\systemprofile\\', '\\Windows\\Fonts\\', …
```
> feat: enhance single item lists test

- rules/windows/process_creation/proc_creation_susp_rcedit_execution.yml
Rcedit can be used to modify the properties of an executable like OriginalFileName, Description, and other properties that are used to detect renamed binaries. If one were to search for "how to modify Windows PE OriginalFilename property" this tool pops right up. See https://security.stackexchange.com/questions/210843/is-it-possible-to-change-original-filename-of-an-exe.
> New Rule: Suspicious Use of Rcedit Utility to Alter Executable Metadata

- rules/windows/process_creation/proc_creation_win_service_stop.yml
This service gets stopped during the Logitech LGHUB auto-update process.  Specifically by this process:
```
"CommandLine": "\"C:\\WINDOWS\\TEMP\\lghub_updater.exe\" --uninstall",
```
> Remove Logitech auto-updater false positive

- rules/windows/process_creation/proc_creation_win_susp_cmd.yml
Example log:
2022-12-28 16:39:47 REDACTED Sysmon: 1: Process Create | RuleName=technique_id=T1059,technique_name=Command-Line Interface | UtcTime=2022-12-28 16:39:47.193 | ProcessGuid={9DDBFBCE-7153-63AC-7207-05000000B701} | ProcessId=8172 | Image=C:\Windows\System32\cmd.exe | FileVersion=6.3.9600.17415 (winblue_r4.141028-1500) | Description=Windows Command Processor | Company=Microsoft Corporation | OriginalFileName=Cmd.Exe | OriginalCommandLine=C:\Windows\system32\cmd.exe /c handle.exe /accepteula -s -p 1988 2&gt; nul | CommandLine=C:\Windows\system32\cmd.exe /c handle.exe /accepteula -s -p 1988 2&gt; nul | CurrentDirectory=E:\Working Share\rmqcluster_service\ | User=NT AUTHORITY\SYSTEM | LogonGuid={9DDBFBCE-92AD-639E-E703-000000000000} | LogonId=0x3e7 | TerminalSessionId=0 | …
> FP: filters out erl.exe running handle.exe with elevated privileges

- rules/windows/process_creation/proc_creation_win_lolbin_runexehelper.yml
- rules/windows/process_creation/proc_creation_win_lolbin_ssh.yml
- rules/windows/process_creation/proc_creation_win_lolbin_unregmp2.yml
Missing rules for OSBinaries lolbin
- Runexehelper.yml (LOLBAS\yml\OSBinaries)
- Ssh.yml (LOLBAS\yml\OSBinaries)
- Unregmp2.yml (LOLBAS\yml\OSBinaries)
> Add missing lolbin OSBinaries

- rules/windows/powershell/powershell_script/posh_ps_token_obfuscation.yml
- rules/windows/process_creation/proc_creation_win_powershell_token_obfuscation.yml
Thanks to this project, we currently use many sigma rules in [Hayabusa](https://github.com/Yamato-Security/hayabusa), Thank you very much :)
- related PR: https://github.com/SigmaHQ/sigma/pull/3825
I found some `|re` blocks have unneeded escapes as follows. So I removed unneeded escapes.
- `"` (double quote)
- No escaping is required **as a regex**(May be needed **as an escape for String literals**)
- ` (backquote)
- No escaping is required **as a regex**
I also found that the required escaping was not present. So I added escapes.
- `{` (left curly bracket)
- `}` (right curly bracket)
Most programming languages(`JavaScript`,`PHP`,`Python`...etc) ​​implicitly resolve it, but these regexes cause compile errors in strict language like `Java` and `Rust`. 
I'd appreciate it if you could fix …
> refactor: regex escapes in `|re` block(`{`, `}`, `"`, `backquote`)

- rules/windows/process_creation/proc_creation_win_lolbin_diantz_ads.yml
- rules/windows/process_creation/proc_creation_win_lolbin_extrac32_ads.yml
- rules/windows/process_creation/proc_creation_win_regedit_import_keys.yml
- rules/windows/process_creation/proc_creation_win_regedit_import_keys_ads.yml
- rules/windows/process_creation/proc_creation_win_regini.yml
- rules/windows/process_creation/proc_creation_win_regini_ads.yml
I noticed that  some rule(`|re` block) has unneeded `\`(backslash) in the character class, so I removed it.
In this case the unneeded backslash doesn't affect the matching process, but I fixed it to make the regex more readable.
Related commit: https://github.com/SigmaHQ/sigma/commit/143744bc128b8de17f74b7a5c50ccf4a06cb9a5a
FIY: https://docs.python.org/3/library/re.html
I would appreciate it if you could review.
Regards.
> refactor: remove unneeded backslash escape in character class(in `|re` block)

- rules/windows/pipe_created/pipe_created_mal_cobaltstrike_re.yml
- rules/windows/process_access/proc_access_win_cobaltstrike_bof_injection_pattern.yml
Hello, Thank you so much for your prompt response :)
It seems that some rule for cobaltstrike intended to detect **single** backslash(not double backslash), so I fixed it.
ref: 
https://labs.withsecure.com/publications/detecting-cobalt-strike-default-modules-via-named-pipe-analysis
https://medium.com/falconforce/falconfriday-direct-system-calls-and-cobalt-strike-bofs-0xff14-741fa8e1bdd6
I would appreciate it if you could review.
Regards.
> fix: remove unneeded double backslash escape

- rules/windows/powershell/powershell_module/posh_pm_invoke_obfuscation_obfuscated_iex.yml
- rules/windows/powershell/powershell_script/posh_ps_invoke_obfuscation_obfuscated_iex.yml
- rules/windows/process_creation/proc_creation_win_invoke_obfuscation_obfuscated_iex_commandline.yml
Thank you for all your hard work in 2022 :)
I fixed an incorrect backslash-escaped regex that may have been intended to simply escape an asterisk(to not act as a quantifier).
I would appreciate it if you could review.
Regards.
> fix: remove incorrect backslash escape(in `|re` block)

- tests/test_rules.py
This PR addresses two little challenges with the `test_rules` unittest.
1. At the moment the stix Tags are only available if the test_rules.py is executed by python (__main__) but isn't set if run as `python3 -m unittest test_rules` causing
```
python3 -m unittest TestRules    
E
======================================================================
ERROR: TestRules (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: TestRules
Traceback (most recent call last):
File "/usr/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
module = __import__(module_name)
ModuleNotFoundError: No module named 'TestRules'
```
Solving it by executing the get_*_data() function as part of the unittest - …
> Rule test enhancements

- rules/windows/powershell/powershell_script/posh_ps_susp_set_alias.yml
I have downgradre my first rule to low because : 
- if I make it too strict I will only capture this script not the technique
- If I make to lacy  I will get mamy FP.
Script Block Logging get all the script. To be effective I need only a log of the set-alias execution.
> Add posh_ps_susp_set_alias

- tests/test_rules.py
- tools/config/thor.yml
This PR:
- Fixes an edge case in the `test_duplicate_detections` test. Where if a keyword rule uses the same selection name no field name. The YAML parser returns a `list` instead of `dict` which breaks the test.
- It also adds a new condition where if the log source is different we don't need to check for a duplicate because we assume that a different log source indicates a "new" rule.
- It introduces a new test specifically for `thor.yml` configuration. Where it checks if Windows event log sources start with the `WinEventLog:` keyword
> feat: test enhancements

- rules/windows/file/file_event/file_event_win_susp_adsi_cache_usage.yml
example:
```
2023-01-12 03:13:39 REDACTED Sysmon: 11: File created | RuleName=technique_id=T1047,technique_name=File System Permissions Weakness | UtcTime=2023-01-12 03:13:39.362 | ProcessGuid={86DC4549-5DD6-63BF-0B01-000000004F00} | ProcessId=9632 | Image=D:\Program Files\Citrix\Receiver StoreFront\Services\DefaultDomainServices\Citrix.DeliveryServices.DomainServices.ServiceHost.exe | TargetFilename=C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Microsoft\Windows\SchCache\REDACTED.com.sch | CreationUtcTime=2020-02-10 19:10:04.049 | User=NT AUTHORITY\NETWORK SERVICE | pid=2620 | level=29 | sys_version=2 | category=File created (rule: FileCreate) | op=Info | Microsoft-Windows-Sysmon/Operational=true | key=0x8000000000000000 | id=21360087 | app="C:\Windows\sysmon64.exe" | tid=8576 …
```
> FP: citrix receiver storefront

- rules/cloud/okta/okta_admin_role_assignment_created.yml
Hey,
There is an option under Okta to create a new Admin Role Assignment and then assign it to a user/group.
This event type should be monitored/hunted because if you are monitoring for specific admin role assignments or specific high-privileged groups, you can miss it.
> Add new rule to detect a new admin role assignment in Okta

- rules/windows/process_creation/proc_creation_win_ads_stored_dll_execution_rundll32.yml
This rule will detect the execution of DLL's using Rundll32 stored in ADS
> ADS stored DLL execution using Rundll32

- rules/linux/builtin/auth/lnx_auth_pwnkit_local_privilege_escalation.yml
- rules/linux/builtin/lnx_nimbuspwn_privilege_escalation_exploit.yml
- rules/network/cisco/bgp/cisco_bgp_md5_auth_failed.yml
- rules/network/huawei/bgp/huawei_bgp_auth_failed.yml
- rules/network/juniper/bgp/juniper_bgp_missing_md5.yml
- rules/windows/builtin/msexchange/win_exchange_proxylogon_oabvirtualdir.yml
- rules/windows/builtin/msexchange/win_exchange_proxyshell_certificate_generation.yml
- rules/windows/builtin/msexchange/win_exchange_proxyshell_remove_mailbox_export.yml
- rules/windows/builtin/msexchange/win_exchange_set_oabvirtualdirectory_externalurl.yml
When a Sigma rule writer wants to create a list of values where all of them must be matched for the rule to trigger, the approach used previously was to have an `all of` condition for a single selector. However, this has now changed, and the new approach is to use an empty key and the |all modifier (i.e., `'|all'`).
This commit (tries to) identify all the rules that used the old approach and modifies them to use the new approach instead.
See SigmaHQ/sigma-specification#53 for further discussion.
> Change rules using all of required-lists to |all

- tools/sigma/backends/limacharlie.py
Expand rules supported for LimaCharlie:
- Windows DNS Queries
- Linux Process Creation (enhanced support)
- Linux File Events
- macOS File Events
Also: fixing a bug in the evaluation of some regular expressions.
> Expand rule support and bug fix for LimaCharlie

- rules/windows/builtin/security/win_security_successful_external_remote_rdp_login.yml
- rules/windows/builtin/security/win_security_successful_external_remote_smb_login.yml
- rules/windows/builtin/security/win_security_successful_external_remote_svc_login.yml
- tests/test_rules.py
Inspired by Dray Agha's recent [post](https://twitter.com/Purp1eW0lf/status/1616144561965002752) about publicly-exposed sensitive ports allowing successful logins. I believe successful login events from public IPs, with logon type of 3 or 10, and an Account Name populated, will be of interest to defenders. I checked the existing rules repository and didn't see a rule covering this activity.
Thanks for considering this! All the best.
> Added external remote service logon from public IP rule.

- tests/test_rules.py
A issue in the pySigma ES Backend throw up some rules that contained unwanted / unneeded re escapes.
(Reference: https://github.com/SigmaHQ/pySigma-backend-elasticsearch/issues/9)
@fukusuket already fixed the rules and this PR should ensure that they won't come back without knowledge.
> Test: Check 're' rules against unwanted/unneeded escapes

- rules/windows/process_creation/proc_creation_win_office_onenote_susp_child_processes.yml
Slight reoranization of the rule with an additional relevant reference.
Additionally adds the `filter_common_childproc` filter to `proc_creation_win_susp_microsoft_onenote_child_process.yml` for common processes that are launched from OneNote. OneNote will commonly launch `Teams.exe -Embedding` for opening documents in Teams, as well as `FileCoAuth.exe -Embedding` when people are sharing/editing specific documents through OneNote.
For some organizations these can create enough noise that it may be warranted to filter out as a part of the rule. Thusfar malicious execution for `Teams.exe` and `FileCoAuth.exe` have not been observed.
> Add common childprocess filter for OneNote

- rules/windows/process_creation/proc_creation_win_cmd_read_contents.yml
The trailing space causes this rule not to trigger when the extension is used (cmd.exe), eg: 
CommandLine: "C:\Windows\system32\cmd.exe" /r < "C:\Users\Administrator\desktop\test.txt"
> Remove Trailing space

- rules/windows/process_creation/proc_creation_win_powershell_base64_iex.yml
Added IEX strings without spaces as I saw it was not detecting this (originally base64 encoded):
`$XX=IEX(('[' + [char]0x53 + 'ystem.Text.Enc' + [char]0x6f + 'ding]::A' + [char]0x53 + 'CII.Get' + [char]0x53 + 'tring([' + [char]0x53 + 'ystem.C' + [char]0x6f + 'nvert]::Fr' + [char]0x6f + 'mBase6' + [char]0x34 + '' + [char]0x53 + 'tring((get-c' + [char]0x6f + 'ntent -path ''c:\wind' + [char]0x6f + 'ws\temp\picture.jpg'')))'));$BB=IEX(('start-sleep 10;$s=$XX;$d = @();$v = 0;$c = 0;while($c -ne $s.length){$v=($v*52)+([Int32][char]$s[$c]-' + [char]0x34 + '0);if((($c+1)%3) -eq 0){while($v -ne 0){$vv=$v%256;if($vv -gt 0){$d+=[char][Int32]$vv}$v=[Int32]($v/256)}}$c+=1;};[array]::Reverse($d);IEX([' + [char]0x53 + 'tring]::J' + [char]0x6f + 'in('''',$d));;'));IEX($BB)`
> added other potential IEX strings

- tools/sigma/parser/modifiers/transform.py
`sigmac` conversion failed with a rule which has `base64offset|contains`, so I fixed it.
Explicitly define `valid_input_types = NodeSubexpression` in `SigmaContainsModifier` class.
- Because `SigmaBase64OffsetModifier` return `NodeSubexpression`,
- then following validation failed if `SigmaContainsModifier` class not define `valid_input_types = NodeSubexpression`
- https://github.com/SigmaHQ/sigma/blob/0.22/tools/sigma/parser/modifiers/base.py#L44-L52
- Fixed https://github.com/SigmaHQ/sigma/issues/4063
> fix: sigmac conversion error with `base64offset|contains` rule

- rules/windows/builtin/system/win_system_invoke_obfuscation_clip_services.yml
[Updated wrong value of ImagePath]
[it was "clip" that is already covered by "clipboard]::".
Real value is "&&" .]
**N/A**
**Reference: 
Sigma Rule Id: 4edf51e1-cb83-4e1a-bc39-800e396068e3 Link: [Invoke-Obfuscation CLIP+ Launcher - Security](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/security/win_security_invoke_obfuscation_clip_services_security.yml)**
> fix: One value of imagePath was wrong

- rules-unsupported/dns_query_win_possible_dns_rebinding.yml
- rules-unsupported/image_load_mimikatz_inmemory_detection.yml
- rules-unsupported/posh_ps_cl_invocation_lolscript_count.yml
- rules-unsupported/posh_ps_cl_mutexverifiers_lolscript_count.yml
- rules-unsupported/proc_creation_win_correlation_apt_silence_downloader_v3.yml
- rules-unsupported/proc_creation_win_correlation_apt_turla_commands_medium.yml
- rules-unsupported/proc_creation_win_correlation_dnscat2_powershell_implementation.yml
- rules-unsupported/proc_creation_win_correlation_multiple_susp_cli.yml
- rules-unsupported/proc_creation_win_correlation_susp_builtin_commands_recon.yml
- rules-unsupported/win_security_global_catalog_enumeration.yml
- rules-unsupported/win_security_rare_schtasks_creations.yml
- rules-unsupported/win_security_susp_failed_logons_explicit_credentials.yml
- rules-unsupported/win_security_susp_failed_logons_single_source.yml
- rules-unsupported/win_security_susp_failed_logons_single_source2.yml
- rules-unsupported/win_security_susp_failed_remote_logons_single_source.yml
- rules-unsupported/win_security_susp_multiple_files_renamed_or_deleted.yml
- rules-unsupported/win_security_susp_samr_pwset.yml
- rules-unsupported/win_susp_failed_hidden_share_mount.yml
- rules-unsupported/win_system_rare_service_installs.yml
- rules-unsupported/win_taskscheduler_rare_schtask_creation.yml
This PR changes the status of rules using the old SIGMAC pipe notation (correlation) to `unsupported`
While the new correlation engine is still in dev the old pipe notation is considered as a deprecated feature and it's discouraged to contribute new rules using. By setting the rest of the rules using these notations future PRs will no longer accept rules using this but instead, defer to the new correlation.
N/A
N/A
> chore: update pipe-notation rules status to unsupported

- rules/windows/builtin/firewall_as/win_firewall_as_add_rule_susp_folder.yml
Add a simple rule from app.any.run sandox 
Cover the result of the commandline
`netsh  advfirewall firewall add rule name="Z0BAZwxx" dir=in action=allow program="C:\Users\admin\AppData\Roaming\Z0BAZwxx\nypezi.exe"`
```xml
<EventData>
<Data Name="RuleId">{5A12AFB7-AEB7-46D5-A609-919D98079CA4}</Data> 
<Data Name="RuleName">Z0BAZwxx</Data> 
<Data Name="Origin">1</Data> 
<Data Name="ApplicationPath">C:\Users\admin\AppData\Roaming\Z0BAZwxx\nypezi.exe</Data> 
<Data Name="ServiceName" /> 
<Data Name="Direction">1</Data> 
<Data Name="Protocol">256</Data> 
<Data Name="LocalPorts" /> 
<Data Name="RemotePorts" /> 
<Data Name="Action">3</Data> 
<Data Name="Profiles">2147483647</Data> 
<Data Name="LocalAddresses">*</Data> 
<Data Name="RemoteAddresses">*</Data> 
<Data …
```
> Add win_firewall_as_add_rule_susp_folder

- rules/windows/create_remote_thread/create_remote_thread_win_susp_remote_thread_source.yml
Fix FP found in testing environment
TargetImage field not available
```
RULE_TITLE: Suspicious Remote Thread Source
RULE_AUTHOR: Perez Diego (@darkquassar), oscd.community
RULE_DESCRIPTION: "Offensive tradecraft is switching away from using APIs like \"CreateRemoteThread\", however, this is still largely observed in the wild.\nThis rule aims to detect suspicious processes (those we would not expect to behave in this way like word.exe or outlook.exe) creating remote threads on other processes.\nIt is a generalistic rule, but it should have a low FP ratio due to the selected range of processes.\n"
RULE_FALSEPOSITIVES: Unknown
RULE_ID: 66d31e5f-52d6-40a4-9615-002d3789a119
RULE_LEVEL: high
RULE_MODIFIED: 2022/12/14
RULE_PATH: 2\957.yms
RULE_REFERENCES:
- Personal research
- Statistical …
```
> fix: FP found in testing environment

- rules/windows/builtin/msexchange/win_exchange_proxyshell_mailbox_export.yml
This PR fixes an issue found with the rule `516376b4-05cd-4122-bae0-ad7641c38d48`
When updating the aforementioned rule in #3646 a typo/misunderstanding of the logic occurred where the condition now is broken. This PR rolls back the condition to a working state as it was intended in the original commit https://github.com/SigmaHQ/sigma/commit/1c919c07c77fccd8999825735ec2fe878122d4bf
N/A
Fixes #4083
> chore: rollback previous state of the rule

- rules/windows/process_creation/proc_creation_win_renamed_binary_highly_relevant.yml
Reg.exe for Qakbot defense evasion.
Renamed reg.exe was used by Qakbot to import reg keys.
https://github.com/pr0xylife/Qakbot/blob/main/Qakbot_BB17_28.02.2023.txt 
`xcopy  C:\Windows\\\\\\system32\\\\\\reg.exe C:\Users\Admin\AppData\Local\Temp\glanduleHoratory.exe /h /s /e`
Tested on 52B sysmon events and no false positives. 
> Add reg.exe to 'Potential Defense Evasion Via Rename Of Highly Relevant Binaries'

- rules-deprecated/windows/proc_creation_win_renamed_psexec.yml
Thank you so much for maintaining rules, I found a typo and fixed it :)
Fixed typo in rule `status` field.
- `depreactaed` -> `deprecated`
None
None
None
None
> fix :`deprecated` status typo

- Pipfile.lock
Upgrade the Pytest library to the latest version which removes their dependency on py. Also as a side note `py` library can't be upgraded as it's already using the latest version
N/A
N/A
N/A
> chore: update pipfile.lock

- rules/windows/builtin/security/win_security_susp_failed_logons_single_process.yml
- rules/windows/builtin/security/win_security_susp_failed_logons_single_source_kerberos.yml
- rules/windows/builtin/security/win_security_susp_failed_logons_single_source_kerberos2.yml
- rules/windows/builtin/security/win_security_susp_failed_logons_single_source_kerberos3.yml
- rules/windows/builtin/security/win_security_susp_failed_logons_single_source_ntlm.yml
- rules/windows/builtin/security/win_security_susp_failed_logons_single_source_ntlm2.yml
This PR changes multi-line condition statements to a single line for maximum compatibility with backends.
For some reason, several sigma rules that use `count` put the condition statement on the next line. Example:
```
condition: 
- selection1 and not filter | count(TargetUserName) by ProcessName > 10
```
This causes parsing errors for certain backends. 
In my limited testing, it works as a single line with and even without single quotes.  I decided to add single quotes just in case.
Example: `condition: 'selection1 and not filter | count(TargetUserName) by ProcessName > 10'`
N/A
This will get rid of parsing errors for some backends.
- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigma …
> moved multi-line condition to single line for rules that use `count`

- rules/windows/builtin/security/win_security_successful_external_remote_rdp_login.yml
- rules/windows/builtin/security/win_security_successful_external_remote_smb_login.yml
These two rules were giving false positives so I fixed them.
There are many cases where `IpAddress: '-'` but `SubjectUserName` does not equal `-` so I removed the `SubjectUserName: '-'` part in order to get rid of false positives.
I also have never seen `'0:0:0:0:0:0:0:1'` being used so I deleted that.
As well as the source IP address should not be coming from a multicast address so I deleted `224.0.0.0/4` as well.
> Fix FPs on CIDR rules

- tools/sigma/backends/mdatp.py
> Adding in integrity level for Microsoft Defender backend

- tools/sigma/backends/elasticsearch.py
- tools/sigma/parser/modifiers/base.py
- tools/sigma/parser/modifiers/mixins.py
- tools/sigma/parser/modifiers/transform.py
- tools/sigma/parser/rule.py
This Pull Request aims to fix some issues due to type check:
- Add recursive type check for list values
- Update apply_list to avoid returning None if value is bytes
In base **SigmaModifier** class the **validate** function does not work recursively.
**SigmaContainsModifier** only accept list, tuple or string but it will accept list values containing integer, resulting in processed data containing None in **apply_list**.
So the first goal of this PR is to prevent that from happening, by checking type of the value recursively.
Furthermore, in the **apply_list** method of **ListOrStringModifierMixin** class, list of bytes will result in a call of **apply_list** on a byte object. This call will return None as the instance check is only made on list, tuple, NodeSubexpression, ConditionOR and …
> Add recursive type check to avoid having illegal types inside of a list

- rules/linux/process_creation/proc_creation_lnx_system_network_discovery.yml
Split selection clause into two. Both filters in the same selection would require seeing `/etc/resolv.conf` and `ifconfig` within the same process creation.
The filters are in an array which _may_ be a lesser known feature in Sigma to make OR'ed statements within the same selection, but it is definitely less readable this way. If this is not a logic fix, it would definitely be a readability one.
N/A
N/A
N/A
> Split selection clause into two

- rules/cloud/okta/okta_password_in_alternateid_field.yml
- tests/test_rules.py
Add a Sigma rule to detect Okta passwords potentially appearing in log files
Per [this blog post](https://www.mitiga.io/blog/how-okta-passwords-can-be-compromised-uncovering-a-risk-to-user-data) from Mitiga, Okta passwords may be accidentally entered into the username field of Okta, and in doing so, will cause the password to be retained in log files. This rule attempts to detect such occurrences.
Pretty printed for readability, with some anonymisation of irrelevant details such as IPs, IDs, location, etc.
```json
{
"actor" : {
"alternateId" : "T3stingMitig4Valid!",
"displayName" : "unknown",
"id" : "unknown",
"type" : "User"
},
"authenticationContext" : {
"externalSessionId" : "unknown"
},
"client" : {
"device" : "Computer",
"geographicalContext" : {
"city" : "London",
"country" : "GB", …
```
> Misentered Okta password logged in alternateId vulnerability

- rules-unsupported/windows/driver_load_invoke_obfuscation_via_stdin_services.yml
I noticed that  `{` was not escaped in some yml `|re` block.
This will cause regex compilation errors in programming languages ​​such as Rust, Java and .NET, So I escaped `{` explicitly.
ref: [Character Escapes in .NET](https://learn.microsoft.com/en-us/dotnet/standard/base-types/character-escapes-in-regular-expressions#character-escapes-in-net)
I've created a PR for a similar fix before, but I overlooked it then :( 
- #3737
- #3837
I understand that the status of this rule is unsupported...
but I thought it would be better if it was a valid regex, so I created a PR. I'd appreciate it if you could fix them.
Regards.
> fix: explicitly escape `{` to make it clear that it is a literal 

- deprecated/windows/proc_creation_win_lolbin_rdrleakdiag.yml
- rules/windows/process_creation/proc_creation_win_lolbin_rdrleakdiag.yml
- rules/windows/process_creation/proc_creation_win_rdrleakdiag_process_dumping.yml
Modified rule to detect every possible way of rdrleakdiag execution while process dumping
The pre-existing rule only detects if  rdrleakdiag.exe is executed as similar to this command
'rdrleakdiag.exe /p 832 /o c:\evil /fullmemdmp /wait 1'.
Same intended action could be performed by any of the command as given below:
1. rdrleakdiag.exe -p 832 -o c:\evil -fullmemdmp -wait 1
2. rdrleakdiag.exe -p 832 /o c:\evil /fullmemdmp -wait 1 (combination of both '-' and '/')
These commands cannot be detected by this rule. So, modifying the rule.
N/A
N/A
> Modified rule to detect every possible way of rdrleakdiag execution

- rules/web/webserver_generic/web_cve_2021_26858_iis_rce.yml
@is3ka1 and I noticed a weird behavior from this rule. And after digging deeper, we found that
when using `all of` in condition, it works differently for map and list in sigma and sigmac.
In this file, the `all of` will be translated to `OR` but it should be `AND`.
Use `"|all"` fixes this.
Ref:
- https://github.com/SigmaHQ/sigma/pull/3952
- https://github.com/SigmaHQ/sigma-specification/discussions/53
Use `"|all"` in `keywords` and remove `all of` from `condition`.
> fix web_cve_2021_26858_iis_rce.yml (all of -> "|all")

- rules/windows/process_creation/proc_creation_win_mstsc_run_local_rdp_file.yml
- rules/windows/process_creation/proc_creation_win_mstsc_run_local_rdp_file_susp_location.yml
I noticed a typo when creating a query conversion script for [Hayabusa](https://github.com/Yamato-Security/hayabusa), so I fixed it.
- rules/windows/process_creation/proc_creation_win_mstsc_run_local_rdp_file.yml
-  Deleted `value-modifier(endswith)` in `Search-Identifier`
- rules/windows/process_creation/proc_creation_win_mstsc_run_local_rdp_file_susp_location.yml
-  Fixed comment typo 
The following commit seems to be the cause.
- https://github.com/SigmaHQ/sigma/commit/83e352c52e45f15e6b9461f6a0f465f9fdbf60b2
My understanding is that a `Search-Identifier` should not have a `value-modifier` according to [sigma-specification doc](https://github.com/SigmaHQ/sigma-specification/blob/main/Sigma_specification.md#value-modifiers).
(I'm sorry if I misunderstood the specification.)
N/A
N/A
- If …
> fix: delete value-modifier in Search-Identifier

- deprecated/windows/powershell_suspicious_invocation_specific.yml
- rules/linux/auditd/lnx_auditd_binary_padding.yml
- rules/linux/auditd/lnx_auditd_find_cred_in_files.yml
- rules/windows/builtin/msexchange/win_exchange_proxyshell_mailbox_export.yml
- rules/windows/builtin/system/microsoft_windows_kernel_general/win_system_susp_sam_dump.yml
Changed to use `'|all'` instead of `all of kewords` to make rules more maintainable
The related issue and discussion are below.
- https://github.com/SigmaHQ/sigma-specification/discussions/53
- https://github.com/SigmaHQ/sigma/pull/3952
N/A
N/A
Thanks for maintaining the rules :)
Regards.
> refactor: use `'|all'` instead of using `all of` for a single selector.

- rules-emerging-threats/2023/TA/3CX-Supply-Chain/proxy_malware_3cx_compromise_c2_beacon_activity.yml
- rules/web/proxy_generic/proxy_apt40.yml
- rules/web/proxy_generic/proxy_download_susp_dyndns.yml
- rules/web/proxy_generic/proxy_download_susp_tlds_blacklist.yml
- rules/web/proxy_generic/proxy_download_susp_tlds_whitelist.yml
- rules/web/proxy_generic/proxy_telegram_api.yml
- rules/web/proxy_generic/proxy_ua_bitsadmin_susp_tld.yml
Current rule filters on r-dns which is not suitable for proxy logs where cs-host is standard.
In current production environment I'm in we map r-dns and cs-host do different fields which causes false positives as r-dns is empty for all our proxy logs
Nothing to add.
> Update proxy_ua_bitsadmin_susp_tld.yml to use proxy field

- rules/windows/powershell/powershell_script/posh_ps_export_certificate.yml
- rules/windows/powershell/powershell_script/posh_ps_susp_export_pfxcertificate.yml
- rules/windows/process_creation/proc_creation_win_powershell_export_certificate.yml
This PR updates the "Suspicious Export-PfxCertificate" based on Splunks research here: https://www.splunk.com/en_us/blog/security/breaking-the-chain-defending-against-certificate-services-abuse.html
I updated the rule to also look for the keyword `Export-Certificate`
I changed the rule title as the rule just seems to look match on when certificates are being exported and is not checking for any keywords that would make it inherently suspicious but feel free to change back.
> update "Suspicious Export-PfxCertificate" rule

- rules-placeholder/windows/win_failed_dns_zone_transfer.yml
- rules/windows/builtin/dns_server/win_dns_server_failed_dns_zone_transfer.yml
New Windows rule to detect failed DNS zone transfer.
no further comments.
```
<System>
<Provider Name="Microsoft-Windows-DNS-Server-Service" Guid="{71a551f5-c893-4849-886b-b5ec8502641e}" /> 
<EventID>6004</EventID> 
<Version>0</Version> 
<Level>3</Level> 
<Task>0</Task> 
<Opcode>0</Opcode> 
<Keywords>0x8000000000080000</Keywords> 
<TimeCreated SystemTime="2020-07-11T12:58:57.4510620Z" /> 
<EventRecordID>343</EventRecordID> 
<Correlation /> 
<Execution ProcessID="1764" ThreadID="2284" /> 
<Channel>DNS Server</Channel> 
<Computer>rootdc1.offsec.lan</Computer> 
<Security UserID="S-1-5-18" /> 
</System>
<EventData Name="DNS_EVENT_BAD_ZONE_TRANSFER_REQUEST">
<Data Name="param1">10.23.23.9</Data> 
<Data …
```
> New rule: Failed DNS Zone Transfer

- rules/windows/registry/registry_set/registry_set_persistence_globalflags.yml
Corrected the detection condition/logic for registry persistence technique using the GlobalFlags and SilentProcessExit Keys
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v GlobalFlag /t REG_DWORD /d 512
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SilentProcessExit\notepad.exe" /v ReportingMode /t REG_DWORD /d 1
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SilentProcessExit\notepad.exe" /v MonitorProcess /d "C:\temp\evil.exe"
The pre-existing rule is wrong because it cannot detect these commands due to logical flaw in the condition. 
N/A
N/A
- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_convent …
> Corrected the detection condition/logic for registry persistence technique

- rules/application/rpc_firewall/rpc_firewall_atsvc_lateral_movement.yml
- rules/application/rpc_firewall/rpc_firewall_atsvc_recon.yml
- rules/application/rpc_firewall/rpc_firewall_dcsync_attack.yml
- rules/application/rpc_firewall/rpc_firewall_efs_abuse.yml
- rules/application/rpc_firewall/rpc_firewall_eventlog_recon.yml
- rules/application/rpc_firewall/rpc_firewall_itaskschedulerservice_lateral_movement.yml
- rules/application/rpc_firewall/rpc_firewall_itaskschedulerservice_recon.yml
- rules/application/rpc_firewall/rpc_firewall_printing_lateral_movement.yml
- rules/application/rpc_firewall/rpc_firewall_remote_dcom_or_wmi.yml
- rules/application/rpc_firewall/rpc_firewall_remote_registry_lateral_movement.yml
- rules/application/rpc_firewall/rpc_firewall_remote_registry_recon.yml
- rules/application/rpc_firewall/rpc_firewall_remote_server_service_abuse.yml
- rules/application/rpc_firewall/rpc_firewall_remote_service_lateral_movement.yml
- rules/application/rpc_firewall/rpc_firewall_sasec_lateral_movement.yml
- rules/application/rpc_firewall/rpc_firewall_sasec_recon.yml
- rules/application/rpc_firewall/rpc_firewall_sharphound_recon_account.yml
- rules/application/rpc_firewall/rpc_firewall_sharphound_recon_sessions.yml
Fixes Zero Networks Blog 404s
It appears that the Zero Networks blog switched from using underscores to dashes in their URLs. This PR updates the blog links so they are no longer 404s.
N/A
N/A
> Fix Zero Networks Blog 404s

- rules-emerging-threats/2022/Exploits/CVE-2022-21554/proc_creation_win_exploit_cve_2023_21554_queuejumper.yml
- rules-emerging-threats/2022/Exploits/CVE-2022-41120/proc_creation_win_exploit_cve_2022_41120_sysmon_eop.yml
fix 2 rules that used 'tag' instead of 'tags'
change tag -> tags in the following rules:
- rules-emerging-threats/2022/Exploits/CVE-2022-21554/proc_creation_win_exploit_cve_2023_21554_queuejumper.yml
- rules-emerging-threats/2022/Exploits/CVE-2022-41120/proc_creation_win_exploit_cve_2022_41120_sysmon_eop.yml
n/a
n/a
> Fix typos: tag -> tags

- README.md
Add [alterix](https://github.com/mtnmunuklu/alterix) to Projects or Products that use Sigma
This pull request adds [alterix](https://github.com/mtnmunuklu/alterix) to the list of projects or products that use Sigma. `alterix` is a tool that converts sigma rules to the query format of the crypttech next generation siem product.
N/A
N/A
N/A
> Add alterix to Projects or Products that use Sigma

- rules/cloud/aws/aws_iam_s3browser_templated_s3_bucket_policy_creation.yml
Adding Sigma rules outlined in the following blog post associated with named cloud-focused threat actor p0-LUCR-1 (aka GUI-vil): https://permiso.io/blog/s/unmasking-guivil-new-cloud-threat-actor
Detects S3 Browser utility creating Inline IAM Policy containing default S3 bucket name placeholder value of <YOUR-BUCKET-NAME>.
Example requestParameters value from iam:PutUserPolicy event in CloudTrail logs:
{
"userName": "FileBackupAccount",
"policyName": "dq",
"policyDocument": "{\\r\\n  \\"Statement\\": [\\r\\n    {\\r\\n      \\"Effect\\": \\"Allow\\",\\r\\n      \\"Action\\": \\"s3:GetObject\\",\\r\\n      \\"Resource\\": \\"arn:aws:s3:::<YOUR-BUCKET-NAME>/*\\",\\r\\n      \\"Condition\\": {}\\r\\n    }\\r\\n  ]\\r\\n}"
}
N/A
- If your PR adds new rules, please consider following and …
> Permiso p0-LUCR-1 (aka GUI-vil)

- rules/windows/powershell/powershell_classic/posh_pc_abuse_nslookup_with_dns_records.yml
- rules/windows/powershell/powershell_classic/posh_pc_alternate_powershell_hosts.yml
- rules/windows/powershell/powershell_classic/posh_pc_delete_volume_shadow_copies.yml
- rules/windows/powershell/powershell_classic/posh_pc_downgrade_attack.yml
- rules/windows/powershell/powershell_classic/posh_pc_exe_calling_ps.yml
- rules/windows/powershell/powershell_classic/posh_pc_powercat.yml
- rules/windows/powershell/powershell_classic/posh_pc_remote_powershell_session.yml
- rules/windows/powershell/powershell_classic/posh_pc_renamed_powershell.yml
- rules/windows/powershell/powershell_classic/posh_pc_susp_download.yml
- rules/windows/powershell/powershell_classic/posh_pc_susp_get_nettcpconnection.yml
- rules/windows/powershell/powershell_classic/posh_pc_susp_zip_compress.yml
- rules/windows/powershell/powershell_classic/posh_pc_tamper_windows_defender_set_mp.yml
- rules/windows/powershell/powershell_classic/posh_pc_wsman_com_provider_no_powershell.yml
- rules/windows/powershell/powershell_classic/posh_pc_xor_commandline.yml
Changed detection rules in `PowerShell Classic` to refer original `Data` fields instead of extracted specific fields. 
Please see the discussion below for more information on the background behind this PR.
https://github.com/SigmaHQ/sigma/discussions/4510
~~If there are no problems with the changes in this PR, I will also modify the `Task Scheduler` detection rules in another PR.~~
(↑Sorry, the Task scheduler event log fields was defined in XML.)
I would appreciate it if you could review.
update: Suspicious XOR Encoded PowerShell Command Line - PowerShell
update: Uncommon PowerShell Hosts
update: Delete Volume Shadow Copies Via WMI With PowerShell
update: PowerShell Downgrade Attack - PowerShell
update: PowerShell Called from an Executable Version Mismatch
update: Netcat The Powershell …
> update: use original `Data` field instead of specific PowerShell Classic log's extracted field

- rules/windows/process_creation/proc_creation_win_susp_obfuscated_ip_download.yml
Removed unnecessary `Lookahead` regular expressions.
I think this rule will not be hit in most cases because of the `(?!.)` at the end. So I removed `(?!.)` What do you think?
(If you want to clearly indicate that there is no character (other than a newline), I think `$` would be fine?)
I'm sorry if I misunderstood the intent of this regular expression...
update: Obfuscated IP Download Activity
N/A
N/A
> update: remove `Lookahead` regular expressions

- rules-emerging-threats/2023/TA/Lace-Tempest/README.md
- rules-emerging-threats/2023/TA/Lace-Tempest/file_event_win_apt_lace_tempest_indicators.yml
- rules-emerging-threats/2023/TA/Lace-Tempest/posh_ps_apt_lace_tempest_eraser_script.yml
- rules-emerging-threats/2023/TA/Lace-Tempest/posh_ps_apt_lace_tempest_malware_launcher.yml
- rules-emerging-threats/2023/TA/Lace-Tempest/posh_ps_apt_lace_tempest_powershell_launcher.yml
- rules-emerging-threats/2023/TA/Lace-Tempest/proc_creation_win_apt_lace_tempest_cobalt_strike_download.yml
- rules-emerging-threats/2023/TA/Lace-Tempest/proc_creation_win_apt_lace_tempest_loader_execution.yml
- rules/windows/process_creation/proc_creation_win_java_susp_child_process.yml
- rules/windows/process_creation/proc_creation_win_java_susp_child_process_2.yml
- rules/windows/process_creation/proc_creation_win_webshell_chopper.yml
- rules/windows/process_creation/proc_creation_win_webshell_hacking.yml
- rules/windows/process_creation/proc_creation_win_webshell_recon_commands_and_processes.yml
- rules/windows/process_creation/proc_creation_win_webshell_susp_process_spawned_from_webserver.yml
- rules/windows/process_creation/proc_creation_win_webshell_tool_recon.yml
This PR adds new ET rules related to Lace Tempest exploitation of SysAid CVE-2023-47246. It also updates multiple webshell rules
new: Lace Tempest File Indicators
new: Lace Tempest PowerShell Evidence Eraser
new: Lace Tempest PowerShell Launcher
new: Lace Tempest Cobalt Strike Download
new: Lace Tempest Malware Loader Execution
update: Suspicious Processes Spawned by Java.EXE - Enhance process coverage by adding new processes and removing unrelated ones
update: Webshell Detection With Command Line Keywords - Enhance process coverage by adding new processes and removing unrelated ones
update: Suspicious Process By Web Server Process - Enhance process coverage by adding new processes and removing unrelated ones
N/A
N/A
- If your PR adds new rules, please consider following and applying …
> New ET Rules - Lace Tempest / SysAid CVE-2023-47246 Exploitation

- rules-emerging-threats/2017/Malware/NotPetya/proc_creation_win_malware_notpetya.yml
- rules-threat-hunting/windows/builtin/security/win_security_scheduled_task_deletion.yml
- rules-threat-hunting/windows/create_remote_thread/create_remote_thread_win_powershell_generic.yml
- rules-threat-hunting/windows/file/file_event/file_event_win_scheduled_task_creation.yml
- rules-threat-hunting/windows/image_load/image_load_dll_system_drawing_load.yml
- rules-threat-hunting/windows/registry/registry_event/registry_event_scheduled_task_creation.yml
- rules/windows/builtin/security/win_security_iso_mount.yml
- rules/windows/create_remote_thread/create_remote_thread_win_powershell_susp_targets.yml
- rules/windows/file/file_event/file_event_win_creation_system_file.yml
- rules/windows/image_load/image_load_wmi_module_load_by_uncommon_process.yml
- rules/windows/process_access/proc_access_win_invoke_patchingapi.yml
- rules/windows/process_creation/proc_creation_win_gpg4win_portable_execution.yml
- rules/windows/process_creation/proc_creation_win_susp_bad_opsec_sacrificial_processes.yml
- rules/windows/process_creation/proc_creation_win_whoami_susp_flags.yml
- rules/windows/process_creation/proc_creation_win_wmiprvse_susp_child_processes.yml
This PR tune multiple rules for FPs found in testing
fix: Bad Opsec Defaults Sacrificial Processes With Improper Arguments - Enhance filter to account for an FP found with MS edge
fix: Files With System Process Name In Unsuspected Locations - Enhance filter to cover other folder variation for windows recovery
fix: Portable Gpg.EXE Execution - Add new legitimate location for GNuGpg
fix: Suspicious WmiPrvSE Child Process - Add a filter for msiexec image used to install new MSI packages via WMI process
update: ISO Image Mounted - Update title and add new filter
update: Potential NT API Stub Patching - Enhance the selection coverage by removing the "C:" prefix to cover other installation possibilities
update: Remote Thread Creation Via PowerShell - Update selection to use endswith modifier …
> Fix FP Found In Testing

- rules/windows/process_creation/proc_creation_win_webshell_susp_process_spawned_from_webserver.yml
Fixes rule parsing error.
Hayabusa and probably other backends cannot parse this rule because it has an extra unneeded asterisk in the condition so I changed it to a single asterisk.
> Rule parse error fix: remove extra asterisk

- rules/windows/process_creation/proc_creation_win_excel_dcom_lateral_movement.yml
- rules/windows/process_creation/proc_creation_win_office_excel_dcom_lateral_movement.yml
This rule is intended to detect suspicious child processes of Excel which could be an indicator of lateral movement leveraging an Excel DCOM object.
new:	 Potential Excel.EXE DCOM Lateral Movement Via ActivateMicrosoftApp
N/A 
N/A 
> Possible Excel DCOM Lateral Movement

- .github/workflows/greetings.yml
- rules/windows/builtin/security/account_management/win_security_access_token_abuse.yml
- rules/windows/pipe_created/pipe_created_hktl_cobaltstrike_susp_pipe_patterns.yml
- rules/windows/powershell/powershell_script/posh_ps_get_acl_service.yml
- rules/windows/process_creation/proc_creation_win_hktl_cobaltstrike_bloopers_cmd.yml
- rules/windows/process_creation/proc_creation_win_pua_adfind_susp_usage.yml
- rules/windows/process_creation/proc_creation_win_schtasks_creation.yml
- tests/sigma_cli_conf.yml
- tests/test_rules.py
Update tests to pySigma 0.10.9 and tag the first rules with the new tagging scheme STP.
chore: update tests to pySigma 0.10.9
chore: add Summiting the Pyramid v1.0.0 tags
N/A
N/A
> chore: Update tests to pySigma 0.10.9

- rules-emerging-threats/2021/TA/HAFNIUM/proc_creation_win_apt_hafnium.yml
- rules-emerging-threats/2021/TA/HAFNIUM/web_exchange_exploitation_hafnium.yml
- rules-emerging-threats/2023/TA/EquationGroup/net_dns_apt_equation_group_triangulation_c2_coms.yml
- rules-emerging-threats/2023/TA/EquationGroup/proxy_apt_equation_group_triangulation_c2_coms.yml
- rules-emerging-threats/2023/TA/FIN7/file_event_win_apt_fin7_powershell_scripts_naming_convention.yml
- rules-emerging-threats/2023/TA/FIN7/posh_ps_apt_fin7_powerhold.yml
- rules-emerging-threats/2023/TA/FIN7/posh_ps_apt_fin7_powertrash_execution.yml
- rules-emerging-threats/2023/TA/FIN7/proc_creation_win_apt_fin7_powertrash_lateral_movement.yml
- rules-emerging-threats/2023/TA/Lazarus/image_load_apt_lazarus_side_load_activity.yml
- rules-emerging-threats/2023/TA/Mustang-Panda-Australia-Campaign/proc_creation_win_apt_mustang_panda_indicators.yml
Add ATT&CK group tags to some of the emerging threats rules
update: Exchange Exploitation Used by HAFNIUM - Add related ATT&CK group tag
update: Potential Operation Triangulation C2 Beaconing Activity - DNS - Add related ATT&CK group tag
update : Potential Operation Triangulation C2 Beaconing Activity - Proxy - Add related ATT&CK group tag
update : Potential POWERTRASH Script Execution - Add related ATT&CK group tag
update : Potential APT FIN7 Related PowerShell Script Created - Add related ATT&CK group tag
update : Potential APT FIN7 POWERHOLD Execution - Add related ATT&CK group tag
update : Potential APT Mustang Panda Activity Against Australian Gov - Add related ATT&CK group tag
update : Potential APT FIN7 Reconnaissance/POWERTRASH Related Activity - Add related ATT&CK group tag
N/A …
> Add ATT&CK Group Tag For Some Emerging Threats Rules

- rules/windows/process_creation/proc_creation_win_browsers_chromium_load_extension.yml
- rules/windows/process_creation/proc_creation_win_browsers_chromium_susp_load_extension.yml
Scope for this rule is too narrow. By limiting the parent processes, you're missing out on important chrome browser extensions. For example, Silver's CursedChrome would pass right through as would BurpSuite's chrome extension.
~~Instead the ParentImage is moved to the `fields` as it is interesting and important for the analyst, but should not narrow the scope of the search.~~
Fro this a lower severity rule that disregard the parent is created.
new: Chromium Browser Instance Executed With Custom Extension
update: Suspicious Chromium Browser Instance Executed With Custom Extension - Fix typo in the rule title and description
`CommandLine= *load-extension=c:\Users\<>\AppData\Roaming\BurpSuite\burp=chromium-extension chrome://newtab`
N/A
- If your PR adds new rules, please consider following …
> New Rule: Generic Chrome Extension Rule With A Widened Scope

- rules/windows/image_load/image_load_dll_rstrtmgr_susp_load.yml
- rules/windows/image_load/image_load_dll_rstrtmgr_suspicious_load.yml
- rules/windows/image_load/image_load_dll_rstrtmgr_uncommon_load.yml
Adds a new rule concerning the load of the library RstrtMgr.dll, seen used by ransomwares, and more recently in a wiper.
> The Restart Manager enables processes to release the locks on targeted files by terminating processes that are using them if required conditions are met. However, this mechanism can be hijacked to serve malicious purposes. [crowdstrike.com](https://www.crowdstrike.com/blog/windows-restart-manager-part-1/)
new: Load Of RstrtMgr DLL From Suspicious Process
new: Load Of RstrtMgr.DLL By An Uncommon Process
False positive example (here installing vscode), filtered out in the yaml.
```xml
<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'>
<System>
<Provider Name='Microsoft-Windows-Sysmon' Guid='{5770385f-c22a-43e0-bf4c-06f5698ffbd9}'/> …
```
> New Rule : Load Of RstrtMgr DLL From Suspicious Process

- rules-emerging-threats/2023/TA/Mint-Sandstorm/proc_creation_win_apt_mint_sandstorm_log4j_wstomcat_execution.yml
The MSTIC [reference](https://www.microsoft.com/en-us/security/blog/2023/04/18/nation-state-threat-actor-mint-sandstorm-refines-tradecraft-to-attack-high-value-targets/) provides the following KQL query for **Log4J Wstomcat Process Execution**:
```
DeviceProcessEvents
| where InitiatingProcessFileName has "ws_tomcatservice.exe" and FileName !in~("repadmin.exe")
```
The current version of c97c625-0350-4f0a-8943-f6cadc88125e treats the `!in~` operator as an `in~` operator, causing the rule to trigger on false positive events:
```yaml
detection:
selection:
ParentImage|endswith: '\ws_tomcatservice.exe'
Image|endswith: '\repadmin.exe'
```
This PR changes it to the following:
```yaml
detection:
selection:
ParentImage|endswith: '\ws_tomcatservice.exe'
filter:
Image|endswith: …
```
> Fix `Mint Sandstorm - Log4J Wstomcat Process Execution` Condition

- rules/linux/process_creation/proc_creation_lnx_dd_process_injection.yml
This commit adds a new experimental rule that attempts to detect process injection by utilizing the dd command to inject malicious code in the process memory under /proc/mem example provided in this project https://github.com/AonCyberLabs/Cexigua/blob/master/overwrite.sh
new: Potential Linux Process Code Injection Via DD Utility
`dd if=payload.bin of=/proc/${PID}/mem`
N/A
> Create Rule to detect Linux Process Code Injection

- rules-placeholder/cloud/azure/azure_ad_account_created_deleted_nonapproved_user.yml
- rules-placeholder/cloud/azure/azure_ad_account_signin_outside_hours.yml
- rules-placeholder/cloud/azure/azure_privileged_account_no_saw_paw.yml
- rules-placeholder/cloud/azure/azure_privileged_account_sigin_expected_controls.yml
- rules-placeholder/cloud/azure/azure_privileged_account_signin_outside_hours.yml
- rules-placeholder/windows/builtin/security/win_security_exploit_cve_2020_1472.yml
- rules-placeholder/windows/builtin/security/win_security_potential_pass_the_hash.yml
- rules-placeholder/windows/builtin/security/win_security_remote_registry_management_via_reg.yml
- rules-placeholder/windows/builtin/security/win_security_susp_interactive_logons.yml
The rules in `rules-placeholder` directory do not contain the `expand` modifier.
The `expand` modifier is added to the fields that has a placeholder string value, for example `'%ServerSystems%'`. The only exception is [this one](https://github.com/SigmaHQ/sigma/blob/426ff8c4126cd7ada94b00724dc5517f9b179da5/rules-placeholder/windows/process_creation/proc_creation_win_userdomain_variable_enumeration.yml#L18-L20), where it is actually a Windows env-var, not a Sigma placeholder per se.
update: Account Created And Deleted By Non Approved Users - Add missing `expand` modifier
update: Authentication Occuring Outside Normal Business Hours - Add missing `expand` modifier
update: Privilege Role Elevation Not Occuring on SAW or PAW - Add missing `expand` modifier
update: Privilege Role Sign-In …
> Use `expand` modifier to tranform placeholders

- rules/windows/pipe_created/pipe_created_hktl_efspotato.yml
Added exclusion for pipe naming that starts with \pipe\*, an example of FP https://github.com/emoacht/Monitorian where the pipe name is \pipe\LOCAL\Monitorian. We keep detection of *\pipe\*, but excluding ^\pipe\*
fix: HackTool - EfsPotato Named Pipe Creation - Add exclusion for pipe names starting with `\pipe\`
```
Pipe Created:
RuleName: -
EventType: CreatePipe
UtcTime: 2023-12-19 02:59:29.816
ProcessGuid: {773bac78-0711-6581-6e19-000000000600}
ProcessId: 17972
PipeName: \pipe\LOCAL\Monitorian
Image: C:\Program Files\WindowsApps\10186emoacht.Monitorian_4.6.0.0_neutral__0q7myvhtpbc7w\MonitorianPlus\MonitorianPlus.exe
User: LAB\user1"
```
N/A
- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigm …
> Filtering FP in pipe_created_hktl_efspotato.yml

- documentation/tools/sigma-logsource-checker.py
This PR fixes issue #4666 -`documentations/tools/sugma-logsource-checker.py` tries to read in non-yaml files and breaks.
chore: add additional checks to the `sigma-logsource-checker.py` so that it only cares about yaml files
N/A
Fixes #4666 
> Fixes #4666 - sigma-logsource-checker tries to parse non-yml files

- deprecated/windows/image_load_side_load_svchost_dlls.yml
- rules/windows/file/file_event/file_event_win_create_non_existent_dlls.yml
- rules/windows/image_load/image_load_side_load_from_non_system_location.yml
- rules/windows/image_load/image_load_side_load_non_existent_dlls.yml
- rules/windows/powershell/powershell_classic/posh_pc_remote_powershell_session.yml
- rules/windows/process_creation/proc_creation_win_sdbinst_susp_extension.yml
- rules/windows/registry/registry_set/registry_set_deviceguard_hypervisorenforcedcodeintegrity_disabled.yml
- rules/windows/registry/registry_set/registry_set_persistence_app_cpmpat_layer_registerapprestart.yml
This PR adds a new rule covering a new persistence technique using the `RegisterAppRestart` AppCompat layer
new: Potential Persistence Via AppCompat RegisterAppRestart Layer
update:  Uncommon Extension Shim Database Installation Via Sdbinst.EXE - Add additional commandline flag that might trigger FPs
update: Hypervisor Enforced Code Integrity Disabled - Add additional path for the HVCI config
update: Creation Of Non-Existent System DLL - Remove driver anchor and the `System32` filter. The reason behind this is that an attacker can copy the file elsewhere and then use a system utility such as copy or xcopy located in the system32 folder to create it again. Which will bypass the rule.
update: Potential System DLL Sideloading From Non System Locations - Remove the driver anchor from the …
> Add Rule Covering New Persistence Technique Using RegisterAppRestart AppCompat Layer

- rules/windows/registry/registry_set/registry_set_terminal_server_tampering.yml
This PR adds two registry keys for the `SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\`registry path that are enabled as part of DarkGate malware. The two keys are:
- DisableSecuritySettings
- DisableRemoteDesktopAntiAlias
update: RDP Sensitive Settings Changed - Add `DisableRemoteDesktopAntiAlias` and `DisableSecuritySettings` as seen used by DarkGate malware
N/A
N/A
> Added RDP reg keys for darkgate malware

- rules/windows/builtin/security/win_security_external_device.yml
- rules/windows/builtin/system/service_control_manager/win_system_service_install_uncommon.yml
1st: Filter condition was still startswith after removing c in last commit but it should also be changed to contains.
2nd: Event 6416 also included deviceDescription, so i updated the event condition
update: External Disk Drive Or USB Storage Device Was Recognized By The System - Update selection to reflect the logic correctly
fix: Uncommon Service Installation Image Path - Update filter logic to use correct modifiers
N/A
N/A
> Update rule condition

- rules/cloud/github/github_push_protection_bypass_detected.yml
- rules/cloud/github/github_push_protection_disabled.yml
- rules/cloud/github/github_secret_scanning_feature_disabled.yml
The Github enterprise keeps on releasing new security features targeting sensitive information (secrets) and now the push protection feature is turned on by default for all public repositories. This pull includes detection rules around these security features.
Ref: 
1. https://thehackernews.com/2024/03/github-rolls-out-default-secret.html
2. https://docs.github.com/en/code-security/secret-scanning/push-protection-for-repositories-and-organizations
3. https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning
new: Github Push Protection Bypass Detected
new: Github Push Protection Disabled
new: Github Secret Scanning Feature Disabled
N/A
N/A …
> Github New Rules for Secret Scanning and Push Protection Features

- rules/windows/image_load/image_load_susp_unsigned_dll.yml
- rules/windows/process_creation/proc_creation_win_powershell_dll_execution.yml
- rules/windows/process_creation/proc_creation_win_susp_powershell_execution_via_dll.yml
This PR aims to add a few images to two rules that involve loading DLLs with relevant images:
LOLBAS references related to "Unsigned DLL Loaded by windows utilities":
- https://lolbas-project.github.io/lolbas/Binaries/Installutil/
- https://lolbas-project.github.io/lolbas/Binaries/Regasm/
- https://lolbas-project.github.io/lolbas/Binaries/Regsvcs/
Reference for update: Potential PowerShell Execution Via DLL - add regsvr32.exe:
- https://github.com/p3nt4/PowerShdll
update: Unsigned DLL Loaded by Windows Utility - Add InstallUtil, RegAsm and RegSvcs as additional process and add additional "null" and "empty" filters to cover for non available fields.
update: Potential PowerShell Execution Via DLL - Add regsvr32 to increase coverage.
N/A
N/A
- If your PR adds new rules, please consider …
> Update two rules involving loading of DLLs with Windows utilities

- rules/windows/process_creation/proc_creation_win_hktl_coercedpotato.yml
- rules/windows/process_creation/proc_creation_win_hktl_handlekatz.yml
- rules/windows/process_creation/proc_creation_win_hktl_sysmoneop.yml
Since `Hashes` contains several hashes, it is necessary to use the `contains` modifier.
update: HackTool - CoercedPotato Execution - Update `Hashes` field to use `contains` modifier
update: HackTool - HandleKatz LSASS Dumper Execution - Update `Hashes` field to use `contains` modifier
update: HackTool - SysmonEOP Execution - Update `Hashes` field to use `contains` modifier
> Fix hashes

- rules/cloud/aws/cloudtrail/aws_update_login_profile.yml
In deploying [this rule](https://github.com/SigmaHQ/sigma/blob/master/rules/cloud/aws/cloudtrail/aws_update_login_profile.yml), the Grafana SecOps team discovered that the `contains` modifier does not reference the field that this rule is trying to reference. Instead, we discovered that there is another modifier in `pySigma` that will enable field referencing which is called [`fieldref`](https://github.com/SigmaHQ/pySigma/blob/main/sigma/modifiers.py#L358) which enables us to update [pySigma-backend-loki](https://github.com/grafana/pySigma-backend-loki/pull/137) to reflect this modifier.
update: AWS User Login Profile Was Modified - use `fieldref` instead of `contains` modifier
An (abridged) event we want to match on:
```json
{"eventName": "UpdateLoginProfile", "userIdentity": {"arn": …
```
> Update AWS Rule to use fieldref modifier instead of contains

- rules/windows/image_load/image_load_side_load_keyscrambler.yml
- rules/windows/process_creation/proc_creation_win_keyscrambler_susp_child_process.yml
KeyScrambler suspicious child process
new: Potentially Suspicious Child Process Of KeyScrambler.exe
```
{
"EventTime": "2024-04-15T11:14:18.365386+00:00",
"Hostname": "ACME",
"Keywords": "9223372036854775808",
"LevelValue": 4,
"EventType": "INFO",
"SeverityValue": 2,
"Severity": "INFO",
"EventID": 1,
"SourceName": "Microsoft-Windows-Sysmon",
"ProviderGuid": "{5770385F-C22A-43E0-BF4C-06F5698FFBD9}",
"Version": 5,
"TaskValue": 1,
"OpcoACMEalue": 0,
"RecordNumber": 6952439,
"ExecutionProcessID": 3472,
"ExecutionThreadID": 4260,
"Channel": "Microsoft-Windows-Sysmon/Operational",
"Domain": "NT AUTHORITY",
"AccountName": "SYSTEM",
"UserID": "S-1-5-18",
"AccountType": "User",
"Message": "Process Create:\r\nRuleName: -\r\nUtcTime: 2024-04-15 11:14:18.364\r\nProcessGuid: …
```
> Suspicious keyscrambler child process

- rules/windows/process_creation/proc_creation_win_csc_susp_dynamic_compilation.yml
- rules/windows/process_creation/proc_creation_win_csc_susp_parent.yml
Just adding a bracket to the regex
fix: Dynamic .NET Compilation Via Csc.EXE - small regex fix
fix: Csc.EXE Execution Form Potentially Suspicious Parent - small regex fix
> Minor fix for rule regex

- rules/windows/powershell/powershell_classic/posh_pc_delete_volume_shadow_copies.yml
- rules/windows/powershell/powershell_script/posh_ps_create_volume_shadow_copy.yml
- rules/windows/powershell/powershell_script/posh_ps_susp_win32_shadowcopy.yml
- rules/windows/powershell/powershell_script/posh_ps_susp_win32_shadowcopy_deletion.yml
- rules/windows/process_creation/proc_creation_win_powershell_base64_wmi_classes.yml
- rules/windows/process_creation/proc_creation_win_powershell_shadowcopy_deletion.yml
"Win32_ShadowCopy" is more correct and it is important when rule is transformed in case-sensitive mode.
>  fix: casing of `Win32_ShadowCopy`

- rules/macos/process_creation/proc_creation_macos_sysctl_discovery.yml
Added a new rule to detect execution of `sysctl` on macOS. 
- `sysctl` can be used to gather interesting macOS host data, including hardware information, memory size, logical cpu information, etc. 
- It has been used in the past by threat actors to determine whether the target macOS host is running on a physical or virtual machine and also for system information discovery.
Example Usage in the wild: 
new: System Information Discovery Via Sysctl - MacOS
> New Rule: proc_creation_macos_sysctl_discovery.yml

- rules/linux/network_connection/net_connection_lnx_domain_localtonet_tunnel.yml
- rules/linux/network_connection/net_connection_lnx_localtonet_tunnel.yml
- rules/windows/network_connection/net_connection_win_domain_localtonet_tunnel.yml
Adds analytics to detect tunneling through the [LocaltoNet](https://localtonet.com/documents) service.
LocaltoNet is a legitimate reverse proxy application that _may_ enable threat actors to perform tactics incl. enabling command-and-control and exfil. Similar to Ngrok. 
A recent campaign includes https://cloud.google.com/blog/topics/threat-intelligence/unc3944-targets-saas-applications
- new: Communication To LocaltoNet Tunneling Service Initiated
- new: Communication To LocaltoNet Tunneling Service Initiated - Linux
Install locally via https://localtonet.com/documents. Generates network event id (Sysmon 3 / 5156). Can alternative be captured by DNS-lookup or Proxy logs (http tunneling, not all protocols).
> New Analytics: LocaltoNet tunneling

- rules-threat-hunting/windows/image_load/image_load_office_word_wll_load.yml
- tests/sigma_cli_conf.yml
A new rule was added to be able to detect Microsoft Office Word Add-In image loads in order to detect initial access or persistence of a threat actor.
new: Microsoft Word Add-In Loaded
N/A
N/A
> Added Rule - Microsoft Office Word Add-In Load (WLL)

- rules-placeholder/windows/process_creation/proc_creation_win_userdomain_variable_enumeration.yml
All of the other placeholder rules use the `|expand` modifier except this one so I figured it was overlooked and added it.
fix: Userdomain Variable Enumeration
> added expand modifier to placeholder rule

- rules/macos/process_creation/proc_creation_macos_hdiutil_create.yml
- rules/macos/process_creation/proc_creation_macos_hdiutil_mount.yml
- rules/macos/process_creation/proc_creation_macos_susp_hdiutil_mount.yml
Thie PR adds the detection of `hdiutil` on macOS, which is used for mounting DMG files and creating DMG files to store exfiltrated data.  For example, the command /usr/bin/hdiutil attach `/tmp/bitget-0.0.7 (1).dmg` will mount to `/Volumes/bitget-0.0.7/`. Notably referenced in the  [Sentinelone IoC Section](https://www.sentinelone.com/blog/from-the-front-lines-unsigned-macos-orat-malware-gambles-for-the-win/) and the [loobins](https://www.loobins.io/binaries/hdiutil/) project.
new:	Disk Image Mounting Via Hdiutil - MacOS
new: Disk Image Creation Via Hdiutil - MacOS
N/A
N/A
> Add Rule: proc_creation_macos_susp_hdiutil_mount.yml

- rules/windows/powershell/powershell_script/posh_ps_token_obfuscation.yml
- rules/windows/process_creation/proc_creation_win_powershell_token_obfuscation.yml
Since lookahead(and lookbehind) regex are not supported in Golang or Rust,
I replaced the lookahead regex with simple `contains` logic as follows.
- before(lookahead regex): <code>(?=.*`)</code>
- after(contains logic):  <code>|contains: '`'</code>
FYI: https://github.com/SigmaHQ/sigma/pull/4526
I think it's difficult to support regex for all languages...,
but I think it might be better to use more supported regex as much as possible.
fix: Powershell Token Obfuscation - Powershell - Changed to not use Lookahead regex
fix: Powershell Token Obfuscation - Process Creation - Changed to not use Lookahead regex
N/A
https://go.dev/play/p/YjkmggquHlV
- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigm …
> Changed to not use `Lookahead` regex

- rules/windows/file/file_delete/file_delete_win_delete_own_image.yml
Add a rule to detect Windows binaries deleting themselves.
new: Process Deletion of Its Own Executable
`AURORA: Notice MODULE: Sigma MESSAGE: Sigma match found RULE_TITLE: Process Deleted i
ts Own Executable RULE_AUTHOR: Max Altgelt RULE_DESCRIPTION: Detects deletion of a process's own executable by itself. This is usually not possible without workarounds and may be used by malware to hide its own traces. RULE_FALSEPOSITIVES:  RULE_ID: f01d1f70-cd41-42ec-9c0b-26dd9c22bf29 RULE_LEVEL: medium RULE_MODIFIED: 2024-09-03 RULE_PATH: correlation.yml RULE_REFERENCES: https://github.com/joaoviictorti/RustRedOps/tree/main/Self_Deletion RULE_SIGTYPE: custom COMMANDLINE: "\"C:\\Users\\Max\\Downloads\\deleteself2.exe\"" COMPUTER: DESKTOP-EEM5B52 CORRELATION_ACTIVITYID: …
> feat: check for processes deleting themselves

- rules/windows/builtin/security/win_security_gp_priv_escalation.yml
- rules/windows/builtin/security/win_security_susp_group_policy_abuse_privilege_addition.yml
Detects the first occurrence of a modification to Group Policy Object Attributes to add privileges to user accounts or use them to add users as local admins.
https://www.elastic.co/guide/en/security/current/group-policy-abuse-for-privilege-addition.html#_setup_275
new: Group Policy Abuse for Privilege Addition
N/A
N/A
> New Rule: win_security_gp_priv_escalation.yml

- rules/windows/network_connection/net_connection_win_btunnels_communication.yml
- rules/windows/network_connection/net_connection_win_domain_btunnels.yml
Similar to DevTunnels and CloudFlared, this tool can also be used for Data Exfiltration and for downloading malicious binaries as well as for C2 communications. 
I have written a research article on the same and adding detection rule into the Sigma repo. 
https://defr0ggy.github.io/research/Utilizing-BTunnel-For-Data-Exfiltration/
> BTunnels Detection for Data Exfiltration

- rules/linux/process_creation/proc_creation_lnx_susp_hktl_execution.yml
- rules/linux/process_creation/proc_creation_lnx_susp_network_utilities_execution.yml
Remove the dual use tool nmap from "Linux HackTool Execution". It's also already covered in "Linux Network Service Scanning Tools Execution" which has the right level for it. Just adding the missing `zenmap` there.
Remove the dual use tool nmap from "Linux HackTool Execution". It's also already covered in "Linux Network Service Scanning Tools Execution" which has the right level for it. Just adding the missing `zenmap` there.
update: Linux HackTool Execution - Remove "zenmap" and "nmap" as they are already covered by 3e102cd9-a70d-4a7a-9508-403963092f31
update: Linux Network Service Scanning Tools Execution - Add "zenmap" utility
N/A
> remove the dual use tool nmap from "Linux HackTool Execution"

- rules/windows/process_creation/proc_creation_win_susp_jwt_token_search.yml
- rules/windows/process_creation/proc_creation_win_susp_office_token_search.yml
Added the string  `eyJhbGciOi` corresponding to `{"alg":` from the JWT token header.
update: Potentially Suspicious JWT Token Search Via CLI - added the `eyJhbGciOi` string, corresponding to `{"alg":` from the JWT token header.
N/A
> Added the string corresponding to "{"alg":" since some token headers start with this

- rules/windows/file/file_event/file_event_win_lsass_default_dump_file_names.yml
Add new patterns for RustiveDump and NativeDump to an old rule. (and a bug fix in the nanodump pattern selection)
update: LSASS Process Memory Dump Files - add new dump pattern for RustiveDump and NativeDump, and exchanged "startswith" with "contains" modifier for better coverage
I exchanged the "startswith" modifier with the "contains" modifier, because the "TargetFileName" field usually contains the full path and not just the filename. 
Therefore "startswith: nanodump" would always be wrong. 
> add: RustiveDump, NativeDump pattern, fix: NanoDump pattern

- rules/windows/process_creation/proc_creation_win_susp_system_user_anomaly.yml
Filter false positives with Google Updater uninstall script running ping.exe to wait
fix: Suspicious SYSTEM User Process Creation - filter false positives with Google Updater uninstall script
```
ProcessId: 5420 Image: C:\Windows\SysWOW64\PING.EXE FileVersion: 10.0.22000.2360 (WinBuild.160101.0800) Description: TCP/IP Ping Command Product: Microsoft® Windows® Operating System Company: Microsoft Corporation OriginalFileName: ping.exe CommandLine: ping -n 2 127.0.0.1 CurrentDirectory: C:\Windows\system32\ User: NT AUTHORITY\SYSTEM LogonGuid: {70ca0443-1b1e-66c3-e703-000000000000} LogonId: 0x3e7 TerminalSessionId: 0 IntegrityLevel: System Hashes: MD5=82E8450A1FA4F2D027C1A90726C3BA39,SHA256=E444CAAC62A336207A93AE8547327EC97C66BA092AE3B1DD87E84B499C35E42F,IMPHASH=497E84B252F5A68B5DC294926603C72 …
```
> fix: FPs with Google Updater Uninstall Script

- rules/windows/file/file_event/file_event_win_susp_right_to_left_override_extension_spoofing.yml
- rules/windows/file/file_event/file_event_win_susp_rtlo_extension_spoofing.yml
Add rule for RTLO extension spoofing, MITRE T1036.002
Detect interactions with files abusing the Right-To-Left Unicode extension spoofing technique.
The rule uses patterns of commonly spoofed extensions.
Example of a spoofed extension:
`Pandora%20Resou%E2%80%AEnls..scr`
The typical structure includes two dots (..) after the reversed extension, followed by the spoofed extension.
For shorter more common patterns we use two dots in front of the reversed extension to avoid potential false positivies.
new: Potential File Extension Spoofing Using Right-to-Left Override
> Detect RTLO extension spoofing, MITRE T1036.002 in File-Events

- rules/linux/auditd/lnx_auditd_user_discovery.yml
Adversaries may use the information from System Owner/User Discovery during automated discovery to shape follow-on behaviors.
update: System Owner or User Discovery - Linux - Add 4 additional tools that can be used for host and user discovery: "whoami", "hostname", "id", "last"
> Add new binaries

- rules/windows/process_creation/proc_creation_win_rundll32_susp_shellexec_execution.yml
- rules/windows/process_creation/proc_creation_win_rundll32_susp_shellexec_ordinal_execution.yml
Adversaries have been observed leveraging the ordinal number of the ShellExec_RunDLL function in the shell32.dll library instead of explicitly using the function name (ShellExec_RunDLL). This technique bypasses this current detection, which rely solely on the function name, enabling execution of arbitrary system binaries such as cmd.exe or powershell.exe.
new: Suspicious ShellExec_RunDLL Call Via Ordinal
https://github.com/user-attachments/assets/5e87360d-aef3-4e7b-9087-292b6d6503ed
> Added ordinal of ShellExec_RunDLL

- rules/windows/registry/registry_event/registry_event_net_ntlm_downgrade.yml
False positives with values and security upgrades
fix: false positives with NetNTLM Downgrade Attack
We see this in Sysmon events: 
```
TargetObject: HKLM\\System\\CurrentControlSet\\Control\\Lsa\\lmcompatibilitylevel Details: DWORD (0x00000005)
```
I think we can fix this by providing the problematic values: 0, 1, 2
But, we also see this: 
```
Image: C:\WINDOWS\system32\services.exe TargetObject: HKLM\System\CurrentControlSet\Control\Lsa\MSV1_0\ntlmminclientsec Details: DWORD (0x20080000)
```
So, the value for this key is much harder to handle. I currently don't know how. 
Options:
- Exclude the `ntlmminclientsec` value from the selection
- Add a false positive note …
> fix: FPs with NetNTLM downgrade attack

- rules/cloud/aws/cloudtrail/aws_rds_dbcluster_actions.yml
Detects modifications to an RDS cluster or the deletion of an RDS cluster. These actions could be part of a data exfiltration attempt or unauthorized exposure of sensitive data.
```
{ [-]
awsCloud_account_ID: 123
awsRegion: sa-east
cwlGroupname: aws-controltower/CloudTrailLogs
eventCategory: Management
eventID: 123
eventName: ModifyDBCluster
eventSource: rds.amazonaws.com
eventTime: 2024-09-18T15:29:09Z
eventType: AwsApiCall
eventVersion: 1.08
managementEvent: true
readOnly: false
recipientAccountId: 123
requestID: 123
requestParameters: { [+]
}
responseElements: { [+]
}
sourceIPAddress: XXX
tlsDetails: { [+]
}
userAgent: APN/1.0 HashiCorp/
userIdentity: { [+]
}
}
```
```
{ [-]
awsCloud_account_ID: 123
awsRegion: sa-east
cwlGroupname: aws-controltower/CloudTrailLogs
eventCategory: …
```
> Modify or Delete AWS RDS Cluster

- rules/cloud/aws/cloudtrail/aws_delete_saml.yml
- rules/cloud/aws/cloudtrail/aws_delete_saml_provider.yml
Monitoring DeleteSAMLProvider events separately from UpdateSAMLProvider makes sense, since these actions have different contexts, risks, and consequences. Tracking both types of events allows you to more fully control changes in the configuration of SAML providers and respond faster to potential threats.
```
{ [-]
awsCloud_account_ID: XXXX
awsRegion: us-east-1
cwlGroupname: aws-controltower/CloudTrailLogs
eventCategory: Management
eventID: 6b09429c
eventName: DeleteSAMLProvider
status:success
eventSource: iam.amazonaws.com
eventTime: 2024-09-12T07:53:45Z
eventType: AwsApiCall
eventVersion: 1.09
managementEvent: true
readOnly: false
recipientAccountId: XXXX
requestID: f082cd90
requestParameters: { [-]
sAMLProviderArn: arn:aws:iam::XXXX:saml-provider/AWSSSO_XXXX_DO_NOT_DELETE
} …
```
> DeleteSAMLProvider AWS

- rules/windows/builtin/application/Other/win_av_relevant_match.yml
- rules/windows/builtin/appxdeployment_server/win_appxdeployment_server_uncommon_package_locations.yml
- rules/windows/builtin/bits_client/win_bits_client_new_transfer_via_uncommon_tld.yml
- rules/windows/builtin/code_integrity/win_codeintegrity_attempted_dll_load.yml
Proposing fixes for multiple rules where normal legitimate events caused hundreds of false positives per system.
Update to following rules:
- **Relevant Anti-Virus Signature Keywords In Application Log**
- Slightly chaning a filter to match a correct antivirus detection name.
- **Uncommon AppX Package Locations**
- Adding more FP filters.
- **BITS Transfer Job With Uncommon Or Suspicious Remote TLD**
- Adding more filters.
- **CodeIntegrity - Unmet Signing Level Requirements By File Under Validation**
- Adding more filters.
**Relevant Anti-Virus Signature Keywords In Application Log**
HTool detected inside
(Boolean enableAttac**hTool**)
According to VirusTotal, vendor that use HTool in their naming have these variants:
- **HTool-**
- **/HTool**
- **.HTool**
Examples:
Win64.HToolMimiKatz …
> FP filters for legitimate events

- rules/windows/dns_query/dns_query_win_remote_access_software_domains_non_browsers.yml
- rules/windows/powershell/powershell_classic/posh_pc_renamed_powershell.yml
- rules/windows/powershell/powershell_classic/posh_pc_wsman_com_provider_no_powershell.yml
Hi,
Proposing a regex fix for following rules:
1. 30a8cb77-8eb3-4cfb-8e79-ad457c5a4592
2. df9a0e0e-fedb-4d6c-8668-d765dfc92aa7
Regex condition update for following rules:
- Suspicious Non PowerShell WSMAN COM Provider
- Renamed Powershell Under Powershell Channel
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
<Provider Name="PowerShell" /> 
<EventID Qualifiers="0">400</EventID> 
<Level>4</Level> 
<Task>4</Task> 
<Keywords>0x80000000000000</Keywords> 
<TimeCreated SystemTime="2024-12-01T14:26:10.0000000Z" /> 
<EventRecordID>3079110</EventRecordID> 
<Channel>Windows PowerShell</Channel> 
<Computer>McServer.mcdermott.local</Computer> 
<Security /> 
</System>
- <EventData>
<Data>Available</Data> 
<Data>None</Data> 
<Data>NewEngineState=Available …
```
> Regex improvement on Powershell rules

- rules/linux/process_creation/proc_creation_lnx_rsync_shell_execution.yml
- rules/linux/process_creation/proc_creation_lnx_rsync_shell_spawn.yml
I reworked the rule for suspicious rsync invocations and added a new one that is supposed to detect rsync exploitations in a generic way (e.g. CVE-2024-12084 https://sysdig.com/blog/detecting-and-mitigating-cve-2024-12084-rsync-remote-code-execution/ ). Since it's more a generic rule than a specific detection for an exploitation of CVE-2024-12084 I decided to not add it to the emerging-threats rule set but add it to the standard set. 
The old rule for suspicious rsync invocations with the -e flag had a wrong description and far too specific strings in the selection. I wonder if this ever matched anywhere. I composed a list of examples so that everyone can understand why the previous values were too specific and show the variety of way in which such a command could be written. 
new: …
> Rsync exploitation

- rules/cloud/m365/audit/microsoft365_bypass_conditional_access.yml
Identifies a successful login to the Microsoft Intune Company Portal which could allow bypassing Conditional Access Policies and InTune device trust using a tool like TokenSmith. This attack will generate a RefreshToken which can then be used with ROADtools to enumerate an Entra ID environment and access other apps in the family of applications this is attached to. 
new: Azure Login Bypassing Conditional Access Policies
> New Rule: Azure Login Bypassing Conditional Access Policies

- rules/windows/image_load/image_load_dll_vsstrace_susp_load.yml
NSIS install using $TEMP are flags matching rules
eg:
https://www.virustotal.com/gui/file/2ed7c8bbdb728a53354849f2801a05dd9719ffe7984002d0cc1dbc5c17696b66 Matches rule Suspicious Volume Shadow Copy Vsstrace.dll Load by frack113 at Sigma Integrated Rule Set (GitHub)
NSIS $TEMP is used like this:
'$TEMP\vc_redist.x64.exe /install /quiet /norestart'
Ideally, the exe to install should be signed by Microsoft from theses directories. So the rule should check if it is signed from Microsoft.
> fix: NSIS install using $TEMP are flags matching rules

- rules/windows/file/file_event/file_event_win_public_folder_payloads.yml
- rules/windows/file/file_event/file_event_win_susp_public_folder_extension.yml
This PR adds a new detection rule for suspicious binaries dropped in public folders based on our [latest report](https://thedfirreport.com/2025/01/27/cobalt-strike-and-a-pair-of-socks-lead-to-lockbit-ransomware/). The rule monitors for potentially malicious executables and scripts placed in `C:\Users\Public\`.
new: Suspicious Binaries and Scripts in Public Folders
> Dfir-report-27138

- rules/windows/builtin/security/win_security_codeintegrity_check_failure.yml
- rules/windows/powershell/powershell_classic/posh_pc_renamed_powershell.yml
Hi,
I am proposing changes for two rules with FP filters added.
- Failed Code Integrity Checks : 470ec5fa-7b4e-4071-b200-4c753100f49b
- For some reason CS EDR failes on code integrity checks generating thousands of events.
- Renamed Powershell Under Powershell Channel : 30a8cb77-8eb3-4cfb-8e79-ad457c5a4592
- I found an example of escaped backslash.
```
<System>
<Provider Name="Microsoft-Windows-Security-Auditing" Guid="54849625-5478-4994-A5BA-3E3B0328C30D">
</Provider>
<EventID>5038</EventID>
<Version>0</Version>
<Level>0</Level>
<Task>12290</Task>
<Keywords>0x8010000000000000</Keywords>
<TimeCreated SystemTime="2025-01-06T19:23:57.574661Z">
</TimeCreated>
<EventRecordID>11882997</EventRecordID> …
```
> FP filters

- rules/windows/registry/registry_set/registry_set_disable_windows_event_log_access.yml
This PR is based on
- https://www.atomicredteam.io/atomic-red-team/atomics/T1562.002#atomic-test-8---modify-event-log-channel-access-permissions-via-registry---powershell
new: Windows Event Log Access Tampering Via Registry
Logs can be found in https://github.com/redcanaryco/atomic-red-team/pull/3006
N/A
> Feat: tamper windows event log

- rules/linux/auditd/lnx_auditd_pers_systemd_reload.yml
- rules/linux/auditd/lnx_auditd_susp_service_reload_or_restart.yml
Detects a reload or a start of a service.  The attackers can also achieve this through the service command.
> Add a new technique with a service

- rules-threat-hunting/windows/process_creation/proc_creation_win_susp_elevated_system_shell.yml
- rules/windows/file/file_event/file_event_win_powershell_drop_binary_or_script.yml
- rules/windows/network_connection/net_connection_win_python.yml
- rules/windows/process_creation/proc_creation_win_conhost_uncommon_parent.yml
- rules/windows/process_creation/proc_creation_win_susp_elevated_system_shell_uncommon_parent.yml
- rules/windows/process_creation/proc_creation_win_susp_inline_win_api_access.yml
- rules/windows/process_creation/proc_creation_win_susp_proc_wrong_parent.yml
- rules/windows/process_creation/proc_creation_win_whoami_parent_anomaly.yml
This makes a little change on  `Python Initiated Connection` rule to reduce the false positive 
fix: Python Initiated Connection: modified the image to remove the fp
fix: Potential Binary Or Script Dropper Via PowerShell: added filters to remove fp
fix:  Potential WinAPI Calls Via CommandLine: added filters to remove fp
fix: Elevated System Shell Spawned From Uncommon Parent Location: Added new filter for parentimage with '-'  value
fix: Windows Processes Suspicious Parent Directory:  Added new filter for parentimage with '-'  value
fix: Whoami.EXE Execution Anomaly: Added new filter for parentimage with '-'  value
fix: Conhost Spawned By Uncommon Parent Process: Added filter for new type of svchost parentcommandline
update: Elevated System Shell Spawned: Added powershell_ise.exe
1. …
> Fixed more fps

- rules-emerging-threats/2023/Exploits/CVE-2023-23397/win_smbclient_connectivity_exploit_cve_2023_23397_outlook_remote_file.yml
Fixing an issue with the field that is used to filter in the rule "Potential CVE-2023-23397 Exploitation Attempt - SMB"
I applied a broader filter to the correct field name and hope that this method ("string|startswith") works for the socket address in that field.
fix: changed filter expression for event id 30804 in CVE-2023-23397 exploitation rule
We didn't get the raw data, only this:
RULEDATE_1: 2024/03/13
DESCRIPTION_1: Detects (failed) outbound connection attempts to internet facing SMB servers. This could be a sign of potential exploitation attempts of CVE-2023-23397.
AUTHOR_1: Nasreddine Bencherchali (Nextron Systems)
EVENT_ID: 30804
EVENT_LEVEL: 2
EVENT_CHANNEL: Microsoft-Windows-SmbClient/Connectivity
EVENT_COMPUTER: Client01
EVENT_TIME: Wed Mar 15 05:43:52 2024
ENTRY: Reason: 7 …
> fix: issue with event id 30804

- rules-emerging-threats/2023/Exploits/CVE-2023-23397/win_smbclient_connectivity_exploit_cve_2023_23397_outlook_remote_file.yml
Add filters for XML raw IP log.
fix: Potential CVE-2023-23397 Exploitation Attempt - SMB - Add filters for IP format when ingesting XML raw event
N/A
N/A
> Add Support for XML

- rules/windows/process_creation/proc_creation_win_adplus_memory_dump.yml
Adding a missing mitre tag to the rule since T1003.001 (OS Credential Dumping: LSASS Memory) is a subtechnique that's part of the credential access tactic.
update:	Potential Adplus.EXE Abuse - adding missing mitre tag
> Add a missing mitre tag to one rule

- rules/windows/process_creation/proc_creation_win_susp_lnk_exec_hidden_cmd.yml
Added a rule to detect possible exploitation of ZDI-CAN-25373 as reported by [Trendmicro](https://www.trendmicro.com/en_us/research/25/c/windows-shortcut-zero-day-exploit.html).
According to Trendmicro, ZDI-CAN-25373 relates to the way Windows displays the contents of shortcut (.lnk) files through the Windows UI. By exploiting this vulnerability, an attacker can prepare a malicious .lnk file for delivery to a victim. Upon examining the file using the Windows-provided user interface, the victim will not be able to tell that the file contains any malicious content. The sections below explain the vulnerability in further detail.
new: Suspicious LNK Command-Line Padding with Whitespace Characters
[0xa.log](https://github.com/user-attachments/files/19347533/0xa.log)
- If your PR adds new …
> Addded rule for LNK Command-Line Padding with Whitespace Characters

- rules/windows/process_creation/proc_creation_win_wmic_recon_product_class.yml
Added AntiSpywareProduct class enumeration
update: Potential Product Class Reconnaissance Via Wmic.EXE: Add AntiSpywareProduct
> Added AntiSpywareProduct class enumeration

- rules/windows/powershell/powershell_script/posh_ps_susp_clear_eventlog.yml
- rules/windows/process_creation/proc_creation_win_susp_eventlog_clear.yml
Added rule to detec clearing of event logs via dotnet class
update: Suspicious Eventlog Clear: Added coverage for eventlog clearing using dotnet class
update: Suspicious Eventlog Clearing or Configuration Change Activity: Added coverage for eventlog clearing using dotnet class
> Added rule to detect clearing of event logs via dotnet class

- rules-emerging-threats/2025/Exploits/proc_creation_win_exploit_cve_2025_30406_centrestack_portal_child_process.yml
- rules/windows/process_creation/proc_creation_win_centrestack_portal_rce.yml
We have observed exploitation of this in the wild today. This rule was crafted based on that exploitation.
We haven't seen any false positives yet, for redaction reasons cannot share the log execution that came after here.
> new: Suspicious Process Spawn by CentreStack Portal AppPool

- rules-emerging-threats/2025/Exploits/CVE-2025-31161/proc_creation_win_crushftp_susp_child_processes.yml
I have updated the sigma rule shared by Huntress blog post
https://www.huntress.com/blog/crushftp-cve-2025-31161-auth-bypass-and-post-exploitation
Original Sigma rule:
https://gist.github.com/JohnHammond/a22bf3103eeb0f985cf1cef4d3fc849f#file-win_proc_creation_shell_child_process_crushftp-yml
new: Suspicious CrushFTP Child Process
> feat: Suspicious CrushFTP Child Process

- rules/windows/powershell/powershell_module/posh_pm_susp_invocation_specific.yml
- rules/windows/powershell/powershell_script/posh_ps_susp_invocation_specific.yml
- rules/windows/process_creation/proc_creation_win_autorun_registry_modified_via_wmic.yml
- rules/windows/process_creation/proc_creation_win_reg_add_run_key.yml
- rules/windows/process_creation/proc_creation_win_reg_direct_asep_registry_keys_modification.yml
- rules/windows/registry/registry_event/registry_event_susp_download_run_key.yml
- rules/windows/registry/registry_set/registry_set_powershell_in_run_keys.yml
- rules/windows/registry/registry_set/registry_set_susp_run_key_img_folder.yml
Updated and Added rule related to Autorun Registry
new: Suspicious Autorun Registry Modified via WMI
update: Suspicious PowerShell Invocations - Specific - PowerShell Module
update: Suspicious PowerShell Invocations - Specific
update: Potential Persistence Attempt Via Run Keys Using Reg.EXE
update: New RUN Key Pointing to Suspicious Folder
update: Suspicious Powershell In Registry Run Keys
update: Direct Autorun Keys Modification
update: Suspicious Run Key from Download
> Updated and Added rule related to Autorun Registry

- rules/application/opencanary/opencanary_httpproxy_login_attempt.yml
- rules/linux/process_creation/proc_creation_lnx_proxy_connection.yml
- rules/linux/process_creation/proc_creation_lnx_susp_curl_fileupload.yml
- rules/macos/process_creation/proc_creation_macos_chflags_hidden_flag.yml
- rules/windows/builtin/application/msiinstaller/win_software_atera_rmm_agent_install.yml
- rules/windows/dns_query/dns_query_win_quickassist.yml
- rules/windows/network_connection/net_connection_win_dialer_initiated_connection.yml
- rules/windows/process_creation/proc_creation_win_findstr_download.yml
- rules/windows/process_creation/proc_creation_win_findstr_subfolder_search.yml
Adding some missing mitre tags for tactics to rules that have specific techniques enabled.
For most of the rules listed below i've added: attack.command-and-control & attack.credential-access because they have a technique tag refers to this tactic.
Update: Hidden Flag Set On File/Directory Via Chflags - MacOS
Update: Suspicious Curl File Upload - Linux
Update: Connection Proxy
Update: OpenCanary - HTTPPROXY Login Attempt
Update: Remote File Download Via Findstr.EXE
Update: Insensitive Subfolder Search Via Findstr.EXE
Update: Atera Agent Installation
Update: DNS Query Request By QuickAssist.EXE
Update: Outbound Network Connection Initiated By Microsoft Dialer …
> Adding additional mitre tags for 9 rules

- rules/windows/builtin/application/mssqlserver/win_mssql_failed_logon_from_external_network.yml
Add a filter to `win_mssql_failed_logon_from_external_network` rule for usage of `local_machine` value instead of an IP.
fix: MSSQL Server Failed Logon From External Network - filter for local_machine without IP
Some Data fields with this value:
```
ServiceName,  Reason: Failed to open the explicitly specified database.,  [CLIENT: <local machine>]
USER,  Reason: Could not find a login matching the name provided.,  [CLIENT: <local machine>]
ServiceName,  Reason: Failed to open the database configured in the login object while revalidating the login on the connection.,  [CLIENT: <local machine>]
```
> Update MSSQL Server Failed Logon From External Network to filter for local machine without IP

- rules-threat-hunting/windows/file/file_event/file_event_win_susp_binary_dropper.yml
- rules-threat-hunting/windows/image_load/image_load_dll_amsi_uncommon_process.yml
- rules-threat-hunting/windows/image_load/image_load_wmi_module_load_by_uncommon_process.yml
- rules/windows/image_load/image_load_dll_system_management_automation_susp_load.yml
- rules/windows/image_load/image_load_side_load_from_non_system_location.yml
- rules/windows/image_load/image_load_side_load_mscorsvc.yml
- rules/windows/image_load/image_load_wsman_provider_image_load.yml
- rules/windows/process_creation/proc_creation_win_addinutil_uncommon_dir_exec.yml
- rules/windows/process_creation/proc_creation_win_aspnet_compiler_exectuion.yml
- rules/windows/process_creation/proc_creation_win_aspnet_compiler_susp_paths.yml
Fixed fps and added coverage for ARM based windows dotnet paths
fix: Potential System DLL Sideloading From Non System Locations : shell32.dll, windows.storage.dll were causing fp from C:\Windows\SyChpe32 directory thus added to filters
fix: Potential DLL Sideloading Of MsCorSvc.DLL: fp for `\Windows\Microsoft.NET\FrameworkArm64\` path resolved by adding it in the filter
ARM Based windows dotnet paths updated in these rules below:
update: Creation of an Executable by an Executable: ARM Based windows dotnet paths updated
update: Amsi.DLL Load By Uncommon Process: ARM Based windows dotnet paths updated
update: WMI Module Loaded By Uncommon Process: ARM Based windows dotnet paths updated
update: PowerShell Core DLL Loaded By Non PowerShell Process: ARM Based windows dotnet paths updated …
> Fixed fps and added coverage for ARM based windows dotnet paths

- rules/windows/process_creation/proc_creation_win_hktl_lazagne.yml
Lazagne rule update
update: HackTool - LaZagne Execution: filter added to reduce fp and added more coverage through imphash
**False positive Event**
> Lazagne rule update

- rules-threat-hunting/windows/image_load/image_load_dll_bitsproxy_load_by_uncommon_process.yml
- rules/windows/process_creation/proc_creation_win_vshadow_exec.yml
A short summary of your pull request.
Adds a new Sigma detection rule Execution of vshadow.exe with -exec Parameter that flags any process creation EventID 1 invoking vshadow.exe with the -exec switch. This helps identify potential misuse of volume shadow copy to hide and execute malware.
new: Proxy Execution via Vshadow - detect invocation of `vshadow.exe` with `-exec` to spot hidden malware execution
> add rule to detect vshadow.exe with -exec parameter

- rules/windows/builtin/security/win_security_kerberos_asrep_roasting.yml
Fix the PreAuthType selection field in the `Potential AS-REP Roasting via Kerberos TGT Requests` rule. Windows event viewer displays the human readable "Pre-Authentication Type", but EventData field is actually PreAuthType. Additionally, PreAuthType is a "Data" field, so must be treated as a string, not an integer
fix: Potential AS-REP Roasting via Kerberos TGT Requests - use the correct PreAuthType selection field name
```
<System>
<Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-a5ba-3e3b0328c30d}" /> 
<EventID>4768</EventID> 
<Version>0</Version> 
<Level>0</Level> 
<Task>14339</Task> 
<Opcode>0</Opcode> 
<Keywords>0x8020000000000000</Keywords> 
<TimeCreated …
```
> Fix "Potential AS-REP Roasting via Kerberos TGT Requests"

- rules/windows/builtin/system/microsoft_windows_kerberos_key_distribution_center/win_system_kdcsvc_cert_use_no_strong_mapping.yml
- rules/windows/builtin/system/microsoft_windows_kerberos_key_distribution_center/win_system_kdcsvc_rc4_downgrade.yml
- rules/windows/builtin/system/microsoft_windows_kerberos_key_distribution_center/win_system_kdcsvc_tgs_no_suitable_encryption_key_found.yml
Sigma rules within [windows/bultin/system/microsoft_windows_kerberos_key_distribution_center/](https://github.com/SigmaHQ/sigma/tree/master/rules/windows/builtin/system/microsoft_windows_kerberos_key_distribution_center) use different `Provider_Name` variables:
-  `Kerberos-Key-Distribution-Center` and
-  `Microsoft-Windows-Kerberos-Key-Distribution-Center`
It seems that both provider names are valid, so I updated the rules to match both names.
update: [win_system_kdcsvc_cert_use_no_strong_mapping.yml](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/system/microsoft_windows_kerberos_key_distribution_center/win_system_kdcsvc_cert_use_no_strong_mapping.yml) - update provider name selection
update: [win_system_kdcsvc_rc4_downgrade.yml](https://github.com/SigmaHQ/sigma/blob/ …
> Adjust provider name selection in kerberos-key-distribution-center rules
