- rules/windows/sysmon/sysmon_mshta_spawn_shell.yml
- rules/windows/sysmon/sysmon_office_shell.yml
- rules/windows/sysmon/sysmon_susp_file_execution.yml
- rules/windows/sysmon/sysmon_webshell_detection.yml
- rules/windows/sysmon/sysmon_webshell_spawn.yml
Added a few things in here to expand. Great idea and tool. Thank you
> Modifications and new adds

- rules/windows/sysmon/sysmon_susp_net_execution.yml
- rules/windows/sysmon/sysmon_susp_wmi_execution.yml
Two new rules to detect net and wmic performing suspicious activity
> wmic and net

- tools/config/logpoint-windows-all.yml
Conditional mapping of SubjectAccountName based on EventID. Not a comprehensive list, but should include most relevant Event IDs.
> Added LogPoint conditional username mapping

- tools/config/logpoint-windows-all.yml
Added field mappings for events with logins (key length, logon process, logon type)
> Added field mappings for events with logins

- rules/windows/builtin/win_susp_samr_pwset.yml
rule to detect mimikatz lsadump::changentlm and lsadump::setntlm
> rule to detect mimikatz lsadump::changentlm and lsadump::setntlm

- rules/windows/builtin/win_susp_certutil_activity.yml
- rules/windows/builtin/win_susp_cli_escape.yml
- rules/windows/builtin/win_susp_phantom_dll.yml
- rules/windows/builtin/win_susp_process_creations.yml
- rules/windows/builtin/win_susp_rundll32_activity.yml
@Neo23x0 please review and merge - looks fine for me.
> Rules from juju4

- tools/backends.py
This is has only been tested slightly.
I would like to be able to pass in the index from the rules.
> Sigmac: X-Pack Watcher Output First Version

- rules/windows/builtin/win_multiple_suspicious_cli.yml
> Detects Quick execution of a series of suspicious commands

- rules/windows/builtin/win_admin_rdp_login.yml
> Admin user remote login

- rules/windows/sysmon/sysmon_stickykey_like_backdoor.yml
Add more accessibility binaries which could be abused.
> Add missing binaries

- Makefile
- tools/sigma/backends.py
Hello,
We developed an es-dsl backend and we propose to integrate it into sigma main branch.
Do you have a dataset that you use for your tests to validate that queries are returning what they are expected to? Could be useful for generic unitests.
Best regards
> es-dsl backend

- rules/windows/sysmon/sysmon_susp_certutil_command.yml
According to the specification:
`author: //str`
> "author" should be a string and not a list.

- rules/windows/builtin/SquiblyTwo.yar
Detects the SquiblyTwo Attack as described by https://subt0x11.blogspot.ch/2018/04/wmicexe-whitelisting-bypass-hacking.html
> added SquiblyTwo Detection

- tools/sigma/backends.py
Hello,
Please find some fixes for our implementation.
Regards
> patched es-dsl

- tools/sigma/backends.py
I have made a first pass at adding support for Graylog seaches in backends.py
I added some comments above new class in backends.py
> Graylog Backend added

- rules/linux/auditd/lnx_auditd_susp_exe_folders.yml
- specify when it is apache only
- add Per-user path
- add archlinux paths
> enhance web server paths

- rules/windows/sysmon/sysmon_powersploit_schtasks.yml
https://github.com/0xdeadbeefJERKY/PowerSploit/blob/8690399ef70d2cad10213575ac67e8fa90ddf7c3/Persistence/Persistence.psm1
> Detects the creation of a schtask via PowerSploit Default Configuration

- tools/sigma/backends.py
backend, which translates your rules to a Splunk Dashboard (XML), where a panel exists for each rule (i.e. when used with -r flag )
> Added support of splunk dashboards (xml)

- rules/windows/sysmon/sysmon_lethalHTA.yml
"Furthermore it can be detected by an mshta.exe process spawned by svchost.exe."
> MSHTA spwaned by SVCHOST as seen in LethalHTA

- rules/windows/sysmon/sysmon_cmstp_execution.yml
Added Sysmon detection rules for CMSTP execution. See http://www.endurant.io/cmstp/detecting-cmstp-enabled-code-execution-and-uac-bypass-with-sysmon/
> Add sysmon_cmstp_execution

- rules/windows/sysmon/sysmon_stickykey_like_backdoor.yml
> ATT&CK tagging

- rules/windows/builtin/win_susp_lsass_dump.yml
- rules/windows/builtin/win_susp_msmpeng_crash.yml
- rules/windows/builtin/win_susp_net_recon_activity.yml
- rules/windows/builtin/win_susp_rc4_kerberos.yml
- rules/windows/builtin/win_susp_rundll32_activity.yml
- rules/windows/builtin/win_susp_sam_dump.yml
- rules/windows/builtin/win_susp_sdelete.yml
- rules/windows/builtin/win_susp_security_eventlog_cleared.yml
tags for some of the windows/builtin rules.
> windows builtin mitre attack tags

- rules/windows/sysmon/sysmon_ghostpack_safetykatz.yml
https://github.com/GhostPack/SafetyKatz
> Possible SafetyKatz Dump of debug.bin

- rules/windows/powershell/powershell_NTFS_Alternate_Data_Streams
- rules/windows/sysmon/sysmon_rundll32_net_connections.yml
Created a new rule for: https://attack.mitre.org/wiki/Technique/T1096
Requesting to check syntax, still learning the ropes of sigma.
> Fixed typo / Created a rule

- rules/network/net_susp_dns_txt_exec_strings.yml
https://twitter.com/stvemillertime/status/1024707932447854592
> DNS TXT Answer with possible execution strings

- rules/windows/sysmon/sysmon_powershell_suspicious_parameter_variation.yml
Add mitre att&ck tags for T1086
> Add MITRE ATT&CK tagging

- rules/windows/sysmon/sysmon_powershell_exploit_scripts.yml
Add tags for https://attack.mitre.org/wiki/Technique/T1086
> Add ATT&CK Matrix tags

- tools/config/qradar.yml
- tools/sigma/backends/qradar.py
My first pull request so hopefully I'm doing it right...  Let me know if you see any issues with the changes.
> Qradar backend: added aggregation and AQL database flow support  

- tools/config/powershell-windows-all.yml
- tools/sigma/backends/powershell.py
Add PowerShell backend and corresponding PowerShell config file. See https://github.com/Neo23x0/sigma/issues/94 for the discussion. I made the PR for easier collaboration on the issue.
If you would like to have it merged into a special branch, I will change it of course.
> Add initial version of the PowerShell backend

- tools/sigma/parser/condition.py
Minor change to improve some comments and docstrings. No code changes.
> Improve the comments on the optimizer

- rules/windows/sysmon/sysmon_powershell_amsi_bypass.yml
- rules/windows/sysmon/sysmon_powershell_network_connection.yml
- rules/windows/sysmon/sysmon_powersploit_schtasks.yml
- rules/windows/sysmon/sysmon_susp_powershell_parent_combo.yml
- rules/windows/sysmon/sysmon_susp_powershell_rundll32.yml
Tagged sysmon rules related to powershell with the T1086 tag. Added tags section where it didn't already exist.
> Additional MITRE ATT&CK Tagging

- tests/test-backend-netwitness.py
- tools/config/netwitness.yml
- tools/setup.py
- tools/sigma/backends/netwitness.py
Created backend for RSA NetWitness queries that are used in the WebUI, some field mappings, and a backend test.  Backend does not support keywords/raw data field searches as the WebUI console does not support that in a single query but in an accompanying field.
> Added NetWitness backend and tests

- rules/windows/builtin/win_disable_event_logging.yml
- rules/windows/sysmon/sysmon_powershell_suspicious_parameter_variation.yml
- tools/config/helk.yml
- Updated HELK field standardization config used by SIGMAC
- Improved SIGMA rule  rules/windows/sysmon/sysmon_powershell_suspicious_parameter_variation.yml to focus only on the CommandLine field and not every string in event logs.
- Improved SIGMA rule rules/windows/builtin/win_disable_event_logging.yml to maintain consistency of event field values
> Elastalert-HELK integration Updates

- rules/windows/builtin/win_powershell_b64_shellcode.yml
- rules/windows/builtin/win_susp_powershell_enc_cmd.yml
- tools/config/helk.yml
+ Updated HELK field-index mapping file
+ After going through all the fields with 'fieldlist' output, I found a few rules that fixed.
> Field-Index Mapping File & SIGMA Rules Field names fix

- rules/windows/builtin/win_plugx_susp_exe_locations.yml
- rules/windows/sysmon/sysmon_plugx_susp_exe_locations.yml
Mostly worried that the filter section not having the correct filters for rc.exe. My google searches suggest it should be correct but can't test this for myself.
> Fixed the RC section to use rc.exe instead of oleview.exe

- rules/windows/sysmon/sysmon_ghostpack_safetykatz.yml
- rules/windows/sysmon/sysmon_mal_namedpipes.yml
- rules/windows/sysmon/sysmon_office_shell.yml
- rules/windows/sysmon/sysmon_powersploit_schtasks.yml
- rules/windows/sysmon/sysmon_susp_schtask_creation.yml
- tests/test_rules.py
I wrote a quick rule test framework. So far it only has two tests but I should be adding more shortly.
The two tests are:
- Check for incorrect MITRE tags
- Check for different file extension
> Rule testing framework

- tools/config/helk.yml
change Destination IP to correct HELK name which is "dst_ip_addr"
> update helk config

- rules/windows/sysmon/sysmon_ssp_added_lsa_config.yml
Proposing this new rule based on a Powersploit and Mimikatz attack against Windows credentials.
> SSP added to LSA configuration

- contrib/sigma2sumologic.py
- tools/sigma/backends/sumologic.py
* backend review
* example script
> Sumologic support update

- rules/windows/builtin/win_possible_applocker_bypass.yml
- rules/windows/builtin/win_susp_time_modification.yml
Using installutil to add features for .NET applications (primarly would occur in developer environments)
> new rule and updated false positive note 

- rules/windows/builtin/win_spn_enum.yml
Fixes an issue referenced in #251 .
> Fixing yara condition

- rules/apt/apt_apt29_tor.yml
- rules/apt/apt_equationgroup_dll_u_load.yml
- rules/apt/apt_hurricane_panda.yml
- rules/apt/apt_slingshot.yml
- rules/apt/apt_sofacy.yml
- rules/apt/apt_sofacy_zebrocy.yml
- rules/apt/apt_tropictrooper.yml
- rules/apt/apt_turla_commands.yml
- rules/apt/apt_unidentified_nov_18.yml
What I hope we would get to is a place where all multi-document yamls are replaced with simple, flat ones. There are still 8 left but using the process_creation logsource really helps reduce the number of these.
> Updated to use the new process_creation logsource

- rules/windows/builtin/win-susp-mshta-execution.yml
hi guys, let me know if something doesn't add up
> adding rule win-susp-mshta-execution.yml

- rules/apt/apt_apt29_thinktanks.yml
- rules/apt/apt_apt29_tor.yml
- rules/apt/apt_babyshark.yml
- rules/apt/apt_bear_activity_gtr19.yml
- rules/apt/apt_carbonpaper_turla.yml
- rules/apt/apt_equationgroup_dll_u_load.yml
- rules/apt/apt_slingshot.yml
- rules/apt/apt_sofacy.yml
- rules/apt/apt_turla_commands.yml
- rules/apt/apt_zxshell.yml
- rules/apt/crime_fireball.yml
Added and fixed the Mitre ATT&CK tagging across the APT ruleset.
> Added and fixed tags on APT rules

- rules/apt/apt_empiremonkey.yml
- rules/windows/process_creation/win_susp_squirrel_lolbin.yml
- rules/windows/process_creation/win_wmi_spwns_powershell.yml
> Sqirrel packages manager, EmpireMonkey, WMI Spawning PowerShel

- tools/sigma/backends/elasticsearch.py
Using Elasticsearch target, `filter` fields are matched on keyword version of field if value contains wildcard.
Default behaviour of elasticsearch is to map string to dual fields
```
{
stringName: value, 
type: "text",
}, {
stringName.keyword: value,
type: "keyword",
}
```
With `ElasticsearchWildcardHandlingMixin`, you can pass an other `keyword_field` name to target your configuration.
Unfortunately, it doesn't not support an empty `keyword_field` as needed by winlogbeat mapping template for example.
```
$ tools/sigmac --target es-qs --config tools/config/elk-winlogbeat.yml rules/windows/builtin/win_user_added_to_local_administrators.yml --backend-option keyword_field=''
(log_name:"Security" AND (event_id:"4732" AND event_data.GroupName:"Administrators") AND (NOT …
```
> Allow empty keyword_field

- tools/config/elk-defaultindex-filebeat.yml
- tools/config/elk-defaultindex-logstash.yml
- tools/config/elk-defaultindex.yml
- tools/config/elk-linux.yml
- tools/config/elk-windows.yml
- tools/config/elk-winlogbeat.yml
- tools/config/helk.yml
- tools/sigma/backends/base.py
- tools/sigma/backends/elasticsearch.py
I find es-dsl clearer than es-qs so why not using it with elastalert.
> introduce elastalert-dsl

- rules/linux/auditd/lnx_auditd_alter_bash_profile.yml
Bash profile configuration files could be abused by attacker to grand persistense, record passwords from console or launch reverse shell. This rule monitor changes in relates files.
ID: [T1156](https://attack.mitre.org/techniques/T1156/)
Tactic: Persistence
Platform:  Linux, macOS
Permissions Required:  User, Administrator
Data Sources: File monitoring,
AuditD Shell configuration Persistence Related Events:
-w /home/<user>/.bashrc -k T1156_bash_profile_and_bashrc
-w /home/<user>/.bash_profile -k T1156_bash_profile_and_bashrc
-w /home/<user>/.profile -k T1156_bash_profile_and_bashrc
-w /etc/profile.d/ -k T1156_bash_profile_and_bashrc
-w /etc/profile -k T1156_bash_profile_and_bashrc
-w /etc/shells -k T1156_bash_profile_and_bashrc
-w /etc/bashrc -k T1156_bash_profile_and_bashrc
-w …
> added rule .bash_profile and .bashrc T1156

- rules/windows/process_creation/win_susp_bcdedit.yml
incorrect process name. accidentally had fsutil, should be bcdedit.
thanks to https://twitter.com/INIT_3 for pointing this out
> update correct process name

- rules/web/web_source_code_enumeration.yml
Web source enumeration via .git web URL requests.
> Web Source Code Enumeration via .git

- tools/config/elk-winlogbeat.yml
useful to detect pass the hash attacks
> Addition of KeyLength field

- tools/sigma/backends/elasticsearch.py
Added 2 more actions on Elasticsearch X-pack Watcher: index and webhook
Added timestamp filter query.
> Added 2 more actions on Elasticsearch X-pack Watcher: index and webhook

- rules/windows/builtin/win_susp_net_recon_activity.yml
- rules/windows/powershell/powershell_malicious_commandlets.yml
- rules/windows/powershell/powershell_malicious_keywords.yml
- rules/windows/powershell/powershell_psattack.yml
- rules/windows/powershell/powershell_suspicious_keywords.yml
> fixed typos

- README.md
As @Neo23x0 was writing in Twitter, more contribution is needed, so a Contribute section seems reasonable to tell people how they can contribute.
https://twitter.com/cyb3rops/status/1158660279825252352
> Add Contribute section

- tools/sigma/backends/wdatp.py
Reference: https://github.com/Neo23x0/sigma/issues/423
Malicious Cmdlets now supported in WDATP.
> Support for Malicious cmdlets in ATP

- rules/windows/sysmon/sysmon_mimikatz_trough_winrm.yml
Detects usage of mimikatz through WinRM protocol
> Detection of usage mimikatz trough WinRM

- tools/config/sumologic.yml
- tools/sigma/backends/sumologic.py
- fix index from config file (was aFL filtering)
- ensure that all rules have an index definition in config/sumologic.ym to optimize query
> sumologic backend: fix index and full mapping coverage

- tools/sigma/backends/qradar.py
This adds support for regex type modifiers to the QRadar backend.
Unfortunately it is not enough to encode the value differently - the whole structure of the resulting query has to be modified (```field imatches 'regex'``` instead of  ```field = 'value'```).
Using the example from [this blog post](https://patzke.org/introducing-sigma-value-modifiers.html), the resulting query looks like this for QRadar:
```SELECT UTF8(payload) as search_payload from events where ("Event ID Code"='1' and LOGSOURCETYPENAME(devicetype)='Microsoft Windows Security Event Log' and Image imatches '^.*\\Temp\\[^\]+.exe$')```
> QRadar backend: add support for re type modifiers

- rules/windows/process_creation/win_office_spawn_exe_from_users_directory.yml
- rules/windows/process_creation/win_shell_spawn_susp_program.yml
- rules/windows/process_creation/win_susp_csc_folder.yml
- rules/windows/process_creation/win_susp_gup.yml
- rules/windows/process_creation/win_system_exe_anomaly.yml
- rules/windows/sysmon/sysmon_control_panel_item.yml
- rules/windows/sysmon/sysmon_tsclient_filewrite_startup.yml
Generated query not working without correct escape.
Check this commit https://github.com/Neo23x0/sigma/commit/3ef930b0943eae586144513fe9732604946843bc
> Escaped '\*' to '\*' where required

- tools/config/helk.yml
- tools/config/winlogbeat-modules-enabled.yml
update HELK config/taxonomy
add winlogbeat config/taxonomy specific to if elastic winlogbeat modules are enabled
> update HELK and add winlogbeat module enabled taxonomy

- rules/windows/process_creation/win_susp_procdump.yml
make rule a bit broader for selection 1+2
> remove .exe from lsass

- tools/sigma/backends/qradar.py
added the cleanValue function so quotes get escaped in the AQL queries. Might need more replacements in the future, depending on the values in the Sigma rules.
> Added the cleanValue function for Qradar

- rules/linux/lnx_shell_clear_cmd_history.yml
history -w will clear the current shell history
shred purposely overwrites data replacing it with random data
> Added Additional history clearing options

- README.md
Apologies for the redundant PR, forgot to add LimaCharlie to the README's list of supported targets.
> Adding LimaCharlie to the README's supported targets.

- rules/windows/powershell/powershell_suspicious_keywords.yml
/cc @Neo23x0 I changed the keyword as we should see the one also found in the screenshots here https://twitter.com/JohnLaTwC/status/850381440629981184.
See #501.
> fix: change keyword and bound it to a field in PS rule

- README.md
- rules/proxy/proxy_chafer_malware.yml
- rules/proxy/proxy_ios_implant.yml
- rules/proxy/proxy_ua_cryptominer.yml
- rules/windows/builtin/win_account_backdoor_dcsync_rights.yml
- rules/windows/builtin/win_ad_object_writedac_access.yml
- rules/windows/builtin/win_non_interactive_powershell.yml
- rules/windows/builtin/win_remote_powershell_session.yml
- rules/windows/builtin/win_scm_database_handle_failure.yml
- rules/windows/builtin/win_scm_database_privileged_operation.yml
- rules/windows/builtin/win_syskey_registry_access.yml
- rules/windows/builtin/win_wmiprvse_spawning_process.yml
- rules/windows/powershell/powershell_alternate_powershell_hosts.yml
- rules/windows/powershell/powershell_remote_powershell_session.yml
- rules/windows/process_creation/win_possible_applocker_bypass.yml
- rules/windows/process_creation/win_susp_rundll32_by_ordinal.yml
- rules/windows/sysmon/sysmon_alternate_powershell_hosts_moduleload.yml
- rules/windows/sysmon/sysmon_alternate_powershell_hosts_pipe.yml
- rules/windows/sysmon/sysmon_createremotethread_loadlibrary.yml
- rules/windows/sysmon/sysmon_non_interactive_powershell_execution.yml
- rules/windows/sysmon/sysmon_powershell_execution_moduleload.yml
- rules/windows/sysmon/sysmon_powershell_execution_pipe.yml
- rules/windows/sysmon/sysmon_rdp_registry_modification.yml
- rules/windows/sysmon/sysmon_remote_powershell_session_network.yml
- rules/windows/sysmon/sysmon_remote_powershell_session_process.yml
- rules/windows/sysmon/sysmon_wmi_module_load.yml
- rules/windows/sysmon/sysmon_wmiprvse_spawning_process.yml
- tools/setup.py
> [OSCD][The ThreatHunter-Playbook] Task 6 #1 

- rules/linux/lnx_chattr_immutable_removal.yml
- rules/linux/lnx_dd_delete_file.yml
- rules/linux/lnx_file_or_folder_permissions.yml
- rules/linux/lnx_pers_systemd_reload.yml
- rules/windows/process_creation/win_dsquery_domain_trust_discovery.yml
- rules/windows/process_creation/win_file_permission_modifications.yml
- rules/windows/process_creation/win_service_stop.yml
OSCD Task 7 - ART
MITRE ATT&CK techniques covered:
* T1222
* T1482
* T1485
* T1501
> [OSCD][ART] Task 7 #1

- rules/windows/process_creation/win_susp_exec_folder.yml
Added 'C:\Windows\Tasks' and 'C:\Windows\System32\Tasks' as suspicious locations accordingly article: https://github.com/ThreatHuntingProject/ThreatHunting/blob/master/hunts/suspicious_process_creation_via_windows_event_logs.md
> Added some suspicious locations

- rules/windows/process_creation/win_susp_svchost.yml
Added svchost.exe as a parent image accordingly this article (https://www.carbonblack.com/2014/06/10/screenshot-demo-hunt-evil-faster-than-ever-with-carbon-black/) and my investigations.
> Added svchost.exe as a parent image

- rules/windows/builtin/win_external_device.yml
- rules/windows/process_creation/win_susp_regsvr32_anomalies.yml
Added cmd.exe to the detection after observing Atomic Red Team test 
https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1117/T1117.md#atomic-test-2---regsvr32-remote-com-scriptlet-execution
> Update and add another selection for regsvr32

- tools/sigma/backends/limacharlie.py
Adding the `falsepositives` field to the metadata reported in the LC engine.
> LC added FP metadata

- rules/windows/malware/av_relevant_files.yml
> Add scriptlets

- rules/windows/sysmon/win_susp_winword_wmidll_load.yml
Respectfully Submit Sigma Rule For The Detection of MS Office Documents Loading WMI DLL's Via Executed VBA Macros
> MS Office Doc Load WMI DLL Rule

- rules/apt/apt_gallium.yml
- rules/windows/sysmon/sysmon_invoke_phantom.yml
-- terminating threads in a svchost process (InvokePhantom uses this technique to disable windows event logging)
-- GALLIUM threat intel IOCs in recent MSTIC blog/release.
> Sigma queries - defense evasion by tampering with svchost; recently released GALLIUM activity group IOCs

- rules/windows/builtin/win_rdp_reverse_tunnel.yml
- rules/windows/malware/av_exploiting.yml
- rules/windows/other/win_defender_bypass.yml
- rules/windows/process_creation/win_malware_emotet.yml
> Bypass Windows Defender

- rules/windows/builtin/win_susp_local_anon_logon_created.yml
- rules/windows/process_creation/win_susp_net_execution.yml
Detection setup I have needed a lowercase user instead of User as per the Taxonomy guide, please correct if that's an issue.
> Created win_susp_local_anon_logon_created.yml

- rules/windows/process_creation/win_process_dump_rundll32_comsvcs.yml
https://twitter.com/Hexacorn/status/1229702521679118336
> fix: fixing too restrictive rule

- tools/sigma/backends/sql.py
Get the converted SQL query after the WHERE statement for any filtering on SQL platform.
Example:
https://github.com/fuseyjz/sigma-sql/blob/master/README.md
> Sigma converter for SQL format

- rules/windows/sysmon/sysmon_registry_trust_record_modification.yml
- rules/windows/sysmon/sysmon_susp_office_dotnet_assembly_dll_load.yml
- rules/windows/sysmon/sysmon_susp_office_dotnet_clr_dll_load.yml
- rules/windows/sysmon/sysmon_susp_office_dotnet_gac_dll_load.yml
- rules/windows/sysmon/sysmon_susp_office_dsparse_dll_load.yml
- rules/windows/sysmon/sysmon_susp_office_kerberos_dll_load.yml
- rules/windows/sysmon/sysmon_susp_winword_vbadll_load.yml
- Rule to alert on trust record modification
- Rule to alert on VBA DLL's loaded by Office Processes
- Rule to alert on GAC DLL loaded by Office Processes
- Rule to alert on VBA DLL's loaded by Office Processes
- Rule to alert on Kerberos DLL loaded by Office Processes
- Rule to alert on CLR DLL loaded by Office Processes
- Rule to alert on Assembly DLL loaded by Office Processes
> New rules for Macro Detections

- rules/windows/process_creation/win_hack_koadic.yml
This rule is based on the Koadic source code (link to exact sloc is provided in references field of the rule).
Thanks to A. for the idea.
> New Koadic detection rule

- rules/windows/process_creation/win_meterpreter_or_cobaltstrike_getsystem_service_start.yml
- rules/windows/sysmon/sysmon_webshell_creation_detect.yml
writing C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\__PSScriptPolicyTest_r23phtye.jsp.ps1
> fix: avoiding FPs with Citrix software

- rules/windows/builtin/win_mmc20_lateral_movement.yml
see https://github.com/Neo23x0/sigma/issues/576
> MMC Lateral Movement Rule 1

- rules/windows/builtin/win_susp_ldap_dataexchange.yml
- rules/windows/sysmon/sysmon_susp_adsi_cache_usage.yml
added two detections which could be used to detect LDAPFragger
> add LDAPFragger detections

- rules/windows/builtin/win_susp_mshta_execution.yml
- rules/windows/process_creation/win_malware_trickbot_recon_activity.yml
- rules/windows/process_creation/win_susp_svchost_no_cli.yml
- rules/windows/sysmon/sysmon_in_memory_assembly_execution.yml
- rules/windows/sysmon/sysmon_minidumwritedump_lsass.yml
- rules/windows/sysmon/sysmon_susp_run_key_img_folder.yml
- rules/windows/sysmon/sysmon_suspicious_remote_thread.yml
Correcting some misconfigured dates. In all cases I am pretty sure that the dates intended are correct, but happy to be corrected.
Some of them are just misconfigurations but some are...kinda weird (like %Y/%d/%m). But fortunately most examples are logically clear which value is which.
> Date typos

- rules/windows/powershell/powershell_wmimplant.yml
Rule to detect CLI parameters used by WMImplant.
> WMImplant detection rule

- rules/windows/powershell/powershell_suspicious_invocation_generic.yml
' - windowstyle hidden ' changed to ' -windowstyle hidden '
> Typo fix for powershell_suspicious_invocation_generic.yml

- rules/windows/powershell/powershell_downgrade_attack.yml
- rules/windows/process_creation/win_powershell_downgrade_attack.yml
Small improvement so this use case can be used with sysmon and security logs.
> Powershell downgrade attack (small improvements)

- rules/windows/process_creation/sysmon_win_chm.yml
- rules/windows/process_creation/win_html_help_spawn.yml
> Create new rule T1223

- CHANGELOG.md
- Makefile
- README.md
- rules/windows/process_creation/win_apt_tropictrooper.yml
- rules/windows/process_creation/win_apt_unidentified_nov_18.yml
- tools/sigma/backends/mdatp.py
WDATP was renamed to MDATP (Microsoft Defender ATP).
MDATP also had schema changes recently: https://techcommunity.microsoft.com/t5/microsoft-defender-atp/advanced-hunting-data-schema-changes/ba-p/1043914
The updates reflect these changes.
> MDATP schema changes

- tools/sigma/backends/logiq.py
- tools/sigmac
Add support for LOGIQ (https://logiq.ai/) backend.
> Add LOGIQ backend.

- rules/windows/builtin/win_user_driver_loaded.yml
- rules/windows/sysmon/sysmon_susp_procexplorer_driver_created_in_tmp_folder.yml
- rules/windows/sysmon/sysmon_susp_service_installed.yml
possible detections for Ghost-In-The-Logs
> Detect Ghost-In-The-Logs (disabling/bypassing ETW)

- tools/sigma/parser/modifiers/transform.py
> Fix for broken endswith modifier

- rules/windows/malware/mal_azorult_reg.yml
Detects registry keys used by Azorult malware
> Registry entry for Azorult malware

- rules/linux/lnx_susp_ssh.yml
- rules/windows/sysmon/sysmon_cve-2020-1048.yml
> Rule devel

- rules/network/zeek/zeek-dce_rpc_domain_user_enumeration.yml
- rules/network/zeek/zeek_dce_rpc_mitre_bzar_execution.yml
- rules/network/zeek/zeek_dce_rpc_mitre_bzar_persistence.yml
- rules/network/zeek/zeek_http_executable_download_from_webdav.yml
- rules/network/zeek/zeek_smb_converted_win_atsvc_task.yml
- rules/network/zeek/zeek_smb_converted_win_impacket_secretdump.yml
- rules/network/zeek/zeek_smb_converted_win_lm_namedpipe.yml
- rules/network/zeek/zeek_smb_converted_win_susp_psexec.yml
- rules/network/zeek/zeek_smb_converted_win_susp_raccess_sensitive_fext.yml
- rules/network/zeek/zeek_smb_converted_win_transferring_files_with_credential_data.yml
- rules/proxy/proxy_executable_download_from_webdav.yml
create two new Zeek rules.
fix typo in smb_files field `path` and `name`
update author name
> Rules: Zeek

- tools/config/arcsight-zeek.yml
- tools/config/ecs-zeek-corelight.yml
- tools/config/ecs-zeek-elastic-beats-implementation.yml
- tools/config/logstash-zeek-default-json.yml
- tools/config/splunk-zeek.yml
- tools/config/winlogbeat-modules-enabled.yml
- tools/config/winlogbeat-old.yml
- tools/config/winlogbeat.yml
This PR adds following for winlogbeat and zeek:
**winlogbeat**
- the `Channel` field
- Wireless (WLAN AutoConfig) fields
**Zeek**
- tweaks categories
- creates SIGMAC's for (some) fields that users will use but should not, so this handles it "automagically" for them.
> SIGMACs: Winlogbeat & Zeek

- rules/windows/builtin/win_alert_ad_user_backdoors.yml
- rules/windows/builtin/win_susp_add_sid_history.yml
It was corrected with reference to this issue
https://github.com/Neo23x0/sigma/issues/777
> Null field check to eliminate false positives

- rules/windows/process_creation/win_apt_greenbug_may20.yml
See Tweet by Joe Johnson
https://twitter.com/Wolpertwo/status/1263433396065370118
> refactor: slightly improved Greenbug rule

- rules/windows/builtin/win_susp_backup_delete.yml
> Fix 'source' value for win_susp_backup_delete

- rules/windows/powershell/powershell_ntfs_ads_access.yml
'Add-Content' could also be used, instead of 'Set-Content'
> Add 'Add-Content' to powershell_ntfs_ads_access

- .github/workflows/sigma-test.yml
- Makefile
- tools/sigma/backends/sql.py
- tools/sigma/backends/sqlite.py
- tools/tests/test_backend_sql.py
- tools/tests/test_backend_sqlite.py
* Improve sql backend with aggregations
* Add sqlite backend including full-text search (fts5)
* Add python unit tests for the SQLBackend and SQLiteBackend
Work mostly done by @haggj
> Add sqlite backend

- rules/windows/sysmon/sysmon_ads_executable.yml
> Move null values out from list in rules

- tools/sigma/backends/mdatp.py
See https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-schema-reference for full scheme and details.
> Improved Microsoft ATP mapping, using Advanced Hunting Schema

- tools/README.md
I noted a few improvements to suggest after reading @neu5ron's new doc Elastic-focused contributions.
> Elastic section updates

- rules/windows/sysmon/sysmon_wmi_persistence_commandline_event_consumer.yml
Fix ImageLoaded filter to match with endswith, rather than exact match.
> Rule needs endwith, not exact match.

- rules/windows/process_creation/win_control_panel_item.yml
Update for method mentioned in https://ired.team/offensive-security/code-execution/code-execution-through-control-panel-add-ins
> Update for new method

- README.md
> s/straight forward/straightforward

- tools/sigma/backends/elasticsearch.py
Add action_throttle_period, mail_from and mail_profile to the XPackWatcherBackend (Elasticsearch)
> Add more Options for XPackWatcherBackend (Elasticsearch)

- rules/windows/powershell/powershell_xor_commandline.yml
- rules/windows/process_creation/win_powershell_xor_commandline.yml
https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=46
> New Rule: PowerShell xor commandline

- rules/windows/process_creation/win_susp_powershell_parent_process.yml
https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=28
> New Rule: Suspicious powershell parent process

- rules/windows/file_event/win_susp_desktopimgdownldr_file.yml
- rules/windows/process_creation/win_susp_copy_systemroot.yml
- rules/windows/process_creation/win_susp_desktopimgdownldr.yml
https://labs.sentinelone.com/living-off-windows-land-a-new-native-file-downldr/
> DesktopImgDownLdr Rules and extra rule

- rules/web/web_cve_2020_5902_f5_bigip.yml
https://twitter.com/yorickkoster/status/1279709009151434754
https://www.ptsecurity.com/ww-en/about/news/f5-fixes-critical-vulnerability-discovered-by-positive-technologies-in-big-ip-application-delivery-controller/
> rule: CVE-2020-5902 F5 BIG-IP Exploitation Attempt

- rules/windows/image_load/sysmon_wmi_persistence_commandline_event_consumer.yml
> Fix typo for rule in image_load category

- tools/sigma/backends/csharp.py
Converts Sigma rule into C# Regex  to be used in LINQ query.
> C# Backend

- rules/windows/builtin/win_user_driver_loaded.yml
legitimate errors generated by Google Chrome are reported often.
Official google standpoint on this:
https://support.google.com/chrome/a/thread/15440066?hl=en
> adding google chrome to FP list

- tools/config/stix-windows.yml
- tools/config/stix.yml
- tools/sigma/backends/stix.py
- DestinationPort -> network-traffic:dst_port
> Incorrect mapping fixes [stix backend]

- rules/windows/other/win_pcap_drivers.yml
Created rule to detect installation of popular windows pcap drivers.
> add win_pcap_drivers.yml

- rules/windows/builtin/win_applocker_file_was_not_allowed_to_run.yml
- tools/config/arcsight.yml
- tools/config/elk-windows.yml
- tools/config/elk-winlogbeat-sp.yml
- tools/config/elk-winlogbeat.yml
- tools/config/logpoint-windows.yml
- tools/config/logstash-windows.yml
- tools/config/powershell-windows-all.yml
- tools/config/powershell.yml
- tools/config/splunk-windows.yml
- tools/config/thor.yml
- tools/config/winlogbeat-modules-enabled.yml
- tools/config/winlogbeat-old.yml
- tools/config/winlogbeat.yml
AppLocker log source.
Microsoft-Windows-AppLocker/MSI and Script
Microsoft-Windows-AppLocker/EXE and DLL
Microsoft-Windows-AppLocker/Packaged app-Deployment
Microsoft-Windows-AppLocker/Packaged app-Execution
New AppLocker rule
> Added AppLocker log source and new rule

- rules/web/web_citrix_cve_2019_19781_exploit.yml
- rules/windows/builtin/win_GPO_scheduledtasks.yml
- rules/windows/builtin/win_alert_ad_user_backdoors.yml
- rules/windows/builtin/win_atsvc_task.yml
- rules/windows/builtin/win_global_catalog_enumeration.yml
- rules/windows/builtin/win_impacket_secretdump.yml
- rules/windows/builtin/win_lm_namedpipe.yml
- rules/windows/builtin/win_susp_psexec.yml
- rules/windows/builtin/win_svcctl_remote_service.yml
- rules/windows/powershell/powershell_data_compressed.yml
- rules/windows/powershell/powershell_shellcode_b64.yml
- rules/windows/powershell/powershell_winlogon_helper_dll.yml
- rules/windows/powershell/powershell_wmimplant.yml
- tests/test_rules.py
Changing `description` to `definition` as per the Sigma schema
> Update logsources description->definition

- rules/windows/process_creation/win_apt_zxshell.yml
- rules/windows/registry_event/sysmon_apt_pandemic.yml
I believe these two instance of 'Command' should be changed to 'CommandLine'. Can someone please verify this is correct.
> Change the selection from Command to CommandLine in a couple of rules

- tools/config/winlogbeat-modules-enabled.yml
- tools/config/winlogbeat.yml
This reverts commit 6c35a7afa0331120c82f93d4748f0cf9153bc568.
> Revert "Ref #933 - Added windows Process Creation to config"

- rules/windows/builtin/win_pass_the_hash_2.yml
- rules/windows/builtin/win_user_driver_loaded.yml
Two changes in this PR:
- Change the status of `production` to `stable`
- Add quotes around a `falsepositives` string due to a colon.
> Minor fixes to two rules

- tools/sigma/backends/powershell.py
Fixes the issue #762 with the PowerShell backend and when rules have a message filter.
> partial(?) fix of #762

- tools/config/stix-linux.yml
- tools/config/stix-windows.yml
- tools/config/stix.yml
The STIX backend translation for rules contains NOT was incorrect and generating invalid STIX pattern. This bug-fix intend to fix it. Moreover mapping updates for STIX backend has added as well
> STIX Backend bug-fix and mapping updates

- rules/web/win_webshell_regeorg.yml
Webshell ReGeorg Detection Via Web Logs
> win_webshell_regeorg.yml

- rules/windows/process_creation/win_apt_taidoor.yml
https://us-cert.cisa.gov/ncas/analysis-reports/ar20-216a
> rule: TAIDOOR malware load

- README.md
- tools/config/stix-linux.yml
- tools/config/stix.yml
- tools/sigma/backends/stix.py
- added and updated fields mapping 
- added "STIX" to project "readme" as target
> STIX Backend added and updated fields mapping 

- tools/config/mitre/tactics.json
- tools/config/mitre/techniques.json
- tools/config/mitre/update_mitre.py
- Updated tactics & techniques json files with automated pull from Mitre CTI Pre, Enterprise & Mobile json repository.
- Added Sub-Techniques 
- Fixed issue where deprecated or revoked techniques could be included in the static json definitions
Addresses Issue : https://github.com/Neo23x0/sigma/issues/974
> + Adding Mitre Sub-Techniques and python update script to fetch latest from Mitre CTI

- tools/config/carbon-black.yml
- tools/sigma/backends/carbonblack.py
- Remap Image to path since some case process_name doesn't work.
- Fix leading wildcard and some escaped characters:
rules/windows/process_creation/win_netsh_wifi_credential_harvesting.yml
Before:  (cmdline:netsh\ wlan\ s\ p*\ k*=clear)*
After: "(cmdline:"netsh wlan s" and p and k and \=clear)"
> Carbon black mapping wrong and fix wild card

- rules/windows/process_access/sysmon_lazagne_cred_dump_lsass_access.yml
https://twitter.com/bh4b3sh/status/1303674603819081728
[LaZagne](https://attack.mitre.org/software/S0349/) is a popular post-exploitation open-source tool for Windows, Linux, and OSX.
LaZagne was most recently used by the [RedCurl](https://www.group-ib.com/resources/threat-research/red-curl.html) group as reported by Group-IB.
> Added Credential Dumping by LaZagne

- rules/windows/other/win_defender_amsi_trigger.yml
Triggering of AMSI detected by Microsoft Defender
> Windows Defender AMSI Trigger Detected

- rules/windows/registry_event/sysmon_comhijack_sdclt.yml
- rules/windows/registry_event/sysmon_comhijack_uac_bypass.yml
addition of specific shell folder registry key and can be used to bypass UAC
> Com hijack shell folder 

- rules/windows/process_creation/win_susp_copy_lateral_movement.yml
Part of oscd sprint 2 - https://github.com/Neo23x0/sigma/issues/576
Sigmac Testing:
`❯ python .\sigmac -t splunk -c .\config\splunk-windows.yml ..\rules\windows\process_creation\win_susp_copy_lateral_movement.yml
((((Image="*\\robocopy.exe" OR Image="*\\xcopy.exe") OR ((Image="*\\cmd.exe") (CommandLine="*copy*"))) OR ((Image="*\\powershell*") (CommandLine="*copy-item*" OR CommandLine="*copy*" OR CommandLine="*cpi *" OR CommandLine="* cp *"))) (CommandLine="*\\\\*\*$*"))`
> [OSCD] Update win_susp_copy_lateral_movement.yml

- rules/windows/process_creation/win_susp_explorer.yml
- rules/windows/process_creation/win_susp_findstr.yml
- rules/windows/process_creation/win_susp_print.yml
- rules/windows/registry_event/sysmon_comhijack_sdclt.yml
explorer.exe LOLbin #40 in https://github.com/Neo23x0/sigma/issues/1014
> [OSCD] Added explorer.exe lolbin

- rules/windows/registry_event/sysmon_comhijack_sdclt.yml
- rules/windows/sysmon/sysmon_psexec_pipes_artifacts.yml
Added a one rule (sysmon_psexec_pipes_artifacts.yml) that closes 2 issues.
> [OSCD] Detecting use PsExec via Pipe Creation/Access to pipes #29 #30

- rules/windows/powershell/powershell_accessing_win_api.yml
https://github.com/Neo23x0/sigma/issues/575
> [OSCD] Detecting use WinAPI Functions in PowerShell #69

- rules/windows/powershell/powershell_code_injection.yml
https://github.com/Neo23x0/sigma/issues/575
> [OSCD] Detecting Code injection with PowerShell in another process #70

- rules/windows/process_creation/win_indirect_cmd_compatibility_assistant.yml
> [OSCD] Pcwrun.exe detection added

- rules/windows/registry_event/sysmon_modify_screensaver_binary_path.yml
OSCD Sprint 2 Atomic Red Team Windows - #1013 
Task 3 - T1546.002: Screensaver
Sigmac test
```bash
$ python tools/sigmac -t splunk -c splunk-windows rules/windows/registry_event/sysmon_modify_screensaver_binary_path.yml
(TargetObject="*\\Control Panel\\Desktop\\SCRNSAVE.EXE" NOT (ParentImage="C:\\Windows\\System32\\services.exe"))
```
> [OSCD] Create sysmon_modify_screensaver_binary_path.yml

- rules/windows/process_creation/win_susp_adfind.yml
Adding shortcut version of command line & some common command lines.
> [OSCD]updated adfind command line

- rules/windows/process_creation/win_invoke_obfuscation_via_var++.yml
> [OSCD] Detects Obfuscated Powershell via VAR++ Launcher #27 (process_creation)

- rules/windows/powershell/powershell_invoke_obfuscation_via_var++.yml
> [OSCD] Detects Obfuscated Powershell via VAR++ Launcher #27 (4104, 4103) 

- rules/windows/powershell/powershell_icmp_exfiltration.yml
OSCD Sprint 2 Atomic Red Team Windows - #1013 
Task 2 - T1048.003: Exfiltration Over Unencrypted/Obfuscated Non-C2 Protocol
Sigmac Test:
```bash
python tools/sigmac -t splunk -c splunk-windows  rules/windows/powershell/powershell_icmp_exfiltration.yml
(source="WinEventLog:Microsoft-Windows-PowerShell/Operational" EventCode="4104" ScriptBlockText="*New-Object*" ScriptBlockText="*System.Net.NetworkInformation.Ping*" ScriptBlockText="*.Send(*")
```
> [OSCD] Create powershell_icmp_exfiltration.yml

- rules/windows/powershell/powershell_invoke_obfuscation_via_stdin.yml
> [OSCD] Detects Obfuscated Powershell via Stdin in Scripts #28 (4104, 4103)

- rules/windows/process_creation/win_invoke_obfuscation_via_stdin.yml
> [OSCD] Detects Obfuscated Powershell via Stdin in Scripts #28 (process_creation)

- rules/windows/process_creation/win_susp_atbroker.yml
This PR is part of OSCD sprint 2
Rule: win_susp_atbroker
Issue: #1014
> [OSCD] LOLBAS atbroker suspicious execution of ATs

- rules/windows/process_creation/win_invoke_obfuscation_via_use_clip.yml
> [OSCD] Detects Obfuscated Powershell via use Clip.exe in Scripts #29 (process_creation)

- rules/windows/powershell/powershell_invoke_obfuscation_via_use_clip.yml
> [OSCD] Detects Obfuscated Powershell via use Clip.exe in Scripts #29 (4104, 4103) 

- rules/windows/process_creation/win_regini.yml
- rules/windows/process_creation/win_regini_ads.yml
Detects the execution of regini.exe.
As far as I know is it not possible to check if there is read from an ADS (unlike the creation of an ADS: Event ID 15), so there is only a detection for the general case.
#1014
> [OSCD] regini LOLBAS 

- rules/windows/process_creation/win_class_exec_xwizard.yml
Regex utilized to specify CLSID
> [OSCD] win_class_exec_xwizard.yml added

- rules/windows/process_creation/win_susp_winrm_execution.yml
> [OSCD] winrm.vbs_2

- rules/windows/process_creation/win_susp_winrm_AWL_bypass.yml
AWL Bypass with Winrm.vbs, copied cscript.exe and malicious WsmPty.xsl/WsmTxt.xsl
#1014
> [OSCD] winrm.vbs_1

- rules/windows/image_load/sysmon_tttracer_mod_load.yml
Both parent execution and module loads implemented in a global rule
> [OSCD] sysmon_tttracer_mod_load.yml added

- rules/windows/process_creation/win_susp_rundll32_setupapi_installhinfsection.yml
LOLBAS Setupapi.yml 100 in #1014
> [OSCD] LOLBAS Setupapi.yml

- rules/windows/process_creation/win_visual_basic_compiler.yml
Parent-child relation defined for suspicious use cases.
> [OSCD] win_visual_basic_compiler.yml added

- tools/config/sumologic-cse.yml
- tools/config/sysmon.yml
- tools/sigma/backends/ala.py
- tools/sigma/backends/carbonblack.py
- tools/sigma/backends/humio.py
- tools/sigma/backends/mdatp.py
- tools/sigma/backends/splunk.py
- tools/sigma/backends/sumologic.py
- tools/sigma/backends/sysmon.py
- tools/sigma/config/mapping.py
Sumo Logic CSE Rule Backend
Updated:
Mapping depence on logsource
Azure Sentinel Query Backend
MDATP: query with few logsources
CROWDSTRIKE: fix generateMapItemTypedNode
> Added: Sumo Logic CSE Rule Backend + Fixes

- tools/sigma/sigma2attack.py
> Update navigator v4

- tools/config/ecs-cloudtrail.yml
- tools/config/ecs-dns.yml
- tools/config/ecs-zeek-corelight.yml
- tools/config/ecs-zeek-elastic-beats-implementation.yml
- tools/config/filebeat-defaultindex.yml
- tools/config/helk.yml
- tools/config/logstash-defaultindex.yml
- tools/config/logstash-linux.yml
- tools/config/logstash-windows.yml
- tools/config/logstash-zeek-default-json.yml
- tools/config/winlogbeat-modules-enabled.yml
- tools/config/winlogbeat-old.yml
- tools/config/winlogbeat.yml
I forgot to adopt the already existing configs regarding kibana-ndjson changes.
> kibana-ndjson for all configs which already have kibana

- tools/sigma/backends/uberagent.py
This commit adds the first version of the uberAgent ESA converter backend for sigma. This backend generates ESA compatible query rules for uberAgent ESA Activity Monitoring.
> Backend: uberAgent ESA converter backend

- .github/workflows/sigma-test.yml
- rules/windows/process_creation/win_susp_file_download_via_gfxdownloadwrapper.yml
> [OSCD] GfxDownloadWrapper downloads file (LoLBin)

- rules/windows/process_creation/win_susp_psexec_eula.yml
- rules/windows/process_creation/win_susp_recon_activity.yml
- rules/windows/process_creation/win_trust_discovery.yml
- rules/windows/registry_event/sysmon_runkey_winekey.yml
Addition based on recent threat reports
> modifying couple of rules

- .github/workflows/sigma-test.yml
- rules/windows/process_creation/win_bad_opsec_sacrificial_processes.yml
[OSCD] Bad Opsec Sacrificial Processes Argument Discrepancy
> [OSCD] Bad Opsec Sacrificial Processes Argument Discrepancy

- rules/linux/macos_emond_launch_daemon.yml
Covering:
Macos task 47 T1546.014: Emond #1012
> [OSCD] MacOS Emond Launch Daemon

- .github/workflows/sigma-test.yml
- rules/windows/registry_event/sysmon_runonce_persistence.yml
Added a rule to detect potential persistence using registry keys
> [OSCD] Added a rule to detect potential persistence using registry keys

- rules/web/web_solarwinds_cve_2020_10148.yml
https://kb.cert.org/vuls/id/843464
Mitigations for _CVE-2020-10148_ is provided by SolarWinds in **Orion Platform Supernova Mitigation.pdf**.
I have tried to reduce false positives as provided in that mitigation file.
> Added rule for CVE-2020-10148 SolarWinds Orion API Authentication Bypass

- .github/workflows/sigma-test.yml
- rules/linux/lnx_security_tools_disabling.yml
Covering:
Linux task 38 T1562.004: Disable or Modify System Firewall #1011
Adding some modifications into an existing sigma rule.
> [OSCD] Firewall Disable (Linux)

- rules/linux/macos_applescript.yml
Covering:
MacOs task 19 T1059.002: AppleScript #1012
> [OSCD] MacOS Applescript

- .github/workflows/sigma-test.yml
- rules/linux/lnx_network_service_scanning.yml
- rules/linux/macos_network_service_scanning.yml
Covering:
Linux task 7 T1046: Network Service Scanning #1011
MacOs task 12 T1046: Network Service Scanning #1012
> [OSCD] Network Service Scanning

- rules/linux/macos_disable_security_tools.yml
> [OSCD] ART sync, test T1562.001: Disable or Modify Tools (macOS)

- rules/linux/macos_xattr_gatekeeper_bypass.yml
> [OSCD] ART sync, test T1553.001: Gatekeeper Bypass (macOS)

- rules/linux/lnx_security_software_discovery.yml
> [OSCD] ART sync, test T1518.001: Security Software Discovery (Linux)

- rules/linux/macos_security_software_discovery.yml
> [OSCD] ART sync, test T1518.001: Security Software Discovery (macOS)

- tools/sigma/backends/elasticsearch.py
- introduce a new backend parameter key "size" to set the number of data rows returned by the query
- support "fields" from sigma rule (copied code from splunk backend :-)
> [backend] [elasticsearch] new parameter and fields support

- rules/linux/lnx_system_network_connections_discovery.yml
> [OSCD] ART sync, test T1049: System Network Connections Discovery (Linux)

- rules/linux/macos_system_network_connections_discovery.yml
> [OSCD] ART sync, test T1049: System Network Connections Discovery (macOS)

- rules/linux/lnx_base64_decode.yml
> [OSCD] ART sync, test T1027: Obfuscated Files or Information (Linux) 

- rules/linux/macos_base64_decode.yml
Task 3 from https://github.com/Neo23x0/sigma/issues/1012
> [OSCD] ART sync, test T1027: Obfuscated Files or Information (macOS)

- tools/sigma/backends/elasticsearch.py
Fix issue https://github.com/Neo23x0/sigma/issues/1285.
Maybe solution more clean, but work!
THanks
> fix issue 1285

- rules/linux/macos_file_and_directory_discovery.yml
> [OSCD] ART sync, test T1083: File and Directory Discovery (macOS)

- rules-unsupported/win_access_fake_files_with_stored_credentials.yml
- rules/windows/builtin/win_access_fake_files_with_stored_credentials.yml
> [OSCD] Add Stored Credentials in Fake Files rule

- rules/windows/builtin/win_powershell_script_installed_as_service.yml
- rules/windows/registry_event/sysmon_powershell_as_service.yml
[OSCD Initiative] Develop Sigma rules for PowerShell Abuse #575: Task #31 (PowerShell Scripts Installed as Services).
> [OSCD] Powershell Script Installed as a Service Rule added

- .github/workflows/sigma-test.yml
- rules/linux/lnx_process_discovery.yml
- rules/windows/registry_event/sysmon_comhijack_sdclt.yml
https://github.com/Neo23x0/sigma/issues/1011 
Task 11
> [OSCD] T1057: Process Discovery

- rules/linux/at_command.yml
- rules/windows/registry_event/sysmon_comhijack_sdclt.yml
https://github.com/Neo23x0/sigma/issues/1011
Task 9
> [OSCD] Scheduled Task/Job: At

- rules/windows/process_creation/win_susp_pester.yml
Detects code execution via Pester.bat (Pester - Powershell Modulte for testing) 
#1014
> [OSCD] 109: Pester.bat 

- rules/windows/powershell/powershell_invoke_obfuscation_via_use_mhsta.yml
Made it a single regular expression.
> [OSCD] Detects Obfuscated Powershell via use MSHTA in Scripts #31 (4104, 4103)

- rules/windows/process_creation/win_invoke_obfuscation_via_use_mhsta.yml
Made it a single regular expression.
> [OSCD] Detects Obfuscated Powershell via use MSHTA in Scripts #31 (process_creation) 

- rules/windows/builtin/win_invoke_obfuscation_via_use_rundll32_services.yml
https://github.com/Neo23x0/sigma/issues/1009 - add Rule3 Task 30
> [OSCD] Detects Obfuscated Powershell via use Rundll32 in Scripts #30 (Services)

- rules/windows/builtin/win_invoke_obfuscation_via_use_mhsta_services.yml
> [OSCD] Detects Obfuscated Powershell via use MSHTA in Scripts #31 (Services)

- rules/windows/builtin/win_invoke_obfuscation_via_use_clip_services.yml
> [OSCD] Detects Obfuscated Powershell via use Clip.exe in Scripts #29 (Services) 

- rules/linux/macos_create_hidden_account.yml
> [OSCD] macOS hidden user creation

- rules/linux/macos_clear_system_logs.yml
Part of https://github.com/Neo23x0/sigma/issues/1012
Adding T1070.002. Glad to move or rename depending on the future location of macos rules.
> [OSCD] Adding t1070_002 - Clear mac system logs

- rules/windows/builtin/win_invoke_obfuscation_via_stdin_services.yml
> [OSCD] Detects Obfuscated Powershell via Stdin in Scripts #28 (Services)

- rules/windows/builtin/win_invoke_obfuscation_via_var++_services.yml
> [OSCD] Detects Obfuscated Powershell via VAR++ Launcher #27 (Services)

- rules/windows/registry_event/sysmon_susp_atbroker_change.yml
This PR is part of OSCD sprint 2
Rule: sysmon_susp_atbroker_change
Issue: #1014
> [OSCD] LOLBAS atbroker suspicious creation of ATs

- rules/linux/macos_screencapture.yml
Part of https://github.com/Neo23x0/sigma/issues/1012
Task 32 - T1113: Screen Capture
> [OSCD] - T1113 - macOS Screencapture via builtin screencapture utility

- rules/windows/process_creation/win_susp_use_of_te_bin.yml
> [OSCD] LOLBin te.exe #133

- rules/windows/process_creation/win_susp_use_of_vsjitdebugger_bin.yml
> [OSCD] LOLBin vsjitdebugger.exe #136

- rules/windows/builtin/win_invoke_obfuscation_clip+_services.yml
- rules/windows/builtin/win_invoke_obfuscation_stdin+_services.yml
- rules/windows/builtin/win_invoke_obfuscation_var+_services.yml
- rules/windows/powershell/powershell_invoke_obfuscation_clip+.yml
- rules/windows/powershell/powershell_invoke_obfuscation_stdin+.yml
- rules/windows/powershell/powershell_invoke_obfuscation_var+.yml
- rules/windows/process_creation/win_invoke_obfuscation_clip+.yml
- rules/windows/process_creation/win_invoke_obfuscation_stdin+.yml
- rules/windows/process_creation/win_invoke_obfuscation_var+.yml
> [OSCD] Tasks 24, 25 & 26: Detection for Invoke-Obfuscation CLIP+, STDIN+ & VAR+ Launchers

- rules/windows/process_creation/win_regedit_export_critical_keys.yml
- rules/windows/process_creation/win_regedit_export_keys.yml
- rules/windows/process_creation/win_regedit_import_keys.yml
- rules/windows/process_creation/win_regedit_import_keys_ads.yml
- rules/windows/sysmon/sysmon_regedit_export_to_ads.yml
(second) Rebase of #1075
The rules cover:
General import (medium level)
ADS import (high level)
General export (low level)
Critical keys export (high level)
ADS export (high level)
> [OSCD] regedit.exe LOLbas 72 [3]

- rules/windows/registry_event/sysmon_wab_dllpath_reg_change.yml
[OSCD] LOLBAS wab.yml (#1014 - 80)
> [OSCD] LOLBAS wab.yml

- rules/windows/process_creation/win_CL_Invocation_LOLScript.yml
[OSCD] LOLBAS CL_Invocation.yml (#1014 - 106)
> [OSCD] LOLBAS CL_Invocation - process_creation

- .github/workflows/sigma-test.yml
- rules/windows/powershell/powershell_CL_Invocation_LOLScript.yml
- rules/windows/powershell/powershell_CL_Invocation_LOLScript_v2.yml
Adding powershell_CL_Invocation_LOLScript.yml Rule (#1014 - 106)
> [OSCD] LOLBAS CL_Invocation - powershell

- .github/workflows/sigma-test.yml
- rules/windows/powershell/powershell_CL_Mutexverifiers_LOLScript.yml
- rules/windows/powershell/powershell_CL_Mutexverifiers_LOLScript_v2.yml
Adding powershell_CL_Mutexverifiers_LOLScript.yml Rule (#1014 - 107)
> [OSCD] LOLBAS CL_Mutexverifiers - powershell

- rules/windows/process_creation/win_manage-bde_lolbas.yml
Adding win_manage-bde_lolbas.yml Rule (#1014 - 108)
> [OSCD] LOLBAS Manage-bde.yml

- rules/windows/process_creation/sysmon_always_install_elevated_msi_spawned_cmd_and_powershell.yml
Page [50](https://image.slidesharecdn.com/kheirkhabarovoffzonefinal-181117201458/95/hunting-for-privilege-escalation-in-windows-environment-50-638.jpg) from #574  Rule 1
Look for msiexec spawning command line or powershell
> [OSCD] Always Install Elevated - Slide 50 - Rule 1

- rules/windows/process_creation/sysmon_always_install_elevated_msi_spawned_cmd_and_powershell_spawned_processes.yml
Page [50](https://image.slidesharecdn.com/kheirkhabarovoffzonefinal-181117201458/95/hunting-for-privilege-escalation-in-windows-environment-50-638.jpg) from #574 Rule 2
Look for msiexec spawning command line or powershell then it spawns other processes
Using enrichment as suggested by @yugoslavskiy - [#574 (comment)](https://github.com/Neo23x0/sigma/issues/574#issuecomment-707441823)
>  [OSCD] Always Install Elevated - Slide 50 - Rule 2

- rules/windows/builtin/win_software_discovery.yml
> [OSCD] Atomic Red Team: Detected Windows Software Discovery (T1518) 

- rules/linux/lnx_susp_histfile_operations.yml
- rules/linux/macos_susp_histfile_operations.yml
For issues [#1011](https://github.com/Neo23x0/sigma/issues/1011) and [#1012](https://github.com/Neo23x0/sigma/issues/1012)
> [OSCD] T1552.003: Suspicious history file operations - Linux/macOS

- rules/windows/process_creation/win_run_powershell_script_from_input_stream.yml
Added a rule to detect the launch of a PowerShell with redirection of the input stream.
Task№ 5 from https://github.com/Neo23x0/sigma/issues/1014
> [OSCD] LOLBIN 5 PowerShell with redirection of the input stream.

- rules/windows/process_creation/win_susp_csi.yml
> [OSCD] suspicious csi.exe (rcsi.exe)  LOLBAS detection rule

- rules/windows/builtin/win_invoke_obfuscation_via_rundll_services.yml
- rules/windows/powershell/powershell_invoke_obfuscation_via_rundll.yml
- rules/windows/process_creation/win_invoke_obfuscation_via_rundll.yml
> [OSCD] Detects Obfuscated Powershell via RUNDLL Launcher #23 (4104, 4103 + Services + process_creation)

- rules/windows/process_creation/win_winword_dll_load.yml
> [OSCD] - Force winword.exe to load DLL (LoLBin)

- rules/windows/process_creation/win_susp_runscripthelper.yml
> [OSCD] - Runscripthelper.exe runs script (LoLBin)

- rules/windows/builtin/win_invoke_obfuscation_via_compress_services.yml
- rules/windows/powershell/powershell_invoke_obfuscation_via_compress.yml
- rules/windows/process_creation/win_invoke_obfuscation_via_compress.yml
> [OSCD] Detects Obfuscated Powershell via COMPRESS OBFUSCATION #19 (4104, 4103 + Services + process_creation)

- rules/windows/builtin/win_av_relevant_match.yml
- rules/windows/malware/av_password_dumper.yml
- rules/windows/malware/av_webshell.yml
- rules/windows/process_creation/win_webshell_detection.yml
some of the AV events are duplicates to win_av_relevant_match.yml, should we clean that up or include the strings in both?
> more AV event and suspicious commands

- rules/windows/process_creation/win_susp_emotet_rudll32_execution.yml
Detecting Emotet DLL loading by looking for rundll32.exe processes with command lines ending in ,RunDLL or ,#1.
Ref: https://paste.cryptolaemus.com/emotet/2020/12/22/emotet-malware-IoCs_12-22-20.html
> Detect Emotet DLL loading by looking rundll32.exe

- rules/windows/builtin/win_ntfs_vuln_exploit.yml
https://twitter.com/jonasLyk/status/1347900440000811010
> rule: NTFS vulnerability

- rules/windows/process_creation/win_webshell_detection.yml
add commands and TTP from https://unit42.paloaltonetworks.com/bumblebee-webshell-xhunt-campaign/
> Add xHunt Campaign: BumbleBee Webshell

- rules/linux/lnx_file_and_directory_discovery.yml
> [OSCD] ART sync, test T1083: File and Directory Discovery (Linux)

- rules/windows/process_creation/win_sus_auditpol_usage.yml
This adds detection for suspicious behaviour of the auditpol binary
> Created win_sus_auditpol_usage.yml

- rules/linux/auditd/lnx_auditd_cve_2021_3156_sudo_buffer_overflow.yml
- rules/web/web_terramaster_cve_2020_28188_rce_exploit.yml
Added payload selection as I suspect '/include/makecvs.php'?Event=' alone might produce false positives. Just my assumption!
> Added rule for TerraMaster TOS CVE-2020-28188

- rules/windows/process_creation/win_susp_rundll32_inline_vbs.yml
- rules/windows/process_creation/win_susp_rundll32_sys.yml
- rules/windows/process_creation/win_susp_vbscript_unc2452.yml
- rules/windows/registry_event/sysmon_reg_vbs_payload_stored.yml
https://www.microsoft.com/security/blog/2021/03/04/goldmax-goldfinder-sibot-analyzing-nobelium-malware/
> UNC2452 rules - GoldMax, GoldFinder, Sibot

- rules/web/win_powershell_snapins_hafnium.yml
- rules/windows/process_creation/win_powershell_reverse_shell_connection.yml
Detect HAFNIUM operations for Reverse Shell Connection using Powershell and Exchange Powershell Snap-ins
> Detect HAFNIUM operations

- tools/sigma/configuration.py
- tools/sigma/parser/rule.py
added functionality for the (documented) parameter logsourcemerging
> functionality for parameter logsourcemerging

- tools/sigma/backends/mdatp.py
Added compatibility to add DeviceImageLoadEvents if "image_load" category is found. Also, field ImageLoaded added to the mapping.
> Updated for use with Image Load events

- rules/windows/process_creation/win_etw_trace_evasion.yml
Just to replace Commandline by CommandLine
> Fix win_etw_trace_evasion rule

- rules/windows/process_creation/win_proc_wrong_parent.yml
> Add "Microsoft Security Client" directory for MsMpEng.exe (Win<8)

- rules/windows/builtin/win_set_oabvirtualdirectory_externalurl.yml
Rule to detect an adversary setting OabVirtualDirectory External URL property to a script
> CVE-2021-27065 - Set OabVirtualDirectory ExternalUrl Property

- rules/windows/malware/av_password_dumper.yml
-Dumpert based LSASS dump using DLL
-Dumpert.exe detection
> Added detection for Dumpert

- rules/web/web_cve_2021_21978_vmware_view_planner_exploit.yml
Note: Google translation is very bad due to being Chinese source. May require your verification.
> Added rule for CVE-2021-21978 in VMware View Planner

- tools/sigma/backends/limacharlie.py
LimaCharlie recently added support for real-time collection of Windows Event Logs (as opposed to the already supported file-based method of collection).
This PR adds a new `lc_target` option for the LimaCharlie backend. This option defaults to the new method (`edr` value) but also supports the old method (`artifact`).
> Add option to support different LimaCharlie targets.

- tools/sigma/backends/elasticsearch.py
Transform supported count() aggregations (> and >=, no count field,
optionally a group by field) into a threshold detection rule.
> Implement Elastic threshold detection rules

- rules/windows/builtin/win_hybridconnectionmgr_svc_installation.yml
- rules/windows/builtin/win_hybridconnectionmgr_svc_running.yml
- rules/windows/registry_event/sysmon_hybridconnectionmgr_svc_installation.yml
- rules/windows/sysmon/sysmon_dns_hybridconnectionmgr_servicebus.yml
A few basic queries to identify behavior related to the installation and use of the Hybrid Connection Manager service. This service can be installed to control an on-prem workstation from Azure function apps (Azure Functions)
References:
* https://twitter.com/_dirkjan/status/1381591080207015936
* https://twitter.com/Cyb3rWard0g/status/1381642789369286662
* https://twitter.com/Cyb3rWard0g/status/1381682435914674178
> HybridConnectionMgr Service Activity

- rules/windows/builtin/win_invoke_obfuscation_obfuscated_iex_services.yml
- rules/windows/builtin/win_meterpreter_or_cobaltstrike_getsystem_service_installation.yml
- rules/windows/builtin/win_tap_driver_installation.yml
Noticed some extra spaces which broke a parser I was writing.
> Remove extra spaces

- tools/config/thor.yml
Needed for THOR using some linux specific rules for scanning generic log files
> THOR: search generic *.log files for product: linux

- tools/config/thor.yml
Revert recent changes for Windows / Linux .log files for THOR
because of massive performance impacts.
> chore: Revert log file changes for THOR sigma configuration

- tools/sigma/backends/limacharlie.py
Expanding our coverage of rules from the Windows only rules to the `linux` directory (Linux and macOS).
This will enable LimaCharlie to generate and apply the Sigma rules for Linux and macOS to the real-time Detection & Response rules engine.
> Add support for macOS rules and fix case sensitivity.

- rules/windows/builtin/win_moriya_rootkit.yml
- rules/windows/image_load/sysmon_alternate_powershell_hosts_moduleload.yml
- rules/windows/image_load/sysmon_susp_python_image_load.yml
- rules/windows/process_creation/win_susp_adfind.yml
- rules/windows/process_creation/win_susp_wuauclt.yml
- rules/windows/registry_event/sysmon_registry_add_local_hidden_user.yml
- rules/windows/registry_event/sysmon_sysinternals_sdelete_registry_keys.yml
I have the rules with : 
`python sigmac --verbose -t elastalert -c .\config\generic\sysmon.yml ..\rules\windows\rule_name.yml`
So I have change **service** to **category** to have the correct EventId.
No change on the detection itselft
> Check category

- rules/network/zeek/zeek_dns_suspicious_zbit_flag.yml
- rules/windows/process_creation/win_regini.yml
- rules/windows/process_creation/win_regini_ads.yml
- rules/windows/registry_event/sysmon_susp_atbroker_change.yml
- rules/windows/sysmon/sysmon_accessing_winapi_in_powershell_credentials_dumping.yml
Fix some typo fields use when convert 
Other errors are in #1496
> Fix some typo

- tools/sigma/backends/uberagent.py
This PR updates the uberAgent ESA backend to generate rules that are compatible with the new uberAgent 6.1 version including new rule types.
> Updated uberAgent backend to support version 6.1.

- rules/linux/macos_change_file_time_attr.yml
- rules/linux/macos_find_cred_in_files.yml
- rules/linux/macos_remote_system_discovery.yml
- rules/windows/powershell/powershell_invoke_obfuscation_via_var++.yml
- rules/windows/process_creation/process_creation_msdeploy.yml
- rules/windows/process_creation/sysmon_proxy_execution_wuauclt.yml
- rules/windows/process_creation/sysmon_susp_webdav_client_execution.yml
- rules/windows/process_creation/win_invoke_obfuscation_via_var++.yml
- rules/windows/process_creation/win_susp_regedit_trustedinstaller.yml
- rules/windows/registry_event/sysmon_wdigest_enable_uselogoncredential.yml
as noted in https://github.com/SigmaHQ/sigma/issues/1506
> duplicate UUIDs, regedit as trusted installer

- rules/windows/builtin/win_mal_service_installs.yml
- rules/windows/registry_event/sysmon_wdigest_enable_uselogoncredential.yml
Find the two last  duplicate uuid
- sysmon_susp_webdav_client_execution.yml
- sysmon_wdigest_enable_uselogoncredential.yml
- win_cobaltstrike_service_installs.yml
- win_mal_service_installs.yml
> Two last duplicate UUID

- rules/compliance/cleartext_protocols.yml
- rules/compliance/host_without_firewall.yml
- rules/linux/lnx_system_info_discovery.yml
- rules/windows/other/win_defender_history_delete.yml
- rules/windows/other/win_possible_zerologon_exploitation_using_wellknown_tools.yml
- rules/windows/process_creation/win_task_folder_evasion.yml
- tools/config/winlogbeat-modules-enabled.yml
- tools/config/winlogbeat-old.yml
- tools/config/winlogbeat.yml
fix some typo or logic in logsource to get more accurate detection
- product is lowercase
- `windefend` service
-  `auditd` service
- `firewall` category
- remove the only use one `other` category
add the `System channel` in winlogbeat config
> Fix some logsource to get more accurate

- rules/windows/process_creation/win_shadow_copies_deletion.yml
* Add diskshadow.exe to existing detection
* Add new detection for wbadmin.exe
* Fix typo in match on L31
* Add raccine refs
> Add further detections to shadow copies deletion

- rules/windows/builtin/win_global_catalog_enumeration.yml
Hi,
the Filtering EvendiD 5156 is in the security channel.
Add ref to microsoft information
> Filtering Platform Connection are in security channel not system

- rules/windows/builtin/win_cobaltstrike_service_installs.yml
Changed for consistency and to avoid issues with some backends.
> Consistency: Service File Name to ServiceFileName

- rules/windows/sysmon/sysmon_config_modification.yml
- tools/config/winlogbeat-modules-enabled.yml
Hi,
The goal is to detect if symon is modified or stopped.
The attacker should normally be silent.
> Detect modification of sysmon configuration by sysmon

- rules/windows/registry_event/sysmon_removal_amsi_registry_key.yml
Remove the AMSI Provider registry key in HKLM\Software\Microsoft\AMSI to disable AMSI inspection
As there is too many way to delete a key  focus on detecting the DeleteKey event.
**Warning** : the keys have to been monitored to work
> T1562.001 Remove the AMSI Provider registry key 

- rules/windows/process_creation/win_susp_ngrok_rdp_pua.yml
Add further detections and ports to ngrok rule. What I did
* Add new selection for a more generic detection of ngrok.exe usage.
* Add WinRM and SMB ports to selection.
* Add authtoken string for authentication of a ngrok client.
* Add further reference.
* Add fp link for https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-channel-ngrok?view=azure-bot-service-4.0
> Update ngrok usage rule

- rules/windows/powershell/powershell_delete_volume_shadow_copies.yml
Hi,
this is the same detection goal as win_shadow_copies_deletion but on the powershell side .
Test with atomic-red-team
> Add t1490 powershell delete volume shadow copie

- tools/sigma/backends/mdatp.py
Support for the equivalent event to EventID 7045 (A new service was installed) for MDATP/MDE.
> MDATP ServiceInstalled mapping

- tools/sigma/filter.py
**Propose**
As there is a es-eql backends now, I have add  a filter to selection rule with near .
Of course add the condition=! to exclude the near rules 
```
python sigmac -t es-eql -r -c .\config\generic\sysmon.yml --filter condition=near ..\rules\windows
python sigmac -t es-qs -r -c .\config\generic\sysmon.yml --filter condition!=near ..\rules\windows
```
> Add New filter condition

- rules/windows/sysmon/sysmon_config_modification.yml
- rules/windows/sysmon/sysmon_dns_hybridconnectionmgr_servicebus.yml
- rules/windows/sysmon/sysmon_wmiprvse_wbemcomn_dll_hijack.yml
Hi,
Convert some rule from hard EventID to category.
> Fix some sysmon category

- rules/windows/builtin/win_arbitrary_shell_execution_via_settingcontent.yml
- rules/windows/builtin/win_asr_bypass_via_appvlp_re.yml
- rules/windows/builtin/win_suspicious_werfault_connection_outbound.yml
- rules/windows/process_creation/win_credential_access_via_password_filter.yml
- rules/windows/process_creation/win_detecting_fake_instances_of_hxtsr.yml
- rules/windows/process_creation/win_hiding_malware_in_fonts_folder.yml
- rules/windows/process_creation/win_lolbas_execution_of_wuauclt.yml
- rules/windows/process_creation/win_lolbin_execution_via_winget.yml
- rules/windows/process_creation/win_modif_of_services_for_via_commandline.yml
- rules/windows/process_creation/win_monitoring_for_persistence_via_bits.yml
- rules/windows/process_creation/win_sticky_keys_unauthenticated_privileged_console_access.yml
- rules/windows/process_creation/win_write_protect_for_storage_disabled.yml
- rules/windows/sysmon/sysmon_abusing_windows_telemetry_for_persistence.yml
Hello,
This is the work of  @sreemanshanker PR  #617.
I've just make the detection pass the test commit.
> Fix all the rules to pass the test

- rules/windows/builtin/win_susp_lsass_dump.yml
- rules/windows/create_remote_thread/sysmon_password_dumper_lsass.yml
- rules/windows/deprecated/sysmon_mimikatz_detection_lsass.yml
- rules/windows/process_access/sysmon_lsass_dump_comsvcs_dll.yml
- rules/windows/process_access/sysmon_lsass_memdump.yml
- rules/windows/process_access/sysmon_mimikatz_trough_winrm.yml
Hi,
Fix rules to get the same logic for lsass.exe.
close #1457 .
> Update rule lsass.exe to endswith

- rules/windows/process_creation/win_netsh_port_fwd.yml
- rules/windows/registry_event/win_portproxy_registry_key.yml
Hope that addition helps others to use their time better than a forensic analysis to find that out ;)
> Add false positive note to PortProxy rules

- rules/windows/other/win_ldap_recon.yml
Detect enumeration / reconnaissance via LDAP query logging
> Add rule to detect AD enumeration

- rules/windows/builtin/win_cobaltstrike_service_installs.yml
- rules/windows/registry_event/sysmon_cobaltstrike_service_installs.yml
Similar approach like in https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/win_cobaltstrike_service_installs.yml, but base on registry events.
> CobaltStrike Service Installations in Registry

- rules/windows/process_creation/win_run_virtualbox.yml
Hi,
Just a cleanup of a old waiting PR from Sep 2020
Close #1022
> Fix file from PR 1022

- rules/windows/builtin/win_exploit_cve_2021_1675_printspooler.yml
- rules/windows/builtin/win_susp_failed_guest_logon.yml
See this thread: https://twitter.com/cyb3rops/status/1410154128563703808
> rules: CVE-2021-1675 exploitation events

- rules/windows/network_connection/sysmon_remote_powershell_session_network.yml
Typo fixes and grammar correction.
> Update sysmon_remote_powershell_session_network.yml - Typos

- rules/web/web_nginx_core_dump.yml
Fixed typo in description field.
> Update web_nginx_core_dump.yml - Typo

- rules/windows/powershell/powershell_powerview_malicious_commandlets.yml
Added new commandlet names based on aliases seen in https://github.com/PowerShellMafia/PowerSploit/blob/master/Recon/PowerView.ps1, fixed a typo, and improved formatting.
> Update powershell_powerview_malicious_commandlets.yml - Addition and Miscellaneous

- rules/windows/process_creation/win_renamed_powershell.yml
Hi,
I have check some powershell I can find (https://github.com/PowerShell/PowerShell).
I get :
- Description: Windows PowerShell
- Description: Windows PowerShell ISE
- Description: pwsh
So I make change to the detection.
> Tune detection in win_renamed_powershell.yml

- rules/windows/file_event/sysmon_susp_pfx_file_creation.yml
Fixed typo and added a possible false positive.
> Update sysmon_susp_pfx_file_creation.yml - Typo

- rules/windows/builtin/win_susp_sdelete.yml
> Update win_susp_sdelete.yml - Outdated Link and Typo

- rules/windows/powershell/powershell_data_compressed.yml
Corrected old link and formatting.
> Update powershell_data_compressed.yml - Outdated link

- rules/windows/registry_event/win_registry_mimikatz_printernightmare.yml
> rule: mimikatz printernightmare

- rules/windows/builtin/win_susp_failed_guest_logon.yml
Hi,
get a error when convert to es-rule because description is 'null' so add one
> fix missing description

- rules/windows/powershell/powershell_renamed_powershell.yml
Hi,
make some test and get 
```
HostApplication=powershell_ise test.ps1
HostApplication=C:\test\powershell_v7.exe test.ps1
HostApplication=frack113 test.ps1
HostApplication=powershell test.ps1
```
So make some change 
close #869
> Fix PR 869

- rules/windows/builtin/win_mal_service_installs.yml
Add new malicious service (javamtsup) by APT29, reference links, and event ID.
Some background references to (new) event ID 4697:
https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4697
https://blog.menasec.net/2019/03/threat-hunting-26-remote-windows.html
> Update win_mal_service_installs.yml - Add service & event ID

- rules/windows/process_creation/win_susp_use_of_vsjitdebugger_bin.yml
Hi
I am working on mapping.
`childimage ` do not exist it is Image.
> childimage do not exist in sysmon schema

- rules/windows/registry_event/win_registry_mimikatz_printernightmare.yml
https://github.com/gentilkiwi/mimikatz/commit/51dc7c0363d4e1e1eb2d35f5d5a25841b0801861#diff-cf4373b6c7195386ac1973681e5561bd96e1bb9e099cfd3febd1111e986bd17cL1450-R1451
> rule: PrinterNightmare Mimikatz update

- rules/windows/builtin/win_smb_file_creation_admin_shares.yml
- rules/windows/image_load/sysmon_uipromptforcreds_dlls.yml
- rules/windows/image_load/sysmon_wmic_remote_xsl_scripting_dlls.yml
> Update mordordatasets links

- rules/windows/process_creation/win_purplesharp_indicators.yml
- rules/windows/process_creation/win_susp_renamed_paexec.yml
Hi,
I have make a update as it is `OriginalFileName` in sysmon SYSMON_CREATE_PROCESS schema
> change OriginalFilename case

- rules/windows/builtin/win_susp_failed_logons_single_source_kerberos.yml
- rules/windows/builtin/win_susp_failed_logons_single_source_kerberos2.yml
- rules/windows/builtin/win_susp_failed_logons_single_source_kerberos3.yml
Hi,
I have corrected some fields that do not exist
ref:
- https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4768
- https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4771
> Fix invalid field name

- rules/windows/builtin/win_metasploit_authentication.yml
- rules/windows/builtin/win_new_or_renamed_user_account_with_dollar_sign.yml
- rules/windows/builtin/win_privesc_cve_2020_1472.yml
- rules/windows/builtin/win_rdp_localhost_login.yml
- rules/windows/builtin/win_susp_failed_logons_single_source.yml
- rules/windows/builtin/win_susp_rottenpotato.yml
- rules/windows/process_creation/win_apt_wocao.yml
Hi,
fix last windows invalid field form windows ref : https://docs.microsoft.com/en-us/windows/security/threat-protection/
> fix invalid windows fields name

- rules/windows/builtin/win_admin_rdp_login.yml
1. Field name changed to `TargetUserName`.
Source: https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624
2. Value changed from `Admin-` to `Admin`.
> Update win_admin_rdp_login.yml - Fix Field Name & Value

- rules/windows/builtin/win_susp_local_anon_logon_created.yml
Hi,
use the correct field nane form https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4720
> win_susp_local_anon_logon_created.yml fix invalid case SamAccountName

- rules/windows/builtin/win_possible_dc_shadow.yml
Hi,
use the correct field nane form https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5136
> fix invalid field EventID 5136

- rules/windows/builtin/win_external_device.yml
Hi,
use the correct field nane form https://docs.microsoft.com/fr-fr/windows/security/threat-protection/auditing/event-6416
> win_external_device.yml  fix invalid field name

- rules/windows/builtin/win_rdp_reverse_tunnel.yml
Hi,
use the correct field nane form https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5156
> win_rdp_reverse_tunnel.yml  fix invalid field name

- rules/windows/process_creation/sysmon_remove_windows_defender_definition_files.yml
- rules/windows/process_creation/sysmon_susp_service_modification.yml
Hi,
Just add 2 rules form atomic-red-team:
- [Remove Windows Defender Definition Files](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1562.001/T1562.001.md#atomic-test-19---remove-windows-defender-definition-files)
- [Stop and Remove Arbitrary Security Windows Service](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1562.001/T1562.001.md#atomic-test-20---stop-and-remove-arbitrary-security-windows-service)
> Add 2 defense-evasion T1562.001 rules

- rules/windows/process_creation/win_apt_apt29_thinktanks.yml
Changed reference link (redirected) and added new one to supplement (old link's images no longer works).
> Update win_apt_apt29_thinktanks.yml - Links

- rules/windows/builtin/win_privesc_cve_2020_1472.yml
- rules/windows/builtin/win_susp_failed_logons_single_process.yml
- rules/windows/builtin/win_susp_failed_logons_single_source_ntlm.yml
- rules/windows/builtin/win_susp_failed_logons_single_source_ntlm2.yml
- rules/windows/builtin/win_susp_logon_explicit_credentials.yml
- rules/windows/process_creation/win_detecting_fake_instances_of_hxtsr.yml
- tools/config/winlogbeat-modules-enabled.yml
- tools/config/winlogbeat.yml
Hi,
I fix some other invalid windows fields and missing mapping
> Fix more windows fields name

- rules/windows/builtin/win_exploit_cve_2021_1675_printspooler.yml
- rules/windows/builtin/win_exploit_cve_2021_1675_printspooler_operational.yml
- rules/windows/image_load/win_suspicious_vss_ps_load.yml
- rules/windows/registry_event/win_registry_mimikatz_printernightmare.yml
> rule: suspicious vss ps load / PrinternightMare updates

- tools/config/thor.yml
dirty fix to allow the application of sections with multiple Event IDs
> refactor: THOR config adjustments

- rules/windows/builtin/win_account_backdoor_dcsync_rights.yml
- rules/windows/builtin/win_susp_eventlog_cleared.yml
- rules/windows/builtin/win_susp_failed_remote_logons_single_source.yml
Hi,
Fix last (I hope) rules with invalid windows field name.
> Last fix invalid windows field name

- rules-unsupported/sysmon_always_install_elevated_msi_spawned_cmd_and_powershell_spawned_processes.yml
- rules-unsupported/win_kernel_and_3rd_party_drivers_exploits_token_stealing.yml
- rules-unsupported/win_possible_privilege_escalation_using_rotten_potato.yml
Hi,
Move rule to rules-unsupported as it use special enrichment field.
close #1646
> Move to rules-unsupported as use special enrichment field

- rules/windows/process_creation/sysmon_uninstall_crowdstrike_falcon.yml
- rules/windows/process_creation/win_powershell_defender_exclusion.yml
Hi,
I've works on [T1562.001 red canary tests](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1562.001/T1562.001.md)
- New rule to  test 21  Uninstall Crowdstrike Falcon on Windows 
- Update to detect  tests 22,23,24 Tamper with Windows Defender Evade Scanning
> Atomic Red team T1562.001

- rules/windows/malware/av_printernightmare_cve_2021_34527.yml
- rules/windows/process_creation/win_susp_netsh_dll_persistence.yml
- rules/windows/sysmon/sysmon_abusing_windows_telemetry_for_persistence.yml
Hi,
I've find some typo error.
I've make **no** detection change.
> Fix some typo error

- rules/windows/builtin/win_susp_athremotefxvgpudisablementcommand.yml
- rules/windows/process_creation/process_creation_protocolhandler_suspicious_file.yml
- rules/windows/process_creation/win_workflow_compiler.yml
Hi,
I check redcany for:
|Tactic|Technique|Technique Name|Test|Test Name|Rule|
|---|---|---|---|---|---|
| defense-evasion|T1218|Signed Binary Proxy Execution|5|ProtocolHandler.exe Downloaded a Suspicious File|New
| defense-evasion|T1218|Signed Binary Proxy Execution|6|Microsoft.Workflow.Compiler.exe Payload Execution|Update
| defense-evasion|T1218|Signed Binary Proxy Execution|7|Renamed Microsoft.Workflow.Compiler.exe Payload Executions|Update
| defense-evasion|T1218|Signed Binary Proxy Execution|8|Invoke-ATHRemoteFXvGPUDisablementCommand base test|New
> Redcanary t1228 end

- rules/windows/other/win_defender_exclusions.yml
- tools/config/thor.yml
tested and works, may need to add the windefend logsource to other backends
> medium level Rule for Windows Defender Exclusions

- rules/windows/powershell/powershell_invoke_obfuscation_via_var++.yml
- rules/windows/process_creation/win_monitoring_for_persistence_via_bits.yml
- rules/windows/sysmon/sysmon_abusing_windows_telemetry_for_persistence.yml
Hi 
Fix some regex with escape `/`
close #1685
> escape / in regex

- rules/windows/other/win_defender_exclusions.yml
- rules/windows/process_creation/win_susp_servu_process_pattern.yml
Hi,
Just fix :
- duplicate UUID
- empty references
> fix missing references and duplicate UUID

- rules/windows/process_creation/sysmon_hack_wce.yml
- rules/windows/process_creation/win_susp_mshta_pattern.yml
- rules/windows/process_creation/win_susp_regsvr32_anomalies.yml
- rules/windows/process_creation/win_susp_regsvr32_no_dll.yml
- fix for wce rule and FPs with Windows cluster service
- mshta anomalies
- regsvr32 anomalies
> several new rules and fixes

- rules/windows/process_creation/process_creation_syncappvpublishingserver_vbs_execute_powershell.yml
- rules/windows/process_creation/win_manage-bde_lolbas.yml
Hi,
Some more Redcanary tests
|Tactic|Technique|Technique Name|Test|Test Name|Rule|
|---|---|---|---|---|---|
|defense-evasion|T1216|Signed Script Proxy Execution|1|SyncAppvPublishingServer Signed Script PowerShell Command Execution|New
|defense-evasion|T1216|Signed Script Proxy Execution|2|manage-bde.wsf Signed Script Command Execution|Update
> Redcanary t1216

- tools/config/logrhythm_winevent.yml
- tools/sigma/backends/elasticsearch.py
Windows security event log and rudimentary backend support for LogRhythm's lucene search functionality.
> Logrhythm support

- rules/windows/powershell/powershell_suspicious_download.yml
Hi,
Just add the powershell-classic channel after test
> Update powershell_suspicious_download.yml 

- rules/windows/builtin/win_susp_zip_compress.yml
HI,
add Task 7 T1074.001: Local Data Staging from #1013
> [OSCD] win_susp_zip_compress.yml T1074.001

- rules/windows/process_creation/process_creation_discover_private_keys.yml
HI,
add Task 5 T1552.004: Private Keys from #1013
> [OSCD] process_creation_discover_private_keys.yml T1552.004

- rules/windows/powershell/powershell_suspicious_mail_acces.yml
Hi,
Develop Sigma rules for Atomic Red Team Test 9 of #1013
Powershell Local Email Collection
> [OSCD] powershell_suspicious_mail_acces.yml T1114.001

- rules/windows/powershell/powershell_powercat.yml
Hi,
Develop Sigma rules for Atomic Red Team Test 8 of #1013
use of [powercat](https://github.com/besimorhino/powercat)
> [OSCD] powershell_powercat.yml T1095

- rules/windows/powershell/powershell_suspicious_mail_acces.yml
- tests/test_rules.py
HI,
Add check for : 
- status (should not be optional for me)
- level
View a error in the terminal for powershell_suspicious_mail_acces.yml
> Add check for status and level

- rules/windows/process_creation/sysmon_apt_sourgrum.yml
- rules/windows/process_creation/win_process_creation_bitsadmin_download.yml
Suspicious behaviours related to an actor tracked by Microsoft as SOURGUM
MSTIC Blog: https://www.microsoft.com/security/blog/2021/07/15/protecting-customers-from-a-private-sector-offensive-actor-using-0-day-exploits-and-devilstongue-malware/
> Suspicious behaviours related to  SOURGUM

- rules/windows/powershell/powershell_automated_collection.yml
- rules/windows/process_creation/process_creation_automated_collection.yml
Hello,
Add:
-  [Automated Collection Command Prompt](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1119/T1119.md#atomic-test-1---automated-collection-command-prompt)
- [Automated Collection PowerShell](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1119/T1119.md#atomic-test-2---automated-collection-powershell)
Feel free to add more sensible data extension (no  Private Keys : process_creation_discover_private_keys.yml)
> Redcanary t1119

- rules/windows/process_creation/sysmon_apt_sourgrum.yml
- rules/windows/process_creation/win_process_creation_bitsadmin_download.yml
- tests/test_rules.py
Hi,
view `fix: bug in author field (cannot be a list)` in the commit
So update the test_rules.py to check author.
Find 2 rules to fix
> Add test_optional_author to test_rules.py

- rules/windows/process_creation/process_creation_susp_7z.yml
Hello,
detect use of suspicius 7z to create a encrypt archive in CommandLine.
> [OSCD] Redcanary t1560.001 7z

- rules/windows/process_creation/process_creation_susp_winzip.yml
Hello,
detect use of winzip to create a encrypt archive in CommandLine.
> [OSCD] Redcanary t1560.001 winzip

- rules/windows/registry_event/sysmon_taskcache_entry.yml
Hi,
We need only to detection the `setvalue`.
:dart: Falsepositive when read the key
> Tune sysmon_taskcache_entry.yml

- rules/windows/process_creation/process_creation_clip.yml
Hi
Develop Sigma rules for Atomic Red Team Test 10 of #1013
Clipboard Data by use of clip
> [OSCD]  process_creation_clip.yml t1115

- rules/cloud/aws_sts_assumedrole_misuse.yml
HI,
Just fix the duplicate UUID
> fix duplicate UUID

- tools/config/generic/sysmon.yml
- tools/config/winlogbeat-modules-enabled.yml
Hi,
Make a big clean-up and update of winlogbeat-modules-enabled.yml 
- remove most of not existant field
- use conditional mapping when need
- map sysmon field
- map powershell field
- map Security Evend field (only Event use in detection ...)
close #1668
> Update winlogbeat-modules-enabled.yml 

- rules/windows/powershell/powershell_timestomp.yml
Hi,
detect timestomp by powershell.
Do not check `timestomp.ps1` word  but what it does.
> [OSCD] powershell_timestomp.yml T1070.006

- rules/windows/powershell/powershell_alternate_powershell_hosts.yml
- rules/windows/powershell/powershell_delete_volume_shadow_copies.yml
- rules/windows/powershell/powershell_remote_powershell_session.yml
Hi,
- powershell_alternate_powershell_hosts.yml : convert list to value as unique
- powershell_delete_volume_shadow_copies.yml : tune need only 400 as in the other rule
- powershell_remote_powershell_session.yml  : split eventid to the correct service
> Cleanup eventid 400 powershell-classic

- rules/windows/powershell/poweshell_detect_vm_env.yml
Hello,
Add Detect Virtualization Environment (Windows) by powershell with `Get-WmiObject`
> [OSCD] Detect Virtualization Environment (Windows) T1497.001

- rules/windows/process_creation/sysmon_apt_sourgrum.yml
HI,
fix the product value
close #1763
> fix product sysmon_apt_sourgrum.yml

- rules/windows/powershell/powershell_keylogging.yml
- rules/windows/powershell/powershell_suspicious_recon.yml
- rules/windows/process_creation/process_creation_susp_recon.yml
- rules/windows/process_creation/sysmon_creation_mavinject_dll.yml
- rules/windows/process_creation/win_susp_psr_capture_screenshots.yml
Some more windows Redcanary
|Tactic|Technique #|Technique Name|Test #|Test Name|Rule|
|---|---|---|---|---|---|
|collection|T1119|Automated Collection|3|Recon information for export with PowerShell|powershell_suspicious_recon.yml|
|collection|T1119|Automated Collection|4|Recon information for export with Command Prompt|process_creation_susp_recon.yml |
|collection|T1056.004|Credential API Hooking|1|Hook PowerShell TLS Encrypt/Decrypt Messages|update ref|
|collection|T1056.001|Keylogging|1|Input Capture|powershell_keylogging.yml |
|collection|T1113|Screen Capture|5|Windows Screencapture|update ref|
> [OSCD] Redcanary TA0009 collection

- rules/windows/process_creation/win_anydesk_silent_install.yml
Quickly made detection for silent installation of AnyDesk Remote Software from the Conti manuals. 
Maybe can be improved with also using the Product field (so simple name name change won't break the detection).
> Silent installation of AnyDesk (Conti)

- rules/cloud/gcp_kubernetes_rolebinding.yml
I didn't see anything for google cloud.
> gcp_kubernetes_rolebinding.yml

- rules/cloud/gcp_kubernetes_rolebinding.yml
> fix duplicate id

- tools/sigma/backends/mdatp.py
Also fixing incorrect parent command line mappings (some sources incorrectly map to `InitiatingProcessCommandLine` which is the child command line)
> Enabling Linux/macOS support on MDATP

- tools/sigma/backends/sql.py
Hey,
The objective of this PR is to introduce a way for the sql backend to select some fields in the query.
I added this feature using BackendOptions to keep the default `SELECT *`.
Here are some examples:
Specify fields of the query by using `--backend-option select=` followed by fields separated by commas without spaces between each.
```
$ tools/sigmac -vdI -t sql -c sysmon rules/windows/sysmon/sysmon_dcom_iertutil_dll_hijack.yml --backend-option table=xxx --backend-option select=yyy,zzz
SELECT yyy, zzz FROM xxx WHERE ((EventID = "11" AND Image = "System" AND TargetFilename LIKE "%\\Internet Explorer\\iertutil.dll" ESCAPE '\') OR (EventID = "7" AND Image LIKE "%\\Internet Explorer\\iexplore.exe" ESCAPE '\' AND ImageLoaded LIKE "%\\Internet Explorer\\iertutil.dll" ESCAPE '\'))
```
If you …
> Add fields selection to sql backend option

- tools/sigma/backends/devo.py
- tools/tests/test_backend_devo.py
Added support to the Devo backend to translate rules defining several conditions using the sigmac tool.
A couple of test cases have been added to cover the functionality.
Please feel free to change or suggest anything.
Regards,
Edu
> [Devo backend] Added support for multicondition rules using Devo subqueries

- rules/windows/powershell/powershell_invoke_nightmare.yml
- rules/windows/powershell/powershell_shellintel_malicious_commandlets.yml
- rules/windows/process_creation/win_malware_conti.yml
- rules/windows/process_creation/win_malware_conti_7zip.yml
- rules/windows/process_creation/win_malware_conti_shadowcopy.yml
- rules/windows/process_creation/win_susp_cmd_shadowcopy_access.yml
Add rules based on the leaks from the Conti group to detect
malicious behaviour.
> feat: Add some rules to detect Conti behaviour

- rules/windows/process_creation/process_creation_coti_sqlcmd.yml
Hi,
detect the use of sqlcmd from Coti leak
> Rule to detect Coti sqlcmd

- rules/linux/lnx_process_discovery.yml
- rules/linux/macos_clear_system_logs.yml
- rules/network/zeek/zeek_susp_kerberos_rc4.yml
- rules/windows/builtin/win_invoke_obfuscation_clip+_services.yml
- rules/windows/builtin/win_register_new_logon_process_by_rubeus.yml
- rules/windows/builtin/win_susp_lsass_dump.yml
- rules/windows/builtin/win_susp_rc4_kerberos.yml
- rules/windows/builtin/win_user_couldnt_call_privileged_service_lsaregisterlogonprocess.yml
- rules/windows/file_event/sysmon_non_priv_program_files_move.yml
- rules/windows/file_event/sysmon_pcre_net_temp_file.yml
- rules/windows/image_load/sysmon_mimikatz_inmemory_detection.yml
- rules/windows/image_load/sysmon_pcre_net_load.yml
- rules/windows/process_creation/win_sdbinst_shim_persistence.yml
- rules/windows/process_creation/win_service_stop.yml
- rules/windows/process_creation/win_susp_atbroker.yml
- rules/windows/raw_access_thread/sysmon_raw_disk_access_using_illegitimate_tools.yml
- rules/windows/registry_event/sysmon_registry_persistence_search_order.yml
- tests/test_rules.py
HI,
Some change
1. test_selection_list_one_value :
Check if a selection (not the list of value in field) get only 1 element.
`keyword` type selection don't get a FP error.
Fix the last 14 rules
2. test_author : 
Change author for optional #1768
Fix the 3 rules whitout `author` put simply "sigma"
3. test_optional_license : 
check if a string
but What else?
> Add more compliance test

- rules/windows/process_access/sysmon_cobaltstrike_bof_injection_pattern.yml
renaming filename and title to represent the changes
> generalise amsi bypass rule to CobaltStrike BOF injection pattern

- rules/windows/image_load/sysmon_wmi_module_load.yml
https://github.com/SigmaHQ/sigma/issues/1871
> fix: FPs with WMIADAP.exe

- tools/sigma/sigma_similarity.py
- tools/sigma_similarity
just fix first errors of #1866
> sigma_similarity fix start errors

- rules/windows/powershell/powershell_trigger_profiles.yml
Hi,
just a [T1546.013](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1546.013/T1546.013.md) from redcanary
> [OSCD] powershell_trigger_profiles T1546.013

- rules/cloud/aws/aws_elasticache_security_group_created.yml
- rules/cloud/aws/aws_elasticache_security_group_modified_or_deleted.yml
- rules/cloud/aws/aws_s3_data_management_tampering.yml
- rules/cloud/aws/aws_snapshot_backup_exfiltration.yml
aws_elasticache_security_group_created.yml
aws_elasticache_security_group_modified_or_deleted.yml
Removed spaces from eventNames
aws_s3_data_management_tampering.yml
Fix typo in title, use s3 as eventSource
aws_snapshot_backup_exfiltration.yml
Use ec2 as eventSource
> Update AWS CloudTrail rules

- tools/sigma/sigma_similarity.py
Hi,
fix the error `NotImplementedError: Base backend doesn't support multiple conditions`  which blocks sigma_similarity
ref: #1866
> sigma_similarity fix when backend support error

- rules/windows/builtin/win_software_discovery.yml
Just update the ref use in conti leak
> update ref from conti_leak

- rules/windows/file_event/sysmon_detect_powerup_dllhijacking.yml
Dear Team, 
Kindly review my PR. Please oblige if anything's wrong/missing as this is my first commit to Sigma :-D
> Adding a rule to detect WriteHijack DLL exploitation by PowerUp

- README.md
Replace travis-ci tatus badge with github actions tatus badge
cc @Neo23x0 @w0rk3r
> chore: update sigma ci badge

- tools/sigma/sigma2attack.py
Just a little fix for the yaml error
```
C:\FrackSigma\sigma\tools>python sigma2attack -d ..\rules
Ignoring rule ..\rules\linux\lnx_buffer_overflows.yml (no tags)
Ignoring rule ..\rules\linux\lnx_clamav.yml (no tags)
Ignoring rule ..\rules\linux\lnx_ldso_preload_injection.yml (no tags)
Ignoring rule ..\rules\linux\lnx_shellshock.yml (no tags)
Ignoring rule ..\rules\linux\lnx_shell_susp_log_entries.yml (no tags)
Ignoring rule ..\rules\linux\lnx_ssh_cve_2018_15473.yml (no tags)
Ignoring rule ..\rules\linux\lnx_susp_failed_logons_single_source.yml (no tags)
Ignoring rule ..\rules\linux\lnx_susp_guacamole.yml (no tags)
Ignoring rule ..\rules\linux\lnx_symlink_etc_passwd.yml (no tags)
Ignoring rule ..\rules\linux\auditd\lnx_auditd_susp_exe_folders.yml (no tags)
Ignoring rule …
```
> sigma2attack.py fix yaml error

- tools/sigma/backends/base.py
Hi,
fix the error "has no len()"  from sigmatools 0.20.0
Find by issue #1866
> fix sigmac error "has no len()"

- rules/windows/powershell/powershell_wmi_persistence.yml
- rules/windows/process_creation/win_susp_netsh_dll_persistence.yml
- rules/windows/process_creation/win_susp_screensaver_reg.yml
hi:
Some redcanary rules
- rules/windows/powershell/powershell_wmi_persistence.yml
- rules/windows/process_creation/win_susp_netsh_dll_persistence.yml (update ref only)
- rules/windows/process_creation/win_susp_screensaver_reg.yml
> Add t1546 redcanary rules

- rules/linux/lnx_security_tools_disabling.yml
- rules/linux/lnx_sudo_cve_2019_14287.yml
- rules/network/zeek/zeek_dns_mining_pools.yml
- rules/network/zeek/zeek_dns_suspicious_zbit_flag.yml
- rules/web/win_powershell_snapins_hafnium.yml
- rules/web/win_webshell_regeorg.yml
- rules/windows/builtin/win_arbitrary_shell_execution_via_settingcontent.yml
- rules/windows/builtin/win_event_log_cleared.yml
- rules/windows/malware/av_webshell.yml
- rules/windows/powershell/powershell_bad_opsec_artifacts.yml
- rules/windows/powershell/powershell_remote_powershell_session.yml
- rules/windows/powershell/powershell_renamed_powershell.yml
- rules/windows/process_access/sysmon_mimikatz_trough_winrm.yml
- rules/windows/process_creation/win_bad_opsec_sacrificial_processes.yml
- rules/windows/process_creation/win_credential_access_via_password_filter.yml
- rules/windows/process_creation/win_lolbas_execution_of_wuauclt.yml
- rules/windows/process_creation/win_modif_of_services_for_via_commandline.yml
- rules/windows/process_creation/win_powershell_disable_windef_av.yml
- rules/windows/process_creation/win_powershell_reverse_shell_connection.yml
- rules/windows/process_creation/win_sticky_keys_unauthenticated_privileged_console_access.yml
- rules/windows/process_creation/win_susp_shell_spawn_from_mssql.yml
- rules/windows/registry_event/sysmon_registry_persistence_key_linking.yml
- Add "# an old one" tag to old techniques
- Add new techniques
> Replace old mitre techniques by new one

- README.md
Hello guys! 
I should have done it years ago.
For some reason, I was always too busy with some other stuff.
I hope it's not too late 🙏
> add ATC to the "Projects or Products that use Sigma" section

- rules/windows/builtin/win_event_log_cleared.yml
- Replacement of the non-conforming attribute by fields that can help the investigation
> Add fields to event log cleared

- rules/network/zeek/zeek_rdp_public_listener.yml
correct zeek fields for `fields` section.
improve false positives information
> correct fields for zeek_rdp_public_listener.yml

- rules/network/zeek/zeek_dce_rpc_potential_petit_potam_efs_rpc_call.yml
should be `operation` not `endpoint` for the detection logic.
added various fields useful for investigation
> condition fix and add fields

- rules/network/zeek/zeek_dns_mining_pools.yml
rule logic should be endswith.
match zeek fields for `fields` section
add false positive information
> improve rule

- rules/network/zeek/zeek_dce_rpc_smb_spoolss_named_pipe.yml
- improve rule logic
- match zeek fields for fields section
- add false positive information
- change rule name to match the logic of the original rule.. Rule said "first" seen, however, no logic that matches that (ie: rare, stacking, etc..)
> improve zeek_dce_rpc_smb_spoolss_named_pipe

- rules/windows/pipe_created/sysmon_efspotato_namedpipe.yml
- rules/windows/process_creation/win_susp_razorinstaller_explorer.yml
- rules/windows/process_creation/win_susp_splwow64.yml
Corresponding change in symon-config
https://github.com/Neo23x0/sysmon-config/pull/13
> rule: EfsPotato Named Pipe, splwow64, RazerInstaller

- rules/cloud/gworkspace/gworkspace_granted_domain_api_access.yml
- rules/linux/auditd/lnx_auditd_cve_2021_3156_sudo_buffer_overflow.yml
- rules/network/zeek/zeek_dce_rpc_printnightmare_print_driver_install.yml
- rules/web/web_cve_2018_2894_weblogic_exploit.yml
- rules/web/web_cve_2020_14882_weblogic_exploit.yml
- rules/web/web_cve_2020_3452_cisco_asa_ftd.yml
- rules/web/web_cve_2021_2109_weblogic_rce_exploit.yml
- rules/web/web_cve_2021_21978_vmware_view_planner_exploit.yml
- rules/web/web_cve_2021_26814_wzuh_rce.yml
- rules/web/web_terramaster_cve_2020_28188_rce_exploit.yml
- rules/windows/builtin/win_exploit_cve_2021_1675_printspooler.yml
- rules/windows/builtin/win_exploit_cve_2021_1675_printspooler_Security.yml
- rules/windows/builtin/win_exploit_cve_2021_1675_printspooler_operational.yml
- rules/windows/driver_load/sysmon_vuln_dell_driver_load.yml
- rules/windows/file_delete/win_cve_2021_1675_printspooler_del.yml
- rules/windows/file_event/sysmon_cve_2021_26858_msexchange.yml
- rules/windows/file_event/win_cve_2021_1675_printspooler.yml
- rules/windows/file_event/win_hivenightmare_file_exports.yml
- rules/windows/file_event/win_outlook_c2_macro_creation.yml
- rules/windows/image_load/sysmon_spoolsv_dll_load.yml
- rules/windows/process_creation/sysmon_cve_2021_26857_msexchange.yml
- rules/windows/process_creation/win_office_spawn_exe_from_users_directory.yml
- rules/windows/process_creation/win_renamed_paexec.yml
- rules/windows/process_creation/win_susp_servu_exploitation_cve_2021_35211.yml
- rules/windows/process_creation/win_susp_servu_process_pattern.yml
- rules/windows/registry_event/sysmon_registry_susp_printer_driver.yml
- rules/windows/registry_event/win_registry_mimikatz_printernightmare.yml
- rules/windows/sysmon/sysmon_cve_2021_31979_cve_2021_33771_exploits.yml
- tests/test_rules.py
hi 
from #1914 
- update test.py (warning in first time)
- fix cve tag (in progress)
- fix unknown tag (not started)
> Update tags 

- rules/cloud/gworkspace/gworkspace_user_granted_admin_privileges.yml
> add gworkspace_user_granted_admin_privileges.yml

- rules/compliance/cleartext_protocols.yml
- rules/compliance/default_credentials_usage.yml
- rules/compliance/group_modification_logging.yml
- rules/compliance/host_without_firewall.yml
- rules/compliance/workstation_was_locked.yml
- rules/windows/process_creation/win_apt_unc2452_cmds.yml
- rules/windows/process_creation/win_apt_unc2452_ps.yml
- rules/windows/process_creation/win_susp_servu_exploitation_cve_2021_35211.yml
- rules/windows/registry_event/sysmon_susp_reg_persist_explorer_run.yml
- rules/windows/sysmon/sysmon_cve_2021_31979_cve_2021_33771_exploits.yml
- tests/test_rules.py
It a upgrade of test.py to follow [wiki tags](https://github.com/SigmaHQ/sigma/wiki/Tags)
close  #1914
> Check invalid tags

- rules/windows/process_creation/win_susp_uac_bypass_trustedpath.yml
https://medium.com/tenable-techblog/uac-bypass-by-mocking-trusted-directories-24a96675f6e
https://www.wietzebeukema.nl/blog/hijacking-dlls-in-windows
Tool: https://github.com/tenable/poc/tree/master/Microsoft/Windows/UACBypass
> rule: UAC bypass by mocking dirs

- rules/windows/powershell/powershell_alternate_powershell_hosts.yml
- rules/windows/powershell/powershell_delete_volume_shadow_copies.yml
- rules/windows/powershell/powershell_xor_commandline.yml
hi
start review of powershell rule 
- powershell_alternate_powershell_hosts fix FP 
- powershell_delete_volume_shadow_copies  fix HostApplication ( my bad 😄 )
- powershell_xor_commandline fix HostApplication
> Powershell correction

- rules/windows/builtin/win_cobaltstrike_service_installs.yml
- rules/windows/process_creation/win_cobaltstrike_process_patterns.yml
based on this report : https://thedfirreport.com/2021/08/29/cobalt-strike-a-defenders-guide/
> rules: cobalt strike rules refactored

- rules/web/web_cve_2021_33766_msexchange_proxytoken.yml
https://www.zerodayinitiative.com/blog/2021/8/30/proxytoken-an-authentication-bypass-in-microsoft-exchange-server
> rule: ProxyToken CVE-2021-33766 Exchange

- rules/windows/registry_event/sysmon_dns_over_https_enabled.yml
> sysmon_dns_over_https_enabled.yml

- rules/windows/builtin/win_powershell_web_request.yml
- rules/windows/powershell/powershell_invoke_nightmare.yml
- rules/windows/powershell/powershell_remote_powershell_session.yml
- rules/windows/powershell/powershell_suspicious_keywords.yml
- rules/windows/powershell/powershell_wmimplant.yml
- rules/windows/powershell/powershell_wsman_com_provider_no_powershell.yml
Hello,
make a check to powershell rule 
- powershell_invoke_nightmare.yml fix detection
- powershell_remote_powershell_session.yml fix detection for not english log
- powershell_suspicious_keywords.yml tune detection 
- powershell_wsman_com_provider_no_powershell.yml fix service
win_powershell_web_request.yml  move to builtin as it not a powershell only rule
> Update PowerShell rules

- rules/windows/file_event/sysmon_uac_bypass_cleanmgr_tmpfile.yml
- rules/windows/file_event/sysmon_uac_bypass_consent_comctl32.yml
- rules/windows/file_event/sysmon_uac_bypass_dotnet_profiler.yml
- rules/windows/file_event/sysmon_uac_bypass_ieinstal.yml
- rules/windows/file_event/sysmon_uac_bypass_msconfig_gui.yml
- rules/windows/file_event/sysmon_uac_bypass_ntfs_reparse_point.yml
- rules/windows/file_event/sysmon_uac_bypass_winsat.yml
- rules/windows/file_event/sysmon_uac_bypass_wmp.yml
- rules/windows/other/win_exchange_proxyshell_remove_mailbox_export.yml
- rules/windows/process_access/sysmon_uac_bypass_wow64_logger.yml
- rules/windows/process_creation/win_cmstp_com_object_access.yml
- rules/windows/process_creation/win_hktl_uacme_uac_bypass.yml
- rules/windows/process_creation/win_uac_bypass_changepk_slui.yml
- rules/windows/process_creation/win_uac_bypass_cleanmgr.yml
- rules/windows/process_creation/win_uac_bypass_computerdefaults.yml
- rules/windows/process_creation/win_uac_bypass_consent_comctl32.yml
- rules/windows/process_creation/win_uac_bypass_dismhost.yml
- rules/windows/process_creation/win_uac_bypass_ieinstal.yml
- rules/windows/process_creation/win_uac_bypass_msconfig_gui.yml
- rules/windows/process_creation/win_uac_bypass_ntfs_reparse_point.yml
- rules/windows/process_creation/win_uac_bypass_pkgmgr_dism.yml
- rules/windows/process_creation/win_uac_bypass_winsat.yml
- rules/windows/process_creation/win_uac_bypass_wmp.yml
- rules/windows/process_creation/win_uac_bypass_wsreset.yml
- rules/windows/registry_event/sysmon_uac_bypass_sdclt.yml
- rules/windows/registry_event/sysmon_uac_bypass_shell_open.yml
- rules/windows/registry_event/sysmon_uac_bypass_winsat.yml
- rules/windows/registry_event/sysmon_uac_bypass_wmp.yml
- tests/test_rules.py
There was some overlap with existing rules. I tried to cover only new aspects. Some scenarios will now trigger two rules. But in some scenarios only the new rules  triggered, so I put them in as an addition.
> Bulk of new rules, mainly UAC Bypasses

- rules/windows/builtin/win_av_relevant_match.yml
- rules/windows/builtin/win_ntfs_vuln_exploit.yml
- rules/windows/builtin/win_scm_database_privileged_operation.yml
- rules/windows/builtin/win_susp_failed_guest_logon.yml
- rules/windows/malware/av_hacktool.yml
- rules/windows/malware/av_relevant_files.yml
- rules/windows/malware/win_mal_darkside.yml
- rules/windows/malware/win_mal_ryuk.yml
- rules/windows/network_connection/sysmon_susp_prog_location_network_connection.yml
- rules/windows/powershell/powershell_invoke_nightmare.yml
Start to add missing tags for #1947
> Add tags when missing

- tools/config/ala.yml
- tools/sigma/backends/ala.py
- tools/sigma/backends/mixins.py
This builds on the ALA backend and outputs an ARM template.
> Azure Sentinel support

- rules/windows/pipe_created/sysmon_mal_namedpipes.yml
- rules/windows/pipe_created/sysmon_susp_wmi_consumer_namedpipe.yml
- rules/windows/wmi_event/sysmon_wmi_susp_encoded_scripts.yml
- rules/windows/wmi_event/sysmon_wmi_susp_scripting.yml
References: 
https://twitter.com/cyb3rops/status/1433066453213777921
https://github.com/RiccardoAncarani/LiquidSnake
> More Named Pipe Rules and WMI rule refactoring

- rules/windows/powershell/powershell_ntfs_ads_access.yml
- rules/windows/powershell/powershell_store_file_in_alternate_data_stream.yml
Hello,
Add Redcanary  t1564.004 test 2 in powershell_store_file_in_alternate_data_stream.yml
Update references in powershell_ntfs_ads_access.yml as match test 4
> Redcanary  t1564.004 test 2

- rules/windows/builtin/win_arbitrary_shell_execution_via_settingcontent.yml
- rules/windows/builtin/win_asr_bypass_via_appvlp_re.yml
- rules/windows/process_creation/win_sticky_keys_unauthenticated_privileged_console_access.yml
Fixed the date on 3 rules, where the month and day were switched.
> fixed rule date to match specification

- rules/windows/registry_event/sysmon_uac_bypass_shell_open.yml
> Additional UAC Bypasses (2)

- rules/windows/process_creation/process_creation_alternate_data_streams.yml
Hello
I have try to not use `re`
the test
```cmd
type C:\temp\evil.exe > "C:\Program Files (x86)\TeamViewer\TeamViewer12_Logfile.log:evil.exe"
extrac32 #{path}\procexp.cab #{path}\file.txt:procexp.exe
findstr /V /L W3AllLov3DonaldTrump #{path}\procexp.exe > #{path}\file.txt:procexp.exe
certutil.exe -urlcache -split -f https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/atomics/T1564.004/src/test.ps1 c:\temp:ttt
makecab #{path}\autoruns.exe #{path}\cabtest.txt:autoruns.cab
print /D:#{path}\file.txt:autoruns.exe #{path}\Autoruns.exe
reg export HKLM\SOFTWARE\Microsoft\Evilreg #{path}\file.txt:evilreg.reg
regedit /E #{path}\file.txt:regfile.reg HKEY_CURRENT_USER\MyCustomRegKey
expand \\webdav\folder\file.bat #{path}\file.txt:file.bat
esentutl.exe /y #{path}\autoruns.exe /d …
```
> Redcanary  t1564.004  ADS test 1

- rules/linux/auditd/lnx_auditd_system_info_discovery.yml
Just starting out with Sigma rule creation, more to come.
> New Rule - Linux-Auditd-System Information Discovery

- rules/windows/file_event/sysmon_tsclient_filewrite_startup.yml
- rules/windows/other/win_defender_amsi_trigger.yml
- rules/windows/other/win_defender_threat.yml
- rules/windows/process_creation/win_malware_conti_shadowcopy.yml
- rules/windows/process_creation/win_malware_dtrack.yml
- rules/windows/process_creation/win_susp_cmd_shadowcopy_access.yml
- rules/windows/process_creation/win_susp_rundll32_inline_vbs.yml
- rules/windows/process_creation/win_susp_screenconnect_access.yml
- rules/windows/process_creation/win_susp_userinit_child.yml
- rules/windows/registry_event/sysmon_reg_vbs_payload_stored.yml
- rules/windows/registry_event/sysmon_suspicious_keyboard_layout_load.yml
- rules/windows/registry_event/sysmon_sysinternals_eula_accepted.yml
hello,
add missing tags to rules #1947
> Add missing Tags 

- rules/linux/auditd/lnx_auditd_susp_exe_folders.yml
- rules/linux/lnx_buffer_overflows.yml
- rules/linux/lnx_clamav.yml
- rules/linux/lnx_ldso_preload_injection.yml
- rules/linux/lnx_shell_susp_log_entries.yml
- rules/linux/lnx_shellshock.yml
- rules/linux/lnx_ssh_cve_2018_15473.yml
- rules/linux/lnx_susp_failed_logons_single_source.yml
- rules/linux/lnx_susp_guacamole.yml
- rules/linux/lnx_symlink_etc_passwd.yml
- rules/linux/modsecurity/modsec_mulitple_blocks.yml
- rules/windows/process_creation/win_apt_mustangpanda.yml
- rules/windows/process_creation/win_exchange_proxylogon_oabvirtualdir.yml
- rules/windows/process_creation/win_malware_conti.yml
- rules/windows/process_creation/win_purplesharp_indicators.yml
- rules/windows/process_creation/win_susp_codepage_switch.yml
- rules/windows/process_creation/win_susp_regedit_trustedinstaller.yml
- rules/windows/process_creation/win_vul_java_remote_debugging.yml
Add more missing tags in rules...
> Add missing Tags #1974

- rules/windows/process_creation/win_susp_control_cve_2021_40444.yml
- https://twitter.com/neonprimetime/status/1435584010202255375
- https://www.joesandbox.com/analysis/476188/1/iochtml
> CVE-2021-40444 process pattern

- rules/windows/process_creation/process_mailboxexport_share.yml
- rules/windows/process_creation/win_apt_hafnium.yml
- rules/windows/process_creation/win_malware_conti_7zip.yml
- rules/windows/process_creation/win_malware_formbook.yml
- rules/windows/process_creation/win_reg_add_run_key.yml
- rules/windows/process_creation/win_susp_psexex_paexec_flags.yml
- rules/windows/process_creation/win_susp_renamed_debugview.yml
- rules/windows/process_creation/win_susp_renamed_paexec.yml
- rules/windows/process_creation/win_susp_rundll32_no_params.yml
- rules/windows/process_creation/win_susp_service_dir.yml
- rules/windows/process_creation/win_susp_splwow64.yml
- rules/windows/process_creation/win_susp_vbscript_unc2452.yml
> Add  missing tags to rule

- rules/windows/file_event/win_file_winword_cve_2021_40444.yml
- rules/windows/process_creation/win_susp_control_cve_2021_40444.yml
Reference:
https://twitter.com/RonnyTNL/status/1436334640617373699
Related Sysmon config change: 
https://github.com/Neo23x0/sysmon-config/pull/17
> CVE-2021-40444 file creation - winword.exe + .cab

- rules/network/net_susp_ipify.yml
Propose making this detection more generic, cover more lookup services than just ipify
https://twitter.com/neonprimetime/status/1436376497980428318
> Propose making rule more generic than just ipify

- rules/cloud/aws/aws_root_account_usage.yml
- rules/network/zeek/zeek_http_executable_download_from_webdav.yml
- rules/windows/builtin/win_metasploit_authentication.yml
- rules/windows/builtin/win_possible_dc_shadow.yml
- rules/windows/create_remote_thread/sysmon_suspicious_remote_thread.yml
- rules/windows/process_creation/Monitor_LOLBins_Process_Creations_by_Office_applications.yml
- rules/windows/process_creation/Monitor_Office_Applications_Spawning_WMI_command-line.yml
- rules/windows/process_creation/Monitor_executable_and_script_files_creation_by_Office_applications_using_file_extentions.yml
- rules/windows/process_creation/process_creation_command_execution_by_office_applications.yml
- rules/windows/process_creation/process_creation_office_application_from_proxy_executing_regsvr32_with_payload.yml
- rules/windows/process_creation/win_nltest_recon.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification.yml
- rules/windows/sysmon/Monitor_Office_Applications_from_proxy_executing_regsvr32_with_payload.yml
- rules/windows/sysmon/Monitor_executable_and_script_files_creation_by_Office_applications_using_file_extentions.yml
- rules/windows/sysmon/Office_Applications_Spawning_WMI_command-line.yml
- tests/test_rules.py
Hello,
I have update test_rules.py
- fix UTF8 error on windows
- check if 'or','and','not','of' are lowercase in condition
fix the 15 rules with bad case condition
> Upgrade test_rules.py

- rules/linux/auditd/lnx_auditd_steghide_embed_steganography.yml
- rules/linux/auditd/lnx_auditd_steghide_extract_steganography.yml
Rules for detecting usage of steghide
> New Linux Auditd Rules - Steghide Steganography

- tools/config/ecs-okta.yml
> ecs-okta.yml

- rules/windows/registry_event/win_outlook_registry_todaypage.yml
> Clean win outlook registry todaypage

- rules/linux/auditd/lnx_auditd_cve_2021_3156_sudo_buffer_overflow.yml
- rules/linux/auditd/lnx_auditd_cve_2021_3156_sudo_buffer_overflow_brutforce.yml
- rules/linux/auditd/lnx_auditd_network_service_scanning.yml
- rules/linux/auditd/lnx_auditd_password_policy_discovery.yml
- rules/linux/auditd/lnx_auditd_system_info_discovery2.yml
- rules/linux/lnx_network_service_scanning.yml
- rules/linux/lnx_security_tools_disabling.yml
- rules/linux/lnx_security_tools_disabling_syslog.yml
- rules/linux/lnx_sudo_cve_2019_14287_user.yml
- rules/linux/lnx_system_info_discovery.yml
hello
Split the linux global rule.
Move the auditd rules to the correct directory.
> Split global linux rule

- rules/windows/registry_event/sysmon_registry_persistence_search_order.yml
Hello,
I have fix the rule from the references.
Need to be check or better test
> [Turla Mosquito] fix detection from references

- rules/windows/registry_event/win_outlook_registry_webview.yml
> cleanup condition win_outlook_registry_webview.yml

- rules/windows/registry_event/sysmon_apt_oceanlotus_registry.yml
- rules/windows/registry_event/sysmon_registry_persistence_key_linking.yml
- rules/windows/registry_event/sysmon_uac_bypass_sdclt.yml
- rules/windows/registry_event/sysmon_uac_bypass_shell_open.yml
By checking rules  find the invalid registry value `_Class`
So fix it 😄 
The sysmon_apt_oceanlotus_registry check the IOC in references.
close #2043
> Fix invalid registry _Class

- rules/web/web_cve_2021_40539_adselfservice.yml
A simple rule for the Log IoCs from https://us-cert.cisa.gov/ncas/alerts/aa21-259a
> Rule for ADSelfService cve_2021_40539

- rules/windows/dns_query/dns_query_regsvr32_network_activity.yml
- rules/windows/file_event/file_event_hack_dumpert.yml
- rules/windows/file_event/file_event_tool_psexec.yml
- rules/windows/image_load/process_creation_tttracer_mod_load.yml
- rules/windows/network_connection/sysmon_regsvr32_network_activity.yml
- rules/windows/other/win_security_wmi_persistence.yml
- rules/windows/other/win_system_defender_disabled.yml
- rules/windows/pipe_created/pipe_created_tool_psexec.yml
- rules/windows/powershell/powershell_classic_alternate_powershell_hosts.yml
- rules/windows/powershell/powershell_classic_remote_powershell_session.yml
- rules/windows/powershell/powershell_classic_suspicious_download.yml
- rules/windows/powershell/powershell_suspicious_download.yml
- rules/windows/process_creation/process_creation_hack_dumpert.yml
- rules/windows/process_creation/process_creation_tool_psexec.yml
- rules/windows/registry_event/registry_event_defender_disabled.yml
- rules/windows/registry_event/registry_event_defender_exclusions.yml
10 more global rules.
Some detection in win_defender_disabled.yml is fix .
close #2017
> Split  global rules

- rules/linux/lnx_clear_syslog.yml
- rules/windows/powershell/powershell_memorydump_getstoragediagnosticinfo.yml
Add rules for:
- Syslog removal on Linux
- Live memory dumping using PowerShell's Get-StorageDiagnosticInfo
> Add two rules

- rules/cloud/okta/okta_admin_role_assigned_to_user_or_group.yml
- rules/cloud/okta/okta_api_token_created.yml
- rules/cloud/okta/okta_api_token_revoked.yml
- rules/cloud/okta/okta_application_modified_or_deleted.yml
- rules/cloud/okta/okta_application_sign-on_policy_modified_or_deleted.yml
- rules/cloud/okta/okta_mfa_reset_or_deactivated.yml
- rules/cloud/okta/okta_network_zone_deactivated_or_deleted.yml
- rules/cloud/okta/okta_policy_modified_or_deleted.yml
- rules/cloud/okta/okta_policy_rule_modified_or_deleted.yml
- rules/cloud/okta/okta_security_threat_detected.yml
- rules/cloud/okta/okta_unauthorized_access_to_app.yml
- rules/cloud/okta/okta_user_account_locked_out.yml
I keep forgetting to add my username, which I want to always include.
> Okta author

- rules/linux/lnx_clear_syslog.yml
More appropriate tags
https://attack.mitre.org/techniques/T1565/
> Changed tags in lnx_clear_syslog.yml

- rules/windows/registry_event/registry_event_abusing_windows_telemetry_for_persistence.yml
Convert the regex to a more usefull Modifiers.
The regex didn't works on kibana because of th `$`
> Convert re to endswith

- contrib/sigmacover.py
- tools/sigma/sigmac.py
When use `--debug` get a "sigmac.log" now
Add if convertion is FAILURE or SUCCESS.
Test only on windows
> Add more debug info to sigmac

- rules/linux/auditd/lnx_auditd_clipboard_collection.yml
New rule for clipboard collection with xclip tool
> New Rule - Linux - Auditd - Clipboard Collection

- contrib/sigmacover.py
Hi,
I make a to too fast commit this morning.
Now works well ,check on 
- windows 10
- ubuntu 20.04
Feel free to make it better
> contrib Sigmacover

- tools/sigma/sigmac.py
> Update filter help

- rules/windows/process_creation/win_susp_mpcmdrun_download.yml
Only correct the tags
close #2059
> fix tags in win_susp_mpcmdrun_download.yml

- tools/config/generic/sysmon.yml
Add EventID 26 from version 13.10 of Sysmon
more info  in https://github.com/trustedsec/SysmonCommunityGuide/blob/master/file_delete_detected.md
> add EventID 26

- rules/windows/powershell/powershell_susp_zip_compress.yml
Get a case where can have only 4104 EventID.
So update the rule to have a detection.
> powershell_susp_zip_compress add 4104

- rules/windows/registry_event/sysmon_susp_run_key_img_folder.yml
Read some malware sandbox repport under the rain
https://app.any.run/tasks/dbd43be7-1e7d-4c86-9462-345aa62f181a/
> add user temp folder

- rules/windows/process_creation/win_pc_set_policies_to_unsecure_level.yml
From https://thedfirreport.com/2021/11/01/from-zero-to-domain-admin/
Same purpose by another way than  rules/windows/powershell/powershell_script/powershell_set_policies_to_unsecure_level.yml
> add win_pc_set_policies_to_unsecure_level

- rules/linux/auditd/lnx_auditd_load_module_insmod.yml
Linux - Auditd - LKMS via insmode command.
> Linux - Auditd - Loading of Kernel Module via Insmod rule

- rules/windows/process_creation/win_pc_susp_cmdl32_lolbas.yml
From https://twitter.com/SwiftOnSecurity/status/1455897435063074824
> add win_pc_susp_cmdl32_lolbas

- .github/workflows/sigma-test.yml
> Use correct pipenv version

- rules/windows/file_event/file_event_executable_and_script_creation_by_office_using_file_ext.yml
- rules/windows/file_event/file_event_script_creation_by_office_using_file_ext.yml
- rules/windows/process_creation/process_creation_lolbins_by_office_applications.yml
- rules/windows/process_creation/process_creation_lolbins_with_wmiprvse_parent_process.yml
- rules/windows/process_creation/process_creation_office_from_proxy_executing_regsvr32_payload.yml
- rules/windows/process_creation/process_creation_office_from_proxy_executing_regsvr32_payload2.yml
Fix some rule where in product `windows` do not have the good case
> fix product windows case

- rules/windows/pipe_created/sysmon_susp_adfs_namedpipe_connection.yml
Fix to the correct logsources as describe in the reference
> fix logsources

- rules/windows/process_creation/win_pc_susp_zipexec.yml
https://twitter.com/SBousseaden/status/1451237393017839616
https://github.com/sbousseaden/EVTX-ATTACK-SAMPLES/blob/master/Execution/sysmon_zipexec.evtx
```bash
frack113@frack113-VM:~/git/Zircolite$ python zircolite.py --ruleset rules.json --evtx sysmon_zipexec.evtx 
███████╗██╗██████╗  ██████╗ ██████╗ ██╗     ██╗████████╗███████╗
╚══███╔╝██║██╔══██╗██╔════╝██╔═══██╗██║     ██║╚══██╔══╝██╔════╝
███╔╝ ██║██████╔╝██║     ██║   ██║██║     ██║   ██║   █████╗
███╔╝  ██║██╔══██╗██║     ██║   ██║██║     ██║   ██║   ██╔══╝
███████╗██║██║  ██║╚██████╗╚██████╔╝███████╗██║   ██║   ███████╗
╚══════╝╚═╝╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝╚═╝   ╚═╝   ╚══════╝
-= Standalone SIGMA Detection tool for EVTX =-
[+] Checking prerequisites
[+] Extracting EVTX Using 'tmp-ULREDZVS' directory …
```
> Add win_pc_susp_zipexec

- rules/windows/builtin/win_rdp_bluekeep_poc_scanner.yml
- rules/windows/builtin/win_scm_database_handle_failure.yml
- rules/windows/builtin/win_susp_logon_explicit_credentials.yml
- rules/windows/create_remote_thread/sysmon_cactustorch.yml
- rules/windows/create_remote_thread/sysmon_susp_powershell_rundll32.yml
- rules/windows/powershell/powershell_script/powershell_software_discovery.yml
Fix rules with correct fieldname.
remove useless EventID for sysmon rules.
> Optimize rules

- rules/windows/builtin/win_alert_lsass_access.yml
- rules/windows/other/win_defender_psexec_wmi_asr.yml
Fix logsource for a correct detection .
> fix logsource for defender

- rules/windows/builtin/win_set_oabvirtualdirectory_externalurl.yml
- rules/windows/malware/registry_event_mal_ursnif.yml
1. better search results for rules concerning Exchange Server
2. another FP found in the wild
> Minor rule changes

- rules/windows/builtin/win_ntfs_vuln_exploit.yml
I have add the correct Provider_Name as there is many eventid 55 in the system channel.
> Add correct provider_name

- rules/windows/image_load/sysmon_wmi_module_load.yml
Get many FP with WMIC.exe
log can be generate simply  by `wmic computersystem get "Model","Manufacturer", "Name", "UserName"`
> sysmon_wmi_module_load.yml add WMIC.exe

- rules/linux/auditd/lnx_auditd_data_exfil_wget.yml
Very cool usage of wget, could be also used with sudo to read restricted files.
> Adding New Linux Auditd rule - Data Exfil with Wget

- rules/windows/builtin/win_susp_ntlm_auth.yml
- rules/windows/create_remote_thread/sysmon_cobaltstrike_process_injection.yml
> Fix field name in windows rules

- rules/windows/other/win_system_defender_disabled.yml
Use some FP to update the detection from event
> Update detection win_system_defender_disabled.yml

- rules/compliance/firewall_cleartext_protocols.yml
- rules/web/web_fortinet_cve_2021_22123_exploit.yml
- rules/web/win_webshell_regeorg.yml
- rules/windows/malware/av_printernightmare_cve_2021_34527.yml
- rules/windows/malware/av_relevant_files.yml
> fix field name

- rules/windows/dns_query/win_dq_lobas_appinstaller.yml
- rules/windows/process_creation/win_pc_lobas_aspnet_compiler.yml
- rules/windows/process_creation/win_pc_lobas_bash.yml
From https://lolbas-project.github.io/#
> Some Lolbas

- rules/windows/process_creation/win_pc_lolbas_configsecuritypolicy.yml
- rules/windows/process_creation/win_pc_lolbas_diantz_ads.yml
- rules/windows/process_creation/win_pc_lolbas_diantz_remote_cab.yml
- rules/windows/process_creation/win_pc_lolbas_extexport.yml
- rules/windows/process_creation/win_pc_lolbas_extrac32.yml
- rules/windows/process_creation/win_pc_lolbas_extrac32_ads.yml
> Lolbas rules

- rules/windows/process_creation/win_pc_susp_regsvr32_image.yml
from [thedfirreport.com](https://thedfirreport.com/2021/11/29/continuing-the-bazar-ransomware-story/) :
> add win_pc_susp_regsvr32_image

- rules/windows/process_creation/win_service_stop.yml
- rules/windows/registry_event/sysmon_registry_persistence_search_order.yml
Find 2 FP because of Kaspersky and TrendMicro
> Antimalware FP

- tools/config/zircolite.yml
Use it for remove many FP in zircolite
``` bash
python sigmac -t sqlite \
-c config/generic/sysmon.yml \
-c config/generic/powershell.yml \
-c config/zircolite.yml \
-r ../rules/windows/ -d --backend-option table=logs \
--output-fields title,id,description,author,tags,level,falsepositives,filename \
--output-format json -o rules.json
```
> Add zircolite config

- tools/sigma/backends/hawk.py
Re-submitting pull request.    o0f
> Fixing added backslashes that are generated by sigma backend

- rules/windows/process_creation/win_xsl_script_processing.yml
See https://petri.com/command-line-wmi-part-3 for example of static formats
> Filtering false positives of static arguments to wmic /format 

- rules/windows/builtin/win_susp_mshta_execution.yml
- rules/windows/process_creation/win_commandline_path_traversal_evasion.yml
I did not update modified for just changing the title. I don't know what is preferred in that case as the logic did not change.
> Add dll+exe files to rule because of CVE-2020-1599

- rules/windows/powershell/powershell_script/powershell_malicious_commandlets.yml
Fixing syntax error, really sorry about this one.  Will look into yaml test we can create to check for invalid chars like : , ' maybe?
> Fixes a syntax error in submitted change where : was intended to be |

- rules/windows/network_connection/sysmon_powershell_network_connection.yml
Conflict resolved, in favor of selection
> Fixing conflict where both selection and filter have the same value.

- rules/windows/file_event/sysmon_susp_desktop_ini.yml
AccessList must have write ability to desktop.ini
> Adding filter for read only accesslist, attack cannot be triggered

- rules/windows/network_connection/sysmon_suspicious_outbound_kerberos_connection.yml
> adding tomcat8 to allowed kerberos outbound.

- tools/config/hawk.yml
- tools/sigma/backends/hawk.py
Adds webserver category, support for begins/endswith and snake_case conversion
> Hawk webserver category, support for begins/endswith and snake_case conversion

- rules/windows/image_load/image_load_wsman_provider_image_load.yml
- rules/windows/image_load/sysmon_uipromptforcreds_dlls.yml
- rules/windows/process_access/sysmon_cred_dump_lsass_access.yml
- rules/windows/process_access/win_susp_proc_access_lsass.yml
- rules/windows/process_creation/win_susp_svchost.yml
Start a new VM windows 10 x64 2004 and update to 20H2.
Get only firefox , git and notepad++ on it
> Fix some FP

- rules/windows/process_creation/win_pc_susp_rundll32_script_run.yml
- rules/windows/process_creation/win_susp_rundll32_activity.yml
- Add win_pc_susp_rundll32_script_run
- Fix win_susp_rundll32_activity from references
> Redcanary 1218 011

- rules/windows/builtin/security/win_lm_namedpipe.yml
Adds sql\query to named pipe list:
> adding sql\query to name pipe list

- rules/windows/process_creation/win_powershell_cmdline_special_characters.yml
Ignore parent image ssm-document-worker
> Adding fp filter for ssm-document-worker

- tools/config/hawk.yml
- tools/sigma/backends/hawk.py
Fixing error when handling regex type. (oof)
> fixes error when implementing regex type, data should not be escaped

- rules/windows/process_creation/win_pc_susp_sc_query.yml
- rules/windows/process_creation/win_susp_net_execution.yml
https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1007/T1007.md
> Add redcannary T1007

- rules/windows/file_event/file_event_susp_system_interactive_powershell.yml
- rules/windows/process_creation/win_susp_system_user_anomaly.yml
- interactive PowerShell as SYSTEM
- Suspicious programs and command lines as SYSTEM
> New rules - Suspicious SYSTEM context

- rules/windows/builtin/security/win_pass_the_hash.yml
- rules/windows/builtin/security/win_pass_the_hash_2.yml
> Corrected filter field name in win_pass_the_hash_2.yml

- rules/windows/builtin/security/win_invoke_obfuscation_stdin_services_security.yml
- rules/windows/builtin/security/win_invoke_obfuscation_via_compress_services_security.yml
- rules/windows/builtin/security/win_invoke_obfuscation_via_rundll_services_security.yml
- rules/windows/builtin/security/win_invoke_obfuscation_via_stdin_services_security.yml
- rules/windows/builtin/security/win_invoke_obfuscation_via_use_clip_services_security.yml
- rules/windows/builtin/security/win_invoke_obfuscation_via_use_mshta_services_security.yml
- rules/windows/builtin/security/win_invoke_obfuscation_via_use_rundll32_services_security.yml
- rules/windows/builtin/security/win_invoke_obfuscation_via_var_services_security.yml
Fixing order of operations for matching to reduce performance impacts
> Fixing errs with invoke obfus

- rules/windows/registry_event/sysmon_asep_reg_keys_modification_currentversion.yml
> sysmon_asep_reg_keys_modification_currentversion OneDriveSetup FP

- rules/windows/process_creation/win_pc_susp_netsh_command.yml
- rules/windows/process_creation/win_pc_susp_network_command.yml
https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1016/T1016.md
test 1 and 2
test 4 already detected
> Add some T1016 windows

- rules/windows/builtin/security/win_lateral_movement_condrv.yml
> Change to deprecated as too many FP

- rules/windows/image_load/sysmon_abusing_azure_browser_sso.yml
> sysmon_abusing_azure_browser_sso.yml FP

- rules/windows/process_creation/sysmon_always_install_elevated_windows_installer.yml
see for details, not found in msiexec /h : https://www.robvanderwoude.com/msiexec.php
> Adding filter for msiexec repair option

- rules/linux/builtin/lnx_susp_dev_tcp.yml
Experimental rule , You can improve it .
> Add lnx_susp_dev_tcp

- rules/windows/network_connection/win_net_python.yml
- rules/windows/process_creation/win_pc_susp_nmap.yml
https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1046/T1046.md
For python use `contains` as name can have version ex "python3.9.exe"
> Add windows t1046 rules

- rules/windows/process_creation/win_susp_net_use_password_plaintext.yml
> Detect net use password plaintext

- rules/windows/powershell/powershell_classic/powershell_pc_susp_get_nettcpconnection.yml
- rules/windows/powershell/powershell_module/powershell_pm_susp_get_nettcpconnection.yml
- rules/windows/process_creation/win_pc_susp_network_listing_connections.yml
- rules/windows/process_creation/win_pc_susp_sharpview.yml
- rules/windows/process_creation/win_pc_susp_tasklist_command.yml
https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1049/T1049.md
As only one test  : https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1057/T1057.md 😄
> Windows T1049 RedCannary

- rules/web/web_cve_2021_44228_log4j_fields.yml
Source: https://community.riskiq.com/article/505098fc/description
> Additional IoC keywords added log4j detection

- rules/windows/powershell/powershell_module/powershell_pm_suspicious_local_group_reco.yml
- rules/windows/powershell/powershell_script/powershell_ps_suspicious_local_group_reco.yml
- rules/windows/process_creation/win_pc_suspicious_ad_reco.yml
https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1069.001/T1069.001.md
> Windows Redcannary T1069 001

- tools/config/thor.yml
Add additional rewrites to powershell sources to map to the fitting rules. Credits for this go to @frack113
> feat: Add finer powershell log source distinguation

- rules/web/web_cve_2021_44228_log4j.yml
Source: https://github.com/Puliczek/CVE-2021-44228-PoC-log4j-bypass-words
> Added current known bypass patterns

- rules/windows/process_creation/win_pc_susp_adfind_enumerate.yml
- rules/windows/process_creation/win_pc_susp_network_listing_connections.yml
- Add win_pc_susp_adfind_enumerate.yml
- Fix ft win_pc_susp_network_listing_connections.yml
> Windows redcannary

- rules/windows/powershell/powershell_module/powershell_pm_suspicious_ad_group_reco.yml
- rules/windows/powershell/powershell_module/powershell_pm_suspicious_smb_share_reco.yml
- rules/windows/powershell/powershell_script/powershell_ps_file_and_directory_discovery.yml
- rules/windows/powershell/powershell_script/powershell_ps_suspicious_ad_group_reco.yml
- rules/windows/powershell/powershell_script/powershell_ps_suspicious_smb_share_reco.yml
> Windows redcannary discovery

- rules/windows/image_load/image_load_wsman_provider_image_load.yml
- rules/windows/image_load/sysmon_suspicious_dbghelp_dbgcore_load.yml
- rules/windows/process_creation/sysmon_always_install_elevated_windows_installer.yml
Get some FP with aurora when update VM Windows 10 20H1 to 21H2
> Aurora fp update

- rules/windows/powershell/powershell_script/powershell_ps_security_software_discovery.yml
- rules/windows/process_creation/win_pc_susp_findstr_385201.yml
https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1518.001/T1518.001.md
> Windows Redcanary T1518.001 discovery

- rules/windows/process_creation/process_creation_advanced_ip_scanner.yml
- rules/windows/process_creation/process_creation_advanced_port_scanner.yml
- rules/windows/process_creation/process_creation_cleanwipe.yml
- rules/windows/process_creation/win_susp_nt_resource_kit_auditpol_usage.yml
- rules/windows/process_creation/win_susp_psloglist.yml
This PR covers the following modifications:
- Advanced Port Scanner - A sister project of advanced IP scanner.
- CleanWipe - A tool that is used to delete Symantec AV.
- Updated "Advanced IP Scanner" to include command line for portable version and updated MITRE techniques.
> Add/Update Rules

- rules/windows/process_creation/win_pc_sqlcmd_veeam_dump.yml
- rules/windows/process_creation/win_pc_susp_reg_open_command.yml
take advantage of the vacations to reread : 
- https://thedfirreport.com/2021/12/13/diavol-ransomware/
> Add thedfirreport Diavol Ransomware rules

- rules/windows/builtin/security/win_samaccountname_spoofing_cve_2021_42287.yml
https://medium.com/@mvelazco/hunting-for-samaccountname-spoofing-cve-2021-42287-and-domain-controller-impersonation-f704513c8a45
> rule: sAMAccountName Spoofing CVE-2021-42287

- tools/sigma/backends/lacework.py
Use `is not null` for non-JSON fields
> fix(lacework): value exists

- rules/windows/file_event/win_fe_susp_desktop_txt.yml
- rules/windows/powershell/powershell_script/powershell_ps_susp_remove_adgroupmember.yml
- rules/windows/powershell/powershell_script/powershell_ps_susp_wallpaper.yml
- rules/windows/powershell/powershell_script/powershell_ps_susp_win32_shadowcopy.yml
- rules/windows/process_creation/win_pc_delete_systemstatebackup.yml
- rules/windows/process_creation/win_pc_susp_cipher.yml
- rules/windows/process_creation/win_pc_susp_schtasks_disable.yml
- rules/windows/process_creation/win_pc_susp_taskkill.yml
Just some Windows Redcannary impact rules
> Windows Redcannary impact

- rules/windows/other/taskscheduler/win_rare_schtask_creation.yml
Open for all task names.  Some can be filtered from the total aggregation count
> filter windows defender in list

- tools/config/hawk.yml
Adding conditions for spring application.
> hawk backend: adding spring application to config

- rules/windows/network_connection/sysmon_susp_rdp.yml
per feature "Passwo…rdstate Remote Session Launcher" https://www.clickstudios.com.au/downloads/version9/Passwordstate_Remote_Session_Launcher_Gateway_Install_Guide.pdf
> Allows PasswordState to initiate rdp connections

- rules/windows/file_event/win_fe_creation_unquoted_service_path.yml
- rules/windows/powershell/powershell_script/powershell_ps_cor_profiler.yml
- rules/windows/powershell/powershell_script/powershell_ps_get_acl_service.yml
- rules/windows/process_creation/win_pc_reg_service_imagepath_change.yml
- rules/windows/registry_event/win_re_add_port_monitor.yml
- rules/windows/registry_event/win_re_shim_databases_persistence.yml
- rules/windows/registry_event/win_re_winlogon_notify_key.yml
Last Windows Redcannary persistence rules for 2021.
> Windows persistence

- rules/windows/file_event/win_fe_creation_new_shim_database.yml
- rules/windows/file_event/win_fe_creation_scr_binary_file.yml
- rules/windows/powershell/powershell_script/powershell_ps_capture_screenshots.yml
- rules/windows/powershell/powershell_script/powershell_ps_cmdlet_scheduled_task.yml
- rules/windows/powershell/powershell_script/powershell_ps_directoryservices_accountmanagement.yml
- rules/windows/powershell/powershell_script/powershell_ps_localuser.yml
- rules/windows/powershell/powershell_script/powershell_ps_office_comobject_registerxll.yml
- rules/windows/powershell/powershell_script/powershell_ps_request_kerberos_ticket.yml
- rules/windows/registry_event/win_re_chrome_extension.yml
- rules/windows/registry_event/win_re_outlook_security.yml
Some more windows Redcannary 😄
> Windows Redcannary 

- rules/windows/raw_access_thread/sysmon_raw_disk_access_using_illegitimate_tools.yml
- add a windows defender FP
- fix some logic in filter2 example ('C:\Windows\System32\*' and '*C:\Windows\System32\taskhostw.exe')
> Update rule sysmon_raw_disk_access_using_illegitimate_tools.yml

- rules/windows/image_load/image_load_wsman_provider_image_load.yml
Start a new lab with a 2019 AD get many FP
> Windows 2019 FP

- rules/windows/process_creation/win_lolbin_cscript_gathernetworkinfo.yml
…for information gathering. Based on the information provided in: https://posts.slayerlabs.com/living-off-the-land/#gathernetworkinfovbs
> windows lolbin 'gathernetworkinfo.vbs' detection

- rules/windows/process_creation/process_creation_susp_format.yml
https://twitter.com/0gtweet/status/1477925112561209344
> rule: format.com fs lolbin

- rules/windows/registry_event/sysmon_taskcache_entry.yml
> Add sysmon_taskcache_entry FP

- rules/proxy/proxy_cobalt_onedrive.yml
- rules/proxy/proxy_susp_flash_download_loc.yml
- rules/web/web_fortinet_cve_2018_13379_preauth_read_exploit.yml
- rules/web/web_solarwinds_cve_2020_10148.yml
- rules/windows/builtin/security/win_impacket_psexec.yml
- rules/windows/process_creation/win_apt_ta505_dropper.yml
- rules/windows/process_creation/win_control_panel_item.yml
- rules/windows/process_creation/win_hack_koadic.yml
- rules/windows/process_creation/win_netsh_fw_add_susp_image.yml
- rules/windows/process_creation/win_netsh_port_fwd_3389.yml
- rules/windows/process_creation/win_netsh_wifi_credential_harvesting.yml
- rules/windows/process_creation/win_plugx_susp_exe_locations.yml
- rules/windows/process_creation/win_susp_certutil_encode.yml
- rules/windows/process_creation/win_susp_codepage_switch.yml
- rules/windows/process_creation/win_susp_commands_recon_activity.yml
- rules/windows/process_creation/win_susp_copy_lateral_movement.yml
- rules/windows/process_creation/win_susp_csc.yml
- rules/windows/process_creation/win_susp_iss_module_install.yml
- rules/windows/process_creation/win_susp_msiexec_web_install.yml
- rules/windows/process_creation/win_susp_ntdsutil.yml
- rules/windows/process_creation/win_susp_outlook.yml
- rules/windows/process_creation/win_susp_ping_hex_ip.yml
- rules/windows/process_creation/win_susp_powershell_parent_combo.yml
- rules/windows/process_creation/win_susp_run_locations.yml
- rules/windows/process_creation/win_susp_sysvol_access.yml
- rules/windows/process_creation/win_susp_wmi_execution.yml
No detection change .
Change status experimental for rule without any change from more than 365 days
> Change status to test

- rules/windows/process_creation/win_pc_netsh_fw_enable_group_rule.yml
- rules/windows/registry_event/win_re_disable_defender_firewall.yml
> Microsoft Defender Firewall

- rules/windows/process_creation/win_susp_firewall_disable.yml
> Fix win susp firewall disable

- rules/windows/powershell/powershell_script/posh_ps_suspicious_iofilestream.yml
the event
But get trouble with the `"` 
When remove trigger 😄
> fix detection posh_ps_suspicious_iofilestream

- rules/windows/file_event/file_event_win_cscript_wscript_dropper.yml
Relates to existing signature but does not focus on command execution
> New signature to detect cscript/wscript dropper using the sysmon file event

- rules/windows/file_event/file_event_win_cscript_wscript_dropper.yml
sorry for my mistake i was not clear in my explanation.
Fix the detection (test with aurora many FP).
> Fix condition

- rules/linux/builtin/lnx_shell_susp_rev_shells.yml
- rules/linux/macos/process_creation/macos_local_account.yml
- rules/linux/other/lnx_susp_vsftp.yml
- rules/linux/process_creation/lnx_local_account.yml
- rules/network/zeek/zeek_dce_rpc_domain_user_enumeration.yml
- rules/network/zeek/zeek_dce_rpc_printnightmare_print_driver_install.yml
- rules/proxy/proxy_cobalt_malformed_uas.yml
- rules/proxy/proxy_ursnif_malware_c2_url.yml
- rules/web/web_exchange_cve_2020_0688_exploit.yml
- rules/windows/builtin/security/win_rdp_localhost_login.yml
- rules/windows/malware/process_creation_mal_darkside_ransomware.yml
- rules/windows/powershell/powershell_script/powershell_azurehound_commands.yml
- rules/windows/powershell/powershell_script/powershell_ntfs_ads_access.yml
- rules/windows/process_creation/win_powershell_xor_commandline.yml
- rules/windows/process_creation/win_sticky_keys_unauthenticated_privileged_console_access.yml
- rules/windows/process_creation/win_susp_crackmapexec_powershell_obfuscation.yml
- rules/windows/process_creation/win_susp_emotet_rundll32_execution.yml
- rules/windows/process_creation/win_susp_spoolsv_child_processes.yml
Use simple quote for detection.
With double quote `"\n"` will be transform to a new line
To echap `'` use `''`
> Simple Quote in detection

- rules/windows/process_creation/process_creation_susp_non_exe_image.yml
- rules/windows/process_creation/win_susp_regsvr32_http_pattern.yml
https://github.com/SigmaHQ/sigma/issues/2560
> fix: FPs with rule that looks for executions of files other than .exe

- tools/config/powershell.yml
> Fix windows-dns-server

- rules/windows/builtin/security/win_net_share_obj_susp_desktop_ini.yml
- tools/config/generic/windows-services.yml
Add windows-services.yml for reference (more info in #2564).
missing mapping only for : 
- category: edr
- product: antivirus
Find a error and fix it in win_net_share_obj_susp_desktop_ini.yml
> Add windows-services.yml

- rules/windows/file_delete/win_fd_delete_appli_log.yml
- rules/windows/network_connection/win_nc_msiexec.yml
- rules/windows/powershell/powershell_script/posh_ps_tamper_defender.yml
- rules/windows/process_creation/win_pc_dsim_remove.yml
- rules/windows/process_creation/win_pc_msiexec_execute_dll.yml
- rules/windows/process_creation/win_pc_msiexec_install_quiet.yml
- rules/windows/registry_event/win_re_disable_administrative_share.yml
Some defense_evasion rules with redcannary
> Windows Redcannary defense_evasion 

- rules/windows/powershell/powershell_script/posh_ps_msxml_com.yml
- rules/windows/powershell/powershell_script/posh_ps_xml_iex.yml
> Add Redcannary Windows Rules

- rules/windows/process_access/win_susp_proc_access_lsass.yml
get a FP when I have open perfmon
> Fix FP win_susp_proc_access_lsass.yml

- rules/windows/file_event/win_fe_susp_colorcpl.yml
simple rule 
https://twitter.com/eral4m/status/1480468728324231172?s=20
> add win_fe_susp_colorcpl

- rules/linux/auditd/lnx_auditd_disable_system_firewall.yml
taking leverage of SERVICE_STOP messages
> Adding new linux auditd rule - Disable Dystem Firewall

- rules/windows/process_creation/win_pc_susp_instalutil.yml
From https://securelist.com/moonbounce-the-dark-side-of-uefi-firmware/105468/
> add win_pc_susp_instalutil

- rules/windows/network_connection/win_nc_imewdbld.yml
- rules/windows/powershell/powershell_script/posh_ps_susp_ssl_keyword.yml
- rules/windows/powershell/powershell_script/posh_ps_test_netconnection.yml
- rules/windows/process_creation/win_pc_cmd_redirect.yml
- rules/windows/process_creation/win_pc_susp_radmin.yml
- rules/windows/process_creation/win_susp_curl_fileupload.yml
- rules/windows/registry_event/win_re_change_security_zones.yml
- rules/windows/registry_event/win_re_hidden_extention.yml
New rules and update of win_susp_curl_fileupload.yml
> Windows Redcannary tests

- rules/windows/registry_event/win_re_blackbyte_ransomware.yml
- https://redcanary.com/blog/blackbyte-ransomware/?utm_source=twitter&utm_medium=social
- https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/blackbyte-ransomware-pt-1-in-depth-analysis/
> Add win_re_blackbyte_ransomware

- rules/windows/process_creation/win_plugx_susp_exe_locations.yml
> Typo fix in win_plugx_susp_exe_locations.yml

- rules/windows/process_creation/sysmon_proxy_execution_wuauclt.yml
Just update references with last lazarus apt information
> sysmon_proxy_execution_wuauclt Update References

- rules/linux/builtin/lnx_pwnkit_local_privilege_escalation.yml
- Fix yaml errors
- change `condition: keyword` to `condition: all of keyword` 
close #2607
> add lnx_pwnkit_local_privilege_escalation

- rules/windows/builtin/application/win_builtin_remove_application.yml
- rules/windows/file_event/win_fe_install_teamviewer_desktop.yml
- rules/windows/process_creation/win_pc_wmic_remove_application.yml
- rules/windows/registry_event/win_re_ie_persistence.yml
> Add windows redcannary rules

- rules/windows/win_pc_susp_takeown.yml
> win_pc_susp_takeown

- rules/windows/powershell/powershell_script/posh_ps_run_from_mount_diskimage.yml
- rules/windows/powershell/powershell_script/posh_ps_suspicious_mount_diskimage.yml
- rules/windows/powershell/powershell_script/posh_ps_suspicious_unblock_file.yml
For Zone.Identifier alternate data stream try sysmon EventID 15 but miss a `SourceFileName` field to detect remove stream.
With aurora get IOC alert too for the file run from ISO.
> Windows Redcannary T1553.005

- rules/windows/builtin/security/win_asr_bypass_via_appvlp_re.yml
- rules/windows/builtin/security/win_invoke_obfuscation_clip_services_security.yml
- rules/windows/builtin/security/win_invoke_obfuscation_stdin_services_security.yml
- rules/windows/builtin/security/win_invoke_obfuscation_via_compress_services_security.yml
- rules/windows/builtin/security/win_invoke_obfuscation_via_stdin_services_security.yml
- rules/windows/builtin/security/win_invoke_obfuscation_via_use_mshta_services_security.yml
- rules/windows/builtin/system/win_invoke_obfuscation_clip_services.yml
https://github.com/SigmaHQ/sigma/issues/2633
> refactor: avoid regex use

- rules/windows/image_load/image_load_susp_advapi32_dll.yml
Detect https://github.com/hlldz/Phant0m 
Compil with mgsys clang++ `#KILL_WITH_T1 = 1`
Works well with aurora.
> add image_load_susp_advapi32_dll

- rules/windows/image_load/image_load_susp_advapi32_dll.yml
FP `C:\Users\administrateur\AppData\Local\Microsoft\OneDrive\22.012.0116.0001\FileCoAuth.exe" -Embedding`
> aurora OneDrive FP

- rules/windows/image_load/image_load_susp_advapi32_dll.yml
Got many FPs with 
- Github Desktop
- VSCode 
- NVidia software 
... more
> fix: far too many FPs with new "Suspicious Load of Advapi31.dll" rule

- rules/windows/process_creation/win_pc_susp_instalutil.yml
InstallUtil.exe is also available under 32 bits path for .net framework
> Avoiding being too narrow for paths

- rules/windows/powershell/powershell_script/posh_ps_get_adreplaccount.yml
Test 2 : https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1003.006/T1003.006.md
> add posh_ps_get_adreplaccount

- rules/windows/process_creation/win_pc_embed_exe_lnk.yml
From https://www.x86matthew.com/view_post?id=embed_exe_lnk
> add win_pc_embed_exe_lnk

- rules/windows/raw_access_thread/sysmon_raw_disk_access_using_illegitimate_tools.yml
> fix: FP noticed with Aurora

- rules/windows/registry_event/sysmon_office_test_regadd.yml
- tools/sigma/sigma-uuid.py
- tools/sigma/sigma_uuid.py
Found some smaller typos in the code
> some smaller typo fixes

- rules/windows/process_creation/win_mimikatz_command_line.yml
Example fp:
```
2022-02-07 16:56:35 internal.host.name Sysmon: 1: Process Create | RuleName=technique_id=T1059.001,technique_name=PowerShell | UtcTime=2022-02-07 16:56:35.056 | ProcessGuid={33dc4d91-4f43-6201-14e7-000000000101} | ProcessId=5028 | Image=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe | FileVersion=10.0.17763.1 (WinBuild.160101.0800) | Description=Windows PowerShell | Company=Microsoft Corporation | OriginalFileName=PowerShell.EXE | OriginalCommandLine=powershell "function Convert-GuidToCompressedGuid { [CmdletBinding()] [OutputType('System.String')] param ( [Parameter(ValueFromPipeline=\"\", ValueFromPipelineByPropertyName=\"\", Mandatory=$true)] [string]$Guid ) begin { $Guid = $Guid.Replace('-', '').Replace('{', '').Replace('}', '') } process { try { $Groups = …
```
> FP mimikatz when loading powershell function Convert-GuidToCompressedGuid

- rules/windows/image_load/sysmon_spoolsv_dll_load.yml
https://github.com/ly4k/SpoolFool
> Add CVE-2022–22718

- rules/windows/process_creation/win_apt_bluemashroom.yml
Example fp related to m$ teams update:
```
2022-02-09 16:49:00 example.host.com Sysmon: 1: Process Create | RuleName=technique_id=T1117,technique_name=Regsvr32 | UtcTime=2022-02-09 16:49:00.975 | ProcessGuid={1F425E1D-F07C-6203-050A-000000009002} | ProcessId=21556 | Image=C:\Windows\SysWOW64\regsvr32.exe | FileVersion=10.0.14393.1378 (rs1_release.170620-2008) | Description=Microsoft(C) Register Server | Company=Microsoft Corporation | OriginalFileName=REGSVR32.EXE | OriginalCommandLine="C:\Windows\SysWOW64\regsvr32.exe" /s /n /i:user "C:\Users\USERNAME\AppData\Local\Microsoft\TeamsMeetingAddin\1.0.21348.1\x86\Microsoft.Teams.AddinLoader.dll" | CommandLine=C:\Windows\SysWOW64\regsvr32.exe /s /n /i:user C:\Users\USERNAME\AppData\Local\Microsoft\TeamsMeetingAddin\1.0.21348.1\x86\Microsoft.Tea …
```
> Adds false positive filter to win apt bluemashroom 

- rules/windows/builtin/wmi/win_wmi_persistence.yml
- rules/windows/image_load/sysmon_uipromptforcreds_dlls.yml
- rules/windows/process_access/sysmon_in_memory_assembly_execution.yml
- rules/windows/process_creation/win_netsh_fw_add.yml
- rules/windows/process_creation/win_pc_msiexec_execute_dll.yml
- rules/windows/process_creation/win_pc_susp_powershell_encode.yml
- rules/windows/raw_access_thread/sysmon_raw_disk_access_using_illegitimate_tools.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_currentversion.yml
- rules/windows/registry_event/sysmon_registry_persistence_search_order.yml
- rules/windows/registry_event/sysmon_runonce_persistence.yml
- rules/windows/registry_event/sysmon_taskcache_entry.yml
Several FPs against a fresh installed Windows with example applications and basic user interaction
> Fix FPs (Example Installation 2)

- rules/linux/process_creation/lnx_bpftrace_unsafe_option_usage.yml
First ever BPF rule in Sigma! (didn't found one)
> rule: add new bpftrace unsafe option rule

- rules/windows/deprecated/powershell_suspicious_invocation_specific.yml
- rules/windows/powershell/powershell_module/posh_pm_suspicious_invocation_specific.yml
- rules/windows/powershell/powershell_script/posh_ps_accessing_win_api.yml
- rules/windows/powershell/powershell_script/posh_ps_set_policies_to_unsecure_level.yml
- rules/windows/powershell/powershell_script/posh_ps_suspicious_invocation_specific.yml
Several FPs against a fresh installed Windows with example applications and basic user interaction
> Fix FPs (Example Installation 3)

- rules/windows/process_creation/win_pc_susp_run_folder.yml
In many sandbox results strange exe start from Temp or Desktop folder.
Level is low as it is more a IOC for the SOC than a Alert
> add win_pc_susp_run_folder

- rules/windows/registry_event/win_re_ie_persistence.yml
FP when install office or open it
> Aurora Office FP

- rules/windows/process_creation/win_pc_esentutl_webcache.yml
- rules/windows/process_creation/win_pc_reg_defender_exclusion.yml
From [thedfirreport Qbot](https://thedfirreport.com/2022/02/07/qbot-likes-to-move-it-move-it/) run the command by hand in a VM with aurora.
Just add the missing one, most has been seen .
> Missing Qbot rules

- rules/windows/process_creation/process_creation_rundll32_not_from_c_drive.yml
Fix `service: windows` to `product: windows`
> process_creation_rundll32_not_from_c_drive.yml invalid logsource

- rules/windows/process_creation/win_proc_wrong_parent.yml
Get many `ParentImage: '-'` with sysmon 13.32
> win_proc_wrong_parent.yml FP

- rules/windows/process_creation/win_file_permission_modifications.yml
Example fp:
```
2022-02-09 15:29:35 example.host.com Sysmon: 1: Process Create | RuleName=technique_id=T1059,technique_name=Command-Line Interface | UtcTime=2022-02-09 15:29:35.190 | ProcessGuid={91e7d9e6-dddf-6203-cb2a-010000003d00} | ProcessId=8204 | Image=C:\Windows\System32\cmd.exe | FileVersion=10.0.17763.1697 (WinBuild.160101.0800) | Description=Windows Command Processor | Company=Microsoft Corporation | OriginalFileName=Cmd.Exe | OriginalCommandLine="C:\Windows\system32\cmd.exe" /C ICACLS "C:\ProgramData\dynatrace\gateway\config\connectivity.history" /reset | CommandLine=C:\Windows\system32\cmd.exe /C ICACLS C:\ProgramData\dynatrace\gateway\config\connectivity.history /reset | CurrentDirectory=C:\Windows\system32\ | User=NT AUTHORITY\SYSTEM | …
```
> Filtering fp of dynatrace behavior

- rules/windows/process_creation/sysmon_always_install_elevated_windows_installer.yml
- rules/windows/process_creation/win_pc_msiexec_execute_dll.yml
- rules/windows/process_creation/win_regedit_import_keys.yml
- rules/windows/raw_access_thread/sysmon_raw_disk_access_using_illegitimate_tools.yml
- rules/windows/registry_event/sysmon_runonce_persistence.yml
Several FPs against a fresh installed Windows with example applications and basic user interaction
> Fix FPs (Example Installation 4)

- rules/windows/deprecated/powershell_suspicious_invocation_specific.yml
- rules/windows/powershell/powershell_script/posh_ps_suspicious_invocation_specific.yml
- rules/windows/process_access/sysmon_in_memory_assembly_execution.yml
- rules/windows/process_creation/process_creation_susp_non_exe_image.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_classes.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_common.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_currentcontrolset.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_currentversion.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_currentversion_nt.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_internet_explorer.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_office.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_winsock2.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_wow6432node.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_wow6432node_currentversion.yml
Several FPs against a fresh installed Windows with example applications and basic user interaction
>  Fix FPs (Example Installation 5)

- rules/windows/process_creation/win_pc_cmd_dosfuscation.yml
Some fun https://www.fireeye.com/content/dam/fireeye-www/blog/pdfs/dosfuscation-report.pdf
> add win_pc_cmd_dosfuscation

- rules/windows/registry_event/win_re_ie_persistence.yml
> Fix FP binary

- .github/workflows/known-FPs.csv
- .github/workflows/matchgrep.sh
- .github/workflows/sigma-test.yml
- rules/windows/process_creation/win_pc_lolbin_wlrmdr.yml
This is the first iteration checking automatically against logs of a freshly installed Windows 10 client, installing some applications and performing basic user interaction.
> New workflow action: Check sigma rules against baseline evtx files

- rules/windows/builtin/firewall_as/win_firewall_as_add_rule.yml
- rules/windows/builtin/firewall_as/win_firewall_as_change_rule.yml
- rules/windows/builtin/firewall_as/win_firewall_as_delete_rule.yml
- rules/windows/builtin/firewall_as/win_firewall_as_failed.yml
- rules/windows/builtin/firewall_as/win_firewall_as_reset.yml
- rules/windows/builtin/firewall_as/win_firewall_as_setting_change.yml
- tools/config/elk-windows.yml
- tools/config/elk-winlogbeat-sp.yml
- tools/config/elk-winlogbeat.yml
- tools/config/generic/windows-services.yml
- tools/config/logpoint-windows.yml
- tools/config/logstash-windows.yml
- tools/config/powershell.yml
- tools/config/splunk-windows.yml
- tools/config/sumologic.yml
- tools/config/thor.yml
- tools/config/winlogbeat-modules-enabled.yml
- tools/config/winlogbeat-old.yml
- tools/config/winlogbeat.yml
- tools/config/zircolite.yml
Add simples rules for builtin Microsoft-Windows-Windows Firewall With Advanced Security/Firewall Event
> Add firewall-as basic rules

- rules/windows/process_creation/win_powershell_cmdline_reversed_strings.yml
Example FP:
```
2022-02-21 19:37:09 redacted.host.name Sysmon: 1: Process Create | RuleName=technique_id=T1086,technique_name=PowerShell | UtcTime=2022-02-21 19:37:09.715 | ProcessGuid={816DD2CC-E9E5-6213-CA11-000000004C00} | ProcessId=7792 | Image=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe | FileVersion=10.0.14393.206 (rs1_release.160915-0644) | Description=Windows PowerShell | Company=Microsoft Corporation | OriginalFileName=PowerShell.EXE | CommandLine=PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARQBuAGMAbwBkAGUAZABDAG8AbQBtAGEAbgBkACAAVQB3AEIAbABBAEgAU …
```
> Filter fp when commands are base64 encoded

- rules/windows/builtin/firewall_as/win_firewall_as_add_rule.yml
- rules/windows/builtin/firewall_as/win_firewall_as_change_rule.yml
- rules/windows/builtin/firewall_as/win_firewall_as_delete_rule.yml
- rules/windows/builtin/firewall_as/win_firewall_as_failed.yml
- rules/windows/builtin/firewall_as/win_firewall_as_reset.yml
- rules/windows/builtin/firewall_as/win_firewall_as_setting_change.yml
Set to low to free the  Actions.
Start to work on filter with the action results
> Set to low as too many FP

- tests/check-baseline-local.sh
> new test: bash script for local baseline check

- tools/config/winlogbeat-modules-enabled.yml
> winlogbeat-modules-enabled fix channel

- rules/windows/process_creation/proc_creation_win_susp_esentutl_params.yml
> Update proc_creation_win_susp_esentutl_params.yml - minor spelling error

- rules/windows/process_creation/proc_creation_win_susp_use_of_sqlps_bin.yml
- rules/windows/process_creation/proc_creation_win_susp_use_of_sqltoolsps_bin.yml
> Fix detection

- rules/windows/registry_event/registry_event_win_office_enable_dde.yml
I have need to enable DDE to pass [redcanary T1559.002](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1559.002/T1559.002.md)
So make a rule to detect it.
> Enable Office dde

- tools/sigma/backends/sqlite.py
SQLite support regular expression via the REGEXP keyword. It works only if an [application-defined SQL function](https://www.sqlite.org/appfunc.html) named "regexp" is added at run-time, then the `X REGEXP Y` operator will be implemented as a call to `regexp(Y,X)`.
One way to implement it in python is to map the `regexp()` function to `re.search()` : [example](https://github.com/wagga40/Zircolite/blob/87798be6e1d37bccf90145becfb8b9ba9c208dd9/zircolite.py#L289).
This PR add a basic support of regex in the SQLite backend, for now the regex given in the Sigma rules are converted **as is**.
> Add basic REGEX support in SQLite Backend
